/-
  Phys.Quantum.Unitarity — N397 (arc-K K1): UNITARITY FROM MONAD IDEMPOTENCY.
  (Probability is conserved under evolution because physical states ARE sheaves and the
   gather monad acts as the IDENTITY on them — unitarity is the idempotency of the gather,
   NOT a separately-imposed postulate.)
  ===========================================================================
  THE FIRST NODE OF ARC K — the DYNAMICAL half of quantum field theory (how states
  are transported / how particles scatter). Arc J (J1–J6) derived the STATIC content:
  the raw 2D fibre (N391), the complex structure `foldComplex`/`J₂` forced by
  self-blindness (N392), the Born rule as a theorem (N393), measurement = the gather
  / the monad μ (N394), duality/entanglement/vacuum (N395), and the consolidation
  (N396). This node (K1) opens the dynamical arc: what a TRANSPORT of a state must be.

  ── THE FORWARD DERIVATION (fold → unitarity; nothing posited) ──
  C6 (best coherence is NOT a fixed point; eternal approach) says the look-back RECURS:
  a state is transported. The transport is generated by the fold's own phase — the
  banked complex unit `Dbl.J` (N2) — so transport is LEFT-MULTIPLICATION by an element
  of the derived complex algebra `Dbl Cut`. The question the theory then forces: does
  transport CONSERVE the self-overlap (probability), or can it create/destroy Unity?

  The answer is fixed by IDEMPOTENCY, and this is the whole content of the node. A
  PHYSICAL state is a SHEAF: the gather monad `μ = totalGather` acts as the IDENTITY on
  it (`totalGather_eq`, μ p = p — the element-level `T² ≅ T` idempotency, `totalGather_idem`).
  The gather resolves Unity ORTHOGONALLY into the two idempotent outcome-gatherers
  (N394: `gatherIn`/`gatherOut` idempotent + orthogonal, `μ = gatherIn + gatherOut = id`),
  and the Born completeness sum of that idempotent resolution is the self-overlap:
  `wIn p + wOut p = g(p,p)` (N394 `outcome_weights_sum` — Parseval). So the quantity a
  transport must conserve to keep a state a normalized sheaf is EXACTLY the completeness
  sum of the idempotent gather.

  Now the transport. On the banked complex algebra the self-overlap is the modulus-square
  `dblNormSq`, and `dblNormSq` is MULTIPLICATIVE (`dblNormSq_mul`, the two-square /
  Brahmagupta–Fibonacci identity — pure algebra on `Dbl Cut`). Therefore left-multiplication
  by `U` preserves `dblNormSq` if and only if `dblNormSq U = 1` (`norm_preserving_iff_unit_phase`).
  These norm-preserving transports form a GROUP (closed under multiplication, contain the
  fold's own phase `Dbl.J`, and each has a conjugate that realises its inverse-modulus,
  `U_mul_dblConj`) — the EMERGENT unitary group, DERIVED as the automorphisms of the
  sheaf's Born self-overlap, never posited.

  ── THE WELD (unitarity = idempotency of the gather) ──
  Transport by a unit phase `U` keeps a state a SHEAF (`evolve_is_sheaf`,
  `μ (evolve U p) = evolve U p` — still idempotent-gather-fixed) AND conserves the Born
  self-overlap, which by the idempotent orthogonal resolution EQUALS the completeness sum
  `wIn p + wOut p` (`unitary_conserves_gather_resolution`). So "probability conservation"
  is not an extra postulate on top of evolution: it IS the statement that transport respects
  the idempotent gather's completeness. Unitarity is the idempotency of the gather.

  ── STANDARD ──
  Unbroken: every object is banked/derived — `Dbl Cut`/`Dbl.J` (N2), `StateFibre`/`bornForm`
  (N391), `toDbl`/`dblNormSq`/`dblConj` (N393), `totalGather`/`wIn`/`wOut`/`outcome_weights_sum`
  (N394). Complete: every claim proved, foundations-only. Physics-words-removable: delete
  "unitary"/"evolution"/"probability"/"scattering" and the content is — `dblNormSq` is
  multiplicative; left-multiplication preserves it iff the multiplier has `dblNormSq = 1`;
  those multipliers form a group; such a multiplier keeps a `totalGather`-fixed state fixed
  and preserves `bornForm`, which equals `wIn + wOut`. Pure math about the banked objects.
  W4.5 SUFFICIENCY: this derives EXACTLY K1 (unitarity from idempotency), not the S-matrix
  (K2–K5). Grade: theorem-route; NO numerical claim.
-/
import Mathlib.Tactic
import Phys.Foundation.Fold
import Phys.Cascade.ComplexUnit
import Phys.Quantum.PrimitiveFibre
import Phys.Quantum.ComplexStructure
import Phys.Quantum.BornRule
import Phys.Quantum.Measurement

/-!
  ## N397 (arc-K K1) — declaration map (all over the derived `Dbl Cut` / banked fold objects)

    dblNormSq_mul                       — ★ the modulus-square is MULTIPLICATIVE (two-square identity).
    fromDbl / toDbl_fromDbl / …         — the banked iso `StateFibre ≅ Dbl Cut` (inverse of N393 `toDbl`).
    bornForm_fromDbl                    — the fibre self-overlap IS the algebra modulus-square.
    evolve                              — TRANSPORT = left-mult by `U : Dbl Cut` (the fold's recursion, C6).
    evolve_is_sheaf                     — ★ the transported state is STILL a sheaf (μ-fixed, idempotency).
    unit_phase_preserves_dblNormSq      — a unit phase (`dblNormSq U = 1`) preserves the modulus-square.
    norm_preserving_iff_unit_phase      — ★ the EMERGENT unitary group = `{U : dblNormSq U = 1}` (derived).
    unitary_conserves_born              — ★ CORE: a unit phase conserves the Born self-overlap of a state.
    unitary_conserves_gather_resolution — ★ WELD: the conserved total = `wIn + wOut`, the idempotent
                                            orthogonal gather-completeness (N394 `outcome_weights_sum`).
    J_is_unit_phase                     — the fold's own phase `Dbl.J` (N2) is a unit phase.
    unit_phase_group_closed             — the unit phases are closed under multiplication (a group).
    U_mul_dblConj                       — `U · U̅ = (dblNormSq U, 0)` (conjugate realises inverse-modulus).
    evolve_J_eInward / …                — [W8] non-vacuity: `Dbl.J` genuinely ROTATES yet conserves.
    unitarity_from_idempotency          — ★★ THE CAPSTONE.
-/

namespace Phys.Quantum

open Phys.Foundation Phys.Cascade Module
open Phys.Foundation.ContinuumQ

/-! ## The modulus-square is multiplicative (the two-square identity). -/

/-- ★ THE MODULUS-SQUARE IS MULTIPLICATIVE. `dblNormSq (z·w) = dblNormSq z · dblNormSq w`
    on the banked complex algebra `Dbl Cut` (the Brahmagupta–Fibonacci two-square identity).
    Pure algebra: the derived complex norm is a ring homomorphism to the derived field on
    the multiplicative structure — the fact that makes a phase-transport norm-preserving. -/
theorem dblNormSq_mul (z w : Dbl ContinuumQ.Cut) :
    dblNormSq (z * w) = dblNormSq z * dblNormSq w := by
  unfold dblNormSq
  simp only [Dbl.mul_re, Dbl.mul_im]
  ring

/-! ## The banked iso `StateFibre ≅ Dbl Cut` (inverse of N393 `toDbl`). -/

/-- The inverse of the banked `toDbl` (N393): read the algebra element back as a fibre point. -/
noncomputable def fromDbl (z : Dbl ContinuumQ.Cut) : StateFibre := (z.re, z.im)

@[simp] theorem fromDbl_re (z : Dbl ContinuumQ.Cut) : (fromDbl z).1 = z.re := rfl
@[simp] theorem fromDbl_im (z : Dbl ContinuumQ.Cut) : (fromDbl z).2 = z.im := rfl

/-- `toDbl ∘ fromDbl = id`. -/
theorem toDbl_fromDbl (z : Dbl ContinuumQ.Cut) : toDbl (fromDbl z) = z := by
  apply Dbl.ext <;> simp [toDbl, fromDbl]

/-- `fromDbl ∘ toDbl = id`. -/
theorem fromDbl_toDbl (p : StateFibre) : fromDbl (toDbl p) = p := by
  cases p; simp [fromDbl, toDbl]

/-- The fibre self-overlap `g` of `fromDbl z` IS the algebra modulus-square of `z`. -/
theorem bornForm_fromDbl (z : Dbl ContinuumQ.Cut) :
    bornForm (fromDbl z) (fromDbl z) = dblNormSq z := by
  unfold bornForm dblNormSq fromDbl; ring

/-! ## Transport = left-multiplication by an algebra element (the fold's recursion, C6). -/

/-- THE TRANSPORT (evolution): left-multiplication by `U : Dbl Cut` in the fibre coordinates.
    C6 (eternal approach) makes the look-back recur; the recursion is generated by the fold's
    own phase (the complex algebra `Dbl Cut`), so a step of evolution is `p ↦ U · p`. -/
noncomputable def evolve (U : Dbl ContinuumQ.Cut) (p : StateFibre) : StateFibre :=
  fromDbl (U * toDbl p)

/-- ★ THE TRANSPORTED STATE IS STILL A SHEAF (idempotency). The gather monad `μ = totalGather`
    acts as the identity on the transported state (`μ (evolve U p) = evolve U p`) — evolution
    maps sheaves to sheaves. This is the element-level `T² ≅ T` idempotency (N394
    `totalGather_idem` / `totalGather_eq`): a physical state stays physical under transport. -/
theorem evolve_is_sheaf (U : Dbl ContinuumQ.Cut) (p : StateFibre) :
    totalGather (evolve U p) = evolve U p := totalGather_eq _

/-- The Born self-overlap of the transported state is the modulus-square of the transport. -/
theorem bornForm_evolve (U : Dbl ContinuumQ.Cut) (p : StateFibre) :
    bornForm (evolve U p) (evolve U p) = dblNormSq (U * toDbl p) := by
  rw [evolve, bornForm_fromDbl]

/-! ## The emergent unitary group = `{U : dblNormSq U = 1}` (DERIVED, not posited). -/

/-- A UNIT PHASE preserves the modulus-square: if `dblNormSq U = 1` then
    `dblNormSq (U · z) = dblNormSq z`. Immediate from multiplicativity. -/
theorem unit_phase_preserves_dblNormSq (U : Dbl ContinuumQ.Cut) (hU : dblNormSq U = 1)
    (z : Dbl ContinuumQ.Cut) : dblNormSq (U * z) = dblNormSq z := by
  rw [dblNormSq_mul, hU, one_mul]

/-- ★ THE EMERGENT UNITARY GROUP, DERIVED. A transport preserves the modulus-square of EVERY
    state iff its multiplier is a unit phase: `(∀ z, dblNormSq (U·z) = dblNormSq z) ↔ dblNormSq U = 1`.
    The "unitary group" is not posited — it is exactly the multipliers of modulus one, the
    automorphisms of the derived self-overlap. -/
theorem norm_preserving_iff_unit_phase (U : Dbl ContinuumQ.Cut) :
    (∀ z, dblNormSq (U * z) = dblNormSq z) ↔ dblNormSq U = 1 := by
  constructor
  · intro h; have := h 1; simpa [dblNormSq] using this
  · intro hU z; exact unit_phase_preserves_dblNormSq U hU z

/-- ★ CORE — A UNIT PHASE CONSERVES THE BORN SELF-OVERLAP. If `dblNormSq U = 1` then transport
    by `U` conserves the Born self-overlap of every state: `g(evolve U p, evolve U p) = g(p,p)`.
    Probability is conserved under evolution — DERIVED from norm-multiplicativity, not posited. -/
theorem unitary_conserves_born (U : Dbl ContinuumQ.Cut) (hU : dblNormSq U = 1)
    (p : StateFibre) : bornForm (evolve U p) (evolve U p) = bornForm p p := by
  rw [bornForm_evolve, dblNormSq_mul, hU, one_mul]
  unfold bornForm dblNormSq toDbl; ring

/-- ★ THE WELD — UNITARITY IS THE IDEMPOTENCY OF THE GATHER. The quantity a unit phase conserves
    is EXACTLY the completeness sum of the idempotent orthogonal gather-resolution:
    `g(evolve U p, evolve U p) = wIn p + wOut p` (N394 `outcome_weights_sum`). Conservation of
    probability is not an extra postulate on evolution — it IS the statement that transport
    respects the idempotent gather's Born completeness (μ = gatherIn + gatherOut = id). -/
theorem unitary_conserves_gather_resolution (U : Dbl ContinuumQ.Cut) (hU : dblNormSq U = 1)
    (p : StateFibre) : bornForm (evolve U p) (evolve U p) = wIn p + wOut p := by
  rw [unitary_conserves_born U hU, outcome_weights_sum]

/-- The fold's OWN phase `Dbl.J` (N2, the derived complex unit `J² = −1`) is a unit phase:
    `dblNormSq Dbl.J = 1`. The generator of the fold's recursion is itself unitary. -/
theorem J_is_unit_phase : dblNormSq (Dbl.J : Dbl ContinuumQ.Cut) = 1 := by
  simp [dblNormSq, Dbl.J]

/-- The unit phases are CLOSED under composition: a group. -/
theorem unit_phase_group_closed (U V : Dbl ContinuumQ.Cut)
    (hU : dblNormSq U = 1) (hV : dblNormSq V = 1) : dblNormSq (U * V) = 1 := by
  rw [dblNormSq_mul, hU, hV, one_mul]

/-- `U · U̅ = (dblNormSq U, 0)`: the conjugate realises the inverse-modulus, so a unit phase
    (`dblNormSq U = 1`) has `dblConj U` as its inverse — the group has inverses. -/
theorem U_mul_dblConj (U : Dbl ContinuumQ.Cut) :
    U * dblConj U = ⟨dblNormSq U, 0⟩ := by
  apply Dbl.ext <;> simp [dblConj, dblNormSq, Dbl.mul_re, Dbl.mul_im] <;> ring

/-- A unit phase `U` has `dblConj U` as a genuine two-sided inverse: `U · U̅ = 1`. -/
theorem unit_phase_inverse (U : Dbl ContinuumQ.Cut) (hU : dblNormSq U = 1) :
    U * dblConj U = 1 := by
  rw [U_mul_dblConj, hU]; rfl

/-! ## [W8] Non-vacuity — the fold's phase genuinely ROTATES, yet conserves. -/

/-- The fold's phase transports the "toward" frame to the "away" frame:
    `evolve Dbl.J eInward = eOutward`. -/
theorem evolve_J_eInward : evolve Dbl.J eInward = eOutward := by
  apply Prod.ext <;> simp [evolve, fromDbl, toDbl, Dbl.J, eInward, eOutward, Dbl.mul_re, Dbl.mul_im]

/-- ★ [W8] NON-VACUITY. Transport by the fold's phase is GENUINELY NONTRIVIAL — it moves the
    "toward" frame OFF itself (`evolve Dbl.J eInward ≠ eInward`). So the conservation is not the
    vacuous statement "evolution does nothing"; it is a real rotation that nonetheless preserves
    the Born self-overlap. -/
theorem evolve_J_nontrivial : evolve Dbl.J eInward ≠ eInward := by
  rw [evolve_J_eInward]
  intro h; exact eInward_ne_eOutward h.symm

/-- ★ [W8] The nontrivial transport CONSERVES the Born self-overlap to `1`:
    `g(evolve Dbl.J eInward, evolve Dbl.J eInward) = 1`. A real rotation, probability conserved. -/
theorem evolve_J_conserves : bornForm (evolve Dbl.J eInward) (evolve Dbl.J eInward) = 1 := by
  rw [unitary_conserves_born Dbl.J J_is_unit_phase, bornForm_eInward_self]

/-! ## THE CAPSTONE — unitarity from monad idempotency. -/

/-- ★★ THE CAPSTONE — UNITARITY FROM MONAD IDEMPOTENCY, DERIVED. On the banked complex algebra
    `Dbl Cut` (N2) with the banked fibre self-overlap `g = bornForm` (N391), the banked
    modulus-square/iso `dblNormSq`/`toDbl` (N393), and the banked idempotent gather
    `μ = totalGather`, `wIn`/`wOut` (N394):
    (i)   the modulus-square is MULTIPLICATIVE (`dblNormSq_mul`);
    (ii)  transport `evolve U = (· ↦ U··)` preserves the modulus-square of every state IFF
          `U` is a unit phase — the EMERGENT unitary group `{dblNormSq U = 1}`, DERIVED, which
          is closed and has conjugate inverses, and contains the fold's own phase `Dbl.J`;
    (iii) a unit phase transport keeps a state a SHEAF (`μ (evolve U p) = evolve U p`, the
          element-level `T² ≅ T` idempotency) and CONSERVES the Born self-overlap, which by the
          idempotent orthogonal gather-resolution EQUALS the completeness sum `wIn p + wOut p`.
    Nothing is posited: unitarity (probability conservation under evolution) is the idempotency
    of the gather — the statement that transport respects the idempotent, orthogonal resolution
    of Unity — not a separately-imposed postulate. Non-vacuity: `Dbl.J` genuinely rotates. -/
theorem unitarity_from_idempotency :
    -- (i) the modulus-square is multiplicative.
    (∀ z w : Dbl ContinuumQ.Cut, dblNormSq (z * w) = dblNormSq z * dblNormSq w) ∧
    -- (ii) the emergent unitary group: norm-preserving ⟺ unit phase; closed; contains J; inverses.
    (∀ U : Dbl ContinuumQ.Cut,
        (∀ z, dblNormSq (U * z) = dblNormSq z) ↔ dblNormSq U = 1) ∧
    (∀ U V : Dbl ContinuumQ.Cut, dblNormSq U = 1 → dblNormSq V = 1 → dblNormSq (U * V) = 1) ∧
    (dblNormSq (Dbl.J : Dbl ContinuumQ.Cut) = 1) ∧
    (∀ U : Dbl ContinuumQ.Cut, dblNormSq U = 1 → U * dblConj U = 1) ∧
    -- (iii) unitarity IS idempotency: transport keeps a sheaf a sheaf and conserves the
    --       idempotent gather's completeness sum.
    (∀ (U : Dbl ContinuumQ.Cut), ∀ p : StateFibre, totalGather (evolve U p) = evolve U p) ∧
    (∀ (U : Dbl ContinuumQ.Cut), dblNormSq U = 1 → ∀ p : StateFibre,
        bornForm (evolve U p) (evolve U p) = wIn p + wOut p) ∧
    -- non-vacuity: the fold's phase genuinely rotates yet conserves.
    (evolve Dbl.J eInward ≠ eInward ∧
        bornForm (evolve Dbl.J eInward) (evolve Dbl.J eInward) = 1) := by
  refine ⟨dblNormSq_mul, norm_preserving_iff_unit_phase, unit_phase_group_closed,
    J_is_unit_phase, unit_phase_inverse, evolve_is_sheaf,
    unitary_conserves_gather_resolution, ⟨evolve_J_nontrivial, evolve_J_conserves⟩⟩

end Phys.Quantum
