-- Phys.lean — the aggregator. Imports every BANKED production module.
-- The gate builds this.
import Phys.Foundation.Fold
import Phys.Foundation.Counting
import Phys.Foundation.CountingArith
import Phys.Foundation.IntegerTower
import Phys.Foundation.RationalTower
import Phys.Foundation.OrderedTower
import Phys.Cascade.ComplexUnit
import Phys.Cascade.Double
import Phys.Cascade.Quaternion
import Phys.Cascade.Octonion
import Phys.Cascade.Sedenion
import Phys.Cascade.ForcedStop
import Phys.Algebra.Operator
import Phys.Algebra.GeneratedModule
import Phys.Algebra.JordanTower
import Phys.Algebra.Alternative
import Phys.Algebra.Derivation
import Phys.Algebra.DerivationDim
import Phys.Algebra.DerivationSkew
import Phys.Algebra.DerivationTraceFree
import Phys.Algebra.DerivationFinrank
import Phys.Algebra.DerivationLowerBound
import Phys.Algebra.DerivationUpperBound
import Phys.Algebra.DerivationBracket
import Phys.Algebra.DerivationStructureConstants
import Phys.Algebra.DerivationRep7
import Phys.Algebra.DerivationPerfect
import Phys.Algebra.DerivationCompact
import Phys.Algebra.DerivationIrreducible
import Phys.Algebra.DerivationIrreducibleFull
import Phys.Algebra.DerivationSimple
import Phys.Algebra.DerivationSimpleStructure
import Phys.Algebra.DerivationSemisimpleModule
import Phys.Algebra.DerivationSimpleCollapse
import Phys.Algebra.DerivationAutGroup
import Phys.Algebra.DerivationAutCompact
import Phys.Algebra.HermitianJordan.Setup
import Phys.Algebra.HermitianJordan.Helpers
import Phys.Algebra.HermitianJordan.CompCentral
import Phys.Algebra.HermitianJordan.Linear
import Phys.Algebra.HermitianJordan.SinglePair
import Phys.Algebra.HermitianJordan.Building
import Phys.Algebra.HermitianJordan.Building2
import Phys.Algebra.HermitianJordan.Building3
import Phys.Algebra.HermitianJordan.Core
import Phys.Algebra.HermitianJordan.Reduction
import Phys.Algebra.HermitianJordan.PieceA
import Phys.Algebra.HermitianJordan.PieceB
import Phys.Algebra.HermitianJordan.PolarFirst
import Phys.Algebra.HermitianJordan.PieceBscale
import Phys.Algebra.HermitianJordan.PieceBdeg2
import Phys.Algebra.HermitianJordan.PieceBdeg1
import Phys.Algebra.HermitianJordan.PieceBfinal
import Phys.Foundation.DerivedSqrtTwo
import Phys.Foundation.ContinuumDerived
import Phys.Foundation.ContinuumField
import Phys.Foundation.ContinuumFieldMul
import Phys.Foundation.ContinuumFieldRing
import Phys.Foundation.ContinuumFieldInverse
import Phys.Foundation.ContinuumCCLO
import Phys.Foundation.ContinuumTopology
