#!/usr/bin/env python3
"""
N23 route-probe (reconnaissance, NOT the deliverable).

Reuses the BANKED 14 derivations + bracket table from killing_rep.py to MEASURE the
tractability of the candidate N23 invariants, so the route decision is a MEASUREMENT
not a guess (PREREG requirement):

  (A) irreducibility of the 7-rep on Im(O ℚ): is there a structural transitivity
      argument? Compute, for each imaginary unit e_i, the span generated by applying
      the 14 restricted 7x7 derivations once / iteratively; check the orbit spans.
  (B) Killing-form nondegeneracy: structure of K (block decomposition? sparsity?).
  (C) the 7-rep trace form tau(i,j)=tr(D7_i D7_j) (a smaller 7x7-product form).
"""
from fractions import Fraction as F

def dbl_mul(z, w): return (z[0]*w[0] - z[1]*w[1], z[0]*w[1] + z[1]*w[0])
def dbl_star(z):   return (z[0], -z[1])
def dbl_add(z, w): return (z[0]+w[0], z[1]+w[1])
def dbl_neg(z):    return (-z[0], -z[1])
DBL_ZERO = (F(0), F(0))
def make_CD(mul, star, add, neg, zero):
    def cd_mul(z, w):
        zr, zi = z; wr, wi = w
        re = add(mul(zr, wr), neg(mul(star(wi), zi)))
        im = add(mul(wi, zr), mul(zi, star(wr)))
        return (re, im)
    def cd_star(z): return (star(z[0]), neg(z[1]))
    def cd_add(z, w): return (add(z[0], w[0]), add(z[1], w[1]))
    def cd_neg(z): return (neg(z[0]), neg(z[1]))
    return cd_mul, cd_star, cd_add, cd_neg, (zero, zero)
h_mul, h_star, h_add, h_neg, h_zero = make_CD(dbl_mul, dbl_star, dbl_add, dbl_neg, DBL_ZERO)
o_mul, o_star, o_add, o_neg, o_zero = make_CD(h_mul, h_star, h_add, h_neg, h_zero)

DMAPS = {
 0:  {2:(5,-1), 3:(4,1), 4:(3,-1), 5:(2,1)},
 1:  {2:(4,-1), 3:(5,-1), 4:(2,1), 5:(3,1)},
 2:  {2:(3,1), 3:(2,-1), 4:(5,-1), 5:(4,1)},
 3:  {1:(6,-1), 3:(4,-1), 4:(3,1), 6:(1,1)},
 4:  {1:(5,1), 2:(6,-1), 5:(1,-1), 6:(2,1)},
 5:  {1:(4,1), 3:(6,-1), 4:(1,-1), 6:(3,1)},
 6:  {1:(3,-1), 3:(1,1), 4:(6,-1), 6:(4,1)},
 7:  {1:(2,-1), 2:(1,1), 5:(6,-1), 6:(5,1)},
 8:  {1:(7,-1), 2:(4,1), 4:(2,-1), 7:(1,1)},
 9:  {1:(4,-1), 2:(7,-1), 4:(1,1), 7:(2,1)},
 10: {1:(5,1), 3:(7,-1), 5:(1,-1), 7:(3,1)},
 11: {1:(2,1), 2:(1,-1), 4:(7,-1), 7:(4,1)},
 12: {1:(3,-1), 3:(1,1), 5:(7,-1), 7:(5,1)},
 13: {2:(3,-1), 3:(2,1), 6:(7,-1), 7:(6,1)},
}
def to_matrix(spec):
    M=[[F(0)]*8 for _ in range(8)]
    for row,(col,coeff) in spec.items():
        M[row][col]=F(coeff)
    return M
D=[to_matrix(DMAPS[k]) for k in range(14)]
def restrict7(M): return [[M[i][j] for j in range(1,8)] for i in range(1,8)]
D7=[restrict7(D[k]) for k in range(14)]

def matmul(A,B,n): return [[sum(A[i][k]*B[k][j] for k in range(n)) for j in range(n)] for i in range(n)]
def matsub(A,B,n): return [[A[i][j]-B[i][j] for j in range(n)] for i in range(n)]
def apply7(M,v): return [sum(M[i][j]*v[j] for j in range(7)) for i in range(7)]
def trace(M,n): return sum(M[i][i] for i in range(n))

def rank(rows):
    rows=[r[:] for r in rows]; r=0
    if not rows: return 0
    ncol=len(rows[0])
    for c in range(ncol):
        piv=None
        for i in range(r,len(rows)):
            if rows[i][c]!=0: piv=i; break
        if piv is None: continue
        rows[r],rows[piv]=rows[piv],rows[r]; pv=rows[r][c]
        rows[r]=[x/pv for x in rows[r]]
        for i in range(len(rows)):
            if i!=r and rows[i][c]!=0:
                f=rows[i][c]; rows[i]=[a-f*b for a,b in zip(rows[i],rows[r])]
        r+=1
        if r==len(rows): break
    return r

# ============ (A) IRREDUCIBILITY: orbit / transitivity ============
# Strong test: does {ρ(D_k)} GENERATE the full matrix algebra End(ImO) (49-dim)?
# (Burnside: over an alg-closed field, irreducible <=> image spans End.)
print("=== (A) irreducibility probes ===")
# A1: from a single nonzero vector v, span of {D7_k v} and iterated orbit.
def orbit_span_from(v):
    vecs=[v[:]]
    changed=True
    while changed:
        changed=False
        cur=rank(vecs)
        new=[]
        for w in vecs:
            for k in range(14):
                new.append(apply7(D7[k],w))
        allv=vecs+new
        if rank(allv)>cur:
            vecs=allv; changed=True
    return rank(vecs)
import itertools
print("  orbit-span dim from each unit e_i (expect 7 for transitivity):",
      [orbit_span_from([F(1) if j==i else F(0) for j in range(7)]) for i in range(7)])
# generic vector
gv=[F(i+1) for i in range(7)]
print("  orbit-span dim from a generic vector:", orbit_span_from(gv))
# A2: associative algebra generated by the 14 ρ(D_k) inside End(ImO)=49-dim
def flat49(M): return [M[i][j] for i in range(7) for j in range(7)]
I7=[[F(1) if i==j else F(0) for j in range(7)] for i in range(7)]
gens=[flat49(I7)]+[flat49(D7[k]) for k in range(14)]
prod_basis=[I7]+[D7[k] for k in range(14)]
words=[I7]+[D7[k] for k in range(14)]
changed=True
while changed:
    changed=False
    cur=rank([flat49(M) for M in words])
    new=list(words)
    for w in words:
        for k in range(14):
            new.append(matmul(w,D7[k],7))
    if rank([flat49(M) for M in new])>cur:
        words=new; changed=True
print("  dim of associative algebra generated by ρ(D_k) in End(ImO) (49=full => absolutely irred):",
      rank([flat49(M) for M in words]))

# ============ (B) Killing form structure ============
print("\n=== (B) Killing-form structure ===")
BASIS=[[D[k][i][j] for i in range(8) for j in range(8)] for k in range(14)]
def solve_in_basis(target):
    rows=[[BASIS[k][coord] for k in range(14)]+[target[coord]] for coord in range(64)]
    r=0; pivcols=[]
    for c in range(14):
        piv=None
        for i in range(r,len(rows)):
            if rows[i][c]!=0: piv=i; break
        if piv is None: continue
        rows[r],rows[piv]=rows[piv],rows[r]; pv=rows[r][c]
        rows[r]=[x/pv for x in rows[r]]
        for i in range(len(rows)):
            if i!=r and rows[i][c]!=0:
                f=rows[i][c]; rows[i]=[a-f*b for a,b in zip(rows[i],rows[r])]
        pivcols.append(c); r+=1
    c=[F(0)]*14
    for idx,col in enumerate(pivcols): c[col]=rows[idx][14]
    return c
def bracket8(A,B): return matsub(matmul(A,B,8),matmul(B,A,8),8)
def flat64(M): return [M[i][j] for i in range(8) for j in range(8)]
C=[[None]*14 for _ in range(14)]
for i in range(14): C[i][i]=[F(0)]*14
for i in range(14):
    for j in range(i+1,14):
        cc=solve_in_basis(flat64(bracket8(D[i],D[j])))
        C[i][j]=cc; C[j][i]=[-v for v in cc]
AD=[[[C[i][j][k] for j in range(14)] for k in range(14)] for i in range(14)]
K=[[trace(matmul(AD[i],AD[j],14),14) for j in range(14)] for i in range(14)]
# adjacency of off-diagonal nonzeros => connected components / block structure
adj={i:set() for i in range(14)}
for i in range(14):
    for j in range(14):
        if i!=j and K[i][j]!=0: adj[i].add(j)
# connected components on off-diagonal graph
seen=set(); comps=[]
for s in range(14):
    if s in seen: continue
    stack=[s]; comp=set()
    while stack:
        x=stack.pop()
        if x in seen: continue
        seen.add(x); comp.add(x)
        stack.extend(adj[x]-seen)
    comps.append(sorted(comp))
print("  off-diagonal coupling graph components (block structure of K):", comps)
print("  off-diagonal pairs:", [(i,j,int(K[i][j])) for i in range(14) for j in range(i+1,14) if K[i][j]!=0])

# ============ (C) 7-rep trace form ============
print("\n=== (C) 7-rep trace form tau(i,j)=tr(D7_i D7_j) ===")
TAU=[[trace(matmul(D7[i],D7[j],7),7) for j in range(14)] for i in range(14)]
print("  diagonal:", [int(TAU[i][i]) for i in range(14)])
print("  rank(tau):", rank([row[:] for row in TAU]))
tau_off=[(i,j,int(TAU[i][j])) for i in range(14) for j in range(i+1,14) if TAU[i][j]!=0]
print("  off-diagonal nonzeros:", tau_off)
print("  tau == c * K ? ratio diag:", [TAU[i][i]/K[i][i] for i in range(3)])
