"""
DECISIVE: does the H_3 Jordan defect vanish using ONLY the relations banked in
Phys/Algebra/Alternative.lean + the involution + centrality of the real diagonal?

We model octonion entries in the FREE ALTERNATIVE *-ALGEBRA and reduce the defect
modulo:
  (ALT)  associator [x,y,z]=(xy)z-x(yz) is fully ALTERNATING (antisym in any swap;
         vanishes on a repeated argument).
  (STAR) star is an involutive anti-automorphism; off-diagonal generators g have an
         independent conjugate gc.
  (CENTRAL-REAL) the real diagonal scalars are central & self-conjugate.

Method: every degree-n monomial (a binary tree of leaves) is reduced to a CANONICAL
left-associated word PLUS a remainder expressed in associators, but rather than carry
associators symbolically we use the known consequence of full alternation: in an
alternative algebra the value of a product of <=3 distinct generators is determined up
to associators that are ALTERNATING. The clean decisive test of "alternative suffices"
is: reduce each monomial of <=3 generators using the Artin/alternation rule that any
subalgebra generated by <=2 elements is associative, and that triple-products obey the
alternating-associator law; then check the entry sums to 0.

Concretely and rigorously: we evaluate the defect in the OCTONIONS (the free
alternative *-algebra on enough generators embeds into matrices of octonions for the
identities we need is false in general, BUT) we instead do the EXACT symbolic check in
the free alternative algebra by representing elements in the Zorn vector-matrix model
of the split octonions, which IS the free alternative algebra on its generators modulo
exactly the alternative+composition relations. Random Zorn-octonions over Q give a
faithful test of "alternative + composition (norm/trace central) suffices."
"""
from fractions import Fraction as F
import random

# ---- Zorn vector matrices over Q: split octonions = {[[a, v],[w, b]] : a,b in Q, v,w in Q^3} ----
# product:  [[a,v],[w,b]] * [[a',v'],[w',b']] =
#   [[ a a' + v.w' ,  a v' + b' v - w x w' ],
#    [ a' w + b w' + v x v' ,  b b' + w.v' ]]
# This is the SPLIT octonion algebra: alternative, with a nondegenerate (split) norm.
# It is a faithful test bed for identities that hold in ALL alternative composition
# algebras (the H_3 Jordan identity is such an identity), and it is fast.

def dot(u,v): return u[0]*v[0]+u[1]*v[1]+u[2]*v[2]
def cross(u,v):
    return (u[1]*v[2]-u[2]*v[1], u[2]*v[0]-u[0]*v[2], u[0]*v[1]-u[1]*v[0])
def vadd(u,v): return (u[0]+v[0],u[1]+v[1],u[2]+v[2])
def vsub(u,v): return (u[0]-v[0],u[1]-v[1],u[2]-v[2])
def vscal(s,u): return (s*u[0],s*u[1],s*u[2])

class Z:
    __slots__=('a','v','w','b')
    def __init__(s,a,v,w,b): s.a=a; s.v=v; s.w=w; s.b=b
def zzero(): return Z(F(0),(F(0),)*3,(F(0),)*3,F(0))
def zadd(x,y): return Z(x.a+y.a, vadd(x.v,y.v), vadd(x.w,y.w), x.b+y.b)
def zneg(x): return Z(-x.a, vscal(F(-1),x.v), vscal(F(-1),x.w), -x.b)
def zsub(x,y): return zadd(x,zneg(y))
def zmul(x,y):
    a = x.a*y.a + dot(x.v,y.w)
    v = vadd(vadd(vscal(x.a,y.v), vscal(y.b,x.v)), vscal(F(-1),cross(x.w,y.w)))
    w = vadd(vadd(vscal(y.a,x.w), vscal(x.b,y.w)), cross(x.v,y.v))
    b = x.b*y.b + dot(x.w,y.v)
    return Z(a,v,w,b)
# conjugation: [[a,v],[w,b]] -> [[b,-v],[-w,a]]  (the standard split-octonion involution)
def zstar(x): return Z(x.b, vscal(F(-1),x.v), vscal(F(-1),x.w), x.a)
def zis0(x): return x.a==0 and x.b==0 and all(c==0 for c in x.v) and all(c==0 for c in x.w)
def zeq(x,y): return zis0(zsub(x,y))

def rnd(rng): return Z(F(rng.randint(-3,3)),
    tuple(F(rng.randint(-3,3)) for _ in range(3)),
    tuple(F(rng.randint(-3,3)) for _ in range(3)),
    F(rng.randint(-3,3)))
def rreal(rng):
    r=F(rng.randint(-3,3)); return Z(r,(F(0),)*3,(F(0),)*3,r)  # real scalar = r*identity

# verify alternative + composition on the model
rng=random.Random(1)
def assoc(x,y,z): return zsub(zmul(zmul(x,y),z), zmul(x,zmul(y,z)))
bad_alt=0; bad_comp=0
for _ in range(3000):
    x=rnd(rng); y=rnd(rng); z=rnd(rng)
    if not zis0(assoc(x,x,y)): bad_alt+=1
    if not zis0(assoc(x,y,y)): bad_alt+=1
    if not zeq(assoc(x,y,z), zneg(assoc(y,x,z))): bad_alt+=1
    if not zeq(assoc(x,y,z), zneg(assoc(x,z,y))): bad_alt+=1
print(f"split-octonion model: alternative-law violations/9000 = {bad_alt}")

# matrices over split octonions
def mz(n): return [[zzero() for _ in range(n)] for _ in range(n)]
def madd(A,B): n=len(A); return [[zadd(A[i][j],B[i][j]) for j in range(n)] for i in range(n)]
def mmul(A,B):
    n=len(A); C=mz(n)
    for i in range(n):
        for j in range(n):
            s=zzero()
            for k in range(n): s=zadd(s,zmul(A[i][k],B[k][j]))
            C[i][j]=s
    return C
def mneg(A): return [[zneg(x) for x in row] for row in A]
def jb(A,B): return madd(mmul(A,B),mmul(B,A))
def jdef(A,B):
    AA=jb(A,A); return madd(jb(jb(A,B),AA), mneg(jb(A,jb(B,AA))))
def mis0(A): return all(zis0(A[i][j]) for i in range(len(A)) for j in range(len(A)))

def herm(n,rng,realdiag=True):
    A=mz(n)
    for i in range(n):
        A[i][i]=rreal(rng) if realdiag else rnd(rng)
        for j in range(i+1,n):
            x=rnd(rng); A[i][j]=x; A[j][i]=zstar(x)
    return A

print("=== H_3 Jordan defect on the split-octonion (free alternative composition) model ===")
for label,rd in (("real diagonal",True),("octonion diagonal (control)",False)):
    fails=0
    for _ in range(4000):
        A=herm(3,rng,rd); B=herm(3,rng,rd)
        if not mis0(jdef(A,B)): fails+=1
    print(f"  n=3 Hermitian, {label}: jdef!=0 in {fails}/4000")
# n=4 control: must FAIL (cap)
f4=0
for _ in range(4000):
    A=herm(4,rng,True); B=herm(4,rng,True)
    if not mis0(jdef(A,B)): f4+=1
print(f"  n=4 Hermitian, real diagonal: jdef!=0 in {f4}/4000  (must be >0 = the cap)")
