"""verify_run64j: find pieceB's clean structural form. pieceB = jdef(Hm1, Y), Y zero-diag
Herm, Hm1 = D+X. pieceB = jdef(D+X,Y) = jdef(D,Y)+CB+jdef(X,Y) = CB (cross terms), since
jdef(D,Y)=0 (lever a) and jdef(X,Y)=0 (banked). CB = T1(Y)+T2(Y).

Hypothesis: CB = 2*(D*K - K*D) for some matrix K (commutator with central D). If so, CB_ij =
K_ij*(d_i - d_j): diagonal auto-0, off-diag needs K off-diag = 0. Try candidate K's built from
X, Y. comm(D,M)_ij = (d_i-d_j) M_ij entrywise (D central diagonal).

Candidates for K (so that CB == comm-with-D form, then reduce to K off-diag = 0):
We look for: CB == sum of comm(D, .) terms with octonion-matrix args from {X,Y}.
Test if CB lies in the module generated by comm(D, W) for W in a basis of degree-(<=2 in X, 1 in Y)
matrix products. Simpler: just check CB_ij / (d_i - d_j) is well-defined (i.e. CB_ii = 0) and
CB_ij for i!=j is INDEPENDENT of the d's up to the (d_i-d_j) factor? Probably not (T2 has d^2).
So measure the d-degree of CB entries.
"""
from fractions import Fraction as F
from collections import defaultdict
SCAL={'d0','d1','d2'}
STAR={'a':'A','b':'B','c':'C','p':'P','q':'Q','r':'R'}
for k,v in list(STAR.items()): STAR[v]=k
def smul(s1,s2): return tuple(sorted(s1+s2))
def Eo(atom): return {((),atom):F(1)}
def Es(s): return {((s,),'1'):F(1)}
ZERO={}
def vadd(*vs):
    r=defaultdict(F)
    for v in vs:
        for k,c in v.items(): r[k]+=c
    return {k:c for k,c in r.items() if c!=0}
def vneg(v): return {k:-c for k,c in v.items()}
def tmul(t1,t2):
    if t1=='1': return t2
    if t2=='1': return t1
    return ('*',t1,t2)
def vmul(a,b):
    r=defaultdict(F)
    for (s1,t1),c1 in a.items():
        for (s2,t2),c2 in b.items(): r[(smul(s1,s2),tmul(t1,t2))]+=c1*c2
    return {k:c for k,c in r.items() if c!=0}
def mz(): return [[dict(ZERO) for _ in range(3)] for _ in range(3)]
def madd(*Ms):
    R=mz()
    for M in Ms:
        for i in range(3):
            for j in range(3): R[i][j]=vadd(R[i][j],M[i][j])
    return R
def mneg(A): return [[vneg(x) for x in row] for row in A]
def msub(A,B): return madd(A,mneg(B))
def mmul(A,B):
    C=mz()
    for i in range(3):
        for j in range(3):
            s=dict(ZERO)
            for k in range(3): s=vadd(s,vmul(A[i][k],B[k][j]))
            C[i][j]=s
    return C
def comm(A,B): return msub(mmul(A,B),mmul(B,A))
def jb(A,B): return madd(mmul(A,B),mmul(B,A))
def jdefM(A,B):
    AA=jb(A,A); return madd(jb(jb(A,B),AA),mneg(jb(A,jb(B,AA))))
def Dm(d): return [[Es(d[0]),dict(ZERO),dict(ZERO)],[dict(ZERO),Es(d[1]),dict(ZERO)],[dict(ZERO),dict(ZERO),Es(d[2])]]
def Xz(o):
    a,b,c=o; return [[dict(ZERO),Eo(a),Eo(b)],[Eo(STAR[a]),dict(ZERO),Eo(c)],[Eo(STAR[b]),Eo(STAR[c]),dict(ZERO)]]
def grid(M): return [[len(M[i][j]) for j in range(3)] for i in range(3)]
def tot(M): return sum(len(M[i][j]) for i in range(3) for j in range(3))
def dscan(M):  # for each entry, the set of d-scalar-degrees present
    out=[[set() for _ in range(3)] for _ in range(3)]
    for i in range(3):
        for j in range(3):
            for (s,t),c in M[i][j].items():
                dd=sum(1 for x in s if x in SCAL)
                out[i][j].add(dd)
    return [[sorted(out[i][j]) for j in range(3)] for i in range(3)]

D=Dm(['d0','d1','d2']); X=Xz(('a','b','c')); Y=Xz(('p','q','r')); Hm1=madd(D,X)
CB=msub(jdefM(Hm1,Y), jdefM(X,Y))   # = pieceB (since jdef(X,Y) banked 0, and jdef(D,Y)=0)
print("pieceB = CB = jdef(Hm1,Y)-jdef(X,Y) [= jdef(Hm1,Y) when core banked]:")
print("  per-entry monomials:", grid(CB))
print("  CB_ii diagonal zero?:", [tot([[CB[i][i]]]) for i in range(3)])
print("  d-degrees per entry:", dscan(CB))
print()
# the diagonal of CB: is it zero? if jdef(Hm1,Y)_ii==jdef(X,Y)_ii then yes
print("  Is CB diagonal exactly 0? ->", all(len(CB[i][i])==0 for i in range(3)))
print()
# Try: CB == 2*comm(D, K) for K with off-diag only. comm(D,K)_ij=(d_i-d_j)K_ij.
# So K_ij = CB_ij / (2(d_i-d_j)). Check CB_ij has overall factor (d_i-d_j): substitute.
# Simplest structural target: maybe jdef(Hm1,Y) = jdef(X,Y) + 2*comm(D, W) with W = jb-ish.
# Let me test candidate W = comm(X, Y)  (XY-YX), and W = X*Y+Y*X etc, fit CB = 2 comm(D,W).
for nm,W in [("comm(X,Y)",comm(X,Y)), ("XY",mmul(X,Y)), ("YX",mmul(Y,X)),
             ("jb(X,Y)",jb(X,Y))]:
    cand=msub(CB, madd(comm(D,W),comm(D,W)))   # CB - 2 comm(D,W)
    print(f"  CB - 2 comm(D, {nm}) residual = {tot(cand)}")
