import numpy as np
from itertools import product

Imat = np.array([
 [0,0,0,0,0,0,0],[0,0,-2,0,0,0,0],[0,2,0,0,0,0,0],
 [0,0,0,0,0,0,0],[0,0,0,0,0,0,0],[0,0,0,0,0,0,-2],[0,0,0,0,0,2,0]],float)
Jmat = np.array([
 [0,0,2,0,0,0,0],[0,0,0,0,0,0,0],[-2,0,0,0,0,0,0],
 [0,0,0,0,0,0,0],[0,0,0,0,0,0,2],[0,0,0,0,0,0,0],[0,0,0,0,-2,0,0]],float)
def comm(A,B): return A@B-B@A
Kmat = comm(Imat,Jmat)/2.0

T1=[0,1,2]; T2=[4,5,6]
def restrict(M,idx): return M[np.ix_(idx,idx)]

for name,T in [("T1",T1),("T2",T2)]:
    I,J,K = restrict(Imat,T),restrict(Jmat,T),restrict(Kmat,T)
    Id=np.eye(3)
    # generate the algebra: all products up to length 2 of {Id,I,J,K}
    gens=[Id,I,J,K]
    words=[Id,I,J,K, I@I,I@J,I@K,J@I,J@J,J@K,K@I,K@J,K@K]
    M=np.array([w.flatten() for w in words])
    rank=np.linalg.matrix_rank(M)
    print(f"{name}: dim of Q-algebra generated by <=2 products of I,J,K =", rank, "(9 => full M_3 => Q-irreducible)")
    # also: any common real eigenvector (1-dim invariant)?
    # skew operators: only real eigenvalue 0; joint kernel on T?
    stack=np.vstack([I,J,K])
    jk = 3 - np.linalg.matrix_rank(stack)
    print(f"   joint kernel dim on {name} = {jk} (0 => no su(2)-fixed vector in the triplet)")

# ALSO: check T1, T2, singlet e4 are invariant and direct-sum ImO
print("\n=== invariance & direct sum ===")
for name,T in [("T1{e1,e2,e3}",T1),("T2{e5,e6,e7}",T2),("sing{e4}",[3])]:
    comp=[i for i in range(7) if i not in T]
    inv = all(np.allclose(M[np.ix_(comp,T)],0) for M in [Imat,Jmat,Kmat])
    print(f"  {name} su(2)_L-invariant: {inv}, dim {len(T)}")
print("  dims sum 3+1+3=7 = dim ImO: OK; disjoint coords: OK")

# Confirm each triplet's restricted operators satisfy so(3): [I,J]=2K etc (scale-free irreducibility indicator)
print("\n=== so(3) closure on each triplet (restricted) ===")
for name,T in [("T1",T1),("T2",T2)]:
    I,J,K = restrict(Imat,T),restrict(Jmat,T),restrict(Kmat,T)
    print(f"  {name}: [I,J]=2K {np.allclose(comm(I,J),2*K)}, [J,K]=2I {np.allclose(comm(J,K),2*I)}, [K,I]=2J {np.allclose(comm(K,I),2*J)}")
