#!/usr/bin/env python3
"""N259 SELECT probe 3 — the EXACT intersection of the two BANKED reductive factors as
Lie subalgebras of so(7), and the shared-Cartan claim.

chargeColourLie = span{Q} + colourImg  (colourImg = imRep(su3_c), in the 14; Q in the 7)  dim 9
electroweakLie  = isospinImg + hyperLine (isospinImg = imRep(su2_L), in the 14; Y in the 7) dim 4

CLAIM to test: chargeColourLie ∩ electroweakLie = span{imRep DI} = span{T3}, dim exactly 1.
And the FORCING: DI ∈ su3_c because DI(u1)=0 ⟹ [DI,Q]=[DI,crossOp u1]=crossOp(DI u1)=0 (u1 one-cause).
Also: the Lie algebra generated by (chargeColourLie ∪ electroweakLie) — dim.
"""
from fractions import Fraction as F
def dbl_mul(z,w): return (z[0]*w[0]-z[1]*w[1], z[0]*w[1]+z[1]*w[0])
def dbl_star(z): return (z[0],-z[1])
def dbl_add(z,w): return (z[0]+w[0], z[1]+w[1])
def dbl_neg(z): return (-z[0],-z[1])
DZ=(F(0),F(0))
def make_CD(mul,star,add,neg,zero):
    def cd_mul(z,w):
        zr,zi=z; wr,wi=w
        return (add(mul(zr,wr),neg(mul(star(wi),zi))), add(mul(wi,zr),mul(zi,star(wr))))
    def cd_star(z): return (star(z[0]),neg(z[1]))
    def cd_add(z,w): return (add(z[0],w[0]),add(z[1],w[1]))
    def cd_neg(z): return (neg(z[0]),neg(z[1]))
    return cd_mul,cd_star,cd_add,cd_neg,(zero,zero)
h_mul,h_star,h_add,h_neg,h_zero=make_CD(dbl_mul,dbl_star,dbl_add,dbl_neg,DZ)
o_mul,o_star,o_add,o_neg,o_zero=make_CD(h_mul,h_star,h_add,h_neg,h_zero)
def o_from_vec(v):
    def dbl(b): return (v[b+0],v[b+1])
    def h(b): return (dbl(b+0),dbl(b+2))
    return (h(0),h(4))
def o_to_vec(z):
    v=[None]*8
    for oi in (0,1):
        H=z[oi]
        for hi in (0,1):
            D=H[hi]
            for di in (0,1): v[oi*4+hi*2+di]=D[di]
    return v
def basis(i):
    v=[F(0)]*8; v[i]=F(1); return o_from_vec(v)
E=[basis(i) for i in range(8)]
ImO=list(range(1,8))
hI=((F(0),F(1)),(F(0),F(0))); hJ=((F(0),F(0)),(F(1),F(0))); hK=h_mul(hI,hJ)
u1=(hI,h_zero); kap1=basis(4)
def reQ(z): return o_to_vec(z)[0]
def gForm(x,y): return reQ(o_mul(x,o_star(y)))
def octCrossO(a,b): return o_add(o_mul(a,b), o_from_vec([gForm(a,b)]+[F(0)]*7))
def mat(op):
    A=[[F(0)]*7 for _ in range(7)]
    for jc,j in enumerate(ImO):
        out=o_to_vec(op(E[j]))
        for ic,i in enumerate(ImO): A[ic][jc]=out[i]
    return A
def matmul(A,B): return [[sum(A[r][t]*B[t][c] for t in range(7)) for c in range(7)] for r in range(7)]
def subm(A,B): return [[A[r][c]-B[r][c] for c in range(7)] for r in range(7)]
def addm(A,B): return [[A[r][c]+B[r][c] for c in range(7)] for r in range(7)]
def scal(c,A): return [[c*A[r][cc] for cc in range(7)] for r in range(7)]
def comm(A,B): return subm(matmul(A,B),matmul(B,A))
def iszero(A): return all(all(x==0 for x in r) for r in A)
def flat(A): return [A[i][j] for i in range(7) for j in range(7)]
Q  = mat(lambda x: octCrossO(u1,x))
Yh = mat(lambda x: octCrossO(kap1,x))
def innerD(P): return mat(lambda x,P=P:(h_add(h_mul(P,x[0]),h_neg(h_mul(x[0],P))),h_add(h_mul(P,x[1]),h_neg(h_mul(x[1],P)))))
DI=innerD(hI); DJ=innerD(hJ); DK=innerD(hK)
def rank_of(mats):
    rows=[flat(m)[:] for m in mats]; nr=len(rows); nc=49; rank=0
    for c in range(nc):
        piv=next((i for i in range(rank,nr) if rows[i][c]!=0),None)
        if piv is None: continue
        rows[rank],rows[piv]=rows[piv],rows[rank]; pv=rows[rank][c]
        rows[rank]=[x/pv for x in rows[rank]]
        for i in range(nr):
            if i!=rank and rows[i][c]!=0:
                f=rows[i][c]; rows[i]=[rows[i][j]-f*rows[rank][j] for j in range(nc)]
        rank+=1
        if rank==nr: break
    return rank
def dim_span(mats): return rank_of(mats)
def nullspace(rows,ncols):
    R=[r[:] for r in rows]; nr=len(R); pivots=[]; r=0; col_piv={}
    for c in range(ncols):
        piv=next((i for i in range(r,nr) if R[i][c]!=0),None)
        if piv is None: continue
        R[r],R[piv]=R[piv],R[r]; pv=R[r][c]; R[r]=[x/pv for x in R[r]]
        for i in range(nr):
            if i!=r and R[i][c]!=0:
                f=R[i][c]; R[i]=[R[i][j]-f*R[r][j] for j in range(ncols)]
        col_piv[c]=r; pivots.append(c); r+=1
        if r==nr: break
    free=[c for c in range(ncols) if c not in col_piv]
    basis=[]
    for fc in free:
        vec=[F(0)]*ncols; vec[fc]=F(1)
        for c in pivots: vec[c]=-R[col_piv[c]][fc]
        basis.append(vec)
    return basis
def vec_to_mat(v): return [[v[i*7+j] for j in range(7)] for i in range(7)]
def build_g2_basis():
    rows=[]
    for ia in range(1,8):
        for ib in range(1,8):
            a=E[ia]; b=E[ib]; ab=o_mul(a,b)
            imag_ab=o_to_vec(ab)[1:8]; imag_a=o_to_vec(a)[1:8]; imag_b=o_to_vec(b)[1:8]
            per_unknown=[]
            for p in range(7):
                for q in range(7):
                    dab=[F(0)]*8; dab[p+1]=imag_ab[q]; dab_o=o_from_vec(dab)
                    da=[F(0)]*8; da[p+1]=imag_a[q]; da_o=o_from_vec(da)
                    db=[F(0)]*8; db[p+1]=imag_b[q]; db_o=o_from_vec(db)
                    expr=o_add(o_add(dab_o, o_neg(o_mul(da_o,b))), o_neg(o_mul(a,db_o)))
                    per_unknown.append(o_to_vec(expr))
            for comp in range(8):
                row=[per_unknown[k][comp] for k in range(49)]
                if any(x!=0 for x in row): rows.append(row)
    return nullspace(rows,49)
g2mats=[vec_to_mat(v) for v in build_g2_basis()]
def colour_centralizer():
    n=len(g2mats); rows=[]; commmats=[comm(M,Q) for M in g2mats]
    for comp in range(49):
        row=[flat(commmats[a])[comp] for a in range(n)]
        if any(x!=0 for x in row): rows.append(row)
    ns=nullspace(rows,n); cmats=[]
    for v in ns:
        M=[[F(0)]*7 for _ in range(7)]
        for a in range(n):
            if v[a]!=0: M=addm(M,scal(v[a],g2mats[a]))
        cmats.append(M)
    return cmats
su3=colour_centralizer()

# The two BANKED reductive factors as spanning matrix sets:
chargeColour = su3 + [Q]          # colourImg (imRep su3, dim 8) + charge line span{Q}  -> dim 9
electroweak  = [DI,DJ,DK,Yh]      # isospinImg (imRep su2, dim 3) + hyperLine span{Y}   -> dim 4
print("dim chargeColourLie =", dim_span(chargeColour), "(expect 9)")
print("dim electroweakLie  =", dim_span(electroweak), "(expect 4)")

# subspace intersection via dim(A)+dim(B)-dim(A+B)
dA=dim_span(chargeColour); dB=dim_span(electroweak); dAB=dim_span(chargeColour+electroweak)
print("\ndim(chargeColour + electroweak as subspace) =", dAB)
print("dim(intersection) = dA+dB-dAB =", dA+dB-dAB)

# What IS the intersection? compute explicit basis of intersection.
def intersection_basis(A,B):
    # vectors in flat 49-space; intersection of span(A) and span(B)
    # method: x = sum a_i A_i = sum b_j B_j -> [A | -B] coeff nullspace, take A-part
    nA=len(A); nB=len(B)
    Af=[flat(m) for m in A]; Bf=[flat(m) for m in B]
    rows=[]  # 49 equations, nA+nB unknowns: sum a_i Af_i - sum b_j Bf_j = 0
    for comp in range(49):
        row=[Af[i][comp] for i in range(nA)]+[-Bf[j][comp] for j in range(nB)]
        rows.append(row)
    ns=nullspace(rows,nA+nB)
    inter=[]
    for v in ns:
        M=[[F(0)]*7 for _ in range(7)]
        for i in range(nA):
            if v[i]!=0: M=addm(M,scal(v[i],A[i]))
        if not iszero(M): inter.append(M)
    return inter
inter=intersection_basis(chargeColour,electroweak)
print("intersection basis size (raw):", len(inter), " dim:", dim_span(inter) if inter else 0)
if inter:
    print("intersection == span{imRep DI = T3}? ", dim_span(inter+[DI])==dim_span(inter)==1)
    # verify each intersection element is a multiple of DI
    print("intersection ⊆ span{DI}:", all(dim_span([DI,m])==1 for m in inter))
    print("DI ∈ intersection:", dim_span(inter) >=1 and all(True for _ in [0]) )

print("\n=== the FORCING of DI ∈ colour su(3)_c (u1 one-cause) ===")
print("DI(u1)=0 ? (u1=hI, DI=innerD(hI))  [DI,Q]==0:", iszero(comm(DI,Q)))
print("=> imRep DI ∈ colourImg AND ∈ isospinImg => in BOTH reductive factors.")

print("\n=== the full internal Lie algebra generated by both factors ===")
def lie_closure(gens, cap=60):
    cur=[g for g in gens]; d=dim_span(cur)
    while True:
        new=list(cur)
        for i in range(len(cur)):
            for j in range(i+1,len(cur)): new.append(comm(cur[i],cur[j]))
        nd=dim_span(new)
        if nd==d: break
        d=nd; cur=new
        if d>=cap: break
    return d
print("dim ⟨chargeColour ∪ electroweak⟩_Lie =", lie_closure(chargeColour+electroweak), " (so(7)=21)")
print("dim(subspace span of both factors) =", dAB, " => they are NOT bracket-closed together (12<21)")

print("\n=== sanity: is T3=DI the UNIQUE shared direction (not Y, not Q, not DJ/DK)? ===")
for nm,M in [("Q",Q),("Y",Yh),("DJ",DJ),("DK",DK)]:
    inCC = dim_span(chargeColour+[M])==dim_span(chargeColour)
    inEW = dim_span(electroweak+[M])==dim_span(electroweak)
    print(f"  {nm}: in chargeColour={inCC}  in electroweak={inEW}  in BOTH={inCC and inEW}")
print("  DI: in chargeColour=",dim_span(chargeColour+[DI])==dim_span(chargeColour),
      " in electroweak=",dim_span(electroweak+[DI])==dim_span(electroweak))
