import Phys.Algebra.LorentzContinuumGenerationConverseCompactWord

#print axioms Phys.Algebra.genTwoPlaneLin_isQvIsomC
#print axioms Phys.Algebra.genTwoPlaneLin_isEvCAdjoint
#print axioms Phys.Algebra.genTwoPlaneLin_adjoint_comp_self
#print axioms Phys.Algebra.genTwoPlaneLin_compact_part_eq_self
#print axioms Phys.Algebra.genTwoPlaneLin_compact_part_mem_genLin
#print axioms Phys.Algebra.genTwoPlaneLin_compact_part_mem_gen2
#print axioms Phys.Algebra.genTwoPlaneLin_e2je2_compact_part_real_coord
