/-
  Counterexamples.DerivationSemisimpleModuleWrongCostume — N30a costume (must be REJECTED).
  ===========================================================================
  THE GARBAGE CLAIM for the N30a Lie→associative SEMISIMPLE-MODULE BRIDGE. N30a banks
  `semisimpleModule_imRep_adjoin`: for any Lie ideal `I` of `derivationLieQ`, the invariant
  7-rep `↥ImO` is a SEMISIMPLE module over the associative subalgebra
  `A_I := Algebra.adjoin ℚ (imRep '' I) ⊆ End ℚ ↥ImO` — every `A_I`-submodule has a
  complement (its `gBil.restrict ImO`-orthogonal, a genuine complement because the Born form is
  DEFINITE on `↥ImO`). This is N27's Born-orthogonal complete reducibility transported to the
  subalgebra; it is the fact the prime-7 / isotypic-Schur structure theorem (N30b) runs on.

  THE GARBAGE CLAIM the kernel MUST reject (anti-vacuity, W8): that `↥ImO` is NOT a semisimple
  `A_I`-module — `¬ IsSemisimpleModule A_I ↥ImO`. The banked forward result
  `semisimpleModule_imRep_adjoin I` PROVES it IS semisimple, so this negation is unprovable:
  `intro h` introduces the (true) semisimplicity hypothesis and leaves `⊢ False`, which cannot
  be discharged. If the orthogonal complement were NOT a genuine complement (the Born form
  degenerate on some subspace, an `A_I`-submodule with no complement), the bridge would be
  vacuous and this negation provable; W8 demands this bite.

  The manifest's PASS_SIGNATURE matches the elaboration error below (`⊢ False`).
-/
import Phys.Algebra.DerivationSemisimpleModule

namespace Counterexamples

open Phys.Algebra Phys.Cascade Phys.Cascade.CD LieAlgebra

attribute [local instance] CD.narCD CD.srCD dblModuleQ cdModuleQ
attribute [local instance] derivationLieQ_semisimple

/-- WRONG: claiming the invariant 7-rep `↥ImO` is NOT a semisimple module over the associative
    subalgebra `A_I` generated by the action of a Lie ideal `I`. The banked forward bridge
    `semisimpleModule_imRep_adjoin I` proves it IS semisimple, so after `intro h` the residual
    goal `⊢ False` cannot be discharged. Must FAIL to compile. -/
theorem semisimpleModule_imRep_adjoin_BOGUS (I : LieIdeal ℚ derivationLieQ) :
    ¬ IsSemisimpleModule
        (Algebra.adjoin ℚ (Set.range (fun x : I => imRep (I.incl x)))) ImO := by
  intro h

end Counterexamples
