import Phys.Algebra.LorentzContinuumOctStabilizerG2KleinFour

namespace Counterexamples

open Phys.Cascade Phys.Algebra
open Phys.Foundation Phys.Foundation.ContinuumQ

attribute [local instance] CD.narCD CD.srCD
attribute [local instance] Phys.Algebra.dblModuleCut

noncomputable section

-- WRONG (costume C173): A BOGUS COMPOSITION-GROUP / THIRD-AUTOMORPHISM / KLEIN-FOUR / GROUP-STRUCTURE /
-- GAUGE-STRUCTURE / G₂ / AUTOMORPHISM / NON-IDENTITY / INDEPENDENCE / STABILIZER / OCTONION-BLOCK /
-- SO(8)/G₂ / SO⁺(1,9)-STRUCTURE CLAIM — "THE THIRD (COMPOSITE) OCTONION AUTOMORPHISM's e₂ SELF-OVERLAP
-- READ-OFF IS 141, NOT 1".
-- N141 banks THE COMPOSITION GROUP ℤ/2 × ℤ/2 ⊂ G₂: the product octCompNeg := octTopNeg * octInnerNeg of
-- N139's outer Cayley–Dickson top-half negation and N140's inner one is a THIRD concrete series-free
-- non-identity octonion algebra-automorphism of the terminal algebra O Cut = CD (H Cut) (octCompNeg_isAlgAut
-- : IsAlgAutCut octCompNeg, via the general composition lever isAlgAutCut_trans). It NEGATES BOTH the outer
-- generator e₂ (octCompNeg_e2 : octCompNeg e₂ = −e₂) and the inner generator innerGen
-- (octCompNeg_innerGen : octCompNeg innerGen = −innerGen), so it is DISTINCT from id (octCompNeg_ne_refl),
-- from octTopNeg (octCompNeg_ne_octTopNeg, on innerGen) and from octInnerNeg (octCompNeg_ne_octInnerNeg,
-- on e₂) — a FOURTH distinct gauge element. The four maps {1, octTopNeg, octInnerNeg, octCompNeg} are each
-- an involution (octCompNeg_mul_self etc.), commute (octTopNeg_comm_octInnerNeg), and form a Subgroup
-- (kleinFour) of the linear-equivalence group generated by the two banked involutions (kleinFour_eq_closure),
-- every element of which squares to 1 (kleinFour_elem_involution) — a concrete ℤ/2 × ℤ/2 ⊂ G₂ = Aut(O);
-- octCompNeg's octonion-block embedding lands in the gauge stabilizer octStab (octBlockEndC_octCompNeg_mem_octStab).
--   THE READ-OFF: the THIRD (composite) non-identity gauge automorphism octCompNeg, like the other gauge
-- automorphisms, preserves the Born self-overlap of e₂, gFormC (octCompNeg e₂)(octCompNeg e₂) =
-- gFormC e₂ e₂ = 1 (octCompNeg_gFormC_e2_eq_one — octCompNeg is a gFormC-isometry, even though it negates e₂).
--   The BOGUS claim that this self-overlap is 141 (a stand-in for ANY wrong composition-group /
-- third-automorphism / Klein-four / group-structure / gauge-structure / G₂ / non-identity / independence /
-- stabilizer / octonion-block / SO(8)/G₂ / SO⁺(1,9)-structure claim: the composite automorphism fails to
-- preserve the Born form / is not a gFormC-isometry / fails to land in the stabilizer / is not actually
-- distinct from the other elements / the Klein-four table is wrong / the fixed/moved axis is mis-read)
-- forces (1 : Cut) = 141, and must NOT compile.
--   The bite is a true counterexample, not vacuous: octCompNeg_gFormC_e2_eq_one is a banked theorem (the
-- third automorphism's e₂ self-overlap GENUINELY reads 1 over the derived field), so the costume's claim of
-- 141 is genuinely FALSE.
--   The false numeric `(1 : Cut) = 141` is DISTINCT from the banked battery (… C170 1=138, C171 1=139,
-- C172 1=140).
--   PHYSICS-WORDS-REMOVABLE: delete "gauge/G₂/SO(8)/Spin(7)/automorphism/derivation/Aut/Lorentz/stabilizer/
-- octonion/observer/internal-symmetry/isometry/independence/composition/Klein-four/group": over the derived
-- complete ordered field `Cut`, O Cut := CD (H Cut), H Cut := CD (Dbl Cut), the Born form gFormC, and the
-- multiplicative-unital Cut-linear self-equiv octCompNeg (⟨⟨p,q⟩,⟨r,s⟩⟩ ↦ ⟨⟨p,−q⟩,⟨−r,s⟩⟩, the composite of
-- the two top-half negations), the scalar gFormC (octCompNeg ⟨⟨0,1⟩,0⟩) (octCompNeg ⟨⟨0,1⟩,0⟩) = 1; claiming
-- 141 forces the false numeric. The bite is a false NUMERIC, name-independent.

/-- BOGUS: the THIRD (composite) non-identity octonion algebra-automorphism `octCompNeg`
    (`= octTopNeg * octInnerNeg`, the composite Cayley–Dickson involution) preserves `e₂`'s Born
    self-overlap read-off `1` (`octCompNeg_gFormC_e2_eq_one`). The WRONG claim that it reads `141`
    (the composite automorphism fails to preserve the form / is not a `gFormC`-isometry / fails to land
    in the gauge stabilizer / is not distinct from the other gauge elements / the Klein-four table is
    wrong) forces the false numeric `(1 : Cut) = 141`, so this must NOT compile. -/
theorem oct_stabilizer_g2_kleinfour_wrong_overlap_BOGUS :
    gFormC (octCompNeg (CD.e2 : O Cut)) (octCompNeg (CD.e2 : O Cut)) = (141 : Cut) := by
  rw [octCompNeg_gFormC_e2_eq_one]

end

end Counterexamples
