/-
  Counterexamples.StandpointArtinVacuityCostume — N### arc-R R7b anti-vacuity (C477).
  ============================================================================================
  W8 ANTI-VACUITY. The R7b node (arc-R R7b — THE GENERATED-SUBALGEBRA ARTIN THEOREM) has genuine
  content only if the LITERAL two-generated subalgebra `NonUnitalAlgebra.adjoin ℚ {a,b}` on the
  banked `O ℚ` is contained in the linear content `span{1,a,b,a·b}` AND that content genuinely
  associates — while the arity-3 obstruction is still genuinely present:
  (1) THE CONTAINMENT: `adjoin ℚ {a,b} ⊆ span{1,a,b,a·b}` (`adjoin_pair_mem_content`), via the
      quadratic norm-scalar closure (`o_quad_rel` from the banked `selfMul`/`Nrm`) + the linearized
      alternative products (`o_a_mul_ab`/`o_ab_mul_b`/…);
  (2) THE ARTIN COROLLARY: every subalgebra generated by two elements associates
      (`twoGenerated_associates`, composing the containment with the banked `assoc_span4_vanishes`);
  (Σ) the non-hollow capstone (`generatedSubalgebra_artin`) bundles (1) ∧ (2) ∧ the banked
      triples-tear (`arity3_tear`) — so the Artin fact sits AGAINST the genuine obstruction.
  A mis-reading where the two-generated subalgebra were NOT contained in the four-dimensional content
  (the quadratic closure failing — products escaping the span), or where that content did NOT
  associate, or where the arity-3 tear were secretly vacuous (`O ℚ` associative), would gut R7b:
  the Artin theorem would be empty or trivially true of an associative algebra.

  THE CERTIFICATE. `cFlag := 1` — a ℕ flag standing for "the R7b generated-subalgebra Artin theorem
  is genuine: the two-generated subalgebra is contained in its four-dimensional content, that
  content associates, and the arity-3 obstruction is nonetheless genuinely present". It is TIED to
  the banked R7b landing by `cFlag_forced` through `adjoin_pair_mem_content`,
  `twoGenerated_associates`, and `generatedSubalgebra_artin`.

  We anchor `min 477 cFlag = 1` (TRUE — `cFlag = 1 < 477`, so the min is `cFlag`).

  THE BOGUS CLAIM (a stand-in for ANY "the subalgebra escapes its content / the content does not
  associate / the Artin theorem is vacuous" mis-reading): that `min 477 cFlag = 477`. It GENUINELY
  equals `1`. Rewriting reduces the bogus claim to the false numeric `1 = 477` in ℕ. The kernel
  cannot close it; it BITES.

  DISTINCT from the banked battery: the pair (477, 1) is fresh (Cid 477 distinct from every prior).

  This file MUST FAIL to compile.
-/
import Phys.Algebra.StandpointArtin
import Mathlib.Tactic

namespace Counterexamples

open Phys.Algebra

/-- THE R7b-NON-VACUITY FLAG: `1` = "the generated-subalgebra Artin theorem is genuine: the
    two-generated subalgebra is contained in span{1,a,b,a·b}, that content associates, and the
    arity-3 obstruction is nonetheless genuinely present". -/
def cFlag : ℕ := 1

/-- TRUE (tied to the banked R7b landing): `cFlag = 1`, and the proof GENUINELY DEPENDS on the
    load-bearing R7b landings — the containment (`adjoin_pair_mem_content`), the Artin corollary
    (`twoGenerated_associates`), and the non-hollow capstone (`generatedSubalgebra_artin`). If any
    were hollow, those decls would not exist and this could not compile. -/
theorem cFlag_forced : cFlag = 1 := by
  have _ := @adjoin_pair_mem_content
  have _ := @twoGenerated_associates
  have _ := @generatedSubalgebra_artin
  rfl

/-- TRUE: `min 477 cFlag = 1`, holding precisely because `cFlag = 1 < 477`. -/
theorem cons_val_true : min (477 : ℕ) cFlag = 1 := by decide

/-- BOGUS: claims `min 477 cFlag = 477`. It GENUINELY equals `1` (`cons_val_true`). A "subalgebra
    escapes its content / content does not associate / Artin theorem is vacuous" mis-reading
    reduces — through the banked R7b landing — to the false numeric `1 = 477`, so this must NOT
    compile. -/
theorem cons_val_wrong_BOGUS :
    min (477 : ℕ) cFlag = 477 := by
  rw [cons_val_true]
  -- ⊢ (1 : ℕ) = 477  (FALSE — the costume bites)

end Counterexamples
