/-
  Counterexamples.TowerGatherGenerateSo7WrongValueCostume — N260 anti-vacuity (C291).
  ===========================================================================
  W8 ANTI-VACUITY. The N260 node banks THE GATHER TEAR REGENERATES THE AMBIENT: over the derived
  octonion rung `O ℚ = CD (H ℚ)`, fundamental 7 = `ImO`, the gather-tear fundamental-7
  (`range crossEmb`, N225) LIE-GENERATES the whole derived `so(7) = skewAdjointLieSubalgebra bornBil`.
  The generated Lie subalgebra `lieGenCross := LieSubalgebra.lieSpan ℚ _ (↑(range crossEmb))` equals
  the ambient so(7) (`crossEmb_lieSpan_eq_so7`), so the 14-dim derivation algebra g₂ (`range imRepL`,
  the adjoint the field POSITS as the structure group) is REGENERATED from brackets of the 7
  (`range_imRepL_le_lieGenCross`), forced by the g₂-irreducibility of the adjoint 14
  (`imRepL_range_no_proper_invariant`).

  The load-bearing quantitative fact — the W8 TEETH anchoring the "the 7 generates ALL of so(7)"
  claim — is that the generated subalgebra fills EXACTLY all `21` dimensions of so(7)
  (`finrank_lieSpan_crossEmb : finrank ℚ lieGenCross.toSubmodule = 21`). NOT smaller (the 7 would
  fail to generate the full ambient — the tear would NOT regenerate g₂). This exact dimension is
  precisely the forced fact that the fundamental-7 tear Lie-generates the entire simple ambient.

  The anchor is that genuine dimension, packaged as the clean equality
  `min 291 (finrank ℚ lieGenCross.toSubmodule) = 21` (which holds precisely BECAUSE
  `finrank_lieSpan_crossEmb = 21`, so `min 291 21 = 21`).

  THE BOGUS CLAIM (a stand-in for ANY wrong reading: the 7 does NOT generate all of so(7) / the
  generated algebra is smaller than 21 / the adjoint 14 is NOT regenerated from the 7): that
  `min 291 (finrank ℚ lieGenCross.toSubmodule)` equals `291`. It GENUINELY equals `21`
  (`generateSo7_finrank_true`). Rewriting the banked value reduces the bogus claim to the false
  numeric `21 = 291` in ℕ. The kernel cannot close it; the costume BITES (exit 1).

  The bite is name-independent: delete every comment and for `O ℚ = CD (H ℚ)`, the Lie subalgebra
  generated by `range crossEmb` inside `Module.End ℚ ImO` has `finrank ℚ … = 21`, so
  `min 291 (finrank …) = 21`, and claiming it equals `291` is genuinely FALSE (21 ≠ 291).

  DISTINCT from the banked battery (… C289 = 4=289, C290 = 1=290): the pair (291, 21) is fresh (RHS
  291 distinct from every prior right-hand value; the LHS anchor is the N260 generation DIMENSION
  `21` — the tear-fills-the-ambient TEETH — DIFFERENT from C290's N259 shared-Cartan intersection
  dimension `1`, C289's N258 electroweak reductive dimension `4`, C288's N257 gather-isometry scale
  `−6`; here the anchor is the FORCED 21-dimensionality of the Lie subalgebra GENERATED by the
  fundamental-7 tear, never before costumed).

  This file MUST FAIL to compile.
-/
import Phys.Algebra.TowerGatherGenerateSo7

namespace Counterexamples

open Phys.Algebra
open Phys.Cascade Phys.Cascade.CD

attribute [local instance] CD.narCD CD.srCD dblModuleQ cdModuleQ

/-- TRUE: `min 291 (finrank ℚ lieGenCross.toSubmodule) = 21`, holding precisely because the
    gather-tear fundamental-7 Lie-generates all `21` dims of the derived so(7) (banked
    `finrank_lieSpan_crossEmb`). -/
theorem generateSo7_finrank_true :
    min (291 : ℕ) (Module.finrank ℚ (lieGenCross.toSubmodule
      : Submodule ℚ (Module.End ℚ ImO))) = 21 := by
  rw [finrank_lieSpan_crossEmb]; norm_num

/-- BOGUS: claims `min 291 (finrank ℚ lieGenCross.toSubmodule) = 291`. It GENUINELY equals `21`
    (`generateSo7_finrank_true`). The WRONG claim (the 7 does not generate all of so(7) / the
    generated algebra is smaller than 21 / the adjoint 14 is not regenerated) reduces — through the
    banked value — to the false numeric `21 = 291`, so this must NOT compile. -/
theorem generateSo7_finrank_wrong_BOGUS :
    min (291 : ℕ) (Module.finrank ℚ (lieGenCross.toSubmodule
      : Submodule ℚ (Module.End ℚ ImO))) = 291 := by
  rw [generateSo7_finrank_true]
  -- ⊢ (21 : ℕ) = 291  (FALSE — the costume bites)

end Counterexamples
