/-
  PROBE 1 (N357) — TIER 1: assemble the FULL covariant derivative ∇_k = D_k + ⁅Γ_k, ·⁆
  (the fold's TWO faces: C6 eternal-approach directional derivative N350 + look-back transport
  commutator N356), and prove ∇g = 0 (full metric-compatibility, BOTH layers vanish on the
  raised metric = identity), hence the cosmological term Λ·g is divergence-free.

  Measured pieces:
    - N350 const_opderiv : HasOpDerivAt0 (fun _ => A) 0     (derivative half of ∇(id) = 0)
    - N356 metric_covTransport_zero : covTransport k id = 0  (bracket half of ∇(id) = 0)
-/
import Phys.Algebra.SpacetimeDivergence
import Phys.Algebra.SpacetimeOperatorDerivative

namespace Phys.Algebra

open Phys.Cascade Phys.Cascade.CD
open Phys.Foundation Phys.Foundation.ContinuumQ
open Filter Set
open scoped Topology

attribute [local instance] CD.narCD CD.srCD
attribute [local instance] Phys.Algebra.dblModuleCut

noncomputable section

/-- THE FULL COVARIANT DERIVATIVE of an operator-valued field `H : Cut → MetricEnd` along the
    parameter, with the connection generated by metric variation `k`. It is the SUM of the two
    banked layers: the directional (C6) derivative `dH` (N350 `HasOpDerivAt0 H dH`) plus the
    look-back transport commutator `covTransport k (H 0) = ⁅Γk, H 0⁆` (N356). -/
def HasCovDerivAt0 (H : Cut → MetricEnd) (k : MetricEnd) (r : MetricEnd) : Prop :=
  ∃ dH : MetricEnd, HasOpDerivAt0 H dH ∧ r = dH + covTransport k (H 0)

/-- ★ FULL METRIC-COMPATIBILITY ∇g = 0: the raised metric is the CONSTANT identity field; both
    layers vanish — derivative half `const_opderiv` (0), bracket half `metric_covTransport_zero`
    (0). So the covariant derivative of the metric is exactly 0. -/
theorem metric_covDeriv_zero (k : MetricEnd) :
    HasCovDerivAt0 (fun _ => (LinearMap.id : MetricEnd)) k 0 := by
  refine ⟨0, const_opderiv _, ?_⟩
  rw [metric_covTransport_zero]
  simp

end

end Phys.Algebra
