"""
The polarization CORE of the middle third:  H (Nrm mult on CD A)  ==>  L(x,y)=0,
where L(x,y) = x*(star x * y) - iota(Nrm x)*y  (left scaling law).

Classical Hurwitz derivation of the scaling law from the composition law uses the
bilinear identities P1/P2 plus the "adjoint" identity bilin(x*y,z)=bilin(y, star x * z).
We test, symbolically over the FREE associative *-ring B on p,q (B=base of CD B; then
work in CD B and CD(CD B)) whether:

  (Adj)   bilin(u*v, w) = bilin(v, star u * w)        is forced by H, and
  the scaling law L follows by nondegeneracy of bilin.

Concretely we test, over CD(CD B) with B free associative *-ring:
  - Is the ADJOINT identity Adj a consequence of H? (compute bilin(uv,w)-bilin(v,star u*w)
    as a polynomial; is it in the ideal generated by the polarized defects?)
We instead do the cheaper CONCRETE confirmation over O=CD(H) (where H holds, base assoc):
  Adj holds on O; and on O, L=0; the question for Lean is the IDENTITY route, which is:
     bilin(L(x,y), w) =? 0 for all w   (nondegeneracy then gives L=0).
Compute bilin(L(x,y),w) and check it vanishes IDENTICALLY given the P-identities.
"""
from fractions import Fraction as Fr
import random

class Alg:
    def __init__(s,add,neg,mul,star,zero,one,dim):
        s.add=add;s.neg=neg;s.mul=mul;s.star=star;s.zero=zero;s.one=one;s.dim=dim
    def sub(s,x,y): return s.add(x,s.neg(y))
Rr=Alg(lambda a,b:a+b,lambda a:-a,lambda a,b:a*b,lambda a:a,Fr(0),Fr(1),1)
def CD(K):
    Z=(K.zero,K.zero); one=(K.one,K.zero)
    def add(z,w): return (K.add(z[0],w[0]),K.add(z[1],w[1]))
    def neg(z): return (K.neg(z[0]),K.neg(z[1]))
    def mul(z,w):
        a,b=z;c,d=w
        return (K.sub(K.mul(a,c),K.mul(K.star(d),b)), K.add(K.mul(d,a),K.mul(b,K.star(c))))
    def star(z): return (K.star(z[0]),K.neg(z[1]))
    return Alg(add,neg,mul,star,Z,one,2*K.dim)
C=CD(Rr); H=CD(C); O=CD(H); S=CD(O)
def flatten(z):
    if isinstance(z,Fr): return [z]
    return flatten(z[0])+flatten(z[1])
def build(vs):
    if len(vs)==1: return vs[0]
    h=len(vs)//2; return (build(vs[:h]),build(vs[h:]))
def rndK(K): return build([Fr(random.randint(-3,3)) for _ in range(K.dim)])
def eq(K,u,v): return all(x==y for x,y in zip(flatten(u),flatten(v)))
def iota(K,a): return (a, K.zero[0])
def Nrm(K,z): return K.mul(z,K.star(z))[0]
# bilin in CD A returns base element: (x*star y + y * star x).re
def bilin(K,x,y): return K.add(K.mul(x,K.star(y)), K.mul(y,K.star(x)))[0]
def L(K,x,y): return K.sub(K.mul(x,K.mul(K.star(x),y)), K.mul(iota(K,Nrm(K,x)),y))

random.seed(202)
print("=== On O (H holds): does bilin(L(x,y), w) vanish identically? (=> nondegen gives L=0) ===")
# Here K=O=CD(H). bilin lives in H (base). Check bilin_O(L(x,y),w)=0 for random x,y,w.
cnt=0;T=300
for _ in range(T):
    x=rndK(O);y=rndK(O);w=rndK(O)
    val=bilin(O, L(O,x,y), w)
    if not eq(H, val, H.zero): cnt+=1
print(f"  bilin(L(x,y),w) != 0 : {cnt}/{T}  (0 => L is bilin-orthogonal to everything on O)")

print()
print("=== The ADJOINT identity: bilin(u*v,w) = bilin(v, star u * w) on O (H holds)? ===")
cnt=0
for _ in range(T):
    u=rndK(O);v=rndK(O);w=rndK(O)
    lhs=bilin(O, O.mul(u,v), w)
    rhs=bilin(O, v, O.mul(O.star(u),w))
    if not eq(H, lhs, rhs): cnt+=1
print(f"  Adj fails {cnt}/{T} on O")

print()
print("=== Does Adj hold on S too (no H there)? (tells if Adj is H-free or needs H) ===")
cnt=0
for _ in range(T):
    u=rndK(S);v=rndK(S);w=rndK(S)
    lhs=bilin(S, S.mul(u,v), w)
    rhs=bilin(S, v, S.mul(S.star(u),w))
    if not eq(O, lhs, rhs): cnt+=1
print(f"  Adj fails {cnt}/{T} on S  (if 0: Adj is a STRUCTURAL identity, H-free!)")
