"""
N2d — THE THEORY-NATIVE REFRAME (W1 step 2).

The bare *-ring defect carries commutator junk. THE ONE LAW: return to the trunk.
The trunk is Born = self-overlap = scalar positivity: in the cascade, x·star x is a
SCALAR (central) and t(x)=x+star x is scalar. Impose THOSE relations and recompute
the A-valued norm defect; check whether it dissolves to a clean base ASSOCIATOR.

Model: free *-ring on imaginary gens g_i (g_i* = -g_i), but evaluate the defect on
the ACTUAL cascade base O (level 3), which HAS central scalar self-overlaps
(verified: born_central holds on O). On O the defect must therefore reveal the pure
associator structure. We compute, for base elements p,q,r,s in O, the defect of
x=(p,q), y=(r,s) and correlate it EXACTLY with base associators.
"""
from fractions import Fraction as Fr
import itertools, random

L=3  # octonion base O
def z0(k): return Fr(0) if k==0 else (z0(k-1),z0(k-1))
def radd(x,y,k): return x+y if k==0 else (radd(x[0],y[0],k-1),radd(x[1],y[1],k-1))
def rneg(x,k): return -x if k==0 else (rneg(x[0],k-1),rneg(x[1],k-1))
def rsub(x,y,k): return radd(x,rneg(y,k),k)
def rstar(x,k): return x if k==0 else (rstar(x[0],k-1),rneg(x[1],k-1))
def rmul(x,y,k):
    if k==0: return x*y
    a,b=x;c,d=y
    return (radd(rmul(a,c,k-1),rneg(rmul(rstar(d,k-1),b,k-1),k-1),k-1),
            radd(rmul(d,a,k-1),rmul(b,rstar(c,k-1),k-1),k-1))
def is0(x,k): return x==0 if k==0 else (is0(x[0],k-1) and is0(x[1],k-1))
def eq(x,y,k): return is0(rsub(x,y,k),k)
def basis(k,i):
    if k==0: return Fr(1)
    h=2**(k-1)
    return (basis(k-1,i),z0(k-1)) if i<h else (z0(k-1),basis(k-1,i-h))
def assoc(x,y,w,k): return rsub(rmul(rmul(x,y,k),w,k), rmul(x,rmul(y,w,k),k), k)
def rand(k,lo=-2,hi=2): return Fr(random.randint(lo,hi)) if k==0 else (rand(k-1,lo,hi),rand(k-1,lo,hi))

# A-valued norm on CD(O): Nrm(z)=z.re·star(z.re)+star(z.im)·z.im ∈ O
def Nrm(z):
    a,b=z
    return radd(rmul(a,rstar(a,L),L), rmul(rstar(b,L),b,L), L)
def cd_mul(z,w):
    a,b=z;c,d=w
    return (rsub(rmul(a,c,L),rmul(rstar(d,L),b,L),L),
            radd(rmul(d,a,L),rmul(b,rstar(c,L),L),L))
def Ddef(x,y):
    return rsub(Nrm(cd_mul(x,y)), rmul(Nrm(x),Nrm(y),L), L)

# 1) On O (central scalar self-overlap), is the A-valued defect ALWAYS a combination
#    of associators? Test: defect for random x,y; compare to associator span.
# Cleaner: test the EASY direction holds when base is ASSOCIATIVE.
#   O is NOT associative. But its sub-*-algebra generated by <=2 elements IS
#   associative (alternative). So if x,y use base elements from an associative
#   subalgebra, defect should be 0.

# pick two octonion units that generate an associative (quaternionic) subalgebra:
# e1,e2,e3 with e1*e2=e3 form a quaternion triple (associative).
print("Test EASY direction on associative subalgebra of O (quaternionic triple e1,e2,e3):")
quat_units=[0,1,2,3]  # 1,e1,e2,e3 span an associative ℍ inside O
fails=0; tot=0
for _ in range(300):
    # random elements of the ℍ-subalgebra
    def rquat():
        v=z0(L)
        for i in quat_units:
            v=radd(v, rmul({0:Fr(1)}.get(0,Fr(1)) and Fr(random.randint(-2,2)) or Fr(0), basis(L,i) if False else basis(L,i), 0) if False else
                   (lambda c,e: tuple_scale(c,e,L))(Fr(random.randint(-2,2)), basis(L,i)), L)
        return v
    # simpler: build via coefficient dict
    pass
print("  (skipped messy builder; using direct coefficient elements below)")

def elem(coeffs):
    """octonion element from dict {index:coeff}."""
    v=z0(L)
    for i,c in coeffs.items():
        e=basis(L,i)
        v=radd(v, scale(c,e,L), L)
    return v
def scale(c,x,k):
    return c*x if k==0 else (scale(c,x[0],k-1),scale(c,x[1],k-1))

# EASY direction on ℍ-subalgebra (indices 0,1,2,3 = 1,e1,e2,e3, associative):
fails=0
for _ in range(500):
    cs1={i:Fr(random.randint(-2,2)) for i in [0,1,2,3]}
    cs2={i:Fr(random.randint(-2,2)) for i in [0,1,2,3]}
    cs3={i:Fr(random.randint(-2,2)) for i in [0,1,2,3]}
    cs4={i:Fr(random.randint(-2,2)) for i in [0,1,2,3]}
    x=(elem(cs1),elem(cs2)); y=(elem(cs3),elem(cs4))
    if not is0(Ddef(x,y),L): fails+=1
print(f"  defect on CD(ℍ-subalgebra): fails {fails}/500 -> {'MULTIPLICATIVE (easy dir holds on assoc base)' if fails==0 else 'BROKEN'}")

# HARD direction: use elements spanning a NON-associative triple (need e1,e2,e4 etc.)
print("\nTest defect when base elements span a NON-associating triple (e1,e2,e4):")
fails=0; tot=0
for _ in range(500):
    cs1={i:Fr(random.randint(-2,2)) for i in [0,1,2,4]}
    cs2={i:Fr(random.randint(-2,2)) for i in [0,1,2,4]}
    cs3={i:Fr(random.randint(-2,2)) for i in [0,1,2,4]}
    cs4={i:Fr(random.randint(-2,2)) for i in [0,1,2,4]}
    x=(elem(cs1),elem(cs2)); y=(elem(cs3),elem(cs4))
    if not is0(Ddef(x,y),L): fails+=1; tot+=1
print(f"  defect on CD(non-assoc span): fails {fails}/500 -> {'BREAKS (hard dir: nonassoc => law fails)' if fails>0 else 'still multiplicative?!'}")
