"""
N2d — THE THEORY-NATIVE REFRAME, done right (W1 step 2 / THE ONE LAW).

Impose the TRUNK structure (Born = self-overlap = scalar positivity): the base A is
a CONJUGATION algebra — every element satisfies  star a = t(a) - a  with t(a) a
CENTRAL scalar (so a + star a and a·star a are central). This is the quadratic
minimal-polynomial structure the whole cascade carries (ℝ,ℂ,ℍ,𝕆 are all quadratic).

Under it, recompute the A-valued norm defect D(x,y)=Nrm(xy)-Nrm(x)Nrm(y) and check
it collapses to a clean base ASSOCIATOR. If yes, the FORCED LINK is clean:
  on conjugation algebras,  Nrm multiplicative on CD A  ⟺  A associative.

We model with sympy: base generators p,q,r NONcommutative & NONassociative is hard
in sympy (it assumes associativity). So instead we VERIFY numerically on the actual
cascade base O (which IS a conjugation algebra, alternative, central self-overlaps),
that the defect is governed purely by base associators, by checking:

  CLAIM: for x=(a,b), y=(c,d) in CD(O),  Nrm(xy) - Nrm(x)Nrm(y)  lies in the linear
  span of base associators [u,v,w] of the components — and is ZERO iff all the
  relevant base triples associate.
"""
from fractions import Fraction as Fr
import itertools, random

L=3
def z0(k): return Fr(0) if k==0 else (z0(k-1),z0(k-1))
def radd(x,y,k): return x+y if k==0 else (radd(x[0],y[0],k-1),radd(x[1],y[1],k-1))
def rneg(x,k): return -x if k==0 else (rneg(x[0],k-1),rneg(x[1],k-1))
def rsub(x,y,k): return radd(x,rneg(y,k),k)
def rstar(x,k): return x if k==0 else (rstar(x[0],k-1),rneg(x[1],k-1))
def rmul(x,y,k):
    if k==0: return x*y
    a,b=x;c,d=y
    return (radd(rmul(a,c,k-1),rneg(rmul(rstar(d,k-1),b,k-1),k-1),k-1),
            radd(rmul(d,a,k-1),rmul(b,rstar(c,k-1),k-1),k-1))
def is0(x,k): return x==0 if k==0 else (is0(x[0],k-1) and is0(x[1],k-1))
def eq(x,y,k): return is0(rsub(x,y,k),k)
def basis(k,i):
    if k==0: return Fr(1)
    h=2**(k-1)
    return (basis(k-1,i),z0(k-1)) if i<h else (z0(k-1),basis(k-1,i-h))
def scale(c,x,k): return c*x if k==0 else (scale(c,x[0],k-1),scale(c,x[1],k-1))
def assoc(x,y,w,k): return rsub(rmul(rmul(x,y,k),w,k), rmul(x,rmul(y,w,k),k), k)

def Nrm(z):
    a,b=z
    return radd(rmul(a,rstar(a,L),L), rmul(rstar(b,L),b,L), L)
def cd_mul(z,w):
    a,b=z;c,d=w
    return (rsub(rmul(a,c,L),rmul(rstar(d,L),b,L),L),
            radd(rmul(d,a,L),rmul(b,rstar(c,L),L),L))
def Ddef(x,y):
    return rsub(Nrm(cd_mul(x,y)), rmul(Nrm(x),Nrm(y),L), L)

# CLAIM 1 (FORCED-LINK contrapositive, the one I most want to bank):
#   if ALL base triples among {x.re,x.im,y.re,y.im} associate, then Ddef(x,y)=0;
#   and there EXIST x,y (from non-associating units) with Ddef≠0.
# Test: random x,y from a 2-generated (=> associative, alternative) subalgebra => D=0.
print("REFRAME RESULT 1 — easy direction on conjugation base, 2-generated (assoc) subalgebra:")
def two_gen_elem(u,v):
    # random element of subalgebra generated by units e_u,e_v and 1  (associative)
    idxs=sorted({0,u,v, })
    # the quaternion subalgebra <1,e_u,e_v,e_u*e_v>; compute e_u*e_v index by product
    euv=rmul(basis(L,u),basis(L,v),L)
    base_elems=[basis(L,0),basis(L,u),basis(L,v),euv]
    v_=z0(L)
    for be in base_elems:
        v_=radd(v_, scale(Fr(random.randint(-2,2)),be,L), L)
    return v_
fails=0
for _ in range(400):
    u,v=random.sample([1,2,3,4,5,6,7],2)
    x=(two_gen_elem(u,v),two_gen_elem(u,v)); y=(two_gen_elem(u,v),two_gen_elem(u,v))
    if not is0(Ddef(x,y),L): fails+=1
print(f"   x,y in CD(<2 generators>):  defect fails {fails}/400 -> "
      f"{'MULTIPLICATIVE (assoc base => law holds)' if fails==0 else 'BROKEN'}")

print("\nREFRAME RESULT 2 — hard direction: components from a NON-associating triple break it:")
# use three units whose triple does NOT associate, e.g. e1,e2,e4
got=0
for _ in range(2000):
    comps=[]
    for _ in range(4):
        v_=z0(L)
        for i in [1,2,4]:
            v_=radd(v_, scale(Fr(random.randint(-1,1)),basis(L,i),L), L)
        comps.append(v_)
    x=(comps[0],comps[1]); y=(comps[2],comps[3])
    if not is0(Ddef(x,y),L): got+=1
print(f"   x,y components in span(e1,e2,e4) [non-assoc triple]: defect NONZERO in {got}/2000 samples")
print("   => non-associativity of the base BREAKS the composition law (forced link, contrapositive).")

# CLAIM 3: the cleanest WITNESS — pure basis components, the N2c structure.
print("\nREFRAME RESULT 3 — cleanest witnesses (pure-unit components), tie to base associator:")
imag=list(range(1,8))
examples=[]
for a4 in itertools.product(imag,repeat=4):
    x=(basis(L,a4[0]),basis(L,a4[1])); y=(basis(L,a4[2]),basis(L,a4[3]))
    if not is0(Ddef(x,y),L):
        examples.append(a4)
print(f"   pure-unit biting witnesses: {len(examples)}; e.g. {examples[:3]}")
# for the first, show the responsible base associator is nonzero
a4=examples[0]
trip=(a4[0],a4[1],a4[2])
print(f"   first witness {a4}: base triple {trip} associates? "
      f"{is0(assoc(basis(L,trip[0]),basis(L,trip[1]),basis(L,trip[2]),L),L)}")
