#!/usr/local/bin/python3
import io

path = "docs/ROADMAP.md"
with io.open(path, "r", encoding="utf-8") as f:
    text = f.read()

# The block to replace: from the N76 FORWARD FRONTIER bullet to just before the
# "- then the remaining gauge/flavour/spacetime nodes" line.
start_anchor = "  - **\u2605 (FORWARD FRONTIER \u2014 the immediate next node, N76) THE EIGENVECTOR HALF OF THE 3-DIM SEED \u2014"
end_anchor = "  - then the remaining gauge/flavour/spacetime nodes"

si = text.find(start_anchor)
ei = text.find(end_anchor)
assert si != -1, "start anchor not found"
assert ei != -1, "end anchor not found"

new_block = (
"  - **\u2605 N76 LANDED RETROSPECTIVE \u2014 THE EIGENVECTOR HALF OF THE 3-DIM SEED over the DERIVED \u211d `Cut`\n"
"    and the terminal algebra `O Cut` (`Phys/Algebra/LorentzContinuumSeedVector.lean`, 9 decls\n"
"    foundations-only [propext, Classical.choice, Quot.sound], independently axiom-audited against the\n"
"    built olean; gate D0\u2013D6 GREEN, costume C107 `6 = 13`).** THE W1 REFRAME + W9 MEASURE-FIRST\n"
"    (ROADMAP \u00a7N76 priority (i)) + W3 DECOMPOSE: the ticket TARGET was the HEAVY group-manifold core\n"
"    (the eigenvector half, the full existence `\u2200 g, \u2203 c u, g = specOpN c u`, the GLOBAL polar/KAK\n"
"    assembly, connectedness, the GLOBAL reverse KAK surjectivity, the full `Spin(9)\u2192SO(9)` exhaustion);\n"
"    MEASURE-FIRST banked the EIGENVECTOR half HERE and confirmed the full-existence ASSEMBLY +\n"
"    connectedness/surjectivity/exhaustion are the genuine HEAVY group-manifold sub-nodes (childed N77).\n"
"    THE GAP this node closed: N75 banked the EIGENVALUE half of the 3-dim seed (a root of the\n"
"    characteristic CUBIC, via `cut_cubic_has_root`); the N70 `deflateC` engine takes the eigen-equation\n"
"    `T v = \u03bb \u2022 v` as its hypothesis, so the MISSING ingredient was a NONZERO `v` satisfying it \u2014 the\n"
"    eigenVECTOR. THE REFRAME (THE ONE LAW): the eigenvector is NOT a determinant-cofactor coordinate\n"
"    grind and NOT a new posit \u2014 it DISSOLVES through Mathlib's general eigenspace machinery APPLIED TO\n"
"    THE DERIVED FIELD `Cut` (STANDARD \u00a73: Mathlib as MACHINERY on a DERIVED object, never as content):\n"
"    a root `\u03bb` of the characteristic polynomial makes the eigenspace nonzero\n"
"    (`Module.End.hasEigenvalue_iff_isRoot_charpoly`), whence a nonzero eigenvector\n"
"    (`HasEigenvalue.exists_hasEigenvector`). BANKED: the prerequisite finite-dimensionality lever\n"
"    `Module.Finite Cut STVC` via the structural `Cut`-linear product equivalences of the cascade rungs\n"
"    `2\u21924\u21928` (`dblProdEquivCut`/`hProdEquivCut`/`oProdEquivCut`, mirroring the banked \u211a route\n"
"    `DerivationFinrank.cdProdEquiv`, NO coordinate basis matrix); `monic_cubic_poly_has_root` (the N75\n"
"    chain joint \u2014 a monic degree-3 polynomial over `Cut` has a root, `cut_cubic_has_root` consumed in\n"
"    `Polynomial` form via `eval_eq_sum_range`); \u2605\u2605 the NON-VACUOUS `dim3_has_eigenvector` (EVERY\n"
"    endomorphism of a 3-dim `Cut`-vector space has a NONZERO `v` with `T v = \u03bb \u2022 v` \u2014 the `natDegree = 3`\n"
"    DERIVED from `finrank`, NOT assumed, so the seed eigenPAIR is completed exactly at the dimension\n"
"    where the cubic root first bites, beyond the 2\u00d72 discriminant radical that topped out N65/N72); and\n"
"    \u2605 the HEADLINE `stvc_eigenvector_of_charpoly_root` (any characteristic-polynomial root `\u03bb` of an\n"
"    endomorphism of the 10-dim `STVC = Cut \u00d7 Cut \u00d7 O Cut` yields a NONZERO `v` with `T v = \u03bb \u2022 v` \u2014 the\n"
"    eigenvalue\u2192eigenvector closure over the genuine product space, the entry the N70 `deflateC` / N74\n"
"    iterated descent consume). DERIVED entirely from the trunk \u2014 the field IS the derived `Cut`, the\n"
"    finite-dimensionality DESCENDS structurally from the cascade rungs `2\u21924\u21928`, and the eigenvalue is\n"
"    the N75 cubic root that descends from the order-completeness the continuum was built with (the three\n"
"    levers each compiled clean in a scratch probe \u22649s \u2014 Finite STVC 8.8s, dim3 seed + STVC eigenvector\n"
"    7.7s, monic cubic joint 7.5s; production \u22647s, all 9 decls foundations-only at first compile,\n"
"    KILL=45s/obligation never approached, NO inflated maxHeartbeats / NO native_decide / NO brute; no\n"
"    name collisions). NO `import Mathlib.Data.Real`/`Complex`, NO posited field, NO posited operator\n"
"    calculus, NO posited Lorentz group. Costume C107 (`LorentzContinuumSeedVectorWrongEigenvalueCostume`)\n"
"    bites a WRONG eigenvalue read off a genuine eigen-equation over `STVC` \u2014 the scaling endomorphism\n"
"    `6 \u2022 id` applied to `v0 = (1,0,0)` has eigen-equation first coordinate `6`; a bogus claim it were\n"
"    `13` forces `6 = 13` (distinct from C84 `8=4`, \u2026, C105 `25=13`, C106 `8=27`). Words-removable: delete\n"
"    \"Lorentz/boost/rotation/spectral/eigenvalue/eigenvector/eigenpair/characteristic/cubic/seed/dimension/\n"
"    rank/Spin/SO(9)/KAK/polar/Cartan/isometry\" \u2192 over the derived field `Cut` and the Cayley\u2013Dickson\n"
"    double\u00b3 `O Cut`, the product space `STVC` is a finite-dimensional `Cut`-vector space, every monic\n"
"    degree-3 polynomial over `Cut` has a root, every endomorphism of a 3-dim `Cut`-space has a nonzero\n"
"    `v` with `T v = \u03bb \u2022 v`, and any characteristic-polynomial root of an endomorphism of `STVC` yields a\n"
"    nonzero `v` with `T v = \u03bb \u2022 v`; pure math. W3 DECOMPOSE: the full existence `\u2200 g, \u2203 c u, g = specOpN c u`\n"
"    (assembled from the COMPLETED seed eigenpair + the N74 iterated descent) + the GLOBAL polar/KAK\n"
"    assembly + connectedness + the GLOBAL reverse KAK surjectivity + the full `Spin(9)\u2192SO(9)` exhaustion\n"
"    is childed N77.\n"
"\n"
"  - **\u2605 (FORWARD FRONTIER \u2014 the immediate next node, N77) THE FULL n-DIM SPECTRAL EXISTENCE \u2014 assembling\n"
"    the now-COMPLETED seed eigenpair (N75 eigenvalue `cut_cubic_has_root` \u00d7 N76 eigenvector\n"
"    `stvc_eigenvector_of_charpoly_root`/`dim3_has_eigenvector`) + the N74 GENERAL ITERATED DESCENT into\n"
"    `\u2200 g, \u2203 c u, g = specOpN c u` (every EvC-self-adjoint operator IS a sum of scaled EvC-orthogonal\n"
"    eigenprojections) + THE GLOBAL POLAR/KAK ASSEMBLY FOR AN ARBITRARY ISOMETRY + CONNECTEDNESS + THE\n"
"    GLOBAL REVERSE KAK SURJECTIVITY (`qvIsomMonoidC` on the connected component `\u2264 genIsomMonoidC2`) +\n"
"    the full `Spin(9)\u2192SO(9)` exhaustion, childed from N76.** N49\u2013N76 banked, over the derived \u211d `Cut`:\n"
"    BOTH one-parameter generator families (`boostOPS`, `rotGenSetC`), the TWO-SIDED Moufang/`Spin(9)`\n"
"    generator `biMulFun u u'`, the EXTENDED generated group `genIsomMonoidC2` with FORWARD soundness\n"
"    (N55), the BORN POSITIVITY / (1,9) signature (N56), the SCALAR (degree-2) square root `cutSqrt`\n"
"    (N57), the INFINITESIMAL CARTAN split `EvC` (N58), the OPERATOR form-adjoint (N59), the operator\n"
"    square roots (N60\u2013N65), the concrete polar factorization (N66), the rank-3 / GENERAL rank-`n`\n"
"    spectral operator `specOpN` (N67\u2013N68), the concrete eigenbasis-existence witness `txMix` (N69), the\n"
"    DEFLATION engine `deflateC` (N70), the SEED EIGENPAIR EXTRACTION `specOpN_eigen` (N71), the\n"
"    CONSTRUCTED octonion-coupling 2\u00d72 seed (N72), the FIRST CLOSED MULTI-STEP DEFLATION DESCENT (N73),\n"
"    the GENERAL ITERATED DEFLATION DESCENT `deflateList`/`specOpN_full_descent` (N74), the ODD-DEGREE\n"
"    ROOT ENGINE `cutCbrt`/`cut_cubic_has_root` (N75 \u2014 the SEED-EIGENVALUE half), AND NOW (N76) the\n"
"    EIGENVECTOR half \u2014 `Module.Finite Cut STVC`, `dim3_has_eigenvector`, `stvc_eigenvector_of_charpoly_root`\n"
"    (a NONZERO eigenvector at the cubic-root eigenvalue, completing the seed eigenPAIR). THE HEAVY CORE\n"
"    that remains \u2014 the genuine group-manifold work \u2014 is: (i) the FULL existence `\u2200 g, \u2203 c u, g = specOpN c u`\n"
"    assembled from the seed + the iterated descent (the deepest joint: the seed produces ONE eigenpair\n"
"    `(\u03bb, v)`; N70 `deflateC` peels it, leaving an EvC-self-adjoint operator on the EvC-orthogonal\n"
"    complement; recursion on dimension \u2014 each step re-seeded by `dim_k_has_eigenvector` at the dropping\n"
"    dimension \u2014 drives the N74 iterated descent to the zero operator, so `g` IS `\u2211\u1d62 \u03bb\u1d62 \u2022 projC u\u1d62`); (ii)\n"
"    the GLOBAL polar/KAK assembly: every `g \u2208 qvIsomMonoidC` factors as `k\u00b7exp(p)` via the operator\n"
"    square root of `g*g`, then `k = g\u00b7exp(p)\u207b\u00b9` with `k*\u2218k = id`; (iii) the compact part `k` via\n"
"    CONNECTEDNESS of the isometry group over `Cut`; (iv) the GLOBAL reverse KAK surjectivity; (v) the\n"
"    full `Spin(9)\u2192SO(9)` exhaustion. Mathlib has NO `SO\u207a(1,9)`, no octonionic spinor cover, no Lie-group\n"
"    integration over `Cut`. MEASURE FIRST + reframe through the trunk \u2014 the immediately-bankable\n"
"    sub-pieces to MEASURE FIRST: (i) the DEFLATION RE-SEEDING at the dropped dimension (the recursion\n"
"    that turns ONE seed eigenpair into the full eigenbasis \u2014 the N74 iterated descent now has BOTH its\n"
"    seed halves; the structural step is `dim_(k\u22121)_has_eigenvector` on the deflated operator's invariant\n"
"    complement), (ii) the full existence `\u2200 g, \u2203 c u, g = specOpN c u` assembled once the re-seeding\n"
"    closes, (iii) a CONCRETE `biMulFun` 2-plane `SO(9)` reachability, (iv) the GLOBAL polar assembly once\n"
"    the n-dim existence is in hand. If the full existence / re-seeding / global polar assembly / reverse\n"
"    surjectivity / connectedness genuinely RESISTS after measure + reframe it is an HONEST W1 dissolution\n"
"    ticket + block, decompose into the immediately-bankable structural piece + child the global\n"
"    remainder. The costume must bite a WRONG existence / re-seeding / reachability / surjectivity /\n"
"    exhaustion claim. NO posited Lorentz group, NO Mathlib \u211d/\u2102 as content \u2014 DERIVE from the banked\n"
"    N49\u2013N76 + the derived \u211d `Cut` + the terminal algebra `O Cut`.\n"
)

text = text[:si] + new_block + text[ei:]
with io.open(path, "w", encoding="utf-8") as f:
    f.write(text)
print("ROADMAP updated: N76 retrospective + N77 forward frontier inserted.")
