/-
  Phys.Algebra.LorentzContinuumGenerationSO8ReflectionDeflation — N117: THE OCTONION-BLOCK
  AXIS-FIXING REFLECTION DEFLATION (the `SO(8)` analogue of N115's `x`-deflation step).

  ===========================================================================
  CONTEXT. N115 banked the `x`-deflation STEP (the `SO(9) → SO(8)` peel) and N116 banked the
  REASSEMBLY (the factorization: every `x`-moving compact isometry = one explicit ninth
  rotation · one `x`-FIXING isometry). The `x`-motion half of the compact-`SO(9)` exhaustion
  is COMPLETE. What remains is the inner BASE CASE — the `x`-fixing stabilizer = the full
  `SO(8)` octonion-block generation. The exhaustion of the `SO(8)` octonion block runs by the
  SAME induction-on-the-motion engine as the `x`-block: an octonion-block `QvC`-isometry `T`
  that MOVES a chosen unit-imaginary axis `e` (`T(0,0,e) = (0,0,w)`, `w ≠ e`) is peeled by an
  explicit block operator that rotates the moved image `w` BACK to `e`, reducing the
  octonion-block rank by one. THIS node banks that octonion-block deflation STEP — ROADMAP
  §N117 priority (i)'s named immediately-bankable structural piece.

  ── THE OBSTRUCTION (measured in N116's recon) AND THE THEORY-NATIVE NAVIGATION ──
  The naive `x`-block route (a single LEFT multiplication, as `deflateNinth` is a single
  axis-rotation) FAILS on the octonion block under NON-ASSOCIATIVITY: `(e·star w)·w ≠ e`
  in general, because the octonions are not associative. The deflation must stay inside the
  ASSOCIATIVE subalgebra `⟨e, w⟩` generated by the axis and its image (Artin's theorem — any
  two octonions generate an associative subalgebra). THE THEORY-NATIVE TOOL is the two-sided
  HALF-TURN `biMulLin n n : v ↦ n·(v·n)` — for a unit-imaginary `n`, the imaginary HOUSEHOLDER
  REFLECTION through the line `n`. It is governed ENTIRELY by the banked ALTERNATIVE laws (N5b
  `mul_mul_left`, the cap's positive lever), which hold for ANY two octonions with NO
  associativity, and `n` lies in `⟨e, w⟩` by construction (`n ∝ e − w`). This is the
  CARTAN–DIEUDONNÉ route: every rotation is a product of reflections, and a SINGLE reflection
  that swaps the moved image back to the chosen axis is the octonion-block analogue of N115's
  single explicit rotation.

  ── THE STRUCTURAL FACTS (DERIVED from the trunk, NOT a posited reflection group) ──
  THE TRACE IDENTITY (`octRefl_trace_id`): over the derived ℝ `Cut`, `z + star z = (2·reQC z)·1`.
  THE IMAGINARY POLARIZATION (`octRefl_polarize_imag`): for imaginary `p, q` (`star = −·`),
    `p·q + q·p = −(2·gFormC p q)·1` — the octonion Clifford relation, the structural heart.
  THE SQUARE OF AN IMAGINARY (`octRefl_mul_self_imag`): `m·m = −(gFormC m m)·1`.
  ★ THE REFLECTION IDENTITY (`octRefl_reflect_imag`): for imaginary `m, v`,
    `m·(v·m) = (gFormC m m)·v − (2·gFormC v m)·m` — the two-sided half-turn IS the (unnormalized)
    reflection that fixes `m`'s orthogonal complement and negates the `m`-line, derived from the
    polarization + the imaginary square + ONE left-alternative law `mul_mul_left` (the only place
    octonion non-associativity is touched — and `mul_mul_left` holds regardless). NO associativity
    assumed, NO coordinate brute.
  ★★ THE BISECTOR SWAP (`octRefl_swap_unnorm` / `octRefl_swap_norm`): for unit-imaginary `e, w`
    with `e ≠ w`, the bisector-perp `m := e − w` reflects `w` onto a scalar multiple of `e`:
    `(e−w)·(w·(e−w)) = (gFormC (e−w) (e−w))·e`; normalizing `n := r⁻¹·(e−w)`
    (`r := cutSqrt (gFormC (e−w) (e−w))`, N57) gives the EXACT swap `n·(w·n) = e`. The reflection
    drawn from the banked block generator that maps the moved image back to the chosen pole.

  ── WHAT THIS NODE BANKS (the deflation operator) ──
  `octDeflate e w := biMulLin n n`, `n := r⁻¹·(e − w)` — the explicit octonion-block deflating
    reflection, a SINGLE two-sided Born-unit generator.
  `octBisector_unit` — the normalized bisector `n` is a UNIT (`gFormC n n = 1`).
  `octDeflate_mem` — SOUND ∈ `genIsomMonoidLin` (a single generator, `Submonoid.subset_closure`).
  `octDeflate_isQvIsomC` — a `QvC`-isometry (`biMulLin_imag_isQvIsomC`, N-ConverseCompact).
  ★★ `octDeflate_apply_image` — `octDeflate e w (0,0,w) = (0,0,e)` (the reflect-back).
  ★★ `octDeflate_step` — THE OCTONION-BLOCK DEFLATION STEP: for an octonion-block `QvC`-isometry
    `T` with `T(0,0,e) = (0,0,w)` (`e` a unit-imaginary axis, `w ≠ e`), the composite
    `octDeflate e w · T` FIXES `(0,0,e)` — the octonion-block axis-motion is PEELED OFF by a
    single explicit block reflection, reducing the `SO(8)` octonion-block rank by one. The
    inductive STEP of the `SO(8)` exhaustion, the octonion-block analogue of `deflateNinth_step`.
  W8 teeth: a concrete axis-moving image `(0,0,je2)` (the unit `ιe₂ ≠ e₂`) reflected back to the
    `e₂` axis via the bisector `e₂ − ιe₂`, reading the deep scalar coordinate.

  ── HOW IT DESCENDS FROM THE TRUNK (UNBROKEN) ──
  Every object is DERIVED: the ALTERNATIVE laws `mul_mul_left` (N5b — the cap's positive lever,
  the octonion alternativity FORWARD from the Cayley–Dickson product); `gFormC` / `reQC` and
  their bilinearity / `gFormC_smul_left` / `gFormC_add_left` / `gFormC_symm` / `gFormC_neg_left`
  (N-LieAlgebra); `gFormC_pos_of_ne` (N115) / `gFormC_nonneg` / `gFormC_eq_zero_iff` (N56);
  `cutSqrt` / `cutSqrt_sq` / `cutSqrt_pos` (N57); `biMulLin` / `biMulLin_imag_isQvIsomC`
  (N-EndBridge / N-ConverseCompact); `genIsomMonoidLin` (N-Generation); `smulCompat_oCut`
  (`Cut` central on `O Cut`); the `Module.End` / `Field Cut` MACHINERY on the DERIVED objects
  (STANDARD §3) — over the derived ℝ `ContinuumQ.Cut` and the terminal algebra `O Cut := CD (H
  Cut)`. NOT a posited Lorentz group / SO⁺(1,9), NOT a posited reflection/Clifford group, NOT a
  posited operator topology, NOT Mathlib ℝ/ℂ as content, NOT a bridge.

  THE MOAT — posit-vs-derive (docs/STANDARD.md §0). The literature POSITS the full `Spin(8)` /
  `SO(8)` and reads off its triality / Moufang generation as the standard structure theorem.
  Here the octonion-block deflation is CONSTRUCTED forward from the trunk: the explicit
  reflection that peels the axis-motion off any octonion-block isometry is BUILT from the banked
  half-turn generator and the derived square root, and PROVED to reflect the moved image back to
  the chosen axis — the reflection identity and the bisector swap fall out of the octonion
  Clifford relation (the imaginary polarization) and ONE alternative law, NOT a posited
  reflection-group structure. The non-associativity obstruction is NAVIGATED, not assumed away:
  the half-turn is governed by alternativity (which the octonions keep), never by associativity
  (which they lost at the cascade stop).

  ── THE FORWARD REMAINDER (childed N118) ──
  The GLOBAL `SO(8)`-generation completeness (iterating this octonion-block deflation step across
  a full unit-imaginary basis to full octonion-block surjectivity — the octonion-block analogue
  of the `x`-block exhaustion now that the STEP is banked) + the literal operator TOPOLOGY over
  `Cut` remain the HEAVY group-manifold core. THIS node banks the octonion-block deflation STEP —
  the immediately-bankable structural piece of ROADMAP §N117 priority (i).

  ── PHYSICS-WORDS-REMOVABLE (docs/STANDARD.md §2) ──
  Delete "Lorentz / rotation / reflection / half-turn / isometry / compact / orthogonal / SO(8)
  / Spin / Clifford / Householder / Cartan / Dieudonné / triality / Moufang / bisector / axis /
  deflation / peel / stabilizer / generation / generator / octonion-block": what remains is pure
  linear algebra over the derived complete ordered field `Cut` — for imaginary `m, v` the operator
  `biMulLin m m` of `Module.End Cut (Cut × Cut × O Cut)` satisfies `m·(v·m) = (gFormC m m)·v −
  (2·gFormC v m)·m`; for unit-imaginary `e ≠ w`, with `n := (cutSqrt (gFormC (e−w) (e−w)))⁻¹·(e−w)`,
  `biMulLin n n (0,0,w) = (0,0,e)`; consequently for any `Cut`-linear `T` preserving `QvC` with
  `T(0,0,e) = (0,0,w)` and `w ≠ e`, the composite sends `(0,0,e)` to `(0,0,e)`. No theorem
  STATEMENT needs a physics word.

  Foundations-only: no posited axiom, no sorry, no kernel-trust bypass, no
  bridge-in-the-forbidden-sense, NO Mathlib number-system content import (the continuum is the
  DERIVED `Cut`), NO posited Lorentz group.
-/
import Phys.Algebra.LorentzContinuumGenerationExhaustionAssembly

namespace Phys.Algebra

open Phys.Cascade Phys.Cascade.CD
open Phys.Foundation Phys.Foundation.ContinuumQ

attribute [local instance] CD.narCD CD.srCD
attribute [local instance] Phys.Algebra.dblModuleCut

noncomputable section
open scoped BigOperators

/-! ## The trace identity, the imaginary polarization, and the imaginary square over the derived ℝ. -/

/-- THE TRACE IDENTITY over the derived ℝ `Cut`: `z + star z = (2·reQC z)·1`. The real part of an
    octonion is recovered as half the trace; `reQC z = z.re.re.re`. A single coordinate `ext`. -/
theorem octRefl_trace_id (z : O Cut) : z + star z = (2 * reQC z) • (1 : O Cut) := by
  ext <;> simp [reQC] <;> ring

/-- For an imaginary `q` (`star q = −q`): `gFormC p q = −reQC (p·q)` (since `gFormC p q = reQC (p·star
    q) = reQC (p·(−q)) = −reQC (p·q)`). The bridge from `gFormC` to the bare product trace. -/
theorem octRefl_gFormC_imag_right {q : O Cut} (hq : star q = -q) (p : O Cut) :
    gFormC p q = - reQC (p * q) := by
  unfold gFormC; rw [hq, mul_neg p q, reQC_neg]

/-- ★ THE IMAGINARY POLARIZATION (the octonion Clifford relation): for imaginary `p, q`,
    `p·q + q·p = −(2·gFormC p q)·1`. The trace identity applied to `p·q` (whose conjugate is
    `star q · star p = (−q)·(−p) = q·p`), with `reQC (p·q) = −gFormC p q`. The structural heart of
    the reflection — two imaginary octonions anticommute up to twice their Born overlap. -/
theorem octRefl_polarize_imag {p q : O Cut} (hp : star p = -p) (hq : star q = -q) :
    p * q + q * p = (-(2 * gFormC p q)) • (1 : O Cut) := by
  have ht := octRefl_trace_id (p * q)
  rw [star_mul, hp, hq, neg_mul_neg] at ht
  rw [octRefl_gFormC_imag_right hq p, show (-(2 * - reQC (p * q))) = 2 * reQC (p * q) by ring]
  exact ht

/-- A self-conjugate octonion is a real scalar: `star y = y ⇒ y = (reQC y)·1`. From the trace
    identity (`y + y = (2·reQC y)·1`), halving over the derived field `Cut`. -/
theorem octRefl_selfconj_eq_smul {y : O Cut} (h : star y = y) : y = (reQC y) • (1 : O Cut) := by
  have ht := octRefl_trace_id y; rw [h] at ht
  have h2 : (2 : Cut) • y = (2 * reQC y) • (1 : O Cut) := by rw [two_smul]; exact ht
  have hc := congrArg (fun z => (2⁻¹ : Cut) • z) h2
  simp only [smul_smul] at hc
  rw [show (2⁻¹ : Cut) * 2 = 1 by norm_num, one_smul,
      show (2⁻¹ : Cut) * (2 * reQC y) = reQC y by ring] at hc
  exact hc

/-- THE SQUARE OF AN IMAGINARY OCTONION: `m·m = −(gFormC m m)·1`. The self-overlap `m·star m` is
    self-conjugate, hence a real scalar `(gFormC m m)·1`; `star m = −m` flips the sign. -/
theorem octRefl_mul_self_imag {m : O Cut} (hm : star m = -m) :
    m * m = (-(gFormC m m)) • (1 : O Cut) := by
  have hsc : star (m * star m) = m * star m := by rw [star_mul, star_star]
  have hreal := octRefl_selfconj_eq_smul hsc
  have hg : reQC (m * star m) = gFormC m m := rfl
  rw [hg] at hreal; rw [hm] at hreal; rw [mul_neg m m] at hreal
  rw [show m * m = -(-(m * m)) by rw [neg_neg], hreal, neg_smul]

/-! ## The reflection identity — the two-sided half-turn IS the (unnormalized) reflection. -/

/-- ★ THE REFLECTION IDENTITY: for imaginary `m, v`,
    `m·(v·m) = (gFormC m m)·v − (2·gFormC v m)·m`. The two-sided half-turn `v ↦ m·(v·m)` is the
    reflection that fixes `m`'s Born-orthogonal complement and negates the `m`-line (unnormalized
    by `gFormC m m`). Derived from the polarization (`v·m = −(2·gFormC v m)·1 − m·v`), the
    left-alternative law `m·(m·v) = (m·m)·v` (N5b `mul_mul_left` — the ONLY contact with
    non-associativity, and it holds regardless), and the imaginary square. NO associativity
    assumed, NO coordinate brute — purely the banked octonion alternativity + Born bilinearity. -/
theorem octRefl_reflect_imag {m : O Cut} (hm : star m = -m) {v : O Cut} (hv : star v = -v) :
    m * (v * m) = (gFormC m m) • v - (2 * gFormC v m) • m := by
  have hpol := octRefl_polarize_imag hv hm
  have hvm : v * m = (-(2 * gFormC v m)) • (1 : O Cut) - m * v := by
    rw [eq_sub_iff_add_eq]; exact hpol
  rw [hvm, mul_sub,
      show m * ((-(2 * gFormC v m)) • (1 : O Cut)) = (-(2 * gFormC v m)) • m by
        rw [smulCompat_oCut.hr, mul_one],
      show m * (m * v) = (m * m) * v from (mul_mul_left m v), octRefl_mul_self_imag hm,
      show ((-(gFormC m m)) • (1 : O Cut)) * v = (-(gFormC m m)) • v by
        rw [smulCompat_oCut.hl, one_mul],
      neg_smul, neg_smul, sub_neg_eq_add]
  abel

/-- `gFormC v (−w) = −gFormC v w` (the right-slot negation; `gFormC_neg_left` reflected through
    `gFormC_symm`). -/
theorem octRefl_gFormC_neg_right (v w : O Cut) : gFormC v (-w) = - gFormC v w := by
  rw [gFormC_symm, gFormC_neg_left, gFormC_symm]

/-! ## The bisector swap — reflect a moved unit back to the chosen axis. -/

/-- ★★ THE BISECTOR SWAP (unnormalized): for unit-imaginary `e, w` (`gFormC e e = gFormC w w = 1`),
    the bisector-perp `m := e − w` reflects `w` onto a scalar multiple of `e`:
    `(e−w)·(w·(e−w)) = (gFormC (e−w) (e−w))·e`. Expanding the reflection identity at `m = e−w`,
    `v = w`: `gFormC w (e−w) = gFormC w e − 1` and `gFormC (e−w) (e−w) = 2 − 2·gFormC w e`, and the
    `w`-component cancels exactly, leaving `(gFormC (e−w) (e−w))·e`. The geometric content of the
    bisector reflection — independent of normalization, by pure module algebra over `Cut`. -/
theorem octRefl_swap_unnorm {e w : O Cut} (he : star e = -e) (hw : star w = -w)
    (hee : gFormC e e = 1) (hww : gFormC w w = 1) :
    (e - w) * (w * (e - w)) = (gFormC (e - w) (e - w)) • e := by
  have hmim : star (e - w) = -(e - w) := by rw [star_sub, he, hw]; abel
  rw [octRefl_reflect_imag hmim hw]
  have hk : gFormC w (e - w) = gFormC w e - gFormC w w := by
    rw [show e - w = e + (-w) by abel, gFormC_add_right, octRefl_gFormC_neg_right]; ring
  have hmm : gFormC (e - w) (e - w) = (2 : Cut) - 2 * gFormC w e := by
    rw [show e - w = e + (-w) by abel, gFormC_add_left, gFormC_add_right, gFormC_add_right,
        gFormC_neg_left, octRefl_gFormC_neg_right, octRefl_gFormC_neg_right, gFormC_neg_left,
        gFormC_symm w e, hee, hww]
    ring
  rw [hk, hww, hmm]
  set k := gFormC w e with hkdef
  module

/-- `(s•m)·(v·(s•m)) = (s·s)·(m·(v·m))` — the two-sided product is HOMOGENEOUS of degree 2 in the
    multiplier, via the smul–mul centrality `smulCompat_oCut` (twice each side). The scaling that
    turns the unnormalized bisector reflection into the unit one. -/
theorem octRefl_biMul_scale (s : Cut) (m v : O Cut) :
    (s • m) * (v * (s • m)) = (s * s) • (m * (v * m)) := by
  rw [smulCompat_oCut.hr s v m, smulCompat_oCut.hl s m (s • (v * m)),
      smulCompat_oCut.hr s m (v * m), smul_smul]

/-- ★★ THE BISECTOR SWAP (normalized) — the EXACT reflect-back. For unit-imaginary `e ≠ w`, the
    normalized bisector `n := r⁻¹·(e − w)` (`r := cutSqrt (gFormC (e−w) (e−w))`, N57) reflects `w`
    exactly onto `e`: `n·(w·n) = e`. The degree-2 scaling (`octRefl_biMul_scale`) turns the
    unnormalized swap `(gFormC (e−w) (e−w))·e` into `(r⁻²·gFormC (e−w) (e−w))·e = 1·e = e` by
    `cutSqrt_sq` on the strictly-positive Born overlap (`gFormC_pos_of_ne`, since `e ≠ w`). -/
theorem octRefl_swap_norm {e w : O Cut} (he : star e = -e) (hw : star w = -w)
    (hee : gFormC e e = 1) (hww : gFormC w w = 1) (hne : e - w ≠ 0) :
    ((cutSqrt (gFormC (e - w) (e - w)))⁻¹ • (e - w)) *
      (w * ((cutSqrt (gFormC (e - w) (e - w)))⁻¹ • (e - w))) = e := by
  have hpos : 0 < gFormC (e - w) (e - w) := gFormC_pos_of_ne hne
  set r := cutSqrt (gFormC (e - w) (e - w)) with hr_def
  have hrr : r * r = gFormC (e - w) (e - w) := cutSqrt_sq (le_of_lt hpos)
  have hr : r ≠ 0 := ne_of_gt (cutSqrt_pos hpos)
  rw [octRefl_biMul_scale, octRefl_swap_unnorm he hw hee hww, smul_smul,
      show r⁻¹ * r⁻¹ * gFormC (e - w) (e - w) = 1 by rw [← hrr]; field_simp,
      one_smul]

/-! ## The octonion-block deflating reflection: the operator, its soundness, and the STEP. -/

/-- THE EXPLICIT OCTONION-BLOCK DEFLATING REFLECTION `octDeflate e w`: the two-sided half-turn
    `biMulLin n n` at the normalized bisector `n := r⁻¹·(e − w)` (`r := cutSqrt (gFormC (e−w)
    (e−w))`). Built to reflect a moved unit-imaginary axis image `(0,0,w)` BACK to the chosen axis
    `(0,0,e)` — the deflation that peels the octonion-block axis-motion off any octonion-block
    `QvC`-isometry. A SINGLE two-sided Born-unit generator drawn from the banked alphabet. -/
def octDeflate (e w : O Cut) : Module.End Cut STVC :=
  biMulLin ((cutSqrt (gFormC (e - w) (e - w)))⁻¹ • (e - w))
           ((cutSqrt (gFormC (e - w) (e - w)))⁻¹ • (e - w))

/-- The normalized bisector `n := r⁻¹·(e − w)` is a UNIT: `gFormC n n = r⁻²·gFormC (e−w) (e−w) = 1`
    (`gFormC` bilinearity + `r·r = gFormC (e−w) (e−w)` by `cutSqrt_sq` on the strictly-positive
    overlap `gFormC_pos_of_ne`). The Born-unit the half-turn generator requires. -/
theorem octBisector_unit {e w : O Cut} (hne : e - w ≠ 0) :
    gFormC ((cutSqrt (gFormC (e - w) (e - w)))⁻¹ • (e - w))
           ((cutSqrt (gFormC (e - w) (e - w)))⁻¹ • (e - w)) = 1 := by
  have hpos : 0 < gFormC (e - w) (e - w) := gFormC_pos_of_ne hne
  set r := cutSqrt (gFormC (e - w) (e - w)) with hr_def
  have hrr : r * r = gFormC (e - w) (e - w) := cutSqrt_sq (le_of_lt hpos)
  have hr : r ≠ 0 := ne_of_gt (cutSqrt_pos hpos)
  rw [gFormC_smul_left, gFormC_smul_right, ← hrr]; field_simp

/-- SOUNDNESS — the deflating reflection lies in the `Module.End` generated two-sided submonoid
    `genIsomMonoidLin`: it is a SINGLE two-sided Born-unit generator `biMulLin n n` (`n` a unit by
    `octBisector_unit`), so `Submonoid.subset_closure` applies. -/
theorem octDeflate_mem {e w : O Cut} (hne : e - w ≠ 0) :
    octDeflate e w ∈ genIsomMonoidLin :=
  Submonoid.subset_closure ⟨_, _, octBisector_unit hne, octBisector_unit hne, rfl⟩

/-- The deflating reflection is a `QvC`-isometry — directly from the half-turn isometry
    `biMulLin_imag_isQvIsomC` (N-ConverseCompact), since `n` is a Born-unit (`octBisector_unit`). -/
theorem octDeflate_isQvIsomC {e w : O Cut} (hne : e - w ≠ 0) :
    IsQvIsomC (octDeflate e w) :=
  biMulLin_imag_isQvIsomC _ (octBisector_unit hne)

/-- ★★ THE REFLECT-BACK — the deflating reflection sends the moved axis image `(0,0,w)` BACK to the
    chosen axis `(0,0,e)`, given unit-imaginary `e ≠ w`. Directly from the normalized bisector swap
    `octRefl_swap_norm` (the `(t,x)` block is fixed by `biMulLin`). The completing-the-square the
    bisector reflection was constructed to perform — staying inside the associative subalgebra
    `⟨e, w⟩`, NO non-associativity obstruction. -/
theorem octDeflate_apply_image {e w : O Cut} (he : star e = -e) (hw : star w = -w)
    (hee : gFormC e e = 1) (hww : gFormC w w = 1) (hne : e - w ≠ 0) :
    octDeflate e w ((0:Cut), (0:Cut), w) = ((0:Cut), (0:Cut), e) := by
  unfold octDeflate
  show ((0:Cut), (0:Cut),
    ((cutSqrt (gFormC (e - w) (e - w)))⁻¹ • (e - w)) *
      (w * ((cutSqrt (gFormC (e - w) (e - w)))⁻¹ • (e - w)))) = ((0:Cut), (0:Cut), e)
  rw [octRefl_swap_norm he hw hee hww hne]

/-- ★★ THE OCTONION-BLOCK DEFLATION STEP — the `SO(8)` analogue of N115's `deflateNinth_step`. For
    ANY octonion-block `QvC`-isometry `T` whose chosen unit-imaginary axis image MOVES (`T (0,0,e) =
    (0,0,w)` with `w ≠ e`), the composite `octDeflate e w · T` FIXES the axis `(0,0,e)`. The
    reflect-back (`octDeflate_apply_image`) reflects the moved image back to the pole:
    `(octDeflate e w · T)(0,0,e) = octDeflate e w (0,0,w) = (0,0,e)`. The octonion-block axis-motion
    is PEELED OFF by a single explicit block reflection drawn from the banked alphabet
    (`octDeflate_mem`, `octDeflate_isQvIsomC`) — the inductive STEP that reduces the `SO(8)`
    octonion-block generation problem by one axis, navigating the non-associativity obstruction
    through the alternativity-governed half-turn. THIS is the octonion-block deflation engine of the
    `SO(8)` exhaustion, banked as a forced, DERIVED reduction. -/
theorem octDeflate_step {T : Module.End Cut STVC}
    {e w : O Cut} (he : star e = -e) (hw : star w = -w)
    (hee : gFormC e e = 1) (hww : gFormC w w = 1)
    (hTimg : T ((0:Cut), (0:Cut), e) = ((0:Cut), (0:Cut), w)) (hne : e - w ≠ 0) :
    (octDeflate e w * T) ((0:Cut), (0:Cut), e) = ((0:Cut), (0:Cut), e) := by
  rw [Module.End.mul_apply, hTimg, octDeflate_apply_image he hw hee hww hne]

/-! ## W8 teeth — a concrete axis-moving image `(0,0,ιe₂)` reflected back to the `e₂` axis. -/

/-- The cascade's terminal imaginary generators `e₂` and `ιe₂` are Born-ORTHOGONAL:
    `gFormC e₂ ιe₂ = 0` (a direct coordinate computation: `e₂·star ιe₂ = e₂·(−ιe₂)` has zero deep
    real part). The two units span a 2-plane, neither a scalar multiple of the other. -/
theorem octDeflate_e2_je2_gFormC_zero :
    gFormC (CD.e2 : O Cut) (je2 : O Cut) = 0 := by
  show reQC ((CD.e2 : O Cut) * star (je2 : O Cut)) = 0
  rw [je2_imag, mul_neg (CD.e2 : O Cut) (je2 : O Cut), reQC_neg]
  show -((CD.e2 : O Cut) * (je2 : O Cut)).re.re.re = 0
  simp [CD.e2, CD.iota]

/-- The cascade's terminal imaginary generators `e₂` and `ιe₂` are DISTINCT as octonions:
    `e₂ − ιe₂ ≠ 0`. If they were equal, `gFormC e₂ e₂ = gFormC e₂ ιe₂` would force `1 = 0`
    (`e2_gFormC_self` vs the Born-orthogonality `octDeflate_e2_je2_gFormC_zero`). A genuine
    axis-MOVING image. -/
theorem octDeflate_witness_ne : (CD.e2 : O Cut) - (je2 : O Cut) ≠ 0 := by
  intro h
  have he2 : (CD.e2 : O Cut) = (je2 : O Cut) := by rw [sub_eq_zero] at h; exact h
  have h1 : gFormC (CD.e2 : O Cut) (CD.e2 : O Cut) = 1 := e2_gFormC_self
  have h0 : gFormC (CD.e2 : O Cut) (je2 : O Cut) = 0 := octDeflate_e2_je2_gFormC_zero
  rw [← he2] at h0
  rw [h1] at h0
  norm_num at h0

/-- ★ W8 — the concrete axis-moving image `(0,0,ιe₂)` (the unit `ιe₂ ≠ e₂`) is reflected BACK to the
    `e₂` axis `(0,0,e₂)` by `octDeflate e₂ ιe₂` (`octDeflate_apply_image`). The octonion-block
    deflation made concrete — a genuine axis-moving image (the moved unit `ιe₂` distinct from the
    chosen axis `e₂`, `octDeflate_witness_ne`) reflected to the axis-fixing pole. -/
theorem octDeflate_witness_image :
    octDeflate (CD.e2 : O Cut) (je2 : O Cut) ((0:Cut), (0:Cut), (je2 : O Cut))
      = ((0:Cut), (0:Cut), (CD.e2 : O Cut)) :=
  octDeflate_apply_image e2_imag je2_imag e2_gFormC_self je2_gFormC_self octDeflate_witness_ne

/-- ★ W8 TEETH — the deep scalar coordinate of the reflected-back image reads the `e₂` axis. The
    distinguishing read-off: the moved image `ιe₂` (whose deep `im.im.re`-style coordinate differs)
    is reflected to `e₂`, whose `re.im.re` coordinate is `1`. -/
theorem octDeflate_witness_coord :
    (octDeflate (CD.e2 : O Cut) (je2 : O Cut)
        ((0:Cut), (0:Cut), (je2 : O Cut))).2.2 = (CD.e2 : O Cut) := by
  rw [octDeflate_witness_image]

end

end Phys.Algebra
