import Phys.Foundation.ContinuumBracket
#print axioms Phys.Foundation.ContinuumQ.geom_partial_le
#print axioms Phys.Foundation.ContinuumQ.geom_tsum_le
#print axioms Phys.Foundation.ContinuumQ.partialExp
#print axioms Phys.Foundation.ContinuumQ.expRemBound
#print axioms Phys.Foundation.ContinuumQ.tail_termwise_le
#print axioms Phys.Foundation.ContinuumQ.expTail_summable
#print axioms Phys.Foundation.ContinuumQ.expTail_le
#print axioms Phys.Foundation.ContinuumQ.cutExp_split
#print axioms Phys.Foundation.ContinuumQ.expTail_nonneg
#print axioms Phys.Foundation.ContinuumQ.cutExp_ge_partial
#print axioms Phys.Foundation.ContinuumQ.cutExp_le_partial_add_rem
#print axioms Phys.Foundation.ContinuumQ.expRemBound_nonneg
#print axioms Phys.Foundation.ContinuumQ.expRemBound_pos
#print axioms Phys.Foundation.ContinuumQ.bracket_no_cross
#print axioms Phys.Foundation.ContinuumQ.expRemBound_lt
#print axioms Phys.Foundation.ContinuumQ.cutExp_certified_bracket
#print axioms Phys.Foundation.ContinuumQ.cutLog_ge_of_expUpper_le
#print axioms Phys.Foundation.ContinuumQ.cutLog_le_of_le_expLower
#print axioms Phys.Foundation.ContinuumQ.cutLog_ge_certified
#print axioms Phys.Foundation.ContinuumQ.cutLog_le_certified
#print axioms Phys.Foundation.ContinuumQ.partialExp_one_four
#print axioms Phys.Foundation.ContinuumQ.expRemBound_one_four
#print axioms Phys.Foundation.ContinuumQ.partialExp_two_three
#print axioms Phys.Foundation.ContinuumQ.cutExp_one_bracket
#print axioms Phys.Foundation.ContinuumQ.cutExp_one_bracket_strict
#print axioms Phys.Foundation.ContinuumQ.cutLog_three_bracket
#print axioms Phys.Foundation.ContinuumQ.cutLog_three_bracket_strict
