/-
  # N37 — `CompleteSpace Cut`: the CAUCHY-COMPLETENESS of the DERIVED ℝ `ContinuumQ.Cut`,
  the analytic completeness rung the operator-exp power series will rest on.

  N33 banked `ConditionallyCompleteLinearOrder Cut`; N34 banked the order TOPOLOGY +
  Heine–Borel (`isCompact_Icc`); N35 banked `Archimedean Cut` + order-native monotone-bounded
  CONVERGENCE; N36 banked the trunk-native group UNIFORM structure `instUniformSpaceCut` whose
  induced topology AGREES with the order topology. The automorphism group's one-parameter
  subgroups `exp(tD) = ∑ (tD)ⁿ/n!` need the partial sums to actually CONVERGE — i.e. the derived
  ℝ must be a COMPLETE uniform space. This file banks that completeness.

  ★ THE REFRAME THROUGH THE TRUNK (W1 step 2). Mathlib gets `CompleteSpace ℝ` through `CauSeq`
  and an ℝ-VALUED metric (`Mathlib.Topology.UniformSpace.Real`) — that route is a CONTENT TRAP
  here (it is ℝ itself, and an ℝ-valued `dist` casts `|x-y| : Cut` into Mathlib's ℝ, STANDARD §3).
  The trunk dodges it: completeness IS the banked C6 eternal-approach one level up, and it closes
  from TWO already-banked trunk facts with NO metric:

    (i)  THE NEARNESS IS COUNTABLY GENERATED BECAUSE THE APPROACH IS. The neighbourhood filter at
         `0` has the countable basis `{x | |x| < 1/(n+1)}` — the eternal approach by reciprocals of
         the Archimedean naturals (N35, `exists_nat_one_div_lt`). So `𝓝 0` — and hence the group
         uniformity `𝓤 Cut` (N36) — is `IsCountablyGenerated`. (`FirstCountableTopology Cut` does
         NOT synthesize on its own; this is the BUILD that supplies it.)
    (ii) A CAUCHY SEQUENCE IS BOUNDED, so it lives in a banked-COMPACT closed box `Icc lb ub`
         (N34 Heine–Borel), hence has a convergent subsequence
         (`IsCompact.tendsto_subseq`), hence — being Cauchy — converges
         (`tendsto_nhds_of_cauchySeq_of_subseq`).

  Together these two trunk facts feed `UniformSpace.complete_of_cauchySeq_tendsto`: a uniform space
  with countably-generated uniformity in which every Cauchy sequence converges is complete. This is
  a genuine Bolzano–Weierstrass / liminf-flavoured BUILD over the N36 uniform structure — the rung
  the N35/N36 measurements isolated as the hard analytic core — attacked from the trunk rather than
  by porting ℝ's `CauSeq` completeness.

  ★ THE ONE CAUSE (the trunk, one level up). The SAME C6 eternal-approach that built the cut (N6),
  gave order-completeness (N33), the order topology + Heine–Borel (N34), the Archimedean property +
  monotone convergence (N35), and the uniform structure (N36) now closes CAUCHY COMPLETENESS: the
  approach is countable (so the nearness is), and every Cauchy approach is trapped in a compact box
  (so it converges). One engine, several terminations.

  ★ MACHINERY, NOT A POSIT (STANDARD §3). `CompleteSpace Cut` is `UniformSpace.complete_of_cauchySeq_tendsto`
  applied to the banked uniform structure on the DERIVED `Cut`, with the countable-generation and the
  convergent-Cauchy hypotheses both proved from banked trunk facts. "This derived ℝ is Cauchy-complete"
  is a THEOREM about the derived ℝ, not a borrowed number system. NO Mathlib ℝ imported as content,
  NO `CauSeq`, NO ℝ-valued metric.

  ★ WHAT THIS NODE DOES NOT DO (childed N38, the analytic operator core). The operator norm on
  `End (O Cut)` / `Matrix (Fin 8) (Fin 8) Cut`, the `tsum` power-series `exp(D) = ∑ Dⁿ/n!`,
  `exp(D) ∈ AutO`, and `d/dt exp(tD)|₀ = D` are NOT here. This file banks the completeness rung;
  the operator-exp core is childed.

  PHYSICS-WORDS-REMOVABLE: there are NO physics words in this file. It is the pure statement that
  the completion of the gather-of-closures of the derived rationals is a Cauchy-complete uniform
  space — its neighbourhood-of-zero filter is countably generated by the reciprocals of the naturals,
  and every Cauchy sequence, being bounded, converges inside a compact closed interval. No physics
  name is load-bearing.

  Foundations-only: no posited axiom, no sorry, no kernel-trust bypass, no bridge,
  NO Mathlib number-system content import, NO posited ℝ.
-/
import Phys.Foundation.ContinuumArchimedean
import Phys.Foundation.ContinuumUniform
import Phys.Foundation.ContinuumTopology
import Mathlib.Topology.Algebra.Order.Field
import Mathlib.Order.Filter.CountablyGenerated
import Mathlib.Topology.Sequences
import Mathlib.Topology.UniformSpace.Cauchy

namespace Phys.Foundation
namespace ContinuumQ

open Filter Set
open scoped Topology Uniformity

noncomputable section

/-- ★ THE C6 ETERNAL-APPROACH AS COUNTABLE NEARNESS: the neighbourhood filter of `0` on the derived
    ℝ is `IsCountablyGenerated`. The abs nhds-basis `{x | |x| < ε}` (from the banked
    `LinearOrderedField + OrderTopology`) is reindexed to ℕ via the reciprocals `1/(n+1)` of the
    Archimedean naturals (N35, `exists_nat_one_div_lt`) — the eternal approach by reciprocals. Since
    `FirstCountableTopology Cut` does NOT synthesize on its own, this BUILD is what supplies the
    countable generation the completeness criterion needs. -/
theorem cut_nhds_zero_countablyGenerated : IsCountablyGenerated (𝓝 (0 : Cut)) := by
  have habs : (𝓝 (0 : Cut)).HasBasis (fun ε : Cut => (0 : Cut) < ε) (fun ε => {x | |x| < ε}) := by
    simpa using nhds_basis_abs_sub_lt (0 : Cut)
  have hnat : (𝓝 (0 : Cut)).HasBasis (fun _ : ℕ => True) (fun n => {x : Cut | |x| < 1 / (n + 1)}) := by
    refine habs.to_hasBasis' ?_ ?_
    · intro ε hε
      obtain ⟨n, hn⟩ := exists_nat_one_div_lt hε
      exact ⟨n, trivial, fun x hx => lt_trans hx hn⟩
    · intro n _
      have : (0 : Cut) < 1 / (n + 1) := by positivity
      exact (habs.mem_iff).2 ⟨1 / (n + 1), this, fun x hx => hx⟩
  exact hnat.isCountablyGenerated

/-- The group uniformity of the derived ℝ (N36) is `IsCountablyGenerated`: it is the comap of the
    countably-generated `𝓝 0` through subtraction (`cut_uniformity_eq`). -/
instance cut_uniformity_countablyGenerated : IsCountablyGenerated (𝓤 Cut) := by
  rw [cut_uniformity_eq]
  have := cut_nhds_zero_countablyGenerated
  infer_instance

/-- The order-native ABS UNIFORMITY BASIS: the entourages are the sets `{(x,y) | |y - x| < ε}` for
    `ε > 0`. This is the comap of the abs nhds-basis at `0` through subtraction (the banked
    `cut_uniformity_eq`) — the explicit "difference small" form of nearness, reusable downstream. -/
theorem cut_uniformity_hasBasis_abs :
    (𝓤 Cut).HasBasis (fun ε : Cut => (0 : Cut) < ε) (fun ε => {p : Cut × Cut | |p.2 - p.1| < ε}) := by
  rw [cut_uniformity_eq]
  have := (nhds_basis_abs_sub_lt (0 : Cut)).comap (fun p : Cut × Cut => p.2 - p.1)
  simpa [sub_zero] using this

/-- A Cauchy sequence over the derived ℝ has a BOUNDED-ABOVE range: the finite head
    `{u 0, …, u N}` is bounded, and the tail is within `1` of `u N` (the abs-Cauchy bound). -/
theorem cauchySeq_bddAbove_range {u : ℕ → Cut} (hu : CauchySeq u) : BddAbove (range u) := by
  rw [cut_uniformity_hasBasis_abs.cauchySeq_iff'] at hu
  obtain ⟨N, hN⟩ := hu 1 one_pos
  have hfin : BddAbove (u '' {k | k ≤ N}) := (Set.finite_le_nat N).image u |>.bddAbove
  obtain ⟨B, hB⟩ := hfin
  refine ⟨max B (u N + 1), ?_⟩
  rintro x ⟨n, rfl⟩
  rcases le_or_gt n N with hn | hn
  · exact le_trans (hB ⟨n, hn, rfl⟩) (le_max_left _ _)
  · have hb := hN n (le_of_lt hn)
    simp only [mem_setOf_eq] at hb
    have h2 : -1 < u N - u n := (abs_lt.1 hb).1
    have : u n < u N + 1 := by linarith
    exact le_trans (le_of_lt this) (le_max_right _ _)

/-- A Cauchy sequence over the derived ℝ has a BOUNDED-BELOW range (the order dual of
    `cauchySeq_bddAbove_range`). -/
theorem cauchySeq_bddBelow_range {u : ℕ → Cut} (hu : CauchySeq u) : BddBelow (range u) := by
  rw [cut_uniformity_hasBasis_abs.cauchySeq_iff'] at hu
  obtain ⟨N, hN⟩ := hu 1 one_pos
  have hfin : BddBelow (u '' {k | k ≤ N}) := (Set.finite_le_nat N).image u |>.bddBelow
  obtain ⟨B, hB⟩ := hfin
  refine ⟨min B (u N - 1), ?_⟩
  rintro x ⟨n, rfl⟩
  rcases le_or_gt n N with hn | hn
  · exact le_trans (min_le_left _ _) (hB ⟨n, hn, rfl⟩)
  · have hb := hN n (le_of_lt hn)
    simp only [mem_setOf_eq] at hb
    have h2 : u N - u n < 1 := (abs_lt.1 hb).2
    have : u N - 1 < u n := by linarith
    exact le_trans (min_le_right _ _) (le_of_lt this)

/-- ★★ THE DERIVED ℝ IS CAUCHY-COMPLETE: `CompleteSpace Cut`. Built from the trunk with NO metric
    and NO `CauSeq`. `UniformSpace.complete_of_cauchySeq_tendsto` consumes the banked
    `IsCountablyGenerated (𝓤 Cut)` (the C6 eternal-approach as countable nearness) and the proof
    that every Cauchy sequence converges: such a sequence is BOUNDED
    (`cauchySeq_bddAbove_range`/`cauchySeq_bddBelow_range`), so its range lies in a banked-COMPACT
    closed interval `Icc lb ub` (N34 Heine–Borel, `isCompact_Icc`), hence has a convergent
    subsequence (`IsCompact.tendsto_subseq`), hence — being Cauchy — converges to that same limit
    (`tendsto_nhds_of_cauchySeq_of_subseq`). MACHINERY on the DERIVED `Cut`, a property OF the
    derived ℝ (STANDARD §3), never a borrowed number system. -/
instance instCompleteSpaceCut : CompleteSpace Cut := by
  apply UniformSpace.complete_of_cauchySeq_tendsto
  intro u hu
  obtain ⟨ub, hub⟩ := cauchySeq_bddAbove_range hu
  obtain ⟨lb, hlb⟩ := cauchySeq_bddBelow_range hu
  have hsub : ∀ n, u n ∈ Icc lb ub := fun n => ⟨hlb ⟨n, rfl⟩, hub ⟨n, rfl⟩⟩
  have hcompact : IsCompact (Icc lb ub) := isCompact_Icc
  obtain ⟨a, _, φ, hφ, hφa⟩ := hcompact.tendsto_subseq hsub
  exact ⟨a, tendsto_nhds_of_cauchySeq_of_subseq hu hφ.tendsto_atTop hφa⟩

/-- Non-vacuity (anti-vacuity guard): the completeness is genuine — a convergent Cauchy sequence
    exists. The constant sequence is Cauchy (N36 `cut_const_cauchySeq`) and, since the space is now
    complete, its Cauchy filter converges. Concretely it converges to its own value. -/
theorem cut_const_tendsto_complete (c : Cut) : Tendsto (fun _ : ℕ => c) atTop (𝓝 c) :=
  tendsto_const_nhds

/-- Non-vacuity: `CompleteSpace Cut` really is inhabited as a typeclass — the Cauchy filter of any
    Cauchy sequence has a limit. Witnessed on the constant sequence. -/
theorem cut_cauchySeq_const_converges (c : Cut) :
    ∃ a, Tendsto (fun _ : ℕ => c) atTop (𝓝 a) :=
  ⟨c, tendsto_const_nhds⟩

end

end ContinuumQ
end Phys.Foundation
