/-
  # N34 — The TOPOLOGY RUNG on the DERIVED continuum: the standard order topology and
  Heine–Borel on the derived ℝ `ContinuumQ.Cut`.

  N33 banked `ConditionallyCompleteLinearOrder Cut` — the derived ℝ (the completion of the
  gather-of-closures of the derived rationals) is conditionally complete in Mathlib's standard
  `IsLUB`/`sSup` idiom. This file installs the STANDARD ORDER TOPOLOGY on that derived ℝ and
  re-exports the analytic facts it unlocks — most importantly HEINE–BOREL (`isCompact_Icc`) and
  finite-product box compactness — as MACHINERY on the DERIVED object.

  WHY THIS NODE (the analytic sub-tower the N32 measurement forced). The automorphism group of
  the terminal Cayley–Dickson algebra is COMPACT because the definite Born form bounds its
  coordinate entries (N32 `aut_entry_abs_le_one`) — but "bounded + closed ⟹ compact" (Heine–Borel)
  is a TOPOLOGICAL statement, and the derived ℝ carried no topology. This file supplies the
  topology: from the banked order-completeness (N33), `Preorder.topology` gives `Cut` a topology,
  `OrderTopology Cut` holds by `rfl`, and then the standard library delivers (all as `inferInstance`
  on the DERIVED object):
    • `T2Space Cut`, `OrderClosedTopology Cut` — the derived ℝ is Hausdorff and order-closed;
    • `IsTopologicalRing Cut` — the field operations are continuous (the derived ℝ is a
      topological ring under its order topology);
    • `CompactIccSpace Cut` (`ConditionallyCompleteLinearOrder.toCompactIccSpace`) ⟹
      ★★ `isCompact_Icc` — HEINE–BOREL on the derived ℝ;
    • `isCompact_univ_pi` ⟹ finite-product BOX compactness `[-1,1]^n`.

  ★ THE REFRAME-THROUGH-THE-TRUNK (W1 step 2). This is not a posited topology: it is the banked
  C6 eternal-approach / gather-of-closures completeness (N33), now spoken in the dialect the
  standard topology library understands. "This derived ℝ is Heine–Borel" is a THEOREM about the
  derived object, not a borrowed number system (STANDARD §3: the metalanguage/content line —
  `TopologicalSpace`/`OrderTopology`/`CompactIccSpace` are standard order MACHINERY applied to the
  DERIVED `Cut`, never a posited ℝ/topology).

  PHYSICS-WORDS-REMOVABLE: there are NO physics words in this file. It is the pure statement that
  the order topology on the completion of the gather-of-closures of the derived rationals is
  Heine–Borel.

  Foundations-only: no posited axiom, no sorry, no kernel-trust bypass, no bridge,
  NO Mathlib number-system content import, NO posited ℝ.
-/
import Phys.Foundation.ContinuumCCLO
import Mathlib.Topology.Order.Compact
import Mathlib.Topology.Algebra.Order.Field
import Mathlib.Topology.Constructions

namespace Phys.Foundation
namespace ContinuumQ

open scoped Classical

noncomputable section

/-- The standard ORDER TOPOLOGY on the derived ℝ, generated by the open rays of the banked
    `LinearOrder Cut` (N6/N10–N14). NOT a posited topology — it is built from the derived order. -/
instance instTopologicalSpaceCut : TopologicalSpace Cut := Preorder.topology Cut

/-- The order topology IS the order topology: `OrderTopology Cut` holds definitionally
    (`Preorder.topology` is by construction generated by the order rays). -/
instance instOrderTopologyCut : OrderTopology Cut := ⟨rfl⟩

/-- The derived ℝ is Hausdorff (a linear order with the order topology is `T2`). -/
theorem t2Space_cut : T2Space Cut := inferInstance

/-- The derived ℝ is a TOPOLOGICAL RING: addition, negation, and multiplication are continuous
    for the order topology (the standard library's `LinearOrderedField + OrderTopology` instance). -/
theorem isTopologicalRing_cut : IsTopologicalRing Cut := inferInstance

/-- The order relation is closed in the product topology on the derived ℝ. -/
theorem orderClosedTopology_cut : OrderClosedTopology Cut := inferInstance

/-- The derived ℝ is a `CompactIccSpace`: every closed interval is compact
    (`ConditionallyCompleteLinearOrder.toCompactIccSpace`, consuming N33's completeness). -/
theorem compactIccSpace_cut : CompactIccSpace Cut := inferInstance

/-- ★★ HEINE–BOREL on the DERIVED ℝ: every closed interval `[a, b]` of the derived continuum is
    topologically COMPACT. This is the rung the N32 compactness measurement forced — it descends
    from the banked order-completeness (N33), which is the banked C6 eternal-approach completion
    one level up. A property OF the derived ℝ, not a posited number system. -/
theorem isCompact_Icc_cut (a b : Cut) : IsCompact (Set.Icc a b) := isCompact_Icc

/-- Finite-product BOX compactness over the derived ℝ: the box `[-1, 1]^n` is compact (Tychonoff
    for a finite index from Heine–Borel on each factor). The home of the bounded automorphism
    coordinate matrices (the N32 unit-box, now topologically compact). -/
theorem isCompact_box {n : ℕ} :
    IsCompact (Set.univ.pi (fun _ : Fin n => Set.Icc (-1 : Cut) 1)) :=
  isCompact_univ_pi (fun _ => isCompact_Icc)

end

end ContinuumQ
end Phys.Foundation
