import Phys.Quantum.NoHiddenVariable

#print axioms Phys.Quantum.NoHiddenVariable.definite_record_void
#print axioms Phys.Quantum.NoHiddenVariable.no_nonzero_definite_record
#print axioms Phys.Quantum.NoHiddenVariable.weight_foldComplex_invariant
#print axioms Phys.Quantum.NoHiddenVariable.phase_partner_same_weight
#print axioms Phys.Quantum.NoHiddenVariable.phase_partner_diff_outcome
#print axioms Phys.Quantum.NoHiddenVariable.outcome_not_phaseInvariant_function
#print axioms Phys.Quantum.NoHiddenVariable.hv_record_sign_is_rejected_sign
#print axioms Phys.Quantum.NoHiddenVariable.forced_sign_has_no_record
#print axioms Phys.Quantum.NoHiddenVariable.no_hidden_variable
#print axioms Phys.Quantum.NoHiddenVariable.no_hidden_variable_nonvacuous
