import Phys.Algebra.LorentzContinuumCliffordSpinHom

namespace N145Probe

open Phys.Cascade Phys.Cascade.CD Phys.Algebra
open Phys.Foundation Phys.Foundation.ContinuumQ

attribute [local instance] CD.narCD CD.srCD
attribute [local instance] Phys.Algebra.dblModuleCut

noncomputable section
open scoped BigOperators

/-- The reflection-unit generating set of the Pin group. -/
def pinGenSet : Set CliffCˣ := { u | ∃ (a : STVC) (ha : BvC a a ≠ 0), u = cliffUnitOf a ha }

/-- THE PIN GROUP: the submonoid of `CliffCˣ` generated by the reflection units. -/
def PinSub : Submonoid CliffCˣ := Submonoid.closure pinGenSet

theorem cliffUnitOf_mem_pinSub {a : STVC} (ha : BvC a a ≠ 0) :
    cliffUnitOf a ha ∈ PinSub :=
  Submonoid.subset_closure ⟨a, ha, rfl⟩

/-- The Pin group lies in the covering submonoid: each reflection unit covers its reflection. -/
theorem pinSub_le_coversSub : PinSub ≤ CoversSub := by
  apply Submonoid.closure_le.mpr
  rintro u ⟨a, ha, rfl⟩
  exact ⟨houseHolderM a, (mem_bvIsomLinMonoid).mpr (houseHolderM_isom ha),
    cliffCovers_reflection ha⟩

/-- Every reflection-word isometry has a covering unit IN the Pin group. -/
theorem pin_covers_word {g : Module.End Cut STVC}
    (hg : g ∈ Submonoid.closure houseHolderMSet) :
    ∃ u, u ∈ PinSub ∧ CliffCovers (u : CliffCˣ) g := by
  induction hg using Submonoid.closure_induction with
  | mem x hx =>
      obtain ⟨a, ha, rfl⟩ := hx
      exact ⟨cliffUnitOf a ha, cliffUnitOf_mem_pinSub ha, cliffCovers_reflection ha⟩
  | one => exact ⟨1, one_mem _, cliffCovers_one⟩
  | mul x y _ _ ihx ihy =>
      obtain ⟨u, hu, hcu⟩ := ihx
      obtain ⟨w, hw, hcw⟩ := ihy
      exact ⟨u * w, mul_mem hu hw, cliffCovers_mul hcu hcw⟩

/-- ★★ THE PIN DOUBLE COVER as a MonoidHom on the honest reflection-generated domain. -/
def coverMapPin : PinSub →* bvIsomLinMonoid :=
  coverMap.comp (Submonoid.inclusion pinSub_le_coversSub)

theorem coverMapPin_coe (u : PinSub) :
    (coverMapPin u : Module.End Cut STVC) = coverOp ⟨(u : CliffCˣ), pinSub_le_coversSub u.prop⟩ := rfl

/-- ★★ THE PIN DOUBLE COVER IS SURJECTIVE ↠ SO⁺(1,9). -/
theorem coverMapPin_surjective : Function.Surjective coverMapPin := by
  rintro ⟨g, hg⟩
  rw [mem_bvIsomLinMonoid] at hg
  have hgc : g ∈ Submonoid.closure houseHolderMSet := by
    rw [reflection_closure_eq_bvIsomLinMonoid]; exact (mem_bvIsomLinMonoid).mpr hg
  obtain ⟨u, hu_pin, hu_cov⟩ := pin_covers_word hgc
  refine ⟨⟨u, hu_pin⟩, ?_⟩
  apply Subtype.ext
  show coverOp ⟨u, pinSub_le_coversSub hu_pin⟩ = g
  exact cliffCovers_unique (coverOp_covers ⟨u, pinSub_le_coversSub hu_pin⟩) hu_cov

/-- The kernel element `-1` is a REFLECTION SQUARE: `(cliffUnitOf mSpaceUnit)² = -1`. -/
theorem cliffUnitOf_mSpaceUnit_sq :
    (cliffUnitOf mSpaceUnit (by rw [BvC_mSpaceUnit_self]; exact neg_ne_zero.mpr one_ne_zero)) ^ 2
      = (-1 : CliffCˣ) := by
  apply Units.ext
  have hms : BvC (mSpaceUnit : STVC) (mSpaceUnit : STVC) ≠ 0 := by
    rw [BvC_mSpaceUnit_self]; exact neg_ne_zero.mpr one_ne_zero
  rw [sq, Units.val_mul, Units.val_neg, Units.val_one, cliffUnitOf_val]
  rw [CliffordAlgebra.ι_sq_scalar QvCQuad mSpaceUnit, QvCQuad_apply, QvC_mSpaceUnit]
  rw [map_neg, map_one]

/-- ★ THE KERNEL ELEMENT `-1` IS A GENUINE PIN ELEMENT (a reflection square). -/
theorem negOne_mem_pinSub : (-1 : CliffCˣ) ∈ PinSub := by
  have hms : BvC (mSpaceUnit : STVC) (mSpaceUnit : STVC) ≠ 0 := by
    rw [BvC_mSpaceUnit_self]; exact neg_ne_zero.mpr one_ne_zero
  have h2 : (cliffUnitOf mSpaceUnit hms) ^ 2 ∈ PinSub := by
    rw [sq]; exact mul_mem (cliffUnitOf_mem_pinSub hms) (cliffUnitOf_mem_pinSub hms)
  have heq : (cliffUnitOf mSpaceUnit hms) ^ 2 = (-1 : CliffCˣ) := cliffUnitOf_mSpaceUnit_sq
  rwa [heq] at h2

/-- The Pin element `-1` lies in the kernel of the Pin double cover (covers `id`). -/
theorem negOne_mem_mker_coverMapPin :
    (⟨(-1 : CliffCˣ), negOne_mem_pinSub⟩ : PinSub) ∈ MonoidHom.mker coverMapPin := by
  rw [MonoidHom.mem_mker]
  apply Subtype.ext
  show coverOp ⟨(-1 : CliffCˣ), pinSub_le_coversSub negOne_mem_pinSub⟩ = (1 : Module.End Cut STVC)
  exact cliffCovers_unique
    (coverOp_covers ⟨(-1 : CliffCˣ), pinSub_le_coversSub negOne_mem_pinSub⟩)
    cover_kernel_neg_one

/-- ★ THE KERNEL IS GENUINELY ORDER ≥ 2 at the group-map level. -/
theorem coverMapPin_mker_nontrivial :
    (⟨(-1 : CliffCˣ), negOne_mem_pinSub⟩ : PinSub) ≠ 1 ∧
    (⟨(-1 : CliffCˣ), negOne_mem_pinSub⟩ : PinSub) ∈ MonoidHom.mker coverMapPin := by
  refine ⟨?_, negOne_mem_mker_coverMapPin⟩
  intro h
  have : (-1 : CliffCˣ) = 1 := congrArg Subtype.val h
  exact cover_kernel_distinct this

/-- W8: the concrete boost (5/3,4/3) is the image under coverMapPin of a Pin covering unit. -/
theorem coverMapPin_boost_apply :
    ∃ u : PinSub, (coverMapPin u : Module.End Cut STVC) = boostEndC ((5:Cut)/3) ((4:Cut)/3) := by
  have hab : ((5:Cut)/3) ^ 2 - ((4:Cut)/3) ^ 2 = 1 := by ring
  have hg : boostEndC ((5:Cut)/3) ((4:Cut)/3) ∈ bvIsomLinMonoid := boostEndC_isBvIsomLin hab
  obtain ⟨pu, hpu⟩ := coverMapPin_surjective ⟨_, hg⟩
  exact ⟨pu, congrArg Subtype.val hpu⟩

end

end N145Probe
