/-
  Phys.Algebra.DerivationSemisimpleModule — N30a: the Lie→associative
  SEMISIMPLE-MODULE BRIDGE `IsSemisimpleModule A_I ↥ImO`.
  ===========================================================================
  The prime-7 / isotypic-Schur structure theorem (N30b) that closes
  `IsSimpleOrder (LieIdeal ℚ derivationLieQ)` runs on an ASSOCIATIVE module fact —
  it needs `V = ImO` to be a SEMISIMPLE module over the associative subalgebra
  `A_I ⊆ End ℚ ImO` generated by the action of a Lie ideal `I`. Mathlib has the
  isotypic/Schur machinery for semisimple ASSOCIATIVE modules, but it has NO
  Lie-module → associative-module semisimplicity bridge. This file BUILDS that
  bridge (docs/RUNBOOK.md W1: Mathlib-absence-is-not-a-wall, build it FORWARD).

  ★ THE TRUNK ROUTE (THE ONE LAW; reuse N27, do NOT re-derive complete reducibility).
  The bridge is N27's Born-orthogonal complete reducibility transported from the WHOLE
  algebra to the SUBalgebra `A_I`. It is proved GENERICALLY: for ANY symmetric reflexive
  bilinear form `B` on a finite-dimensional space `V` whose restriction to every subspace
  is nondegenerate (the DEFINITE / Born-positivity hypothesis), and ANY set `S` of
  `B`-skew-adjoint operators, the module `V` over `Algebra.adjoin K S` is SEMISIMPLE:
  every `A`-submodule `P` has the `B`-orthogonal complement of its underlying subspace as
  an `A`-submodule complement. The orthogonal is `A`-stable because `A` is generated by
  `B`-skew-adjoint operators (`adjoin_stable_orthogonal`, by `Algebra.adjoin_induction`),
  and it is a genuine linear complement because `B` is definite
  (`isCompl_orthogonal_of_restrict_nondegenerate`). Then the bridge is the INSTANTIATION
  at `V = ↥ImO`, `B = gBil.restrict ImO` (definite by the banked Born anisotropy
  `gForm_self_eq_zero`), `S = imRep '' I` (skew-adjoint by the banked N28 `restrictOp_skew`).

  ★ WHAT THIS FILE BANKS (FORWARD, foundations-only, NO posited G₂):
    skewAdjoint_mapsTo_orthogonal — a skew-adjoint operator preserving `N` preserves
                                    `B.orthogonal N` (generic; mirrors N27
                                    `deriv_mapsTo_orthogonal`).
    adjoin_stable_orthogonal      — `B.orthogonal (P.restrictScalars K)` is `A`-stable for
                                    `A = adjoin K S`, `S` skew-adjoint (generic).
    isCompl_of_restrictScalars    — `IsCompl` transfers down the scalar-restriction
                                    order-embedding `Submodule A V → Submodule K V`.
    orthogonalASubmodule          — the `A`-submodule with carrier `B.orthogonal
                                    (P.restrictScalars K)` (the complement).
    isSemisimpleModule_adjoin     — ★★ THE GENERIC BRIDGE: `IsSemisimpleModule
                                    (adjoin K S) V` from definiteness + skew-adjointness.
    imRep_isSkewAdjoint_gImO      — `imRep D` is skew-adjoint for `gBil.restrict ImO`
                                    (instantiation lever, banked N28 `restrictOp_skew`).
    gImO_restrict_nondegenerate   — `(gBil.restrict ImO).restrict W` is nondegenerate for
                                    every `W` (the Born anisotropy on `↥ImO`).
    semisimpleModule_imRep_adjoin — ★★★ THE BRIDGE at `↥ImO`: for any Lie ideal `I`,
                                    `IsSemisimpleModule A_I ↥ImO` with
                                    `A_I = Algebra.adjoin ℚ (imRep '' I)`.

  THE MOAT — posit-vs-derive (docs/STANDARD.md §0). NO `LieAlgebra.g₂`/`G₂` imported to
  assert anything. `IsSemisimpleModule`/`ComplementedLattice`/`Submodule A`/`Algebra.adjoin`/
  `Module.End`/`BilinForm.orthogonal` are MACHINERY on the DERIVED object (docs/STANDARD.md §3);
  the result is a STRUCTURAL FACT about the banked `imRep`/`gBil`/`ImO`, proved from their own
  banked definiteness (N27) + skew-adjointness (N28).

  PHYSICS-WORDS-REMOVABLE (docs/STANDARD.md §2). Delete "g₂ / gauge / compact / simple":
  what remains is the pure statement that the associative subalgebra generated by the action
  of a Lie ideal on the invariant 7-dim subspace `ker(star+1)` of the Cayley–Dickson double
  of a double of a double of ℚ acts SEMISIMPLY (every submodule has a complement).

  Foundations-only: no posited axiom, no sorry, no kernel-trust bypass, no bridge.
-/
import Phys.Algebra.DerivationSimpleStructure
import Mathlib.RingTheory.SimpleModule.Basic

namespace Phys.Algebra

open Phys.Cascade Phys.Cascade.CD LieAlgebra
open LinearMap (BilinForm)

attribute [local instance] CD.narCD CD.srCD dblModuleQ cdModuleQ
attribute [local instance] derivationLieQ_semisimple

noncomputable section

/-! ## The GENERIC bridge: a definite symmetric form makes the adjoin-action semisimple.

    Proved for an arbitrary symmetric reflexive form `B` on a finite-dimensional `V` whose
    restriction to every subspace is nondegenerate (the Born-positivity / definite
    hypothesis), and an arbitrary set `S` of `B`-skew-adjoint operators. This is N27's
    Born-orthogonal complete reducibility transported from the whole derivation algebra to
    the subalgebra `Algebra.adjoin K S`. -/

section Generic

variable {K V : Type*} [Field K] [AddCommGroup V] [Module K V]

/-- ★ A `B`-skew-adjoint operator `T` that preserves a subspace `N` preserves the
    `B`-orthogonal complement `B.orthogonal N`. The skew-adjointness moves `T` across the
    (symmetric) form onto `N`, where invariance closes it. Generic mirror of the banked N27
    `deriv_mapsTo_orthogonal`. -/
theorem skewAdjoint_mapsTo_orthogonal (B : BilinForm K V) (hsymm : B.IsSymm)
    (N : Submodule K V) (T : Module.End K V) (hskew : B.IsSkewAdjoint T)
    (hN : ∀ n ∈ N, T n ∈ N) {x : V} (hx : x ∈ B.orthogonal N) :
    T x ∈ B.orthogonal N := by
  have hsymmeq : ∀ a b : V, B a b = B b a := by
    intro a b; have := hsymm.eq a b; simpa using this
  rw [BilinForm.mem_orthogonal_iff]
  intro n hn
  rw [BilinForm.isOrtho_def]
  have hxortho : B (T n) x = 0 := by
    have : B.IsOrtho (T n) x := (BilinForm.mem_orthogonal_iff.mp hx) (T n) (hN n hn)
    rwa [BilinForm.isOrtho_def] at this
  calc B n (T x) = B (T x) n := hsymmeq n (T x)
    _ = B x ((-T) n) := hskew x n
    _ = B x (-(T n)) := by rw [LinearMap.neg_apply]
    _ = -(B x (T n)) := by rw [map_neg]
    _ = -(B (T n) x) := by rw [hsymmeq x (T n)]
    _ = 0 := by rw [hxortho, neg_zero]

/-- ★ The `B`-orthogonal complement of an `A`-submodule's underlying `K`-subspace is
    `A`-STABLE, when `A = Algebra.adjoin K S` and every generator `T ∈ S` is `B`-skew-adjoint.
    By `Algebra.adjoin_induction`: generators preserve it (`skewAdjoint_mapsTo_orthogonal`,
    since the `A`-submodule is closed under the generators' action); `algebraMap` is a
    `K`-scalar and a `K`-subspace is `smul`-closed; sums/products of preservers preserve. -/
theorem adjoin_stable_orthogonal (B : BilinForm K V) (hsymm : B.IsSymm)
    (S : Set (Module.End K V)) (hS : ∀ T ∈ S, B.IsSkewAdjoint T)
    (P : Submodule (Algebra.adjoin K S) V) (a : Module.End K V)
    (ha : a ∈ Algebra.adjoin K S) {x : V}
    (hx : x ∈ B.orthogonal (P.restrictScalars K)) :
    a x ∈ B.orthogonal (P.restrictScalars K) := by
  have hbase : ∀ T ∈ S, ∀ y ∈ B.orthogonal (P.restrictScalars K),
      T y ∈ B.orthogonal (P.restrictScalars K) := by
    intro T hT y hy
    have hTA : T ∈ Algebra.adjoin K S := Algebra.subset_adjoin hT
    have hpres : ∀ n ∈ P.restrictScalars K, T n ∈ P.restrictScalars K := by
      intro n hn
      have : (⟨T, hTA⟩ : Algebra.adjoin K S) • n ∈ P := P.smul_mem ⟨T, hTA⟩ hn
      simpa [Submodule.restrictScalars_mem] using this
    exact skewAdjoint_mapsTo_orthogonal B hsymm (P.restrictScalars K) T (hS T hT) hpres hy
  refine Algebra.adjoin_induction
    (p := fun b _ => ∀ z ∈ B.orthogonal (P.restrictScalars K),
      b z ∈ B.orthogonal (P.restrictScalars K))
    ?_ ?_ ?_ ?_ ha x hx
  · intro T hT z hz; exact hbase T hT z hz
  · intro r z hz
    have heq : (algebraMap K (Module.End K V) r) z = r • z := by
      simp [Algebra.algebraMap_eq_smul_one]
    rw [heq]; exact (B.orthogonal (P.restrictScalars K)).smul_mem r hz
  · intro f g _ _ hf hg z hz
    show (f + g) z ∈ B.orthogonal (P.restrictScalars K)
    rw [LinearMap.add_apply]
    exact (B.orthogonal (P.restrictScalars K)).add_mem (hf z hz) (hg z hz)
  · intro f g _ _ hf hg z hz
    show (f * g) z ∈ B.orthogonal (P.restrictScalars K)
    rw [Module.End.mul_apply]; exact hf _ (hg z hz)

/-- ★ `IsCompl` transfers DOWN the scalar-restriction order embedding
    `Submodule A V ↪ Submodule K V`: if the underlying `K`-submodules are complementary then
    the `A`-submodules are (the embedding preserves `⊓`, `⊔`, `⊥`, `⊤` and is injective). -/
theorem isCompl_of_restrictScalars (A : Subalgebra K (Module.End K V))
    (P P' : Submodule A V)
    (h : IsCompl (P.restrictScalars K) (P'.restrictScalars K)) : IsCompl P P' := by
  have hinj := Submodule.restrictScalars_injective K A V
  constructor
  · rw [disjoint_iff]; apply hinj
    rw [Submodule.restrictScalars_inf, Submodule.restrictScalars_bot]
    exact disjoint_iff.mp h.disjoint
  · rw [codisjoint_iff]; apply hinj
    rw [Submodule.restrictScalars_sup, Submodule.restrictScalars_top]
    exact codisjoint_iff.mp h.codisjoint

/-- The `A`-submodule (`A = adjoin K S`) whose carrier is the `B`-orthogonal complement of
    `P.restrictScalars K` — the candidate complement. `A`-closed by `adjoin_stable_orthogonal`. -/
def orthogonalASubmodule (B : BilinForm K V) (hsymm : B.IsSymm)
    (S : Set (Module.End K V)) (hS : ∀ T ∈ S, B.IsSkewAdjoint T)
    (P : Submodule (Algebra.adjoin K S) V) : Submodule (Algebra.adjoin K S) V where
  carrier := B.orthogonal (P.restrictScalars K)
  add_mem' := (B.orthogonal (P.restrictScalars K)).add_mem
  zero_mem' := (B.orthogonal (P.restrictScalars K)).zero_mem
  smul_mem' := fun a _ hx => adjoin_stable_orthogonal B hsymm S hS P (a : Module.End K V) a.2 hx

/-- ★★ THE GENERIC BRIDGE. For a finite-dimensional space `V` with a symmetric reflexive form
    `B` that is DEFINITE (its restriction to every subspace is nondegenerate — the Born
    positivity), and any set `S` of `B`-skew-adjoint operators, the module `V` over the
    associative subalgebra `Algebra.adjoin K S` is SEMISIMPLE: every `A`-submodule has the
    `B`-orthogonal complement as an `A`-submodule complement. N27's complete reducibility,
    transported to the subalgebra. NO averaging, NO posited compact group, NO posited G₂. -/
theorem isSemisimpleModule_adjoin [FiniteDimensional K V]
    (B : BilinForm K V) (hsymm : B.IsSymm) (hrefl : B.IsRefl)
    (hnd : ∀ W : Submodule K V, (B.restrict W).Nondegenerate)
    (S : Set (Module.End K V)) (hS : ∀ T ∈ S, B.IsSkewAdjoint T) :
    IsSemisimpleModule (Algebra.adjoin K S) V := by
  have hcl : ComplementedLattice (Submodule (Algebra.adjoin K S) V) := by
    rw [complementedLattice_iff]
    intro P
    refine ⟨orthogonalASubmodule B hsymm S hS P, ?_⟩
    apply isCompl_of_restrictScalars
    have hcarrier : (orthogonalASubmodule B hsymm S hS P).restrictScalars K
        = B.orthogonal (P.restrictScalars K) := rfl
    rw [hcarrier]
    exact B.isCompl_orthogonal_of_restrict_nondegenerate hrefl (hnd (P.restrictScalars K))
  exact ⟨⟩

end Generic

/-! ## The instantiation at `↥ImO` — the Lie→associative bridge (FORWARD, NO posited G₂). -/

/-- `imRep D` is skew-adjoint for the restricted Born form `gBil.restrict ImO`. This is the
    banked N28 `restrictOp_skew` for `ImO`, since `restrictOp ImO _ D = imRep D` definitionally. -/
theorem imRep_isSkewAdjoint_gImO (D : derivationLieQ) :
    (gBil.restrict ImO).IsSkewAdjoint (imRep D) :=
  restrictOp_skew ImO (fun D x hx => derivLieQ_mapsTo D x hx) D

/-- The restriction of the Born form to `ImO`, then to any subspace `W`, is NONDEGENERATE —
    the Born anisotropy `gForm_self_eq_zero` (the definite / compact signature) on `↥ImO`. -/
theorem gImO_restrict_nondegenerate (W : Submodule ℚ ImO) :
    ((gBil.restrict ImO).restrict W).Nondegenerate := by
  refine ⟨?_, ?_⟩
  · intro x hx
    have h0 : gForm ((x : ImO) : O ℚ) ((x : ImO) : O ℚ) = 0 := by
      simpa [BilinForm.restrict, gBil_apply] using hx x
    exact Subtype.ext (Subtype.ext (gForm_self_eq_zero.mp h0))
  · intro y hy
    have h0 : gForm ((y : ImO) : O ℚ) ((y : ImO) : O ℚ) = 0 := by
      simpa [BilinForm.restrict, gBil_apply] using hy y
    exact Subtype.ext (Subtype.ext (gForm_self_eq_zero.mp h0))

/-- ★★★ THE Lie→ASSOCIATIVE SEMISIMPLE-MODULE BRIDGE. For ANY Lie ideal `I` of
    `derivationLieQ`, the invariant 7-rep `↥ImO` is a SEMISIMPLE module over the associative
    subalgebra `A_I := Algebra.adjoin ℚ (imRep '' I) ⊆ End ℚ ↥ImO` generated by the action of
    `I`. Every `A_I`-submodule has a complement — the prime-7 / isotypic-Schur structure
    theorem (N30b) runs on exactly this. Built FORWARD by instantiating the generic bridge at
    the DEFINITE Born form `gBil.restrict ImO` (banked N27 anisotropy) with the `I`-action's
    SKEW-ADJOINT generators (banked N28 `restrictOp_skew`). NO posited G₂, NO bridge. -/
theorem semisimpleModule_imRep_adjoin (I : LieIdeal ℚ derivationLieQ) :
    IsSemisimpleModule
      (Algebra.adjoin ℚ (Set.range (fun x : I => imRep (I.incl x)))) ImO :=
  isSemisimpleModule_adjoin (gBil.restrict ImO) (gBil_restrict_symm ImO)
    ((gBil_restrict_symm ImO).isRefl) gImO_restrict_nondegenerate
    (Set.range (fun x : I => imRep (I.incl x)))
    (by rintro T ⟨x, rfl⟩; exact imRep_isSkewAdjoint_gImO (I.incl x))

end
end Phys.Algebra
