/-
  Phys.Algebra.DerivationDblPhase — N186: THE U(1) HYPERCHARGE PHASE ALGEBRA
  `so(Born on Dbl ℚ) ≅ so(2) ≅ u(1)`, dimension 1 — the THIRD Standard-Model
  gauge factor's rank, on the complex-unit rung `Dbl ℚ`.
  ===========================================================================
  THE THIRD SM GAUGE FACTOR. The Standard-Model gauge group `SU(3) × SU(2) × U(1)`
  now has its COLOUR `SU(3) ⊂ G₂ = Der(O)` banked (N42a/b/c, `dim G₂ = 14`, N20) and
  its WEAK-ISOSPIN `SU(2) = Der(H)` banked (N184 bracket `⁅ad_i,ad_j⁆ = 2·ad_k` +
  N185 `dim = 3`). THIS node banks the remaining U(1) HYPERCHARGE factor — the abelian
  phase rotation on the cascade's FIRST doubling, the complex-unit rung `Dbl ℚ` (N2),
  one Cayley–Dickson step BELOW the quaternions `H ℚ = CD (Dbl ℚ)`.

  ★ THE KEY MEASUREMENT (docs/RUNBOOK.md W9 measure-first, frozen in PREREG). `Dbl ℚ` is
  COMMUTATIVE, so its INNER derivations VANISH (`ad_q = q·x − x·q = 0` for all `q`) — the
  U(1) is NOT an inner-derivation story like su(2)/g₂. The correct, theory-faithful object
  is the SKEW-ROTATION algebra of the self-overlap (Born) form: the skew-adjoint operators
  `so(bForm)` of `bForm v w := (v · star w).re` on the 2-dimensional `Dbl ℚ`. This is
  `so(2)`, and `so(2) ≅ u(1)` is the abelian 1-dimensional Lie algebra GENERATED by the
  phase rotation `z ↦ J·z` — exactly multiplication by the DERIVED complex unit `J`
  (the fold-root `mulJ_isFoldRoot`, N2), whose square is `−1`.

  ★ THE ROUTE — the so(n)-bound (N28) reused at the smallest rung (docs/RUNBOOK.md W2:
  import-and-USE a banked theorem). N28 (`DerivationIrreducibleFull.lean`) BUILT FORWARD
  the so(n)-type dimension bound `finrank_skewAdjoint_le_choose`: the skew-adjoint operators
  of a symmetric nondegenerate form on a `d`-dimensional space have dimension `≤ C(d, 2)`,
  via the exterior-power injection `D ↦ ((x,y) ↦ Φ (D x) y)` into `Dual (⋀² V)`. Applied to
  `V = Dbl ℚ` (`finrank = 2`, banked N19 `finrank_dbl_eq_two`): the UPPER bound is
  `C(2, 2) = 1`. The LOWER bound is the nonzero skew generator `L_J` (`L_J ≠ 0` and
  skew-adjoint), giving `1 ≤ dim`. Hence `dim = 1` — the dim-1 analog of `dim G₂ = 14`
  (colour) and `dim su(2) = 3` (isospin), here the FULL classification-sufficient signature
  (there is exactly ONE 1-dimensional Lie algebra up to isomorphism — necessarily abelian).

  WHAT IS BANKED HERE (forward, foundations-only):
    bForm              — the self-overlap (Born) form `(v,w) ↦ (v · star w).re` on `Dbl ℚ`.
    bForm_self         — `bForm v v = v.re² + v.im²` (the positivity, one rung down).
    bForm_isSymm       — `bForm` is symmetric.
    bForm_self_eq_zero — anisotropy: `bForm v v = 0 ↔ v = 0` (the Born positivity).
    bForm_nondegenerate— `bForm` is nondegenerate (definite ⟹ nondegenerate).
    L_J                — the phase rotation `z ↦ J·z` (multiplication by the complex unit).
    L_J_skew           — ★ the phase rotation is SKEW-ADJOINT for `bForm` (`J* = −J`).
    L_J_ne_zero        — the phase rotation is genuinely nonzero (W8 anti-vacuity).
    dim_le_one         — UPPER bound `dim so(bForm) ≤ C(2,2) = 1` (the so(n)-bound N28).
    skewAdjoint_ne_bot — the skew-adjoint algebra is nonzero (contains `L_J`).
    one_le_dim         — LOWER bound `1 ≤ dim so(bForm)`.
    finrank_phase_eq_one — ★★ THE u(1) ≅ so(2) DIMENSION = 1 (the third SM gauge rank).
    phase_eq_span_L_J  — ★ the WHOLE phase algebra IS the span of `L_J`: the derived complex
                         unit `J` GENERATES the entire u(1) (the generator is the algebra).

  THE MOAT — posit-vs-derive (docs/STANDARD.md §0). The division-algebra-physics field
  (Furey, Dixon, Günaydin–Gürsey) POSITS the complex line ℂ and reads `U(1)` phase off by
  hand. Here `Dbl ℚ` is the cascade's OWN first doubling (N2, the forced complex unit), `J`
  is the DERIVED fold-root, and `dim u(1) = 1` DESCENDS from the so(n)-bound (N28) +
  `finrank_dbl_eq_two` (N19) — NO posited u(1)/so(2)/U(1)/Lie group, NO Mathlib ℝ/ℂ as
  content (ℚ is the coefficient field the `finrank`/`BilinForm` statements are WRITTEN IN,
  the N6/N16/N42/N184/N185 precedent; the OBJECT is the derived complex-unit rung).

  PHYSICS-WORDS-REMOVABLE (docs/STANDARD.md §2). Delete "hypercharge / U(1) / so(2) / phase /
  gauge": what remains is the pure statement that the skew-adjoint operators of the form
  `(v,w) ↦ (v · star w).re` on the 2-dimensional commutative algebra `Dbl ℚ` form a
  1-dimensional space, spanned by multiplication by the element `J` with `J · J = −1`. No
  theorem STATEMENT needs a physics word.

  Foundations-only: no posited axiom, no sorry, no kernel-trust bypass, no bridge.
-/
import Phys.Algebra.DerivationIrreducibleFull
import Mathlib.Tactic

namespace Phys.Algebra

open Phys.Cascade Phys.Cascade.CD
open LinearMap (BilinForm)

attribute [local instance] dblModuleQ

noncomputable section

/-- `star` is ℚ-linear on the complex-unit rung (componentwise). -/
theorem dbl_star_qsmul (c : ℚ) (w : Dbl ℚ) : star (c • w) = c • star w := by
  ext <;> simp [Dbl.star_re', Dbl.star_im', Dbl.smul_re, Dbl.smul_im]

/-- ★ THE SELF-OVERLAP (BORN) FORM on the complex-unit rung `Dbl ℚ`:
    `bForm v w := (v · star w).re` (the trunk's self-overlap form, one rung below `O`). -/
def bForm : BilinForm ℚ (Dbl ℚ) where
  toFun v := {
    toFun := fun w => (v * star w).re
    map_add' := by intro w1 w2; simp [Dbl.mul_re, Dbl.star_re', Dbl.star_im']; ring
    map_smul' := by
      intro c w
      simp only [RingHom.id_apply, smul_eq_mul]
      show (v * star (c • w)).re = c * (v * star w).re
      rw [dbl_star_qsmul]
      simp [Dbl.mul_re, Dbl.smul_re, Dbl.smul_im]; ring }
  map_add' := by intro v1 v2; ext w; simp [Dbl.mul_re, Dbl.star_re', Dbl.star_im']; ring
  map_smul' := by
    intro c v; ext w
    simp only [RingHom.id_apply, smul_eq_mul, LinearMap.smul_apply, LinearMap.coe_mk,
      AddHom.coe_mk]
    show ((c • v) * star w).re = c * (v * star w).re
    simp [Dbl.mul_re, Dbl.smul_re]; ring

@[simp] theorem bForm_apply (v w : Dbl ℚ) : bForm v w = (v * star w).re := rfl

/-- `bForm v v = v.re² + v.im²` — a sum of two ℚ-squares (the Born positivity, one rung down). -/
theorem bForm_self (v : Dbl ℚ) : bForm v v = v.re ^ 2 + v.im ^ 2 := by
  simp only [bForm_apply, Dbl.mul_re, Dbl.star_re', Dbl.star_im']; ring

/-- `bForm` is symmetric (the self-overlap form is symmetric). -/
theorem bForm_symm (v w : Dbl ℚ) : bForm v w = bForm w v := by
  simp only [bForm_apply, Dbl.mul_re, Dbl.star_re', Dbl.star_im']; ring

theorem bForm_isSymm : (bForm).IsSymm := ⟨fun x y => bForm_symm x y⟩

/-- ★ ANISOTROPY: `bForm v v = 0 ↔ v = 0` — the Born positivity (a sum of two squares
    vanishes iff each coordinate does). The definiteness the nondegeneracy rests on. -/
theorem bForm_self_eq_zero {v : Dbl ℚ} : bForm v v = 0 ↔ v = 0 := by
  rw [bForm_self]
  constructor
  · intro h
    have hre : v.re = 0 := by nlinarith [sq_nonneg v.re, sq_nonneg v.im]
    have him : v.im = 0 := by nlinarith [sq_nonneg v.re, sq_nonneg v.im]
    exact Dbl.ext hre him
  · intro h; subst h; simp

/-- ★ `bForm` is NONDEGENERATE — the definite (compact) self-overlap form. -/
theorem bForm_nondegenerate : bForm.Nondegenerate := by
  refine ⟨?_, ?_⟩
  · intro x hx
    have : bForm x x = 0 := hx x
    exact bForm_self_eq_zero.mp this
  · intro y hy
    have : bForm y y = 0 := by rw [bForm_symm]; exact hy y
    exact bForm_self_eq_zero.mp this

/-- ★ THE PHASE ROTATION `z ↦ J·z` — multiplication by the DERIVED complex unit `J`
    (the fold-root, N2). The candidate generator of the u(1) ≅ so(2) phase algebra. -/
def L_J : Module.End ℚ (Dbl ℚ) where
  toFun z := Dbl.J * z
  map_add' := by intro x y; ring
  map_smul' := by
    intro c z; simp only [RingHom.id_apply]
    show Dbl.J * (c • z) = c • (Dbl.J * z)
    ext <;> simp [Dbl.J, Dbl.mul_re, Dbl.mul_im, Dbl.smul_re, Dbl.smul_im]

@[simp] theorem L_J_apply (z : Dbl ℚ) : L_J z = Dbl.J * z := rfl

/-- ★ THE PHASE ROTATION IS SKEW-ADJOINT for the self-overlap form: `bForm (J·x) y =
    bForm x (−(J·y))`, i.e. `J* = −J`. The complex unit's conjugate is its negation, so
    multiplication-by-`J` lands in `so(bForm)`. -/
theorem L_J_skew : bForm.IsSkewAdjoint L_J := by
  intro x y
  show bForm (Dbl.J * x) y = bForm x ((-L_J) y)
  simp only [LinearMap.neg_apply, L_J_apply, bForm_apply]
  simp only [Dbl.J, Dbl.mul_re, Dbl.mul_im, Dbl.star_re', Dbl.star_im', Dbl.neg_re, Dbl.neg_im]
  ring

/-- ★ W8 ANTI-VACUITY: the phase rotation is genuinely NONZERO (`J · 1 = J ≠ 0`). The
    skew-adjoint algebra is not the zero space; the dimension `1` has teeth. -/
theorem L_J_ne_zero : L_J ≠ 0 := by
  intro h
  have h1 : L_J (1 : Dbl ℚ) = 0 := by rw [h]; rfl
  rw [L_J_apply, mul_one] at h1
  have : (1 : ℚ) = 0 := by have := congrArg Dbl.im h1; simpa [Dbl.J] using this
  exact one_ne_zero this

instance : FiniteDimensional ℚ (Dbl ℚ) :=
  Module.Finite.equiv dblProdEquiv.symm

/-- UPPER BOUND: `dim so(bForm) ≤ C(finrank (Dbl ℚ), 2) = C(2, 2) = 1` — the so(n)-type
    bound (N28 `finrank_skewAdjoint_le_choose`) at the smallest rung, over `finrank_dbl_eq_two`
    (N19). -/
theorem dim_le_one : Module.finrank ℚ bForm.skewAdjointSubmodule ≤ 1 := by
  have h := finrank_skewAdjoint_le_choose bForm bForm_isSymm bForm_nondegenerate
  rw [finrank_dbl_eq_two] at h
  simpa using h

/-- The skew-adjoint algebra is NONZERO — it contains the nonzero phase rotation `L_J`. -/
theorem skewAdjoint_ne_bot : bForm.skewAdjointSubmodule ≠ ⊥ := by
  intro h
  apply L_J_ne_zero
  have hmem : L_J ∈ bForm.skewAdjointSubmodule :=
    (LinearMap.mem_skewAdjointSubmodule _).mpr L_J_skew
  rw [h, Submodule.mem_bot] at hmem
  exact hmem

/-- LOWER BOUND: `1 ≤ dim so(bForm)` (the algebra is nonzero). -/
theorem one_le_dim : 1 ≤ Module.finrank ℚ bForm.skewAdjointSubmodule :=
  Submodule.one_le_finrank_iff.mpr skewAdjoint_ne_bot

/-- ★★ THE u(1) ≅ so(2) DIMENSION = 1. The THIRD Standard-Model gauge factor's rank, the
    dim-1 analog of `dim G₂ = 14` (colour, N20) and `dim su(2) = 3` (isospin, N185). The
    skew-rotation algebra of the self-overlap form on the complex-unit rung is exactly
    1-dimensional — the FULL classification-sufficient signature of `u(1)` (the unique
    1-dimensional, necessarily abelian, Lie algebra). -/
theorem finrank_phase_eq_one : Module.finrank ℚ bForm.skewAdjointSubmodule = 1 :=
  le_antisymm dim_le_one one_le_dim

/-- ★ THE DERIVED COMPLEX UNIT GENERATES THE WHOLE u(1): the entire phase algebra is the
    span of the single phase rotation `L_J`. So `so(2) ≅ u(1)` is exactly multiplication by
    the fold-derived complex unit `J` — the generator IS the algebra, not merely one element
    of it. -/
theorem phase_eq_span_L_J : bForm.skewAdjointSubmodule = ℚ ∙ L_J := by
  symm
  apply Submodule.eq_of_le_of_finrank_eq
  · rw [Submodule.span_le, Set.singleton_subset_iff]
    exact (LinearMap.mem_skewAdjointSubmodule _).mpr L_J_skew
  · rw [finrank_span_singleton L_J_ne_zero, finrank_phase_eq_one]

end

end Phys.Algebra
