/-
  Phys.Algebra.DerivationUpperBound — N20 (U): the UPPER BOUND dim_ℚ Der(O ℚ) ≤ 14
  (the so(7)→g₂ cut 21→14), closing the EXACT dimension dim_ℚ Der(O ℚ) = 14.
  ===========================================================================
  N19 banked the LOWER bound `14 ≤ finrank ℚ derivationQ` (14 explicit independent
  derivations) and the scaffold `finrank ℚ (O ℚ) = 8`, `derivationQ` as a ℚ-submodule
  of `Module.End ℚ (O ℚ)`, the bounds `14 ≤ dim ≤ 64`. THIS module proves the matching
  UPPER bound `finrank ℚ derivationQ ≤ 14`, derived FORWARD, NO posited `G₂`; with
  `le_antisymm` against the banked lower bound this closes `finrank ℚ derivationQ = 14`.

  ★ THE TRUNK REFRAME OF THE 21→14 CUT (the genuinely-hard rep-theoretic half, here
  DISSOLVED from the fold rather than ground out by a generic so(7) representation
  argument). The octonion shape `O ℚ` is multiplicatively GENERATED by three imaginary
  units `e1, e2, e4`: `e3 = e1·e2`, `e5 = e1·e4`, `e6 = e2·e4`, `e7 = (e1·e2)·e4`, and
  `e0 = 1`. So a derivation `D` (which satisfies `D 1 = 0` and the Leibniz law) is
  COMPLETELY DETERMINED by the three values `D e1, D e2, D e4` (`determined`). This
  places `Der(O ℚ)` inside `(O ℚ)³` via `D ↦ (D e1, D e2, D e4)`.

  ★ THE CUT. Each `D ei` is trace-free (lands in the 7-dim imaginary subspace — banked
  N18 `deriv_reQ_zero`), so the naive count is `3 × 7 = 21`. The Leibniz law on the
  generator products imposes EXACTLY the constraints that cut `21 → 14`: reading the
  deep-real (`c0`) coordinate of the Leibniz identity at each generator product — which
  vanishes because the product's derivative is itself trace-free — forces, together with
  the 14 pivot coordinates, every coordinate of `D e1, D e2, D e4` to vanish. The single
  genuinely-octonionic step is the `e3·e4 = e7` relation (the non-associativity that
  STOPPED the cascade: the associator `(e1,e2,e4) = 2 e7 ≠ 0`); here it is fully
  structural, the c0-coordinate of one Leibniz instance.

  ★ THE BOUND. The 14 pivot coordinates assemble into an injective ℚ-linear map
  `coordMap : derivationQ →ₗ[ℚ] (Fin 14 → ℚ)`; injectivity is exactly the cascade above
  (`coordMap_injective`). `LinearMap.finrank_le_finrank_of_injective` then gives
  `finrank ℚ derivationQ ≤ finrank ℚ (Fin 14 → ℚ) = 14`. Combined with the banked
  `finrank_derivationQ_ge_14`, `le_antisymm` closes `finrank ℚ derivationQ = 14`.

  THE MOAT — posit-vs-derive (docs/STANDARD.md §0). The division-algebra field POSITS
  `𝕆` and reads `dim Der(𝕆) = dim g₂ = 14` off the exceptional Lie algebra by hand. Here
  the count is DERIVED FORWARD from the Leibniz law on the DERIVED octonion product:
  the lower bound by 14 explicit derivations (N19), the upper bound by the generator
  determination + the structural cut (this node). No `LieAlgebra.g2` / `G₂` is imported
  to assert the value. The `Module ℚ` / `finrank` / `Submodule` structure is MACHINERY
  on the DERIVED object `O ℚ` (docs/STANDARD.md §3), not a posited number system.

  PHYSICS-WORDS-REMOVABLE (docs/STANDARD.md §2). Delete "gauge / g₂ / automorphism":
  what remains is the pure statement that the Leibniz-derivation ℚ-submodule of the
  Cayley–Dickson double of a double of a double has dimension at most 14, and (with the
  banked lower bound) exactly 14. No theorem STATEMENT needs a physics word.

  Foundations-only: no posited axiom, no sorry, no kernel-trust bypass, no bridge.
-/
import Phys.Algebra.DerivationLowerBound
import Mathlib.LinearAlgebra.Dimension.StrongRankCondition
import Mathlib.Tactic

namespace Phys.Algebra

open Phys.Cascade Phys.Cascade.CD

attribute [local instance] CD.narCD CD.srCD dblModuleQ cdModuleQ

/-! ## The concrete imaginary basis units `e0 … e7` of `O ℚ` (coordinate layout
    `c0 … c7`). Machinery on the DERIVED object (docs/STANDARD.md §3). -/

/-- The unit `e0 = 1`. -/
def u0 : O ℚ := 1
/-- The generator `e1`. -/
def u1 : O ℚ := ⟨⟨⟨0,1⟩, ⟨0,0⟩⟩, ⟨⟨0,0⟩, ⟨0,0⟩⟩⟩
/-- The generator `e2`. -/
def u2 : O ℚ := ⟨⟨⟨0,0⟩, ⟨1,0⟩⟩, ⟨⟨0,0⟩, ⟨0,0⟩⟩⟩
/-- The product `e3 = e1·e2`. -/
def u3 : O ℚ := ⟨⟨⟨0,0⟩, ⟨0,1⟩⟩, ⟨⟨0,0⟩, ⟨0,0⟩⟩⟩
/-- The generator `e4`. -/
def u4 : O ℚ := ⟨⟨⟨0,0⟩, ⟨0,0⟩⟩, ⟨⟨1,0⟩, ⟨0,0⟩⟩⟩
/-- The product `e5 = e1·e4`. -/
def u5 : O ℚ := ⟨⟨⟨0,0⟩, ⟨0,0⟩⟩, ⟨⟨0,1⟩, ⟨0,0⟩⟩⟩
/-- The product `e6 = e2·e4`. -/
def u6 : O ℚ := ⟨⟨⟨0,0⟩, ⟨0,0⟩⟩, ⟨⟨0,0⟩, ⟨1,0⟩⟩⟩
/-- The product `e7 = e3·e4`. -/
def u7 : O ℚ := ⟨⟨⟨0,0⟩, ⟨0,0⟩⟩, ⟨⟨0,0⟩, ⟨0,1⟩⟩⟩

/-- A local simp-set name list for unfolding the Cayley–Dickson product/star/neg/add
    on coordinates. -/
private lemma mul_u12 : u1 * u2 = u3 := by
  ext <;> simp [u1, u2, u3, CD.mul_re, CD.mul_im, CD.add_re, CD.add_im,
    Dbl.mul_re, Dbl.mul_im, Dbl.add_re, Dbl.add_im, CD.star_re, CD.star_im,
    Dbl.star_re', Dbl.star_im', CD.neg_re, CD.neg_im, Dbl.neg_re, Dbl.neg_im]

private lemma mul_u14 : u1 * u4 = u5 := by
  ext <;> simp [u1, u4, u5, CD.mul_re, CD.mul_im, CD.add_re, CD.add_im,
    Dbl.mul_re, Dbl.mul_im, Dbl.add_re, Dbl.add_im, CD.star_re, CD.star_im,
    Dbl.star_re', Dbl.star_im', CD.neg_re, CD.neg_im, Dbl.neg_re, Dbl.neg_im]

private lemma mul_u24 : u2 * u4 = u6 := by
  ext <;> simp [u2, u4, u6, CD.mul_re, CD.mul_im, CD.add_re, CD.add_im,
    Dbl.mul_re, Dbl.mul_im, Dbl.add_re, Dbl.add_im, CD.star_re, CD.star_im,
    Dbl.star_re', Dbl.star_im', CD.neg_re, CD.neg_im, Dbl.neg_re, Dbl.neg_im]

private lemma mul_u34 : u3 * u4 = u7 := by
  ext <;> simp [u3, u4, u7, CD.mul_re, CD.mul_im, CD.add_re, CD.add_im,
    Dbl.mul_re, Dbl.mul_im, Dbl.add_re, Dbl.add_im, CD.star_re, CD.star_im,
    Dbl.star_re', Dbl.star_im', CD.neg_re, CD.neg_im, Dbl.neg_re, Dbl.neg_im]

private lemma sq_u1 : u1 * u1 = -1 := by
  ext <;> simp [u1, CD.mul_re, CD.mul_im, CD.add_re, CD.add_im,
    Dbl.mul_re, Dbl.mul_im, Dbl.add_re, Dbl.add_im, CD.star_re, CD.star_im,
    Dbl.star_re', Dbl.star_im', CD.neg_re, CD.neg_im, Dbl.neg_re, Dbl.neg_im]

private lemma sq_u2 : u2 * u2 = -1 := by
  ext <;> simp [u2, CD.mul_re, CD.mul_im, CD.add_re, CD.add_im,
    Dbl.mul_re, Dbl.mul_im, Dbl.add_re, Dbl.add_im, CD.star_re, CD.star_im,
    Dbl.star_re', Dbl.star_im', CD.neg_re, CD.neg_im, Dbl.neg_re, Dbl.neg_im]

private lemma sq_u4 : u4 * u4 = -1 := by
  ext <;> simp [u4, CD.mul_re, CD.mul_im, CD.add_re, CD.add_im,
    Dbl.mul_re, Dbl.mul_im, Dbl.add_re, Dbl.add_im, CD.star_re, CD.star_im,
    Dbl.star_re', Dbl.star_im', CD.neg_re, CD.neg_im, Dbl.neg_re, Dbl.neg_im]

/-! ## `D 1 = 0`, trace-free, and the basis decomposition. -/

/-- Any ℚ-linear Leibniz derivation kills the unit: `D 1 = 0`. -/
theorem derivQ_one (D : Module.End ℚ (O ℚ)) (hD : IsDerivQ D) : D 1 = 0 := by
  have h := hD 1 1
  simp only [one_mul, mul_one] at h
  have hh : D 1 + D 1 = D 1 + 0 := by rw [add_zero]; exact h.symm
  exact add_left_cancel hh

/-- ★ THE TRACE-FREE BRIDGE: a `IsDerivQ` derivation, viewed as a ℤ-linear map, is an
    N6 `IsDeriv`, so the banked N18 `deriv_reQ_zero` applies — every output `D x` has
    vanishing deep-real coordinate. This bridges `IsDerivQ` to the whole banked
    N16/N17/N18 qualitative so(7) characterization. -/
theorem derivQ_reQ_zero (D : Module.End ℚ (O ℚ)) (hD : IsDerivQ D) (x : O ℚ) :
    (D x).re.re.re = 0 := by
  have hDz : IsDeriv (D.restrictScalars ℤ) := fun a b => hD a b
  have := deriv_reQ_zero (D.restrictScalars ℤ) hDz x
  simpa [reQ, LinearMap.restrictScalars_apply] using this

/-- The coordinate decomposition `x = Σ cᵢ(x) • eᵢ` over the 8 basis units. -/
theorem basis_decomp (x : O ℚ) :
    x = c0 x • u0 + c1 x • u1 + c2 x • u2 + c3 x • u3 + c4 x • u4 + c5 x • u5 + c6 x • u6 + c7 x • u7 := by
  ext <;> simp [c0, c1, c2, c3, c4, c5, c6, c7, u0, u1, u2, u3, u4, u5, u6, u7,
    cd_qsmul_re, cd_qsmul_im, Dbl.smul_re, Dbl.smul_im, CD.add_re, CD.add_im,
    Dbl.add_re, Dbl.add_im]

/-! ## THE DETERMINATION LEMMA — a derivation is fixed by its three generator values. -/

/-- ★ THE DETERMINATION LEMMA: a ℚ-linear Leibniz derivation that kills the three
    multiplicative generators `e1, e2, e4` is the zero map. The octonion shape is
    generated by `e1, e2, e4`: `e3 = e1·e2`, `e5 = e1·e4`, `e6 = e2·e4`,
    `e7 = e3·e4`; the Leibniz law propagates `D e1 = D e2 = D e4 = 0` to all eight
    basis units, and `basis_decomp` + ℚ-linearity then give `D x = 0` for every `x`. -/
theorem determined (D : Module.End ℚ (O ℚ)) (hD : IsDerivQ D)
    (h1 : D u1 = 0) (h2 : D u2 = 0) (h4 : D u4 = 0) : D = 0 := by
  have h0 : D u0 = 0 := derivQ_one D hD
  have h3 : D u3 = 0 := by rw [← mul_u12, hD u1 u2, h1, h2]; simp
  have h5 : D u5 = 0 := by rw [← mul_u14, hD u1 u4, h1, h4]; simp
  have h6 : D u6 = 0 := by rw [← mul_u24, hD u2 u4, h2, h4]; simp
  have h7 : D u7 = 0 := by rw [← mul_u34, hD u3 u4, h3, h4]; simp
  refine LinearMap.ext fun x => ?_
  rw [basis_decomp x]
  simp only [map_add, map_smul, h0, h1, h2, h3, h4, h5, h6, h7, smul_zero, add_zero,
    LinearMap.zero_apply]

/-! ## THE STRUCTURAL CUT 21→14 — the generator coordinates forced to vanish.

    Each lemma reads the deep-real (`c0`) coordinate of a Leibniz identity at a
    generator product. The left side `D (eᵢ·eⱼ)` is trace-free (`derivQ_reQ_zero`),
    so its `c0` vanishes; expanding the right side `D eᵢ · eⱼ + eᵢ · D eⱼ` in
    coordinates yields a linear relation among the generator coordinates. With the 14
    pivot coordinates known zero, these cascade every coordinate of `D e1, D e2, D e4`
    to zero. The single octonionic step is `e3·e4 = e7` (the non-associativity that
    stopped the cascade). -/

/-- C0: from `e1·e1 = -1`, the `c0` of the Leibniz identity gives `(D e1).c1 = 0`. -/
theorem cut_e1_c1 (D : Module.End ℚ (O ℚ)) (hD : IsDerivQ D) : (D u1).re.re.im = 0 := by
  have h := hD u1 u1
  rw [sq_u1, map_neg, derivQ_one D hD, neg_zero] at h
  set a := D u1 with ha
  have hc := congrArg (fun z => z.re.re.re) h
  simp only [u1, CD.mul_re, CD.add_re, Dbl.mul_re, Dbl.add_re, CD.star_re, CD.star_im,
    Dbl.star_re', Dbl.star_im', CD.neg_re, Dbl.neg_re, Dbl.neg_im,
    CD.zero_re, CD.zero_im, Dbl.zero_re, Dbl.zero_im] at hc
  ring_nf at hc
  linarith [hc]

/-- C2: from `e2·e2 = -1`, `(D e2).c2 = 0`. -/
theorem cut_e2_c2 (D : Module.End ℚ (O ℚ)) (hD : IsDerivQ D) : (D u2).re.im.re = 0 := by
  have h := hD u2 u2
  rw [sq_u2, map_neg, derivQ_one D hD, neg_zero] at h
  set a := D u2 with ha
  have hc := congrArg (fun z => z.re.re.re) h
  simp only [u2, CD.mul_re, CD.add_re, Dbl.mul_re, Dbl.add_re, CD.star_re, CD.star_im,
    Dbl.star_re', Dbl.star_im', CD.neg_re, Dbl.neg_re, Dbl.neg_im,
    CD.zero_re, CD.zero_im, Dbl.zero_re, Dbl.zero_im] at hc
  ring_nf at hc
  linarith [hc]

/-- C6: from `e4·e4 = -1`, `(D e4).c4 = 0`. -/
theorem cut_e4_c4 (D : Module.End ℚ (O ℚ)) (hD : IsDerivQ D) : (D u4).im.re.re = 0 := by
  have h := hD u4 u4
  rw [sq_u4, map_neg, derivQ_one D hD, neg_zero] at h
  set a := D u4 with ha
  have hc := congrArg (fun z => z.re.re.re) h
  simp only [u4, CD.mul_re, CD.add_re, Dbl.mul_re, Dbl.add_re, CD.star_re, CD.star_im,
    Dbl.star_re', Dbl.star_im', CD.neg_re, Dbl.neg_re, Dbl.neg_im,
    CD.zero_re, CD.zero_im, Dbl.zero_re, Dbl.zero_im] at hc
  ring_nf at hc
  linarith [hc]

/-- C1: from `e1·e2 = e3`, the `c0` of the Leibniz identity gives
    `(D e1).c2 + (D e2).c1 = 0`. -/
theorem cut_e12_c0 (D : Module.End ℚ (O ℚ)) (hD : IsDerivQ D) :
    (D u1).re.im.re + (D u2).re.re.im = 0 := by
  have h := hD u1 u2
  have hc := congrArg (fun z => z.re.re.re) h
  simp only [] at hc
  rw [mul_u12, derivQ_reQ_zero D hD u3] at hc
  set a := D u1 with ha
  set b := D u2 with hb
  simp only [u1, u2, CD.mul_re, CD.add_re, Dbl.mul_re, Dbl.add_re, CD.star_re, CD.star_im,
    Dbl.star_re', Dbl.star_im', CD.neg_re, Dbl.neg_re, Dbl.neg_im,
    CD.zero_im, Dbl.zero_re, Dbl.zero_im] at hc
  ring_nf at hc
  linarith [hc]

/-- C3: from `e1·e4 = e5`, the `c0` of the Leibniz identity gives
    `(D e1).c4 + (D e4).c1 = 0`. -/
theorem cut_e14_c0 (D : Module.End ℚ (O ℚ)) (hD : IsDerivQ D) :
    (D u1).im.re.re + (D u4).re.re.im = 0 := by
  have h := hD u1 u4
  have hc := congrArg (fun z => z.re.re.re) h
  simp only [] at hc
  rw [mul_u14, derivQ_reQ_zero D hD u5] at hc
  set a := D u1 with ha
  set b := D u4 with hb
  simp only [u1, u4, CD.mul_re, CD.add_re, Dbl.mul_re, Dbl.add_re, CD.star_re, CD.star_im,
    Dbl.star_re', Dbl.star_im', CD.neg_re, Dbl.neg_re, Dbl.neg_im,
    CD.zero_im, Dbl.zero_re, Dbl.zero_im] at hc
  ring_nf at hc
  linarith [hc]

/-- C4: from `e2·e4 = e6`, the `c0` of the Leibniz identity gives
    `(D e2).c4 + (D e4).c2 = 0`. -/
theorem cut_e24_c0 (D : Module.End ℚ (O ℚ)) (hD : IsDerivQ D) :
    (D u2).im.re.re + (D u4).re.im.re = 0 := by
  have h := hD u2 u4
  have hc := congrArg (fun z => z.re.re.re) h
  simp only [] at hc
  rw [mul_u24, derivQ_reQ_zero D hD u6] at hc
  set a := D u2 with ha
  set b := D u4 with hb
  simp only [u2, u4, CD.mul_re, CD.add_re, Dbl.mul_re, Dbl.add_re, CD.star_re, CD.star_im,
    Dbl.star_re', Dbl.star_im', CD.neg_re, Dbl.neg_re, Dbl.neg_im,
    CD.zero_im, Dbl.zero_re, Dbl.zero_im] at hc
  ring_nf at hc
  linarith [hc]

/-- C5 (the octonionic step): from `e3·e4 = e7`, the `c0` of the Leibniz identity gives
    `(D e3).c4 + (D e4).c3 = 0`. The non-associativity (`associator (e1,e2,e4) = 2 e7`)
    enters precisely here, as the one product not reducible to the so(7) skew relations. -/
theorem cut_e34_c0 (D : Module.End ℚ (O ℚ)) (hD : IsDerivQ D) :
    (D u3).im.re.re + (D u4).re.im.im = 0 := by
  have h := hD u3 u4
  have hc := congrArg (fun z => z.re.re.re) h
  simp only [] at hc
  rw [mul_u34, derivQ_reQ_zero D hD u7] at hc
  set a := D u3 with ha
  set b := D u4 with hb
  simp only [u3, u4, CD.mul_re, CD.add_re, Dbl.mul_re, Dbl.add_re, CD.star_re, CD.star_im,
    Dbl.star_re', Dbl.star_im', CD.neg_re, Dbl.neg_re, Dbl.neg_im,
    CD.zero_im, Dbl.zero_re, Dbl.zero_im] at hc
  ring_nf at hc
  linarith [hc]

end Phys.Algebra

