/-
  Phys.Algebra.GeneratedModule — N4: THE GENERATED OPERATOR ALGEBRA + the MODULE
  (SPINOR) STRUCTURE the terminal algebra forces.
  ===========================================================================
  THE SECOND NODE OF THE ALGEBRA LAYER (depth 2), building DIRECTLY on N3
  (`Phys/Algebra/Operator.lean`). N3 derived — forward from the cascade — that the
  imaginary left-multiplications `Lop a : y ↦ a · y` of the octonion shape
  `CD (CD B)` satisfy, in the ASSOCIATIVE operator ring `AddMonoid.End (CD (CD B))`,
  the quadratic (Clifford) relation `Lop a * Lop b + Lop b * Lop a = − Lop (ι (bilin a b))`
  (`clifford_op`) and `Lop a * Lop a = − Lop (ι (Nrm a))` on imaginaries (`L_sq_op`),
  governed by the BANKED Born self-overlap `bilin` / `Nrm` (N2).

  This module reads off the SECOND purely-algebraic structure that forces:

    (i)  THE FULL SET OF GENERATING RELATIONS, as forced laws. For an imaginary `a`
         with `Nrm a = 1` the operator squares to `−1` (`unit_sq_op`); for orthogonal
         imaginary `a, b` (`bilin a b = 0`) the operators ANTICOMMUTE
         (`ortho_anticomm_op`). These generalize N3's single concrete pair
         (`L_unit_sq` / `units_anticommute`) to ANY orthonormal imaginary family,
         governed by the banked `bilin` / `Nrm`. Made concrete on the terminal `O ℚ`
         at a full 7-element imaginary coordinate family `ebasis`: each imaginary,
         each `Nrm = 1`, pairwise `bilin = 0` — so all seven squares are `−1`
         (`Lbasis_sq`) and all twenty-one distinct pairs anticommute (`Lbasis_anticomm`).

    (ii) THE GENERATED SUBALGEBRA + ITS MODULE. The unital associative subring
         `gen` of `AddMonoid.End (CD (CD B))` GENERATED by the imaginary
         left-multiplications (`Subring.closure`), with the terminal algebra
         `CD (CD B)` a MODULE over it (`genModule`, via the tautological
         `End`-action restricted along `gen ↪ End`). The Clifford relation holds
         INSIDE `gen` (`clifford_in_gen`); the module action of a generator recovers
         the octonion left-multiplication (`gen_smul_Lop` : `g • y = a · y`); and
         `gen` is genuinely NON-commutative (`gen_noncomm`), so the module is not a
         trivial scalar action — it carries the same octonionic non-associativity
         that stopped the cascade.

  THE MOAT — posit-vs-derive (docs/STANDARD.md §0). The division-algebra-physics
  field POSITS the Clifford module (it starts from `𝕆` and writes down a spinor space
  by hand). Here the generated algebra and its module are DERIVED FORWARD from the
  banked `CD` product + `star` + `Lop` (N3) — no Mathlib `CliffordAlgebra` /
  `QuadraticForm` import asserting the structure IS a Clifford algebra / spinor module
  (that would POSIT the very structure we derive; the SAME drift trap N3 avoided). The
  governing form is the banked `bilin` / `Nrm`, not a freshly posited inner product.

  PURELY ALGEBRAIC — the ⚠ STANDING DEPENDENCY GATE (the continuum) is NOT tripped:
  everything lives over the cascade's ground ring (`ℚ` witnesses; `B` a `CommRing`),
  the module is over the generated subring (no `ℝ`, no completeness, no Lie group).

  PHYSICS-WORDS-REMOVABLE (docs/STANDARD.md §2). Delete "spinor / gauge / Clifford":
  what remains is the theorem that the imaginary left-multiplication endomorphisms of
  the Cayley–Dickson double of a double generate a unital associative subring of `End`
  inside which they square to `−1` and pairwise anticommute when orthonormal under the
  self-overlap form, and that the terminal algebra is a module over that subring on
  which a generator acts as left multiplication. No theorem STATEMENT needs a physics
  word.

  Foundations-only: no posited axiom, no sorry, no kernel-trust bypass, no bridge.
-/
import Phys.Algebra.Operator
import Mathlib.Algebra.Ring.Subring.Basic
import Mathlib.Tactic

namespace Phys.Algebra

open Phys.Cascade
open Phys.Cascade.CD

/-! ## THE GENERATING RELATIONS over the octonion shape `CD (CD B)` (generic, forced). -/
section Carrier
variable {B : Type*} [CommRing B] [StarRing B]
attribute [local instance] CD.narCD CD.srCD

/-- Generic `Lop 1 = 1`: left multiplication by the unit is the identity endomorphism. -/
theorem Lop_one' : Lop (1 : CD (CD B)) = 1 := by
  apply AddMonoidHom.ext; intro y; show (1 : CD (CD B)) * y = y; exact one_mul y

/-- Generic `Lop 0 = 0`: left multiplication by zero is the zero endomorphism. -/
theorem Lop_zero : Lop (0 : CD (CD B)) = 0 := by
  apply AddMonoidHom.ext; intro y; show (0 : CD (CD B)) * y = 0
  ext <;> simp

/-- `ι (1 : CD B) = 1` in `CD (CD B)`. -/
theorem iota_one : (iota (1 : CD B) : CD (CD B)) = 1 := by ext <;> simp [iota]

/-- `ι (0 : CD B) = 0` in `CD (CD B)`. -/
theorem iota_zero : (iota (0 : CD B) : CD (CD B)) = 0 := by ext <;> simp [iota]

/-- ★ THE UNIT-SQUARE RELATION (forced). For an IMAGINARY element `a` (`star a = −a`)
    of unit self-overlap (`Nrm a = 1`), the left-multiplication operator squares to
    `−1` in the associative endomorphism ring: `Lop a * Lop a = −1`. This is the
    `J² = −1` law at operator level, now for ANY normalized imaginary direction —
    generalizing N3's single concrete `L_unit_sq`. Derived from the banked `L_sq_op`
    (`Lop a * Lop a = − Lop (ι (Nrm a))`) by substituting `Nrm a = 1`. -/
theorem unit_sq_op (a : CD (CD B)) (ha : star a = -a) (hN : Nrm a = 1) :
    Lop a * Lop a = -1 := by
  rw [L_sq_op a ha, hN, iota_one, Lop_one']

/-- ★ THE ANTICOMMUTATION RELATION (forced). For ORTHOGONAL imaginary elements
    `a, b` (`star a = −a`, `star b = −b`, `bilin a b = 0`), the left-multiplication
    operators ANTICOMMUTE in the associative endomorphism ring:
    `Lop a * Lop b + Lop b * Lop a = 0`. The complete generating relation on an
    orthonormal imaginary family — generalizing N3's single concrete
    `units_anticommute`. Derived from the banked Clifford relation `clifford_op`
    (`= − Lop (ι (bilin a b))`) by substituting `bilin a b = 0`. -/
theorem ortho_anticomm_op (a b : CD (CD B)) (ha : star a = -a) (hb : star b = -b)
    (hbil : bilin a b = 0) :
    Lop a * Lop b + Lop b * Lop a = 0 := by
  rw [clifford_op a b ha hb, hbil, iota_zero, Lop_zero, neg_zero]

/-! ## THE GENERATED SUBALGEBRA + the MODULE structure. -/

/-- THE GENERATING SET: the imaginary left-multiplication endomorphisms. A physicist
    recognizes these as the Clifford generators; here they are exactly the operators
    `Lop a` for `a` imaginary. -/
def genSet : Set (AddMonoid.End (CD (CD B))) :=
  {f | ∃ a : CD (CD B), star a = -a ∧ Lop a = f}

/-- ★ THE GENERATED OPERATOR SUBALGEBRA: the unital associative subring of
    `AddMonoid.End (CD (CD B))` generated by the imaginary left-multiplications.
    Associative + unital by construction (a subring of the associative `End` ring) —
    the associative operator algebra a physicist recognizes as the Clifford algebra,
    DERIVED as the closure of the derived generators, never posited. -/
def gen : Subring (AddMonoid.End (CD (CD B))) := Subring.closure genSet

/-- Each imaginary left-multiplication is a member of the generated subalgebra. -/
theorem Lop_mem_gen (a : CD (CD B)) (ha : star a = -a) : Lop a ∈ gen (B := B) :=
  Subring.subset_closure ⟨a, ha, rfl⟩

/-- ★ THE TERMINAL ALGEBRA IS A MODULE OVER THE GENERATED SUBALGEBRA. The
    tautological action of `AddMonoid.End (CD (CD B))` on `CD (CD B)` (apply the
    endomorphism), restricted along the inclusion `gen ↪ End`, makes `CD (CD B)` a
    module over `gen` — the object a physicist recognizes as the spinor module on
    which the Clifford/operator algebra acts. Built from the derived generators, not
    posited. -/
noncomputable def genModule : Module (gen (B := B)) (CD (CD B)) :=
  Module.compHom _ (gen (B := B)).subtype

/-- The module action is application: for `g : gen` and `y`, `g • y = g y`. -/
theorem gen_smul (g : gen (B := B)) (y : CD (CD B)) :
    (letI := genModule (B := B); (g • y : CD (CD B))) = (g : AddMonoid.End (CD (CD B))) y := rfl

/-- ★ THE MODULE ACTION OF A GENERATOR RECOVERS THE OCTONION LEFT-MULTIPLICATION:
    for imaginary `a`, the generated-algebra element `⟨Lop a, _⟩` acts on `y` exactly
    as `a · y`. The module structure IS left multiplication by the terminal algebra —
    not an abstract representation, the cascade's own product reorganized. -/
theorem gen_smul_Lop (a : CD (CD B)) (ha : star a = -a) (y : CD (CD B)) :
    (letI := genModule (B := B);
      ((⟨Lop a, Lop_mem_gen a ha⟩ : gen) • y : CD (CD B))) = a * y := rfl

/-- The value `− Lop (ι (bilin a b))` of the operator anticommutator lies in the
    generated subalgebra (it equals `Lop a * Lop b + Lop b * Lop a`, a sum of
    products of generators). -/
theorem anticomm_val_mem (a b : CD (CD B)) (ha : star a = -a) (hb : star b = -b) :
    - Lop (iota (bilin a b)) ∈ gen (B := B) := by
  rw [← clifford_op a b ha hb]
  exact Subring.add_mem _ (Subring.mul_mem _ (Lop_mem_gen a ha) (Lop_mem_gen b hb))
    (Subring.mul_mem _ (Lop_mem_gen b hb) (Lop_mem_gen a ha))

/-- ★ THE CLIFFORD RELATION HOLDS INSIDE THE GENERATED SUBALGEBRA. For imaginary
    `a, b`, the generators `⟨Lop a, _⟩`, `⟨Lop b, _⟩` of `gen` satisfy the polarized
    quadratic relation `gᵃ * gᵇ + gᵇ * gᵃ = − Lop (ι (bilin a b))` as an identity of
    `gen` elements — the operator/Clifford relation realized in the generated algebra
    itself, with the governing form the banked `bilin`. -/
theorem clifford_in_gen (a b : CD (CD B)) (ha : star a = -a) (hb : star b = -b) :
    (⟨Lop a, Lop_mem_gen a ha⟩ : gen) * ⟨Lop b, Lop_mem_gen b hb⟩
      + ⟨Lop b, Lop_mem_gen b hb⟩ * ⟨Lop a, Lop_mem_gen a ha⟩
      = ⟨- Lop (iota (bilin a b)), anticomm_val_mem a b ha hb⟩ := by
  apply Subtype.ext
  show Lop a * Lop b + Lop b * Lop a = - Lop (iota (bilin a b))
  exact clifford_op a b ha hb

end Carrier

/-! ## CONCRETE — a full imaginary basis of the terminal `O ℚ` realizing the relations.

    `O ℚ = CD (H ℚ) = CD (CD (Dbl ℚ))` is the octonion shape with `B := Dbl ℚ`. Its
    imaginary part is 7-dimensional; the seven coordinate units below form a genuine
    orthonormal imaginary family over the cascade ground ring `ℚ` (NOT the continuum —
    the gate is not tripped). Each is imaginary, has `Nrm = 1`, and is pairwise
    orthogonal under the banked Born form `bilin`, so the generating relations
    (`Lbasis_sq`, `Lbasis_anticomm`) hold across the WHOLE basis. -/
section Concrete
attribute [local instance] CD.narCD CD.srCD

/-- THE SEVEN IMAGINARY COORDINATE UNITS of the terminal algebra `O ℚ`, indexed by
    `Fin 7`. (The eighth coordinate, `re.re.re`, is the real/scalar line and is
    excluded — these are exactly the imaginary directions.) -/
def ebasis : Fin 7 → O ℚ
  | 0 => ⟨⟨⟨0, 1⟩, ⟨0, 0⟩⟩, ⟨⟨0, 0⟩, ⟨0, 0⟩⟩⟩
  | 1 => ⟨⟨⟨0, 0⟩, ⟨1, 0⟩⟩, ⟨⟨0, 0⟩, ⟨0, 0⟩⟩⟩
  | 2 => ⟨⟨⟨0, 0⟩, ⟨0, 1⟩⟩, ⟨⟨0, 0⟩, ⟨0, 0⟩⟩⟩
  | 3 => ⟨⟨⟨0, 0⟩, ⟨0, 0⟩⟩, ⟨⟨1, 0⟩, ⟨0, 0⟩⟩⟩
  | 4 => ⟨⟨⟨0, 0⟩, ⟨0, 0⟩⟩, ⟨⟨0, 1⟩, ⟨0, 0⟩⟩⟩
  | 5 => ⟨⟨⟨0, 0⟩, ⟨0, 0⟩⟩, ⟨⟨0, 0⟩, ⟨1, 0⟩⟩⟩
  | 6 => ⟨⟨⟨0, 0⟩, ⟨0, 0⟩⟩, ⟨⟨0, 0⟩, ⟨0, 1⟩⟩⟩

set_option maxHeartbeats 4000000

/-- Each basis unit is IMAGINARY (`star (ebasis i) = − ebasis i`). -/
theorem ebasis_imag (i : Fin 7) : star (ebasis i) = -(ebasis i) := by
  fin_cases i <;> (ext <;> simp [ebasis])

/-- Each basis unit has unit self-overlap (`Nrm (ebasis i) = 1`). -/
theorem ebasis_nrm (i : Fin 7) : Nrm (ebasis i) = (1 : H ℚ) := by
  fin_cases i <;>
    (rw [Nrm_def]; ext <;>
      simp [ebasis, Dbl.mul_re, Dbl.mul_im, Dbl.star_re', Dbl.star_im'])

/-- THE BORN FORM LANDS IN THE SCALAR LINE — `re.re` component. On `O ℚ` the banked
    `bilin x y` is the doubled real part `2 · ⟨x, y⟩` (the eight-coordinate dot
    product); its other three coordinates vanish identically (below). The trunk's
    self-overlap, polarized, is the scalar inner product — read off, not posited. -/
theorem bilin_re_re (x y : O ℚ) : (bilin x y).re.re =
    2 * (x.re.re.re * y.re.re.re + x.re.re.im * y.re.re.im + x.re.im.re * y.re.im.re
      + x.re.im.im * y.re.im.im + x.im.re.re * y.im.re.re + x.im.re.im * y.im.re.im
      + x.im.im.re * y.im.im.re + x.im.im.im * y.im.im.im) := by
  simp only [bilin, CD.add_re, CD.mul_re, CD.mul_im, CD.star_re, CD.star_im, CD.neg_re,
    CD.neg_im, Dbl.add_re, Dbl.add_im, Dbl.mul_re, Dbl.mul_im, Dbl.star_re', Dbl.star_im',
    Dbl.neg_re, Dbl.neg_im]
  ring

/-- The Born form's `re.im` coordinate vanishes identically on `O ℚ`. -/
theorem bilin_re_im (x y : O ℚ) : (bilin x y).re.im = 0 := by
  simp only [bilin, CD.add_re, CD.mul_re, CD.mul_im, CD.star_re, CD.star_im, CD.neg_re,
    CD.neg_im, Dbl.add_re, Dbl.add_im, Dbl.mul_re, Dbl.mul_im, Dbl.star_re', Dbl.star_im',
    Dbl.neg_re, Dbl.neg_im]
  ring

/-- The Born form's `im.re` coordinate vanishes identically on `O ℚ`. -/
theorem bilin_im_re (x y : O ℚ) : (bilin x y).im.re = 0 := by
  simp only [bilin, CD.add_re, CD.add_im, CD.mul_re, CD.mul_im, CD.star_re, CD.star_im,
    CD.neg_re, CD.neg_im, Dbl.add_re, Dbl.add_im, Dbl.mul_re, Dbl.mul_im, Dbl.star_re',
    Dbl.star_im', Dbl.neg_re, Dbl.neg_im]
  ring

/-- The Born form's `im.im` coordinate vanishes identically on `O ℚ`. -/
theorem bilin_im_im (x y : O ℚ) : (bilin x y).im.im = 0 := by
  simp only [bilin, CD.add_re, CD.add_im, CD.mul_re, CD.mul_im, CD.star_re, CD.star_im,
    CD.neg_re, CD.neg_im, Dbl.add_re, Dbl.add_im, Dbl.mul_re, Dbl.mul_im, Dbl.star_re',
    Dbl.star_im', Dbl.neg_re, Dbl.neg_im]
  ring

/-- Orthogonality reduces to the scalar dot product: if the `re.re` coordinate of
    `bilin x y` vanishes, then `bilin x y = 0` in `H ℚ` (the other three coordinates
    vanish identically). The 8-coordinate brute force on `H ℚ` DISSOLVES to a single
    scalar equation — the trunk's self-overlap is the scalar form. -/
theorem ortho_of_dot (x y : O ℚ) (h : (bilin x y).re.re = 0) : bilin x y = (0 : H ℚ) := by
  ext
  · exact h
  · exact bilin_re_im x y
  · exact bilin_im_re x y
  · exact bilin_im_im x y

/-- ★ THE BASIS IS ORTHONORMAL: distinct imaginary basis units are orthogonal under
    the banked Born form, `bilin (ebasis i) (ebasis j) = 0` for `i ≠ j`. Via
    `ortho_of_dot`, the 49-case computation collapses to the scalar dot product, each
    case a `simp`. -/
theorem ebasis_ortho (i j : Fin 7) (h : i ≠ j) :
    bilin (ebasis i) (ebasis j) = (0 : H ℚ) := by
  apply ortho_of_dot
  rw [bilin_re_re]
  fin_cases i <;> fin_cases j <;> first | (exact absurd rfl h) | (simp [ebasis])

/-- ★ THE WHOLE-BASIS SQUARE RELATIONS. Every basis-unit operator squares to `−1` in
    `End (O ℚ)`: `Lop (ebasis i) * Lop (ebasis i) = −1`. The complete set of square
    relations on the imaginary basis — `J² = −1` realized at the operator level in
    every imaginary direction. -/
theorem Lbasis_sq (i : Fin 7) :
    Lop (ebasis i) * Lop (ebasis i) = -1 :=
  unit_sq_op (ebasis i) (ebasis_imag i) (ebasis_nrm i)

/-- ★ THE WHOLE-BASIS ANTICOMMUTATION RELATIONS. Distinct basis-unit operators
    ANTICOMMUTE in `End (O ℚ)`: `Lop (ebasis i) * Lop (ebasis j) + Lop (ebasis j) *
    Lop (ebasis i) = 0` for `i ≠ j`. The complete set of anticommutation relations
    on the imaginary basis — the full generating relations a physicist recognizes as
    the Clifford algebra of the terminal algebra's imaginary space. -/
theorem Lbasis_anticomm (i j : Fin 7) (h : i ≠ j) :
    Lop (ebasis i) * Lop (ebasis j) + Lop (ebasis j) * Lop (ebasis i) = 0 :=
  ortho_anticomm_op (ebasis i) (ebasis j) (ebasis_imag i) (ebasis_imag j) (ebasis_ortho i j h)

/-- Each basis-unit operator is a member of the generated subalgebra on `O ℚ`. -/
theorem ebasis_mem_gen (i : Fin 7) : Lop (ebasis i) ∈ gen (B := Dbl ℚ) :=
  Lop_mem_gen (ebasis i) (ebasis_imag i)

/-- ★ THE GENERATED SUBALGEBRA IS GENUINELY NON-COMMUTATIVE (anti-vacuity, W8). On the
    terminal algebra `O ℚ`, two of its generators — the left-multiplications by the
    orthogonal imaginary units `e₂` and `ι e₂` — do NOT commute in the operator ring.
    So `gen` is not the trivial scalar ring and its module is not a scalar action: it
    carries the same octonionic non-associativity (`op_nonassoc`) that stopped the
    cascade. The square and anticommutation relations are therefore genuine structure,
    not a vacuous restatement. -/
theorem gen_noncomm :
    Lop (CD.e2 : O ℚ) * Lop (CD.iota (CD.e2 : H ℚ))
      ≠ Lop (CD.iota (CD.e2 : H ℚ)) * Lop (CD.e2 : O ℚ) := by
  intro h
  have h1 := congrArg (fun f : AddMonoid.End (O ℚ) => f 1) h
  have hL : (CD.e2 : O ℚ) * ((CD.iota (CD.e2 : H ℚ)) * 1)
      = (CD.iota (CD.e2 : H ℚ)) * ((CD.e2 : O ℚ) * 1) := h1
  rw [mul_one, mul_one] at hL
  have hc := congrArg (fun z : O ℚ => z.im.im.re) hL
  simp only [CD.e2, CD.iota, CD.mul_re, CD.mul_im, CD.star_re, CD.star_im,
    CD.add_re, CD.add_im, CD.neg_re, CD.neg_im, CD.zero_re, CD.zero_im, CD.one_re, CD.one_im,
    Dbl.mul_re, Dbl.mul_im, Dbl.star_re', Dbl.star_im', Dbl.add_re, Dbl.add_im,
    Dbl.neg_re, Dbl.neg_im, Dbl.zero_re, Dbl.zero_im, Dbl.one_re, Dbl.one_im,
    mul_zero, mul_one, zero_mul, one_mul, add_zero, zero_add, neg_zero, neg_neg] at hc
  norm_num at hc

end Concrete

end Phys.Algebra
