/-
  Phys.Algebra.LorentzContinuumLieAlgebra — N51: THE INFINITESIMAL ISOMETRY LIE ALGEBRA of the
  continuum Born form over the DERIVED ℝ `Cut` — the tangent algebra of the connected isometry
  component `SO⁺(1,9)`, DERIVED as the bracket-closed `Cut`-submodule of form-skew endomorphisms,
  with the infinitesimal boost + rotation generators as members and their commutator landing back
  inside.
  ===========================================================================
  THE NEXT FORCED NODE after the continuum rotation generator (N50(a)). N49 banked the continuum
  carrier `STVC = Cut × Cut × O Cut`, the continuum Born form `QvC = t² − x² − gFormC v v`, the
  hyperbolic BOOST isometry `boostC_isom`, and the continuum isometry monoid `qvIsomMonoidC`. N50
  banked the COMPACT ROTATION isometry `rotC_isom` and the `Cut`-pinned Born composition law
  `gFormC_comp` — completing BOTH one-parameter generator families of the connected component over
  the derived ℝ. The ticket TARGET for N51 is the FULL SURJECTIVITY onto `SO⁺(1,9)`: that EVERY
  orientation/time-preserving continuum isometry of `QvC` is a finite product of those generators.

  ── W3 DECOMPOSITION (the full surjectivity is a multi-node arc) ──
  The full surjectivity is a deep GLOBAL Lie-group theorem (exp-integration of the tangent algebra,
  Cartan/polar KAK decomposition, connectedness + topology of the isometry group over the derived
  ℝ). NONE of that global machinery is banked: Mathlib has no `SO⁺(1,9)`, no octonionic spinor
  cover, no Lie-group integration over the derived `Cut`; the banked `expO` stack (N41) is a
  per-point vector exponential of derivations of `O Cut`, not a flow on the 11-dim coordinate space
  `STVC`, and there is no banked "finite product of one-parameter subgroups" theorem. So — exactly
  as the ROADMAP §N51 paragraph and the parent N50 handoff anticipate — the global surjectivity is
  childed (N52), and THIS node banks the immediately-available, theory-native piece: the
  INFINITESIMAL ISOMETRY LIE ALGEBRA, the TANGENT algebra of the connected component.

  The connected component is generated by the one-parameter subgroups; the tangent (the
  infinitesimal generators) of "preserves `QvC`" is the FORM-SKEW endomorphisms — the linear maps
  `T` with `d/ds QvC(e^{sT}p)|₀ = 0`, i.e. `B(Tp,q) + B(p,Tq) = 0` for the polarized form `B`. The
  surjectivity claim "generated by the boost + rotation one-parameter subgroups" has, as its
  infinitesimal/tangent shadow, "the boost + rotation infinitesimal generators lie in, and close
  under the Lie bracket within, the infinitesimal-isometry algebra." That is what this node proves.

  ── THE W1 REFRAME (THE ONE LAW): the rotation-generator skewness from POLARIZING `gFormC_comp` ──
  The infinitesimal rotation generator `v ↦ a·v` is form-skew exactly when `a` is "imaginary"
  (`gFormC a 1 = 0`). The classical proof appeals to an adjoint/Clifford structure; the banked
  generic adjoint `adjoint3` lives at the wrong Cayley–Dickson depth. The theory-native route:
  POLARIZE the banked Born composition law `gFormC_comp` (`gFormC (x·y)(x·y) = gFormC x x·gFormC y y`)
  twice — once in the multiplied slot (`v ↦ v+w`) to get the LEFT composition identity
  `gFormC (a·v)(a·w) = gFormC a a·gFormC v w`, once in the MULTIPLIER (`a ↦ a+b`) to get the mixed
  identity `gFormC (a·v)(b·w) + gFormC (b·v)(a·w) = 2·gFormC a b·gFormC v w` — and specialize
  `b = 1` to THE SKEW IDENTITY `gFormC (a·v) w + gFormC v (a·w) = 2·gFormC a 1·gFormC v w`, which
  vanishes precisely on the imaginary `a`. Pure biadditivity + field arithmetic over `Cut`, NO
  coordinate brute, NO adjoint at the wrong depth, NO analysis, NO new posit.

  WHAT IS PROVED (each a theorem, foundations-only, forward from the banked objects):
    reQC_add/_neg/_star/_smul     — the deep-real read-off `reQC` is additive/odd/star-invariant/
                                    `Cut`-homogeneous over the continuum.
    gFormC_symm/_add_*/_smul_*/_zero_*/_neg_* — the continuum Born self-overlap form is a symmetric
                                    `Cut`-bilinear form (mirrors the banked ℚ `gForm` layer).
    gFormC_leftcomp               — ★ THE LEFT COMPOSITION IDENTITY `gFormC (a·v)(a·w) =
                                    gFormC a a · gFormC v w`, polarizing `gFormC_comp` in the slot.
    gFormC_mixed                  — ★ the mixed-multiplier identity, polarizing again in the multiplier.
    gFormC_skew                   — ★★ THE SKEW IDENTITY `gFormC (a·v) w + gFormC v (a·w) =
                                    2·gFormC a 1·gFormC v w` — the engine of infinitesimal-rotation
                                    skewness, theory-native from the Born composition law.
    BvC                           — THE POLARIZED Minkowski form `B p q = t·t' − x·x' − gFormC v v'`.
    BvC_self/_symm/_add_*/_sub_*/_neg_*/_smul_* — `B` is symmetric `Cut`-bilinear and polarizes `QvC`.
    IsInfIsomC                    — ★ THE INFINITESIMAL ISOMETRY (form-skew) predicate
                                    `∀ p q, B(T p) q + B p (T q) = 0` — the tangent condition.
    infIsom_zero/_add/_smul       — the form-skew maps are a `Cut`-submodule.
    infIsom_bracket               — ★★ BRACKET-CLOSURE: the commutator `⁅S,T⁆` of two form-skew maps
                                    is form-skew — the Lie-algebra structure of the tangent space,
                                    generic from biadditivity + skewness (NO coordinate brute).
    infIsomLieAlg                 — ★ THE TANGENT LIE ALGEBRA as a `LieSubalgebra Cut (Module.End Cut
                                    STVC)`: the infinitesimal isometry algebra of the connected
                                    component, DERIVED — not a posited Lie algebra of `SO⁺(1,9)`.
    boostGenC / boostGenC_inf     — ★★ THE INFINITESIMAL BOOST generator `(t,x,v) ↦ (x,t,0)` is
                                    form-skew (pure field arithmetic on the `(t,x)` block).
    rotGenC / rotGenC_inf         — ★★ THE INFINITESIMAL ROTATION generator `(t,x,v) ↦ (0,0,a·v)`
                                    is form-skew when `a` is imaginary (`gFormC a 1 = 0`), via the
                                    skew identity — the compact infinitesimal generator.
    boost_rot_bracket_mem         — ★★★ THE HEADLINE: the commutator of the infinitesimal boost and
                                    an imaginary infinitesimal rotation lies in the tangent algebra —
                                    the boost + rotation infinitesimal generators CLOSE under the Lie
                                    bracket within the infinitesimal-isometry algebra (the tangent
                                    shadow of "generated by the one-parameter subgroups").
    boostGenC_ne_zero / boostGenC_mem — ★ NON-VACUITY (W8): the tangent algebra contains a NONZERO
                                    element, so it is not the trivial `{0}` algebra.

  WHAT IS CHILDED (N52, the heavy remainder). The GLOBAL exp-integration of this tangent algebra to
  the connected component, the Cartan/polar (KAK) decomposition, and the actual SURJECTIVITY (that
  every connected continuum isometry is a finite product of the one-parameter subgroups) — a deep
  global Lie-group theorem over the derived ℝ with no Mathlib machinery. An honest W1 remainder,
  childed onto the chain tail; THIS node banks its tangent algebra.

  THE MOAT — posit-vs-derive (docs/STANDARD.md §0). That the Lie algebra of the octonionic
  Minkowski isometry group is `𝔰𝔬(1,9)`, generated by infinitesimal boosts + rotations, is standard
  (Sudbery, Manogue–Dray, Baez). Here the tangent algebra, its bracket-closure, and the generator
  memberships DESCEND from the banked continuum Born form + the banked Born composition law
  `gFormC_comp` (polarized to the skew identity) over the DERIVED ℝ `Cut` — NO posited Lorentz Lie
  algebra, NO Mathlib ℝ/ℂ as content. The W1 reframe (polarize the Born composition law rather than
  invoke an adjoint at the wrong CD depth) is exactly what makes the infinitesimal rotation skewness
  re-ground over the continuum.

  PHYSICS-WORDS-REMOVABLE (docs/STANDARD.md §2). Delete "Lorentz / boost / rotation / isometry /
  SO⁺(1,9) / generator / Lie / tangent / spinor": what remains is the theorem that, over the derived
  complete ordered field `Cut` and the Cayley–Dickson double³ `O Cut`, the `Cut`-linear self-maps
  `T` of `Cut × Cut × O Cut` with `∀ p q, B(T p) q + B p (T q) = 0` (for the symmetric bilinear form
  `B p q = t·t' − x·x' − gFormC v v'`) form a bracket-closed `Cut`-submodule of `Module.End Cut
  (Cut × Cut × O Cut)`, containing `(t,x,v) ↦ (x,t,0)` and `(t,x,v) ↦ (0,0,a·v)` for every `a` with
  `gFormC a 1 = 0`, with the commutator of these two landing back inside. No theorem STATEMENT needs
  a physics word.

  Foundations-only: no posited axiom, no sorry, no kernel-trust bypass, no bridge, NO Mathlib
  number-system content import (the continuum is the DERIVED `Cut`), NO posited Lorentz group.
-/
import Phys.Algebra.LorentzContinuumRotation
import Phys.Algebra.DerivationOExp
import Mathlib.Algebra.Lie.OfAssociative
import Mathlib.Algebra.Lie.Subalgebra

namespace Phys.Algebra

open Phys.Cascade Phys.Cascade.CD
open Phys.Foundation Phys.Foundation.ContinuumQ

attribute [local instance] CD.narCD CD.srCD

noncomputable section

/-! ## The continuum Born form as a symmetric `Cut`-bilinear form (the `gForm` layer over `Cut`). -/

/-- `reQC` is additive. -/
theorem reQC_add (a b : O Cut) : reQC (a + b) = reQC a + reQC b := by
  simp [reQC, CD.add_re, Dbl.add_re]

/-- `reQC` is odd. -/
theorem reQC_neg (a : O Cut) : reQC (-a) = - reQC a := by
  simp [reQC, CD.neg_re, Dbl.neg_re]

/-- `reQC` is star-invariant (the deep-real part is fixed by conjugation). -/
theorem reQC_star (z : O Cut) : reQC (star z) = reQC z := by
  simp [reQC, CD.star_re, Dbl.star_re']

/-- `reQC` is `Cut`-homogeneous (the componentwise `Cut`-action). -/
theorem reQC_smul (c : Cut) (x : O Cut) : reQC (c • x) = c * reQC x := by
  show ((c • x).re.re.re) = c * x.re.re.re
  show (c • x.re.re).re = c * x.re.re.re
  rw [Dbl.smul_re]

/-- `gFormC` is symmetric. -/
theorem gFormC_symm (v w : O Cut) : gFormC v w = gFormC w v := by
  unfold gFormC; rw [← reQC_star (v * star w), star_mul, star_star]

/-- `gFormC` is additive in the right slot. -/
theorem gFormC_add_right (v w₁ w₂ : O Cut) :
    gFormC v (w₁ + w₂) = gFormC v w₁ + gFormC v w₂ := by
  unfold gFormC; rw [star_add, mul_add_na, reQC_add]

/-- `gFormC` is additive in the left slot. -/
theorem gFormC_add_left (v₁ v₂ w : O Cut) :
    gFormC (v₁ + v₂) w = gFormC v₁ w + gFormC v₂ w := by
  rw [gFormC_symm, gFormC_add_right, gFormC_symm v₁ w, gFormC_symm v₂ w]

/-- `gFormC` is `Cut`-homogeneous in the left slot. -/
theorem gFormC_smul_left (c : Cut) (v w : O Cut) : gFormC (c • v) w = c * gFormC v w := by
  unfold gFormC; rw [smulCompat_oCut.hl c v (star w), reQC_smul]

/-- `gFormC` is `Cut`-homogeneous in the right slot (by symmetry). -/
theorem gFormC_smul_right (c : Cut) (v w : O Cut) : gFormC v (c • w) = c * gFormC v w := by
  rw [gFormC_symm, gFormC_smul_left, gFormC_symm w v]

/-- `gFormC` vanishes on the left zero. -/
theorem gFormC_zero_left (w : O Cut) : gFormC 0 w = 0 := by
  unfold gFormC; rw [zero_mul]; rfl

/-- `gFormC` is odd in the left slot (from additivity + the zero value). -/
theorem gFormC_neg_left (v w : O Cut) : gFormC (-v) w = - gFormC v w := by
  have h := gFormC_add_left (-v) v w
  rw [neg_add_cancel v, gFormC_zero_left] at h
  linarith [h]

/-! ## The polarized skew identity — POLARIZING the banked Born composition law `gFormC_comp`. -/

/-- ★ THE LEFT COMPOSITION IDENTITY `gFormC (a·v)(a·w) = gFormC a a · gFormC v w`. The banked Born
    composition law `gFormC_comp` (the diagonal `gFormC (a·v)(a·v) = gFormC a a · gFormC v v`)
    POLARIZED in the multiplied slot (`v ↦ v+w`). -/
theorem gFormC_leftcomp (a v w : O Cut) :
    gFormC (a * v) (a * w) = gFormC a a * gFormC v w := by
  have h := gFormC_comp a (v + w)
  have hv := gFormC_comp a v
  have hw := gFormC_comp a w
  rw [mul_add_na] at h
  simp only [gFormC_add_left, gFormC_add_right, mul_add] at h
  rw [gFormC_symm (a * w) (a * v), gFormC_symm w v] at h
  linarith [h, hv, hw]

/-- ★ THE MIXED-MULTIPLIER IDENTITY `gFormC (a·v)(b·w) + gFormC (b·v)(a·w) = 2·gFormC a b·gFormC v w`.
    The left composition identity POLARIZED in the multiplier (`a ↦ a+b`). -/
theorem gFormC_mixed (a b v w : O Cut) :
    gFormC (a * v) (b * w) + gFormC (b * v) (a * w) = 2 * gFormC a b * gFormC v w := by
  have h := gFormC_leftcomp (a + b) v w
  have ha := gFormC_leftcomp a v w
  have hb := gFormC_leftcomp b v w
  rw [add_mul, add_mul] at h
  simp only [gFormC_add_left, gFormC_add_right, add_mul] at h
  rw [gFormC_symm b a] at h
  linarith [h, ha, hb]

/-- ★★ THE SKEW IDENTITY `gFormC (a·v) w + gFormC v (a·w) = 2·gFormC a 1·gFormC v w`. The `b = 1`
    specialization of the mixed identity (`a·1 = a`, `1·w = w`). When `a` is imaginary
    (`gFormC a 1 = 0`) the left-multiplication `v ↦ a·v` is `gFormC`-skew — the engine of
    infinitesimal-rotation skewness, theory-native from the Born composition law (no adjoint, no
    coordinate brute). -/
theorem gFormC_skew (a v w : O Cut) :
    gFormC (a * v) w + gFormC v (a * w) = 2 * gFormC a 1 * gFormC v w := by
  have h := gFormC_mixed a 1 v w
  rw [one_mul, one_mul] at h
  exact h

/-! ## The polarized Minkowski form `BvC`. -/

/-- THE POLARIZED MINKOWSKI FORM `B p q = t·t' − x·x' − gFormC v v'` — the symmetric bilinear
    polarization of the banked continuum Born quadratic form `QvC`. -/
def BvC (p q : STVC) : Cut := p.1 * q.1 - p.2.1 * q.2.1 - gFormC p.2.2 q.2.2

/-- The polarized form recovers the quadratic form on the diagonal: `B p p = QvC p`. -/
theorem BvC_self (p : STVC) : BvC p p = QvC p := by
  obtain ⟨t, x, v⟩ := p
  show t * t - x * x - gFormC v v = t ^ 2 - x ^ 2 - gFormC v v
  ring

/-- `BvC` is symmetric. -/
theorem BvC_symm (p q : STVC) : BvC p q = BvC q p := by
  obtain ⟨t, x, v⟩ := p; obtain ⟨t', x', v'⟩ := q
  show t * t' - x * x' - gFormC v v' = t' * t - x' * x - gFormC v' v
  rw [gFormC_symm v v']; ring

/-- `BvC` is additive in the left slot. -/
theorem BvC_add_left (p p' q : STVC) : BvC (p + p') q = BvC p q + BvC p' q := by
  obtain ⟨t, x, v⟩ := p; obtain ⟨t', x', v'⟩ := q; obtain ⟨t2, x2, v2⟩ := p'
  show (t + t2) * t' - (x + x2) * x' - gFormC (v + v2) v' = _
  rw [gFormC_add_left]
  show _ = (t * t' - x * x' - gFormC v v') + (t2 * t' - x2 * x' - gFormC v2 v'); ring

/-- `BvC` is odd in the left slot. -/
theorem BvC_neg_left (p q : STVC) : BvC (-p) q = - BvC p q := by
  obtain ⟨t, x, v⟩ := p; obtain ⟨t', x', v'⟩ := q
  show (-t) * t' - (-x) * x' - gFormC (-v) v' = _
  rw [gFormC_neg_left]; show _ = -(t * t' - x * x' - gFormC v v'); ring

/-- `BvC` subtracts in the left slot. -/
theorem BvC_sub_left (p p' q : STVC) : BvC (p - p') q = BvC p q - BvC p' q := by
  rw [sub_eq_add_neg, BvC_add_left, BvC_neg_left, sub_eq_add_neg]

/-- `BvC` subtracts in the right slot (by symmetry). -/
theorem BvC_sub_right (p q q' : STVC) : BvC p (q - q') = BvC p q - BvC p q' := by
  rw [BvC_symm, BvC_sub_left, BvC_symm q p, BvC_symm q' p]

/-! ## The infinitesimal isometry (form-skew) predicate and the tangent Lie algebra. -/

/-- ★ THE INFINITESIMAL ISOMETRY (form-skew) PREDICATE: a `Cut`-linear self-map `T` of the
    continuum coordinate space is form-skew iff `∀ p q, B(T p) q + B p (T q) = 0` — the tangent
    condition `d/ds QvC(e^{sT}p)|₀ = 0`, the infinitesimal generator of the continuum isometry
    structure. The tangent space of the connected isometry component, over the DERIVED ℝ. -/
def IsInfIsomC (T : Module.End Cut STVC) : Prop := ∀ p q : STVC, BvC (T p) q + BvC p (T q) = 0

/-- The applied commutator of two endomorphisms: `⁅S,T⁆ r = S (T r) − T (S r)`. -/
theorem bracketEnd_apply (S T : Module.End Cut STVC) (r : STVC) :
    (⁅S, T⁆ : Module.End Cut STVC) r = S (T r) - T (S r) := by
  have h : (⁅S, T⁆ : Module.End Cut STVC) = S * T - T * S := Ring.lie_def S T
  rw [h, LinearMap.sub_apply, Module.End.mul_apply, Module.End.mul_apply]

/-- `BvC` vanishes on the left zero. -/
theorem BvC_zero_left (q : STVC) : BvC 0 q = 0 := by
  obtain ⟨t', x', v'⟩ := q
  show (0 : Cut) * t' - 0 * x' - gFormC 0 v' = 0
  rw [gFormC_zero_left]; ring

/-- The zero map is form-skew. -/
theorem infIsom_zero : IsInfIsomC 0 := by
  intro p q
  show BvC 0 q + BvC p 0 = 0
  rw [BvC_zero_left, BvC_symm p 0, BvC_zero_left]; ring

/-- The form-skew maps are closed under addition. -/
theorem infIsom_add {S T : Module.End Cut STVC} (hS : IsInfIsomC S) (hT : IsInfIsomC T) :
    IsInfIsomC (S + T) := by
  intro p q
  show BvC ((S + T) p) q + BvC p ((S + T) q) = 0
  rw [LinearMap.add_apply, LinearMap.add_apply, BvC_add_left, BvC_symm p (S q + T q),
    BvC_add_left, BvC_symm (S q) p, BvC_symm (T q) p]
  linarith [hS p q, hT p q]

/-- The form-skew maps are closed under the `Cut`-scalar action. -/
theorem infIsom_smul (c : Cut) {T : Module.End Cut STVC} (hT : IsInfIsomC T) :
    IsInfIsomC (c • T) := by
  intro p q
  show BvC ((c • T) p) q + BvC p ((c • T) q) = 0
  rw [LinearMap.smul_apply, LinearMap.smul_apply]
  -- BvC (c•Tp) q + BvC p (c•Tq) = c*(BvC (Tp) q + BvC p (Tq)) = 0
  have hl : BvC (c • T p) q = c * BvC (T p) q := by
    obtain ⟨t, x, v⟩ := (T p); obtain ⟨t', x', v'⟩ := q
    show (c • t) * t' - (c • x) * x' - gFormC (c • v) v' = c * (t * t' - x * x' - gFormC v v')
    rw [gFormC_smul_left]; show c * t * t' - c * x * x' - c * gFormC v v' = _; ring
  have hr : BvC p (c • T q) = c * BvC p (T q) := by
    obtain ⟨t, x, v⟩ := p; obtain ⟨t', x', v'⟩ := (T q)
    show t * (c • t') - x * (c • x') - gFormC v (c • v') = c * (t * t' - x * x' - gFormC v v')
    rw [gFormC_smul_right]; show t * (c * t') - x * (c * x') - c * gFormC v v' = _; ring
  rw [hl, hr, ← mul_add, hT p q, mul_zero]

/-- ★★ BRACKET-CLOSURE: the commutator `⁅S,T⁆` of two form-skew maps is form-skew. GENERIC from the
    biadditivity of `B` + the skewness of `S`, `T` — the Lie-algebra structure of the tangent space,
    with NO coordinate brute. (`B(S(Tp))q = −B(Tp)(Sq) = B(p)(T(Sq))`, and the four such moves cancel
    in pairs.) -/
theorem infIsom_bracket {S T : Module.End Cut STVC} (hS : IsInfIsomC S) (hT : IsInfIsomC T) :
    IsInfIsomC ⁅S, T⁆ := by
  intro p q
  rw [bracketEnd_apply, bracketEnd_apply, BvC_sub_left, BvC_sub_right]
  -- (B(S(Tp))q − B(T(Sp))q) + (B p (S(Tq)) − B p (T(Sq)))
  have e1 := hS (T p) q      -- B(S(Tp))q + B(Tp)(Sq) = 0
  have e2 := hT (S p) q      -- B(T(Sp))q + B(Sp)(Tq) = 0
  have e3 := hS p (T q)      -- B(Sp)(Tq) + B p (S(Tq)) = 0
  have e4 := hT p (S q)      -- B(Tp)(Sq) + B p (T(Sq)) = 0
  linarith [e1, e2, e3, e4]

/-- ★ THE TANGENT LIE ALGEBRA as a `LieSubalgebra Cut (Module.End Cut STVC)`: the infinitesimal
    isometry algebra of the connected component, DERIVED — the form-skew endomorphisms, closed under
    `0`, `+`, `Cut`-`smul`, and the Lie bracket. Not a posited Lie algebra of `SO⁺(1,9)`. -/
def infIsomLieAlg : LieSubalgebra Cut (Module.End Cut STVC) where
  carrier := {T | IsInfIsomC T}
  add_mem' hS hT := infIsom_add hS hT
  zero_mem' := infIsom_zero
  smul_mem' c _ hT := infIsom_smul c hT
  lie_mem' hS hT := infIsom_bracket hS hT

@[simp] theorem mem_infIsomLieAlg {T : Module.End Cut STVC} :
    T ∈ infIsomLieAlg ↔ IsInfIsomC T := Iff.rfl

/-! ## The infinitesimal generators — the boost (off-diagonal shear) and the rotation (left-mult). -/

/-- THE INFINITESIMAL BOOST generator `(t,x,v) ↦ (x,t,0)` — the off-diagonal shear in the
    time–space plane, `d/ds boostFunC|₀`. -/
def boostGenC : Module.End Cut STVC where
  toFun p := (p.2.1, p.1, 0)
  map_add' p q := by ext <;> simp
  map_smul' c p := by ext <;> simp

/-- ★★ THE INFINITESIMAL BOOST IS FORM-SKEW: `(t,x,v) ↦ (x,t,0)` is `BvC`-skew, by pure field
    arithmetic on the `(t,x)` block (the `v`-block is sent to `0`, so its `gFormC` term vanishes).
    The non-compact infinitesimal generator. -/
theorem boostGenC_inf : IsInfIsomC boostGenC := by
  intro p q
  obtain ⟨t, x, v⟩ := p; obtain ⟨t', x', v'⟩ := q
  show BvC (x, t, (0 : O Cut)) (t', x', v') + BvC (t, x, v) (x', t', (0 : O Cut)) = 0
  show (x * t' - t * x' - gFormC 0 v') + (t * x' - x * t' - gFormC v 0) = 0
  rw [gFormC_zero_left, gFormC_symm v 0, gFormC_zero_left]; ring

theorem boostGenC_mem : boostGenC ∈ infIsomLieAlg := boostGenC_inf

/-- THE INFINITESIMAL ROTATION generator `(t,x,v) ↦ (0,0,a·v)` — left-multiplication of the nine
    space directions by a fixed `a`, leaving the `(t,x)` block at `0`. The compact infinitesimal
    generator. -/
def rotGenC (a : O Cut) : Module.End Cut STVC where
  toFun p := (0, 0, a * p.2.2)
  map_add' p q := by
    refine Prod.ext (by simp) (Prod.ext (by simp) ?_)
    show a * (p.2.2 + q.2.2) = a * p.2.2 + a * q.2.2
    exact mul_add_na a p.2.2 q.2.2
  map_smul' c p := by
    refine Prod.ext (by simp) (Prod.ext (by simp) ?_)
    show a * (c • p.2.2) = c • (a * p.2.2)
    exact smulCompat_oCut.hr c a p.2.2

/-- ★★ THE INFINITESIMAL ROTATION IS FORM-SKEW when `a` is IMAGINARY (`gFormC a 1 = 0`): the
    `(t,x)` block is sent to `0`, and on the space block the skew identity gives
    `gFormC (a·v) v' + gFormC v (a·v') = 2·gFormC a 1·gFormC v v' = 0`. The compact infinitesimal
    generator, form-skew exactly on the imaginary axis — derived from the polarized Born composition
    law `gFormC_skew`, NO coordinate brute. -/
theorem rotGenC_inf {a : O Cut} (ha : gFormC a 1 = 0) : IsInfIsomC (rotGenC a) := by
  intro p q
  obtain ⟨t, x, v⟩ := p; obtain ⟨t', x', v'⟩ := q
  show BvC (0, 0, a * v) (t', x', v') + BvC (t, x, v) (0, 0, a * v') = 0
  show (0 * t' - 0 * x' - gFormC (a * v) v') + (t * 0 - x * 0 - gFormC v (a * v')) = 0
  have hskew := gFormC_skew a v v'
  rw [ha, mul_zero, zero_mul] at hskew
  -- hskew : gFormC (a*v) v' + gFormC v (a*v') = 0
  linarith [hskew]

theorem rotGenC_mem {a : O Cut} (ha : gFormC a 1 = 0) : rotGenC a ∈ infIsomLieAlg := rotGenC_inf ha

/-- ★★★ THE HEADLINE: the commutator of the infinitesimal boost and an IMAGINARY infinitesimal
    rotation lies in the tangent algebra — the boost + rotation infinitesimal generators CLOSE under
    the Lie bracket within the infinitesimal-isometry algebra. The Lie-algebra-of-the-connected-
    component structure, the tangent shadow of "the connected isometry component is generated by the
    boost + rotation one-parameter subgroups." -/
theorem boost_rot_bracket_mem {a : O Cut} (ha : gFormC a 1 = 0) :
    ⁅boostGenC, rotGenC a⁆ ∈ infIsomLieAlg :=
  infIsom_bracket boostGenC_inf (rotGenC_inf ha)

/-! ## NON-VACUITY (W8) — the tangent algebra is not the trivial `{0}` algebra. -/

/-- ★ NON-VACUITY: the infinitesimal boost generator is NOT the zero map — it sends `(1,0,0)` to
    `(0,1,0)`, which has nonzero second component. So the tangent algebra contains a genuine nonzero
    element and is not the trivial `{0}` Lie algebra. -/
theorem boostGenC_ne_zero : boostGenC ≠ 0 := by
  intro hcontra
  have := congrArg (fun T => (T ((1 : Cut), (0 : Cut), (0 : O Cut))).2.1) hcontra
  -- (boostGenC (1,0,0)).2.1 = 1 ; (0 map ...).2.1 = 0
  simp only [boostGenC, LinearMap.coe_mk, AddHom.coe_mk, LinearMap.zero_apply] at this
  exact one_ne_zero this

/-- NON-VACUITY (imaginary witness exists): the generator construction is realized — the boost
    generator is a concrete nonzero member of the tangent algebra. -/
theorem infIsomLieAlg_ne_bot : infIsomLieAlg ≠ ⊥ := by
  intro hbot
  have hmem : boostGenC ∈ infIsomLieAlg := boostGenC_mem
  rw [hbot] at hmem
  rw [LieSubalgebra.mem_bot] at hmem
  exact boostGenC_ne_zero hmem

end

end Phys.Algebra
