/-
  Phys.Algebra.LorentzContinuumCliffordPinGroup — N145: THE PIN GROUP + THE SURJECTIVE
  DOUBLE COVER WITH ORDER-2 KERNEL — `Pin(1,9) ↠ SO⁺(1,9)` ON THE HONEST DOMAIN.
  Over the derived ℝ `Cut`, the terminal algebra `O Cut`, the spacetime `STVC`, the indefinite
  Minkowski form `BvC`, the Clifford algebra `CliffC = CliffordAlgebra QvCQuad`.
  ===========================================================================
  CONTEXT — THE FORWARD JOINT (W4.5 SUFFICIENCY: advance, do not re-pin), and THE ONE LAW
  reframe that produced it.

  N144 banked the cover as a surjective `MonoidHom coverMap : CoversSub →* bvIsomLinMonoid`,
  where `CoversSub` is the submonoid of ALL units covering SOME isometry. N136 banked the
  set-level `{±1}` cover kernel (`cover_neg_unit`, `cover_kernel_distinct`). The forward joint
  the ticket floated was: lift `{±1} = ker coverMap` to the precise `MonoidHom` kernel.

  ── MEASURE-FIRST (the decisive reframe — THE ONE LAW). ──
  MEASURED: `ker coverMap` on `CoversSub` is NOT `{±1}`. Every nonzero scalar unit `algebraMap λ`
  (`λ : Cut`, `λ ≠ 0`) is central in `CliffC` and grade-0 (so `involute` fixes it), hence
  `involute(λ)·ι v·λ⁻¹ = λ·λ⁻¹·ι v = ι v` — EVERY scalar unit covers `id`. So the kernel of the
  cover on the scalar-bloated `CoversSub` is the FULL scalar group, not `{±1}`. The literal
  candidate is mathematically false because `CoversSub` is the wrong DOMAIN. Returning to what
  the theory says: the honest double cover's domain is the **Pin group** — the submonoid
  GENERATED BY THE CASCADE'S OWN REFLECTION UNITS `cliffUnitOf a` (matching N132's
  `houseHolderMSet`), exactly as the literature's Pin group is the reflection-generated subgroup.
  On the Pin domain the order-2 kernel element `-1` is a genuine REFLECTION SQUARE
  (`(cliffUnitOf mSpaceUnit)² = algebraMap (QvC mSpaceUnit) = algebraMap (-1) = -1`), a Pin
  element, and the restricted cover is STILL surjective onto `SO⁺(1,9)`. This OPENS the honest
  two-to-one structure neither N136 (set-level on arbitrary units) nor N144 (cover on the bloated
  `CoversSub`) carried: the cover restricted to the reflection-generated Pin DOMAIN as a
  surjective `MonoidHom` whose `MonoidHom.mker` is GENUINELY order ≥ 2 at the group-map level.

  ── WHAT THIS NODE BANKS ──
    pinGenSet                 — THE REFLECTION-UNIT GENERATING SET `{cliffUnitOf a | BvC a a ≠ 0}`.
    PinSub                    — THE PIN GROUP: `Submonoid.closure pinGenSet ⊆ CliffCˣ` — the
                                honest double-cover domain, generated by the cascade's own
                                reflection units (not all units).
    cliffUnitOf_mem_pinSub    — each reflection unit is a Pin element.
    pinSub_le_coversSub       — `PinSub ≤ CoversSub`: each generator covers its reflection.
    pin_covers_word           — every reflection-word isometry has a covering unit IN `PinSub`.
    ★★ coverMapPin            — THE PIN DOUBLE COVER `PinSub →* bvIsomLinMonoid` (the restriction
                                of `coverMap` to the honest reflection-generated domain).
    coverMapPin_coe           — the value is the covered operator.
    ★★ coverMapPin_surjective — THE SURJECTIVITY `↠ SO⁺(1,9)`: the Pin group (not all units)
                                already covers the full continuum Lorentz group.
    cliffUnitOf_mSpaceUnit_sq — `(cliffUnitOf mSpaceUnit)² = -1`: the kernel element is a
                                reflection square (`ι_sq_scalar`, `QvC mSpaceUnit = -1`).
    ★ negOne_mem_pinSub       — `(-1 : CliffCˣ) ∈ PinSub`: the kernel element is a GENUINE Pin
                                element (a reflection square) — the new content vs N136's
                                set-level kernel over arbitrary units.
    negOne_mem_mker_coverMapPin — `⟨-1,_⟩ ∈ MonoidHom.mker coverMapPin`: the Pin element `-1`
                                lies in the kernel of the Pin double cover (covers `id`).
    ★ coverMapPin_mker_nontrivial — `⟨-1,_⟩ ≠ 1 ∧ ∈ mker`: the kernel is GENUINELY order ≥ 2 at
                                the group-map level — the two-to-one datum the surjective cover
                                alone does not capture.
    W8 (genuinely-indefinite teeth):
    coverMapPin_boost_apply   — the CONCRETE boost `(5/3,4/3)` is the image under `coverMapPin`
                                of a Pin covering unit — the Pin surjectivity realized on a real
                                boost. The read-off the costume C177 negates.

  THE MOAT — posit-vs-derive (docs/STANDARD.md §0). The literature POSITS the Pin group as the
  reflection-generated subgroup of the Clifford units and POSITS the double cover with its `{±1}`
  kernel as the defining datum. Here the Pin group is DERIVED (`Submonoid.closure` of the
  cascade's OWN reflection units `cliffUnitOf`, which are the `ι` of the trunk's Householder
  axes), the cover is the banked twisted adjoint, the surjectivity onto the DERIVED Lorentz
  group `bvIsomLinMonoid` (N132's reflection-word classification) is assembled FORWARD, and the
  order-2 kernel element is a DERIVED reflection square — no posited Pin/Spin group, no posited
  cover, no posited kernel, no Mathlib ℝ/ℂ as content, no bridge.

  DERIVED from the banked N49–N144 + the derived ℝ `Cut` + the terminal algebra `O Cut` + the
  spacetime `STVC` + the indefinite Minkowski form `BvC` + the Clifford algebra `CliffC`.
  Foundations-only.

  PHYSICS-WORDS-REMOVABLE (docs/STANDARD.md §2). Delete "Pin / Spin / cover / spinor / Lorentz /
  Minkowski / reflection / boost / kernel / double / two-to-one / homomorphism / group-map /
  surjectivity / SO⁺(1,9) / bridge": what remains is pure algebra over the derived complete
  ordered field `Cut`, `STVC = Cut × Cut × O Cut`, the Clifford algebra `CliffC` of `QvCQuad`,
  its `ι`, and the predicate `CliffCovers` — the submonoid generated by the units `cliffUnitOf a`
  lies in `CoversSub`, the covered-operator `MonoidHom` restricts to it and is onto
  `bvIsomLinMonoid`, the element `(cliffUnitOf mSpaceUnit)² = -1` lies in this submonoid and in
  the `MonoidHom`'s `mker`, and `-1 ≠ 1`. No theorem STATEMENT needs a physics word.

  Foundations-only: no posited axiom, no sorry, no kernel-trust bypass, no bridge, NO Mathlib
  number-system content import (the continuum is the DERIVED `Cut`; `CliffordAlgebra` / `ι` /
  `ι_sq_scalar` / `MonoidHom` / `Submonoid` / `MonoidHom.mker` are MACHINERY on the derived
  form), NO posited Clifford/Pin/Spin/cover/group/kernel structure.
-/
import Phys.Algebra.LorentzContinuumCliffordCoverKernel
import Phys.Algebra.LorentzContinuumCliffordSpinHom

namespace Phys.Algebra

open Phys.Cascade Phys.Cascade.CD
open Phys.Foundation Phys.Foundation.ContinuumQ

attribute [local instance] CD.narCD CD.srCD
attribute [local instance] Phys.Algebra.dblModuleCut

noncomputable section
open scoped BigOperators

/-! ## The Pin group — the submonoid generated by the reflection units. -/

/-- THE REFLECTION-UNIT GENERATING SET of the Pin group: the Clifford units `cliffUnitOf a` of the
    anisotropic vectors (the `ι` of the trunk's Householder axes). -/
def pinGenSet : Set CliffCˣ := { u | ∃ (a : STVC) (ha : BvC a a ≠ 0), u = cliffUnitOf a ha }

/-- THE PIN GROUP: the submonoid of `CliffCˣ` GENERATED BY the reflection units — the honest
    double-cover domain (the reflection-generated subgroup, matching N132's `houseHolderMSet`),
    NOT the scalar-bloated `CoversSub` of all units covering some isometry. -/
def PinSub : Submonoid CliffCˣ := Submonoid.closure pinGenSet

/-- Each reflection unit is a Pin element. -/
theorem cliffUnitOf_mem_pinSub {a : STVC} (ha : BvC a a ≠ 0) :
    cliffUnitOf a ha ∈ PinSub :=
  Submonoid.subset_closure ⟨a, ha, rfl⟩

/-- THE PIN GROUP LIES IN THE COVERING SUBMONOID: each generator `cliffUnitOf a` covers its
    reflection `houseHolderM a` (`cliffCovers_reflection`), so the whole generated submonoid is a
    submonoid of `CoversSub` (`Submonoid.closure_le`). -/
theorem pinSub_le_coversSub : PinSub ≤ CoversSub := by
  apply Submonoid.closure_le.mpr
  rintro u ⟨a, ha, rfl⟩
  exact ⟨houseHolderM a, (mem_bvIsomLinMonoid).mpr (houseHolderM_isom ha),
    cliffCovers_reflection ha⟩

/-- Every reflection-word isometry `g ∈ Submonoid.closure houseHolderMSet` has a covering unit IN
    the Pin group: induction over the generators (each generator covered by its `cliffUnitOf`,
    which is a Pin generator; identity by `1`; products compose and stay in `PinSub`). The Pin
    element covering a word `R₁···Rₙ` is the product `ι a₁···ι aₙ`. -/
theorem pin_covers_word {g : Module.End Cut STVC}
    (hg : g ∈ Submonoid.closure houseHolderMSet) :
    ∃ u, u ∈ PinSub ∧ CliffCovers (u : CliffCˣ) g := by
  induction hg using Submonoid.closure_induction with
  | mem x hx =>
      obtain ⟨a, ha, rfl⟩ := hx
      exact ⟨cliffUnitOf a ha, cliffUnitOf_mem_pinSub ha, cliffCovers_reflection ha⟩
  | one => exact ⟨1, one_mem _, cliffCovers_one⟩
  | mul x y _ _ ihx ihy =>
      obtain ⟨u, hu, hcu⟩ := ihx
      obtain ⟨w, hw, hcw⟩ := ihy
      exact ⟨u * w, mul_mem hu hw, cliffCovers_mul hcu hcw⟩

/-! ## THE PIN DOUBLE COVER — the cover restricted to the honest domain, surjective. -/

/-- ★★ THE PIN DOUBLE COVER `PinSub →* bvIsomLinMonoid`: the restriction of the cover group map
    `coverMap` (N144) to the reflection-generated Pin domain (`coverMap ∘ inclusion`). A genuine
    `MonoidHom` sending each Pin element to the (unique) continuum-Lorentz isometry it covers. -/
def coverMapPin : PinSub →* bvIsomLinMonoid :=
  coverMap.comp (Submonoid.inclusion pinSub_le_coversSub)

/-- The value of `coverMapPin` is the covered operator. -/
theorem coverMapPin_coe (u : PinSub) :
    (coverMapPin u : Module.End Cut STVC)
      = coverOp ⟨(u : CliffCˣ), pinSub_le_coversSub u.prop⟩ := rfl

/-- ★★ THE PIN DOUBLE COVER IS SURJECTIVE `↠ SO⁺(1,9)`: the Pin group (the reflection-generated
    domain, NOT all units) already covers the FULL continuum Lorentz group `bvIsomLinMonoid`.
    Every isometry is a reflection word (N132 `reflection_closure_eq_bvIsomLinMonoid`), and every
    reflection word has a covering unit in `PinSub` (`pin_covers_word`); uniqueness
    (`cliffCovers_unique`) makes the covered operator exactly `g`. -/
theorem coverMapPin_surjective : Function.Surjective coverMapPin := by
  rintro ⟨g, hg⟩
  rw [mem_bvIsomLinMonoid] at hg
  have hgc : g ∈ Submonoid.closure houseHolderMSet := by
    rw [reflection_closure_eq_bvIsomLinMonoid]; exact (mem_bvIsomLinMonoid).mpr hg
  obtain ⟨u, hu_pin, hu_cov⟩ := pin_covers_word hgc
  refine ⟨⟨u, hu_pin⟩, ?_⟩
  apply Subtype.ext
  show coverOp ⟨u, pinSub_le_coversSub hu_pin⟩ = g
  exact cliffCovers_unique (coverOp_covers ⟨u, pinSub_le_coversSub hu_pin⟩) hu_cov

/-! ## The order-2 kernel element is a genuine Pin element (a reflection square). -/

/-- THE KERNEL ELEMENT `-1` IS A REFLECTION SQUARE: `(cliffUnitOf mSpaceUnit)² = -1`. The Clifford
    square of the spacelike reflection unit is the scalar `algebraMap (QvC mSpaceUnit)`
    (`ι_sq_scalar`), and `QvC mSpaceUnit = -1` (the spacelike signature), so the square is
    `algebraMap (-1) = -1`. -/
theorem cliffUnitOf_mSpaceUnit_sq :
    (cliffUnitOf mSpaceUnit (by rw [BvC_mSpaceUnit_self]; exact neg_ne_zero.mpr one_ne_zero)) ^ 2
      = (-1 : CliffCˣ) := by
  apply Units.ext
  rw [sq, Units.val_mul, Units.val_neg, Units.val_one, cliffUnitOf_val]
  rw [CliffordAlgebra.ι_sq_scalar QvCQuad mSpaceUnit, QvCQuad_apply, QvC_mSpaceUnit]
  rw [map_neg, map_one]

/-- ★ THE KERNEL ELEMENT `-1` IS A GENUINE PIN ELEMENT: `(-1 : CliffCˣ) ∈ PinSub`. It is the
    SQUARE of the spacelike reflection unit (`cliffUnitOf_mSpaceUnit_sq`), hence a product of two
    Pin generators — a genuine reflection word. This is the new content over N136's set-level
    kernel (which negated an ARBITRARY covering unit): here `-1` is exhibited as an element of the
    honest reflection-generated Pin domain. -/
theorem negOne_mem_pinSub : (-1 : CliffCˣ) ∈ PinSub := by
  have hms : BvC (mSpaceUnit : STVC) (mSpaceUnit : STVC) ≠ 0 := by
    rw [BvC_mSpaceUnit_self]; exact neg_ne_zero.mpr one_ne_zero
  have h2 : (cliffUnitOf mSpaceUnit hms) ^ 2 ∈ PinSub := by
    rw [sq]; exact mul_mem (cliffUnitOf_mem_pinSub hms) (cliffUnitOf_mem_pinSub hms)
  rwa [cliffUnitOf_mSpaceUnit_sq] at h2

/-- The Pin element `-1` lies in the kernel of the Pin double cover: it covers the identity
    operator (`cover_kernel_neg_one`, N136), so its covered operator is `1` by uniqueness. -/
theorem negOne_mem_mker_coverMapPin :
    (⟨(-1 : CliffCˣ), negOne_mem_pinSub⟩ : PinSub) ∈ MonoidHom.mker coverMapPin := by
  rw [MonoidHom.mem_mker]
  apply Subtype.ext
  show coverOp ⟨(-1 : CliffCˣ), pinSub_le_coversSub negOne_mem_pinSub⟩
    = (1 : Module.End Cut STVC)
  exact cliffCovers_unique
    (coverOp_covers ⟨(-1 : CliffCˣ), pinSub_le_coversSub negOne_mem_pinSub⟩)
    cover_kernel_neg_one

/-- ★ THE KERNEL IS GENUINELY ORDER ≥ 2 AT THE GROUP-MAP LEVEL: the Pin element `-1` is in
    `MonoidHom.mker coverMapPin` and is DISTINCT from the identity Pin element (`cover_kernel_distinct`,
    `(2 : CliffC) ≠ 0`). So the Pin double cover is genuinely TWO-to-one — the kernel the
    surjectivity alone does not capture. With `coverMapPin_surjective` this characterizes
    `Pin(1,9) ↠ SO⁺(1,9)` as a surjective group map with a nontrivial kernel. -/
theorem coverMapPin_mker_nontrivial :
    (⟨(-1 : CliffCˣ), negOne_mem_pinSub⟩ : PinSub) ≠ 1 ∧
    (⟨(-1 : CliffCˣ), negOne_mem_pinSub⟩ : PinSub) ∈ MonoidHom.mker coverMapPin := by
  refine ⟨?_, negOne_mem_mker_coverMapPin⟩
  intro h
  exact cover_kernel_distinct (congrArg Subtype.val h)

/-! ## W8 teeth — a concrete boost is the image of a Pin covering unit. -/

/-- ★ W8 NON-VACUITY — the CONCRETE boost `(5/3,4/3)` (a genuine non-identity Lorentz element,
    off-diagonal `4/3 ≠ 0`) is the IMAGE under `coverMapPin` of a Pin covering unit. The Pin
    surjectivity realized on a real boost: `boostEndC (5/3) (4/3)` is a `BvC`-isometry, hence the
    image of some `u ∈ PinSub`. The read-off the costume C177 negates. -/
theorem coverMapPin_boost_apply :
    ∃ u : PinSub,
      (coverMapPin u : Module.End Cut STVC) = boostEndC ((5:Cut)/3) ((4:Cut)/3) := by
  have hab : ((5:Cut)/3) ^ 2 - ((4:Cut)/3) ^ 2 = 1 := by ring
  have hg : boostEndC ((5:Cut)/3) ((4:Cut)/3) ∈ bvIsomLinMonoid := boostEndC_isBvIsomLin hab
  obtain ⟨pu, hpu⟩ := coverMapPin_surjective ⟨_, hg⟩
  exact ⟨pu, congrArg Subtype.val hpu⟩

end

end Phys.Algebra
