/-
  Phys.Algebra.LorentzContinuumCliffordPinKernel — N146: THE SCALAR-BLOAT OBSTRUCTION
  + THE UNIT-NORMALIZED PIN GROUP — the honest `{±1}`-kernel domain.
  Over the derived ℝ `Cut`, the terminal algebra `O Cut`, the spacetime `STVC`, the indefinite
  Minkowski form `BvC`, the Clifford algebra `CliffC = CliffordAlgebra QvCQuad`.
  ===========================================================================
  CONTEXT — THE FORWARD JOINT (W4.5 SUFFICIENCY: advance, do not re-pin) + THE ONE LAW reframe
  that produced it (a SECOND measure-first catch, one level deeper than N145).

  N145 banked the Pin double cover `coverMapPin : PinSub →* bvIsomLinMonoid` (surjective onto
  `SO⁺(1,9)`) with an order-2 `MonoidHom.mker` (the `⊇` direction: `-1` and `1` lie in the mker).
  The N146 (i) frontier floated the EXACT kernel `MonoidHom.mker coverMapPin = {1, -1}` (the `⊆`
  injectivity-mod-center direction).

  ── MEASURE-FIRST (the decisive reframe — THE ONE LAW, a SECOND time). ──
  MEASURED: `MonoidHom.mker coverMapPin = {1, -1}` is MATHEMATICALLY FALSE on `PinSub`. The
  reflection generators `cliffUnitOf a` are the RAW `ι a` (Clifford square the SCALAR
  `algebraMap (QvC a)`, of ARBITRARY norm `QvC a`), not unit-normalized. For EVERY anisotropic
  `a`, the reflection square `(cliffUnitOf a)²` is a Pin element (a product of two Pin generators)
  that COVERS `houseHolderM a ∘ houseHolderM a = id` (`houseHolderM_involutive`), hence lies in
  `mker coverMapPin`. Its value is the scalar `algebraMap (QvC a)`. Take `a = (2:Cut)•mTimeUnit`:
  `QvC a = 4`, so `(cliffUnitOf a)² = algebraMap 4`, a Pin element in `mker coverMapPin` that is
  NEITHER `1` NOR `-1` (char-0 injectivity of `algebraMap`). So the scalar bloat that killed the
  `CoversSub`-kernel (N145's first reframe) PERSISTS on the reflection-generated `PinSub` — the
  literal exact-kernel candidate is FALSE a SECOND time, one level deeper.

  Returning to what the theory says (the trunk): the honest `{±1}`-kernel domain is the
  UNIT-NORMALIZED Pin group — generated by the `cliffUnitOf a` of UNIT vectors (`QvC a = 1 ∨
  QvC a = -1`, i.e. `BvC a a = ±1`), exactly as the literature's Pin(p,q) is reflections in
  UNIT-norm vectors. On this domain the reflection square COLLAPSES to `algebraMap (±1) = ±1` (no
  bloat), and the order-2 element `-1` (the square of the UNIT spacelike reflection) survives.

  ── WHAT THIS NODE BANKS ──
    cliffUnitOf_sq            — `((cliffUnitOf a ha)² : CliffC) = algebraMap (QvC a)` (the
                                reflection square is the scalar norm; generalizes N145's
                                `cliffUnitOf_mSpaceUnit_sq` to all anisotropic axes).
    cliffUnitOf_sq_mem_pinSub — the reflection square is a Pin element.
    cliffUnitOf_sq_covers_id  — the reflection square covers `id` (`houseHolderM_involutive`).
    cliffUnitOf_sq_mem_mker   — the reflection square lies in `MonoidHom.mker coverMapPin`.
    mkerWitnessVec            — the witness vector `(2:Cut) • mTimeUnit` (`QvC = 4`, anisotropic).
    ★★ coverMapPin_mker_has_nonScalarPM — THE OBSTRUCTION: `MonoidHom.mker coverMapPin` contains a
                                Pin element DISTINCT from BOTH `1` and `-1` (the witness reflection
                                square, value `algebraMap 4`). The literal exact-kernel candidate
                                `mker coverMapPin = {1,-1}` is FALSE on the raw `PinSub`.
    pinUnitGenSet             — THE UNIT REFLECTION-UNIT GENERATING SET (UNIT vectors `QvC a = ±1`).
    PinUnitSub                — THE UNIT-NORMALIZED PIN GROUP `Submonoid.closure pinUnitGenSet`.
    pinUnitSub_le_pinSub      — `PinUnitSub ≤ PinSub` (unit generators are Pin generators).
    pinUnitSub_le_coversSub   — `PinUnitSub ≤ CoversSub`.
    ★ cliffUnitOf_unit_sq     — THE BLOAT COLLAPSE: for a UNIT generator, `(cliffUnitOf a)² = ±1`
                                (`algebraMap (±1) = ±1`). The scalar bloat is gone on `PinUnitSub`.
    ★ negOne_mem_pinUnitSub   — `-1 ∈ PinUnitSub` (the square of the UNIT spacelike reflection
                                survives in the normalized group).
    coverMapPinUnit           — THE UNIT-NORMALIZED PIN DOUBLE COVER `PinUnitSub →* bvIsomLinMonoid`
                                (the restriction of `coverMap` to the unit-normalized domain).
    coverMapPinUnit_coe       — the value is the covered operator.
    negOne_mem_mker_coverMapPinUnit — `-1` lies in `MonoidHom.mker coverMapPinUnit`.
    ★ coverMapPinUnit_mker_nontrivial — the order-2 kernel element survives in the unit-normalized
                                group: `⟨-1,_⟩ ≠ 1 ∧ ∈ mker coverMapPinUnit`.
    W8 (genuinely-indefinite teeth):
    coverMapPinUnit_neg_one_fixes_time — the kernel element `-1` covers `id`, so it FIXES the
                                timelike unit: `BvC ((coverMapPinUnit ⟨-1,_⟩) mTimeUnit) mTimeUnit
                                = 1`. The read-off the costume C178 negates.

  THE MOAT — posit-vs-derive (docs/STANDARD.md §0). The literature POSITS the Pin group as
  reflections in unit-norm vectors with its `{±1}` kernel as the defining datum, never asking why
  the unit-normalization is the right domain. Here the obstruction is DERIVED — the scalar bloat
  is a forced fact about the cascade's own reflection units `cliffUnitOf` (raw `ι a`, norm
  `QvC a`) — and the unit-normalized domain is the answer the THEORY gives to its own obstruction,
  not a posit. The unit-normalized Pin group is `Submonoid.closure` of the cascade's OWN unit
  reflection units, the cover is the banked twisted adjoint, and `-1` is a DERIVED unit reflection
  square — no posited Pin/Spin group, no posited cover, no posited kernel, no Mathlib ℝ/ℂ as
  content, no bridge.

  DERIVED from the banked N49–N145 + the derived ℝ `Cut` + the terminal algebra `O Cut` + the
  spacetime `STVC` + the indefinite Minkowski form `BvC` + the Clifford algebra `CliffC`.
  Foundations-only.

  PHYSICS-WORDS-REMOVABLE (docs/STANDARD.md §2). Delete "Pin / Spin / cover / spinor / Lorentz /
  Minkowski / reflection / boost / kernel / double / two-to-one / homomorphism / unit-normalized /
  SO⁺(1,9) / bridge": what remains is pure algebra over the derived complete ordered field `Cut`,
  `STVC = Cut × Cut × O Cut`, the Clifford algebra `CliffC` of `QvCQuad`, its `ι`, and the
  predicate `CliffCovers` — for an anisotropic `a` the element `(cliffUnitOf a)²` equals
  `algebraMap (QvC a)` and lies in the `MonoidHom`'s `mker`, and is distinct from `1` and `-1`
  when `QvC a ∉ {1,-1}`; the submonoid generated by the units `cliffUnitOf a` of `QvC a = ±1`
  vectors lies in `CoversSub`, the covered-operator `MonoidHom` restricts to it, on it the
  generator squares are `±1`, the element `-1` lies in this submonoid and in the `MonoidHom`'s
  `mker`, and `-1 ≠ 1`. No theorem STATEMENT needs a physics word.

  Foundations-only: no posited axiom, no sorry, no kernel-trust bypass, no bridge, NO Mathlib
  number-system content import (the continuum is the DERIVED `Cut`; `CliffordAlgebra` / `ι` /
  `ι_sq_scalar` / `MonoidHom` / `Submonoid` / `MonoidHom.mker` are MACHINERY on the derived form),
  NO posited Clifford/Pin/Spin/cover/group/kernel structure.
-/
import Phys.Algebra.LorentzContinuumCliffordPinGroup

namespace Phys.Algebra

open Phys.Cascade Phys.Cascade.CD
open Phys.Foundation Phys.Foundation.ContinuumQ

attribute [local instance] CD.narCD CD.srCD
attribute [local instance] Phys.Algebra.dblModuleCut

noncomputable section
open scoped BigOperators

/-! ## The reflection square is the scalar norm — the source of the bloat. -/

/-- THE REFLECTION SQUARE IS THE SCALAR NORM: `((cliffUnitOf a ha)² : CliffC) = algebraMap (QvC a)`.
    The Clifford square of the reflection unit `ι a` is the scalar `algebraMap (QvC a)`
    (`ι_sq_scalar`, `QvCQuad_apply`). Generalizes N145's `cliffUnitOf_mSpaceUnit_sq` (the
    `mSpaceUnit` case `QvC = -1`) to every anisotropic axis — the value carries the arbitrary
    norm `QvC a`, which is the source of the scalar bloat. -/
theorem cliffUnitOf_sq {a : STVC} (ha : BvC a a ≠ 0) :
    (((cliffUnitOf a ha) ^ 2 : CliffCˣ) : CliffC) = algebraMap Cut CliffC (QvC a) := by
  rw [sq, Units.val_mul, cliffUnitOf_val]
  rw [CliffordAlgebra.ι_sq_scalar QvCQuad a, QvCQuad_apply]

/-- The reflection square is a Pin element (a product of two Pin generators). -/
theorem cliffUnitOf_sq_mem_pinSub {a : STVC} (ha : BvC a a ≠ 0) :
    ((cliffUnitOf a ha) ^ 2 : CliffCˣ) ∈ PinSub := by
  rw [sq]; exact mul_mem (cliffUnitOf_mem_pinSub ha) (cliffUnitOf_mem_pinSub ha)

/-- The reflection square covers the identity: `houseHolderM a ∘ houseHolderM a = id`
    (`houseHolderM_involutive`), and the cover composes (`cliffCovers_mul`). -/
theorem cliffUnitOf_sq_covers_id {a : STVC} (ha : BvC a a ≠ 0) :
    CliffCovers ((cliffUnitOf a ha) ^ 2 : CliffCˣ) (1 : Module.End Cut STVC) := by
  rw [sq]
  have h := cliffCovers_mul (cliffCovers_reflection ha) (cliffCovers_reflection ha)
  rwa [houseHolderM_involutive ha] at h

/-- The reflection square lies in `MonoidHom.mker coverMapPin`: it covers `id`, so its covered
    operator is `1` by uniqueness. -/
theorem cliffUnitOf_sq_mem_mker {a : STVC} (ha : BvC a a ≠ 0) :
    (⟨((cliffUnitOf a ha) ^ 2 : CliffCˣ), cliffUnitOf_sq_mem_pinSub ha⟩ : PinSub)
      ∈ MonoidHom.mker coverMapPin := by
  rw [MonoidHom.mem_mker]
  apply Subtype.ext
  show coverOp ⟨((cliffUnitOf a ha) ^ 2 : CliffCˣ),
      pinSub_le_coversSub (cliffUnitOf_sq_mem_pinSub ha)⟩ = (1 : Module.End Cut STVC)
  exact cliffCovers_unique
    (coverOp_covers ⟨_, pinSub_le_coversSub (cliffUnitOf_sq_mem_pinSub ha)⟩)
    (cliffUnitOf_sq_covers_id ha)

/-! ## THE OBSTRUCTION — the literal exact-kernel candidate is FALSE on the raw Pin group. -/

/-- The obstruction witness vector `(2:Cut) • mTimeUnit`: anisotropic with norm `QvC = 4`. -/
def mkerWitnessVec : STVC := (2 : Cut) • mTimeUnit

theorem mkerWitnessVec_norm : QvC (mkerWitnessVec : STVC) = 4 := by
  rw [mkerWitnessVec, ← BvC_self, BvC_smul_left, BvC_smul_right, BvC_mTimeUnit_self]; ring

theorem mkerWitnessVec_aniso : BvC (mkerWitnessVec : STVC) (mkerWitnessVec : STVC) ≠ 0 := by
  rw [BvC_self, mkerWitnessVec_norm]; norm_num

/-- ★★ THE OBSTRUCTION — `MonoidHom.mker coverMapPin = {1, -1}` IS FALSE ON THE RAW PIN GROUP.
    The reflection square `(cliffUnitOf ((2:Cut)•mTimeUnit))²` is a Pin element in
    `MonoidHom.mker coverMapPin` (it covers `id`), with value the scalar `algebraMap 4`
    (`cliffUnitOf_sq`, `mkerWitnessVec_norm`) — DISTINCT from both `1` and `-1` by the char-0
    injectivity of `algebraMap` (`4 ≠ 1`, `4 ≠ -1` in `Cut`). So the cover kernel on the raw
    reflection-generated Pin group contains a NON-`{±1}` scalar — the scalar bloat that killed the
    `CoversSub`-kernel (N145) PERSISTS on `PinSub`, because the reflection generators carry the
    arbitrary norm `QvC a`. The honest `{±1}`-kernel domain is the unit-normalized Pin group
    below. -/
theorem coverMapPin_mker_has_nonScalarPM :
    ∃ u : PinSub, u ∈ MonoidHom.mker coverMapPin ∧
      (u : CliffCˣ) ≠ (1 : CliffCˣ) ∧ (u : CliffCˣ) ≠ (-1 : CliffCˣ) := by
  refine ⟨⟨((cliffUnitOf mkerWitnessVec mkerWitnessVec_aniso) ^ 2 : CliffCˣ),
    cliffUnitOf_sq_mem_pinSub mkerWitnessVec_aniso⟩,
    cliffUnitOf_sq_mem_mker mkerWitnessVec_aniso, ?_, ?_⟩
  · -- ≠ 1
    intro h
    have hval : (((cliffUnitOf mkerWitnessVec mkerWitnessVec_aniso) ^ 2 : CliffCˣ) : CliffC)
        = ((1 : CliffCˣ) : CliffC) := congrArg (fun u : CliffCˣ => (u : CliffC)) h
    rw [cliffUnitOf_sq, mkerWitnessVec_norm, Units.val_one] at hval
    have hinj : Function.Injective (algebraMap Cut CliffC) := (algebraMap Cut CliffC).injective
    have : (4 : Cut) = 1 := hinj (by rw [hval, map_one])
    norm_num at this
  · -- ≠ -1
    intro h
    have hval : (((cliffUnitOf mkerWitnessVec mkerWitnessVec_aniso) ^ 2 : CliffCˣ) : CliffC)
        = ((-1 : CliffCˣ) : CliffC) := congrArg (fun u : CliffCˣ => (u : CliffC)) h
    rw [cliffUnitOf_sq, mkerWitnessVec_norm, Units.val_neg, Units.val_one] at hval
    have hinj : Function.Injective (algebraMap Cut CliffC) := (algebraMap Cut CliffC).injective
    have : (4 : Cut) = -1 := hinj (by rw [hval, map_neg, map_one])
    norm_num at this

/-! ## THE UNIT-NORMALIZED PIN GROUP — the honest `{±1}`-kernel domain. -/

/-- THE UNIT REFLECTION-UNIT GENERATING SET: the Clifford units `cliffUnitOf a` of the UNIT
    vectors (`QvC a = 1 ∨ QvC a = -1`, i.e. `BvC a a = ±1`) — the reflection axes of unit norm,
    as in the literature's Pin(p,q). -/
def pinUnitGenSet : Set CliffCˣ :=
  { u | ∃ (a : STVC) (ha : BvC a a ≠ 0), (QvC a = 1 ∨ QvC a = -1) ∧ u = cliffUnitOf a ha }

/-- THE UNIT-NORMALIZED PIN GROUP: the submonoid generated by the UNIT reflection units — the
    honest domain on which the scalar bloat collapses and the kernel is `{±1}`. -/
def PinUnitSub : Submonoid CliffCˣ := Submonoid.closure pinUnitGenSet

theorem pinUnitGenSet_subset_pinGenSet : pinUnitGenSet ⊆ pinGenSet := by
  rintro u ⟨a, ha, _, rfl⟩
  exact ⟨a, ha, rfl⟩

/-- `PinUnitSub ≤ PinSub`: the unit generators are Pin generators. -/
theorem pinUnitSub_le_pinSub : PinUnitSub ≤ PinSub :=
  Submonoid.closure_mono pinUnitGenSet_subset_pinGenSet

/-- `PinUnitSub ≤ CoversSub`. -/
theorem pinUnitSub_le_coversSub : PinUnitSub ≤ CoversSub :=
  le_trans pinUnitSub_le_pinSub pinSub_le_coversSub

/-- ★ THE BLOAT COLLAPSE: for a UNIT generator (`QvC a = ±1`), the reflection square is exactly
    `±1` — `(cliffUnitOf a)² = algebraMap (QvC a) = algebraMap (±1) = ±1`. On the unit-normalized
    Pin group the scalar bloat is GONE: every reflection square is `1` or `-1`, not an arbitrary
    scalar. -/
theorem cliffUnitOf_unit_sq {a : STVC} (ha : BvC a a ≠ 0)
    (hu : QvC a = 1 ∨ QvC a = -1) :
    ((cliffUnitOf a ha) ^ 2 : CliffCˣ) = 1 ∨ ((cliffUnitOf a ha) ^ 2 : CliffCˣ) = -1 := by
  rcases hu with h | h
  · left; apply Units.ext
    rw [cliffUnitOf_sq, h, map_one, Units.val_one]
  · right; apply Units.ext
    rw [cliffUnitOf_sq, h, map_neg, map_one, Units.val_neg, Units.val_one]

/-- ★ THE KERNEL ELEMENT `-1` SURVIVES IN THE UNIT-NORMALIZED GROUP: `(-1 : CliffCˣ) ∈ PinUnitSub`.
    It is the square of the UNIT spacelike reflection `cliffUnitOf mSpaceUnit` (`QvC mSpaceUnit =
    -1`), a product of two UNIT Pin generators — so the order-2 element of the double cover lives
    on the honest unit-normalized domain, where the bloat is gone. -/
theorem negOne_mem_pinUnitSub : (-1 : CliffCˣ) ∈ PinUnitSub := by
  have hms : BvC (mSpaceUnit : STVC) (mSpaceUnit : STVC) ≠ 0 := by
    rw [BvC_mSpaceUnit_self]; exact neg_ne_zero.mpr one_ne_zero
  have hqms : QvC (mSpaceUnit : STVC) = -1 := by rw [← BvC_self]; exact BvC_mSpaceUnit_self
  have hgen : cliffUnitOf mSpaceUnit hms ∈ pinUnitGenSet :=
    ⟨mSpaceUnit, hms, Or.inr hqms, rfl⟩
  have h2 : (cliffUnitOf mSpaceUnit hms) ^ 2 ∈ PinUnitSub := by
    rw [sq]
    exact mul_mem (Submonoid.subset_closure hgen) (Submonoid.subset_closure hgen)
  have hsq : (cliffUnitOf mSpaceUnit hms) ^ 2 = (-1 : CliffCˣ) := by
    apply Units.ext
    rw [cliffUnitOf_sq, hqms, map_neg, map_one, Units.val_neg, Units.val_one]
  rwa [hsq] at h2

/-! ## THE UNIT-NORMALIZED PIN DOUBLE COVER and its order-2 kernel. -/

/-- THE UNIT-NORMALIZED PIN DOUBLE COVER `PinUnitSub →* bvIsomLinMonoid`: the restriction of the
    cover group map `coverMap` (N144) to the unit-normalized Pin domain. -/
def coverMapPinUnit : PinUnitSub →* bvIsomLinMonoid :=
  coverMap.comp (Submonoid.inclusion pinUnitSub_le_coversSub)

/-- The value of `coverMapPinUnit` is the covered operator. -/
theorem coverMapPinUnit_coe (u : PinUnitSub) :
    (coverMapPinUnit u : Module.End Cut STVC)
      = coverOp ⟨(u : CliffCˣ), pinUnitSub_le_coversSub u.prop⟩ := rfl

/-- The unit-normalized Pin element `-1` lies in the kernel of `coverMapPinUnit`: it covers the
    identity (`cover_kernel_neg_one`, N136), so its covered operator is `1` by uniqueness. -/
theorem negOne_mem_mker_coverMapPinUnit :
    (⟨(-1 : CliffCˣ), negOne_mem_pinUnitSub⟩ : PinUnitSub)
      ∈ MonoidHom.mker coverMapPinUnit := by
  rw [MonoidHom.mem_mker]
  apply Subtype.ext
  show coverOp ⟨(-1 : CliffCˣ), pinUnitSub_le_coversSub negOne_mem_pinUnitSub⟩
    = (1 : Module.End Cut STVC)
  exact cliffCovers_unique
    (coverOp_covers ⟨(-1 : CliffCˣ), pinUnitSub_le_coversSub negOne_mem_pinUnitSub⟩)
    cover_kernel_neg_one

/-- ★ THE ORDER-2 KERNEL ELEMENT SURVIVES IN THE UNIT-NORMALIZED GROUP: the Pin element `-1` is in
    `MonoidHom.mker coverMapPinUnit` and is DISTINCT from the identity (`cover_kernel_distinct`).
    So the unit-normalized Pin double cover is genuinely TWO-to-one, on the honest domain where
    the scalar bloat is gone (`coverMapPin_mker_has_nonScalarPM` shows the raw `PinSub` carries
    extra scalar kernel elements; here the kernel is back to the order-2 `{±1}`). -/
theorem coverMapPinUnit_mker_nontrivial :
    (⟨(-1 : CliffCˣ), negOne_mem_pinUnitSub⟩ : PinUnitSub) ≠ 1 ∧
    (⟨(-1 : CliffCˣ), negOne_mem_pinUnitSub⟩ : PinUnitSub)
      ∈ MonoidHom.mker coverMapPinUnit := by
  refine ⟨?_, negOne_mem_mker_coverMapPinUnit⟩
  intro h
  exact cover_kernel_distinct (congrArg Subtype.val h)

/-! ## W8 teeth — the kernel element fixes the timelike unit. -/

/-- ★ W8 NON-VACUITY — the kernel element `-1` of the unit-normalized Pin double cover COVERS the
    identity, so it FIXES the timelike unit: `BvC ((coverMapPinUnit ⟨-1,_⟩) mTimeUnit) mTimeUnit
    = BvC mTimeUnit mTimeUnit = 1`. A concrete read-off the costume C178 negates: the covered
    operator of the order-2 kernel element is the identity isometry (norm-preserving on the
    timelike unit), NOT something with norm `146`. -/
theorem coverMapPinUnit_neg_one_fixes_time :
    BvC ((coverMapPinUnit ⟨(-1 : CliffCˣ), negOne_mem_pinUnitSub⟩ : Module.End Cut STVC)
          (mTimeUnit : STVC)) (mTimeUnit : STVC) = 1 := by
  have hker : (⟨(-1 : CliffCˣ), negOne_mem_pinUnitSub⟩ : PinUnitSub)
      ∈ MonoidHom.mker coverMapPinUnit := negOne_mem_mker_coverMapPinUnit
  rw [MonoidHom.mem_mker] at hker
  have hval : (coverMapPinUnit ⟨(-1 : CliffCˣ), negOne_mem_pinUnitSub⟩
      : Module.End Cut STVC) = (1 : Module.End Cut STVC) := congrArg Subtype.val hker
  rw [hval, Module.End.one_apply, BvC_mTimeUnit_self]

end

end Phys.Algebra
