/-
  Phys.Algebra.LorentzContinuumCliffordPinSurjective — N151: THE SURJECTIVITY of the
  UNIT-NORMALIZED PIN DOUBLE COVER `coverMapPinUnit ↠ SO⁺(1,9)`.
  Over the derived ℝ `Cut`, the terminal algebra `O Cut`, the spacetime `STVC`, the indefinite
  Minkowski form `BvC`, the Clifford algebra `CliffC = CliffordAlgebra QvCQuad`.
  ===========================================================================
  CONTEXT — THE OTHER HALF OF THE DOUBLE COVER (W4.5 SUFFICIENCY: advance to the genuinely-new
  datum) + THE ONE LAW reframe (the reflection is scale-invariant in its axis).

  N150 banked the EXACT KERNEL `MonoidHom.mker coverMapPinUnit = {1, -1}` — the unit-normalized
  Pin double cover `coverMapPinUnit : PinUnitSub →* bvIsomLinMonoid` is injective-mod-{±1}. That
  closed the KERNEL half of `Pin(1,9) ↠ SO⁺(1,9)`. The remaining open structure of the cover is
  its SURJECTIVITY: every Lorentz isometry is covered by a UNIT-normalized Pin element.

  ── THE ONE LAW REFRAME (trunk-native, NOT a grind). ──
  N144 (`coverMap_surjective`) already covers ALL of `SO⁺(1,9)` — but on the BLOATED domain
  `CoversSub`, whose reflection generators `cliffUnitOf a` use RAW axes of ARBITRARY norm `QvC a`.
  The literal descent to the unit-normalized domain `PinUnitSub` (generated by UNIT axes,
  `QvC a = ±1`) would seem to need an entirely new cover construction. Returning to what the
  theory says: a Householder reflection depends ONLY on the DIRECTION of its axis —
    `houseHolderM (c • a) = houseHolderM a`   for `c ≠ 0`   (`houseHolderM_smul`),
  because rescaling the axis rescales the projection coefficient `2·(BvC a a)⁻¹·BvC a p` by
  `c⁻²·c = c⁻¹` against the `c•a` factor, cancelling. So ANY anisotropic axis `a` is replaced by
  the UNIT axis `unitAxis a := (cutSqrt |QvC a|⁻¹) • a` (`QvC (unitAxis a) = sign(QvC a) = ±1`,
  via the banked scalar square root `cutSqrt`, N57, the order-completeness of the derived ℝ `Cut`),
  whose `cliffUnitOf` is a UNIT Pin GENERATOR (`pinUnitGenSet`) covering the SAME reflection
  `houseHolderM a`. Re-running the cover induction over reflection words now lands inside
  `PinUnitSub`, and N132's classification (`reflection_closure_eq_bvIsomLinMonoid`, every isometry
  IS a reflection word) + `coverOp` uniqueness give the surjectivity of `coverMapPinUnit`.

  Together with N150's kernel, `Pin(1,9) ↠ SO⁺(1,9)` is now a SURJECTIVE two-to-one group
  homomorphism — DERIVED forward, no posited Pin/Spin group, no posited cover, no posited
  surjectivity.

  ── WHAT THIS NODE BANKS ──
    QvC_smul                  — `QvC (c • a) = c·c·QvC a` (the quadratic form scales by `c²`).
    houseHolderM_smul         — ★ THE SCALE-INVARIANCE: `houseHolderM (c • a) = houseHolderM a`
                                for `c ≠ 0` — the reflection depends only on the axis DIRECTION.
    unitNormCut               — the rescale scalar `cutSqrt |QvC a|⁻¹`.
    unitNormCut_sq            — `unitNormCut a · unitNormCut a = |QvC a|⁻¹` (`cutSqrt_sq`).
    unitNormCut_pos           — `0 < unitNormCut a` for `QvC a ≠ 0` (`cutSqrt_pos`).
    unitAxis                  — the UNIT axis `unitNormCut a • a` (same direction, `QvC = ±1`).
    QvC_unitAxis              — `QvC (unitAxis a) = 1 ∨ QvC (unitAxis a) = -1` for `QvC a ≠ 0`.
    unitAxis_aniso            — `BvC (unitAxis a) (unitAxis a) ≠ 0` (the unit axis is anisotropic).
    houseHolderM_unitAxis     — `houseHolderM (unitAxis a) = houseHolderM a` (scale-invariance).
    cliffUnitOf_unitAxis_mem  — the unit-axis covering generator lands in `PinUnitSub`.
    cliffUnitOf_unitAxis_covers — it covers the SAME reflection `houseHolderM a`.
    cover_global_reflection_word_pinUnit — ★★ the reflection-word cover landing in `PinUnitSub`.
    cover_global_bvIsom_pinUnit — ★★ every `BvC`-isometry has a UNIT-normalized covering unit.
    ★★★ coverMapPinUnit_surjective — THE SURJECTIVITY `coverMapPinUnit ↠ SO⁺(1,9)`.
    coverMapPinUnit_boost_apply — W8 teeth: the concrete boost `(5/3,4/3)` is the image of a
                                UNIT-normalized Pin element.

  STANDARD (the second gate):
  • UNBROKEN — every object from the chain N49–N150 + the derived ℝ `Cut` + `cutSqrt` (N57) +
    `BvC`/`QvC`/`houseHolderM` + the cover/Pin family (N133–N146); `CliffordAlgebra`/`Submonoid`/
    `cutSqrt` are MACHINERY on the derived form `QvCQuad` over the derived field `Cut`. No Mathlib
    ℝ/ℂ as content, no posited group/cover/surjectivity, no bridge.
  • COMPLETE — all decls foundations-only `{propext, Classical.choice, Quot.sound}` (audited).
  • PHYSICS-WORDS-REMOVABLE — delete Lorentz/reflection/cover/spinor/Clifford/Pin/Minkowski/
    isometry/surjectivity/unit-normalized: the statement stands as pure algebra over the derived
    field `Cut` — every `BvC`-isometry of `STVC` is the covered operator of an element of the
    submonoid `PinUnitSub` (generated by the unit-axis Clifford units), via the scale-invariance
    `houseHolderM (c•a) = houseHolderM a` and the unit-normalization `cutSqrt |QvC a|⁻¹`.
-/
import Phys.Algebra.LorentzContinuumCliffordPinExactKernelComplete

namespace Phys.Algebra

open Phys.Cascade Phys.Cascade.CD
open Phys.Foundation Phys.Foundation.ContinuumQ

attribute [local instance] CD.narCD CD.srCD
attribute [local instance] Phys.Algebra.dblModuleCut

noncomputable section

/-! ## Scale-invariance of the reflection and the unit-axis normalization. -/

/-- `QvC (c • a) = c·c·QvC a` — the quadratic form scales by `c²` (bilinearity of `BvC`). -/
theorem QvC_smul (c : Cut) (a : STVC) : QvC (c • a) = c * c * QvC a := by
  rw [← BvC_self, BvC_smul_left, BvC_smul_right, BvC_self]; ring

/-- ★ THE SCALE-INVARIANCE OF THE REFLECTION: `houseHolderM (c • a) = houseHolderM a` for `c ≠ 0`.
    A Householder reflection depends only on the DIRECTION of its axis: rescaling `a ↦ c•a` rescales
    the projection coefficient `2·(BvC a a)⁻¹·BvC a p` by `c⁻²·c = c⁻¹` against the `c•a` factor,
    which cancels. The trunk fact that makes the unit-normalization possible. -/
theorem houseHolderM_smul {a : STVC} (c : Cut) (hc : c ≠ 0) (ha : BvC a a ≠ 0) :
    houseHolderM (c • a) = houseHolderM a := by
  apply LinearMap.ext
  intro p
  rw [houseHolderM_apply, houseHolderM_apply]
  have hcc : BvC (c • a) (c • a) = c * c * BvC a a := by
    rw [BvC_smul_left, BvC_smul_right]; ring
  have hcp : BvC (c • a) p = c * BvC a p := by rw [BvC_smul_left]
  rw [hcc, hcp, smul_smul]
  have hco : 2 * (c * c * BvC a a)⁻¹ * (c * BvC a p) * c
      = 2 * (BvC a a)⁻¹ * BvC a p := by
    field_simp
  rw [hco]

/-- The rescale scalar `cutSqrt |QvC a|⁻¹` taking an anisotropic axis to a unit axis (N57 `cutSqrt`,
    the order-completeness of the derived ℝ `Cut`). -/
noncomputable def unitNormCut (a : STVC) : Cut := cutSqrt (|QvC a|⁻¹)

/-- `unitNormCut a · unitNormCut a = |QvC a|⁻¹` (the defining square, `cutSqrt_sq` on `|QvC a|⁻¹ ≥ 0`). -/
theorem unitNormCut_sq (a : STVC) : unitNormCut a * unitNormCut a = |QvC a|⁻¹ :=
  cutSqrt_sq (inv_nonneg.mpr (abs_nonneg _))

/-- `0 < unitNormCut a` for `QvC a ≠ 0` (`cutSqrt_pos` on the strictly-positive `|QvC a|⁻¹`). -/
theorem unitNormCut_pos {a : STVC} (ha : QvC a ≠ 0) : 0 < unitNormCut a :=
  cutSqrt_pos (inv_pos.mpr (abs_pos.mpr ha))

/-- The unit-normalized axis: the same direction as `a`, rescaled to `QvC = ±1`. -/
noncomputable def unitAxis (a : STVC) : STVC := unitNormCut a • a

/-- `QvC (unitAxis a) = 1 ∨ QvC (unitAxis a) = -1` for an anisotropic `a` (`QvC a ≠ 0`):
    `QvC (unitAxis a) = |QvC a|⁻¹·QvC a = sign(QvC a) = ±1`. -/
theorem QvC_unitAxis {a : STVC} (ha : QvC a ≠ 0) :
    QvC (unitAxis a) = 1 ∨ QvC (unitAxis a) = -1 := by
  have hval : QvC (unitAxis a) = |QvC a|⁻¹ * QvC a := by
    unfold unitAxis; rw [QvC_smul, unitNormCut_sq]
  rcases lt_or_gt_of_ne ha with h | h
  · right
    rw [hval, abs_of_neg h, inv_neg, neg_mul, inv_mul_cancel₀ ha]
  · left
    rw [hval, abs_of_pos h, inv_mul_cancel₀ (ne_of_gt h)]

/-- The unit axis is anisotropic: `BvC (unitAxis a) (unitAxis a) = QvC (unitAxis a) = ±1 ≠ 0`. -/
theorem unitAxis_aniso {a : STVC} (ha : QvC a ≠ 0) :
    BvC (unitAxis a) (unitAxis a) ≠ 0 := by
  rw [BvC_self]
  rcases QvC_unitAxis ha with h | h <;> rw [h]
  · exact one_ne_zero
  · exact neg_ne_zero.mpr one_ne_zero

/-- `houseHolderM (unitAxis a) = houseHolderM a` — the unit axis reflects across the SAME hyperplane
    (scale-invariance `houseHolderM_smul`, the rescale scalar is nonzero). -/
theorem houseHolderM_unitAxis {a : STVC} (ha : BvC a a ≠ 0) :
    houseHolderM (unitAxis a) = houseHolderM a := by
  have hqa : QvC a ≠ 0 := by rw [← BvC_self]; exact ha
  unfold unitAxis
  exact houseHolderM_smul (unitNormCut a) (ne_of_gt (unitNormCut_pos hqa)) ha

/-! ## The unit-axis covering generator lands in `PinUnitSub` and covers the same reflection. -/

/-- The unit-axis Clifford unit `cliffUnitOf (unitAxis a)` is a UNIT Pin generator: it lies in
    `pinUnitGenSet` (its axis has `QvC = ±1`), hence in `PinUnitSub`. -/
theorem cliffUnitOf_unitAxis_mem {a : STVC} (hqa : QvC a ≠ 0) :
    cliffUnitOf (unitAxis a) (unitAxis_aniso hqa) ∈ PinUnitSub :=
  Submonoid.subset_closure ⟨unitAxis a, unitAxis_aniso hqa, QvC_unitAxis hqa, rfl⟩

/-- The unit-axis Clifford unit covers the SAME reflection `houseHolderM a` (it covers
    `houseHolderM (unitAxis a)`, which equals `houseHolderM a` by scale-invariance). -/
theorem cliffUnitOf_unitAxis_covers {a : STVC} (ha : BvC a a ≠ 0) :
    CliffCovers (cliffUnitOf (unitAxis a) (unitAxis_aniso (by rw [← BvC_self]; exact ha)))
      (houseHolderM a) := by
  have hqa : QvC a ≠ 0 := by rw [← BvC_self]; exact ha
  have hc := cliffCovers_reflection (unitAxis_aniso hqa)
  rwa [houseHolderM_unitAxis ha] at hc

/-! ## The global cover landing in the UNIT-normalized Pin group, and surjectivity. -/

/-- ★★ THE GLOBAL COVER over the reflection-word group, landing in `PinUnitSub`: EVERY
    `g ∈ Submonoid.closure houseHolderMSet` has a UNIT-normalized covering unit. The reflection is
    scale-invariant in its axis (`houseHolderM_smul`), so each generator's RAW axis is replaced by
    its unit axis (`unitAxis`, `QvC = ±1`), whose `cliffUnitOf` is a UNIT Pin generator covering the
    SAME reflection — the cover induction now lands inside `PinUnitSub`. -/
theorem cover_global_reflection_word_pinUnit {g : Module.End Cut STVC}
    (hg : g ∈ Submonoid.closure houseHolderMSet) :
    ∃ u : CliffCˣ, u ∈ PinUnitSub ∧ CliffCovers u g := by
  induction hg using Submonoid.closure_induction with
  | mem x hx =>
      obtain ⟨a, ha, rfl⟩ := hx
      have hqa : QvC a ≠ 0 := by rw [← BvC_self]; exact ha
      refine ⟨cliffUnitOf (unitAxis a) (unitAxis_aniso hqa), ?_, ?_⟩
      · exact cliffUnitOf_unitAxis_mem hqa
      · have hc := cliffCovers_reflection (unitAxis_aniso hqa)
        rwa [houseHolderM_unitAxis ha] at hc
  | one => exact ⟨1, Submonoid.one_mem _, cliffCovers_one⟩
  | mul x y _ _ ihx ihy =>
      obtain ⟨u, hu, hcu⟩ := ihx
      obtain ⟨w, hw, hcw⟩ := ihy
      exact ⟨u * w, mul_mem hu hw, cliffCovers_mul hcu hcw⟩

/-- ★★ THE GLOBAL SURJECTIVITY over the UNIT-normalized Pin group: EVERY linear `BvC`-isometry
    `g ∈ bvIsomLinMonoid` (the full continuum Lorentz group `SO⁺(1,9)`, N132) has a UNIT-normalized
    covering unit `u ∈ PinUnitSub`. Combines `cover_global_reflection_word_pinUnit` with N132's
    classification `reflection_closure_eq_bvIsomLinMonoid`. -/
theorem cover_global_bvIsom_pinUnit {g : Module.End Cut STVC}
    (hg : g ∈ bvIsomLinMonoid) :
    ∃ u : CliffCˣ, u ∈ PinUnitSub ∧ CliffCovers u g := by
  apply cover_global_reflection_word_pinUnit
  rw [reflection_closure_eq_bvIsomLinMonoid]
  exact hg

/-- ★★★ THE SURJECTIVITY of the UNIT-normalized Pin double cover `coverMapPinUnit ↠ SO⁺(1,9)`:
    `coverMapPinUnit` is ONTO the continuum Lorentz group `bvIsomLinMonoid`. With N150's exact
    kernel `{1,-1}` this completes the double-cover picture: `Pin(1,9) ↠ SO⁺(1,9)` is a surjective
    two-to-one group homomorphism, DERIVED forward (no posited Pin/Spin group, no posited cover,
    no posited surjectivity). -/
theorem coverMapPinUnit_surjective : Function.Surjective coverMapPinUnit := by
  rintro ⟨g, hg⟩
  obtain ⟨u, hu, hcov⟩ := cover_global_bvIsom_pinUnit hg
  refine ⟨⟨u, hu⟩, ?_⟩
  apply Subtype.ext
  rw [coverMapPinUnit_coe]
  exact cliffCovers_unique (coverOp_covers ⟨u, pinUnitSub_le_coversSub hu⟩) hcov

/-! ## W8 teeth — a concrete boost is the image of a UNIT-normalized Pin element. -/

/-- ★ W8 NON-VACUITY — the CONCRETE boost `(5/3,4/3)` (a genuine non-identity Lorentz element,
    off-diagonal `4/3 ≠ 0`) is the IMAGE under `coverMapPinUnit` of a UNIT-normalized Pin element.
    The surjectivity realized on a real boost: `boostEndC (5/3) (4/3)` is a `BvC`-isometry, hence
    has a UNIT-normalized covering unit `u ∈ PinUnitSub` with `coverMapPinUnit u = boostEndC ..`. -/
theorem coverMapPinUnit_boost_apply :
    ∃ u : PinUnitSub,
      (coverMapPinUnit u : Module.End Cut STVC) = boostEndC ((5:Cut)/3) ((4:Cut)/3) := by
  have hab : ((5:Cut)/3) ^ 2 - ((4:Cut)/3) ^ 2 = 1 := by ring
  have hg : boostEndC ((5:Cut)/3) ((4:Cut)/3) ∈ bvIsomLinMonoid := boostEndC_isBvIsomLin hab
  obtain ⟨u, hu, hcov⟩ := cover_global_bvIsom_pinUnit hg
  refine ⟨⟨u, hu⟩, ?_⟩
  rw [coverMapPinUnit_coe]
  exact cliffCovers_unique (coverOp_covers ⟨u, pinUnitSub_le_coversSub hu⟩) hcov

end

end Phys.Algebra
