/-
  # N178 — THE ABSTRACT GROUP OBJECT of the gauge Klein four-group `kleinFour` (N141):
  #         `kleinFour ≅ ℤ/2 × ℤ/2` as an abstract group, over the DERIVED ℝ `ContinuumQ.Cut`.

  N141 (`Phys/Algebra/LorentzContinuumOctStabilizerG2KleinFour.lean`) banked the CONCRETE
  4-element subgroup `kleinFour : Subgroup (O Cut ≃ₗ[Cut] O Cut)` — the carrier
  `{1, octTopNeg, octInnerNeg, octCompNeg}` of three concrete octonion algebra-automorphisms
  (members of G₂ = Aut(O)) plus the identity — together with its generation
  `kleinFour_eq_closure` and the elementary fact that every element squares to `1`
  (`kleinFour_elem_involution`). N141 NEVER computed the CARDINALITY, NEVER the EXPONENT,
  NEVER the abstract group-object class, and NEVER the isomorphism to the canonical
  `ℤ/2 × ℤ/2`. Those are the genuinely-unbanked ABSTRACT GROUP-OBJECT structure: the
  classification statement "this concrete subgroup of the automorphism group of the terminal
  algebra IS, as an abstract group, the Klein four-group `ℤ/2 × ℤ/2`."

  THIS file banks that abstract group object:

    1. `kleinFour_natCard_eq_four` — `Nat.card ↥kleinFour = 4` (the four concrete elements are
       pairwise distinct: the banked distinctness facts `octCompNeg_ne_octInnerNeg`,
       `octInnerNeg_ne_octTopNeg`, `octCompNeg_ne_octTopNeg` plus `1 ≠ each`).
    2. `kleinFour_monoidExponent_eq_two` — `Monoid.exponent ↥kleinFour = 2` (the exponent
       divides `2` because every element squares to `1` via `kleinFour_elem_involution`, and is
       not `1` because `octTopNeg ≠ 1`).
    3. `kleinFour_isKleinFour` — the abstract group-object class `IsKleinFour ↥kleinFour`
       (cardinality 4 + exponent 2), assembled from (1) and (2).
    4. `kleinFour_not_isCyclic` — the structural fingerprint distinguishing `ℤ/2 × ℤ/2` from the
       OTHER order-4 group `ℤ/4`: the Klein four-group is NOT cyclic.
    5. `kleinFour_mulEquiv_zmod2sq_nonempty` — the ABSTRACT ISO:
       `Nonempty (↥kleinFour ≃* Multiplicative (ZMod 2 × ZMod 2))` — the concrete gauge
       subgroup is, as an abstract group, exactly `ℤ/2 × ℤ/2`.

  THE ONE LAW / W1 REFRAME — no analysis, all levers banked. The cardinality is the `ncard` of
  the explicit 4-element carrier (`Set.ncard_insert_of_notMem` ×3 + `Set.ncard_singleton`),
  closed entirely by the banked pairwise-distinctness facts of N139/N140/N141. The exponent is
  `Monoid.exponent_dvd_of_forall_pow_eq_one` fed by the banked involution fact, pinned to `2`
  (not `1`) by one banked non-identity element. The abstract iso is Mathlib's
  `IsKleinFour.nonempty_mulEquiv` (any two Klein four-groups are isomorphic) applied to the
  derived group object and the canonical `ZMod 2 × ZMod 2`. The Mathlib Klein-four / `ZMod 2`
  machinery operates on the DERIVED group object `↥kleinFour`; it is NOT content (no Mathlib ℝ/ℂ
  as content, no posited group / topology / `π₀`).

  ## PHYSICS-WORDS-REMOVABLE (docs/STANDARD.md §2)
  Delete every physics word (gauge / automorphism / G₂ / Aut(O) / component / Klein / parity /
  symmetry): the statements stand as pure group theory over the derived ℝ `Cut` and the terminal
  algebra `O Cut`. For the explicit 4-element subgroup `kleinFour` of the `Cut`-linear
  automorphism group `O Cut ≃ₗ[Cut] O Cut`, generated by the two banked involutions
  `{octTopNeg, octInnerNeg}`: its cardinality is `4`, its exponent is `2`, it satisfies the
  abstract mixin `IsKleinFour`, it is not cyclic, and it is abstractly isomorphic (`≃*`) to
  `Multiplicative (ZMod 2 × ZMod 2)`. Every step is a theorem; the names carry no logical weight.
-/
import Phys.Algebra.LorentzContinuumOctStabilizerG2KleinFour
import Mathlib.GroupTheory.SpecificGroups.KleinFour

namespace Phys.Algebra

open Phys.Cascade Phys.Cascade.CD
open Phys.Foundation Phys.Foundation.ContinuumQ

attribute [local instance] CD.narCD CD.srCD

noncomputable section

/-! ## A — the identity is distinct from each of the three concrete automorphisms.
    (`1 = LinearEquiv.refl` and the banked `_ne_refl` facts of N139/N140/N141.) -/

/-- `1 ≠ octTopNeg` (the identity is not the top-half negation; `octTopNeg` moves `e₂`). -/
theorem kleinFour_one_ne_octTopNeg : (1 : O Cut ≃ₗ[Cut] O Cut) ≠ octTopNeg := by
  rw [LinearEquiv.one_eq_refl]; exact fun h => octTopNeg_ne_refl h.symm

/-- `1 ≠ octInnerNeg` (the identity is not the inner negation; `octInnerNeg` moves `innerGen`). -/
theorem kleinFour_one_ne_octInnerNeg : (1 : O Cut ≃ₗ[Cut] O Cut) ≠ octInnerNeg := by
  rw [LinearEquiv.one_eq_refl]; exact fun h => octInnerNeg_ne_refl h.symm

/-- `1 ≠ octCompNeg` (the identity is not the composite negation; `octCompNeg` moves `e₂`). -/
theorem kleinFour_one_ne_octCompNeg : (1 : O Cut ≃ₗ[Cut] O Cut) ≠ octCompNeg := by
  rw [LinearEquiv.one_eq_refl]; exact fun h => octCompNeg_ne_refl h.symm

/-! ## B — the cardinality of the abstract group object. -/

/-- ★ `Nat.card ↥kleinFour = 4` — the four concrete elements `{1, octTopNeg, octInnerNeg,
    octCompNeg}` are pairwise distinct, so the order of the abstract group is exactly `4`. -/
theorem kleinFour_natCard_eq_four : Nat.card ↥kleinFour = 4 := by
  show Nat.card (kleinFour : Set (O Cut ≃ₗ[Cut] O Cut)) = 4
  rw [Nat.card_coe_set_eq]
  show ({1, octTopNeg, octInnerNeg, octCompNeg} : Set (O Cut ≃ₗ[Cut] O Cut)).ncard = 4
  rw [Set.ncard_insert_of_notMem, Set.ncard_insert_of_notMem,
      Set.ncard_insert_of_notMem, Set.ncard_singleton]
  · simp only [Set.mem_singleton_iff]; exact octCompNeg_ne_octInnerNeg.symm
  · simp only [Set.mem_insert_iff, Set.mem_singleton_iff, not_or]
    exact ⟨octInnerNeg_ne_octTopNeg.symm, octCompNeg_ne_octTopNeg.symm⟩
  · simp only [Set.mem_insert_iff, Set.mem_singleton_iff, not_or]
    exact ⟨kleinFour_one_ne_octTopNeg, kleinFour_one_ne_octInnerNeg, kleinFour_one_ne_octCompNeg⟩

/-! ## C — the exponent of the abstract group object. -/

/-- ★ `Monoid.exponent ↥kleinFour = 2` — the exponent divides `2` (every element squares to `1`,
    `kleinFour_elem_involution`) and is not `1` (the non-identity element `octTopNeg ≠ 1`). The
    elementary abelian 2-group fingerprint. -/
theorem kleinFour_monoidExponent_eq_two : Monoid.exponent ↥kleinFour = 2 := by
  have htop : octTopNeg ∈ kleinFour := by simp only [kleinFour, Subgroup.mem_mk]; tauto
  have hdvd : Monoid.exponent ↥kleinFour ∣ 2 := by
    apply Monoid.exponent_dvd_of_forall_pow_eq_one
    intro g
    apply Subtype.ext
    rw [pow_two]
    exact kleinFour_elem_involution g.1 g.2
  rcases (Nat.dvd_prime Nat.prime_two).mp hdvd with h1 | h2
  · exfalso
    have hg : (⟨octTopNeg, htop⟩ : ↥kleinFour) ^ Monoid.exponent ↥kleinFour = 1 :=
      Monoid.pow_exponent_eq_one _
    rw [h1, pow_one] at hg
    exact kleinFour_one_ne_octTopNeg (congrArg Subtype.val hg).symm
  · exact h2

/-! ## D — the abstract group object and the isomorphism to `ℤ/2 × ℤ/2`. -/

/-- ★★ THE ABSTRACT GROUP OBJECT: the concrete gauge subgroup `kleinFour` satisfies the abstract
    Klein-four mixin `IsKleinFour` (cardinality 4 + exponent 2). The classification statement that
    the concrete subgroup of `Aut(O)` IS the abstract Klein four-group. -/
instance kleinFour_isKleinFour : IsKleinFour ↥kleinFour where
  card_four := kleinFour_natCard_eq_four
  exponent_two := kleinFour_monoidExponent_eq_two

/-- ★ NOT CYCLIC — the structural fingerprint distinguishing `ℤ/2 × ℤ/2` from the only OTHER
    order-4 group `ℤ/4`. Together with order 4, this pins the abstract type. -/
theorem kleinFour_not_isCyclic : ¬ IsCyclic ↥kleinFour :=
  IsKleinFour.not_isCyclic

/-- ★★ THE ABSTRACT ISO: the concrete gauge subgroup `kleinFour` is, as an abstract group, exactly
    `ℤ/2 × ℤ/2` (`Multiplicative (ZMod 2 × ZMod 2)`). Any two Klein four-groups are isomorphic
    (`IsKleinFour.nonempty_mulEquiv`), and `ZMod 2 × ZMod 2` is the canonical one. -/
theorem kleinFour_mulEquiv_zmod2sq_nonempty :
    Nonempty (↥kleinFour ≃* Multiplicative (ZMod 2 × ZMod 2)) :=
  IsKleinFour.nonempty_mulEquiv

end

end Phys.Algebra
