/-
  # N179 — THE ABSTRACT GROUP OBJECT of the `O(1,9)` DISCRETE COMPONENT GROUP
  #         (the `π₀(O(1,9)) = 4` statement) over the DERIVED ℝ `ContinuumQ.Cut`.

  N173 (`Phys/Algebra/LorentzContinuumFullO19.lean`) banked the three discrete sign-flip
  reflections `parityLin`, `timeRevLin`, `ptLin` as elements of the MONOID
  `Module.End Cut STVC` (`STVC = Cut × Cut × O Cut`), together with the Klein-four relations
  (`parityLin_sq`/`timeRevLin_sq`/`ptLin_sq`: each squares to `1`; `parity_timeRev_comm`:
  they commute; `ptLin_eq`: `ptLin = parityLin * timeRevLin`) and the pairwise distinctness
  (`fullO19_components_distinct`), and the full component reduction
  `joinedIdQvC_discreteReduce` (every `QvC`-isometry of the indefinite Born form with
  `det = ±1` is moved into the identity component by one of the four). But N173 NEVER formed
  a GROUP from them, NEVER computed the cardinality, exponent, abstract group-object class,
  or the isomorphism to the canonical `ℤ/2 × ℤ/2`. Those are the genuinely-unbanked ABSTRACT
  GROUP OBJECT of the discrete component group of the full indefinite orthogonal group — the
  `π₀(O(1,9)) = 4` classification statement, a DIFFERENT object from the gauge G₂ Klein-four
  `kleinFour` (N178), which lives inside `Aut(O) = G₂ ⊂ O(8)`.

  ── THE LIFT (the only genuinely-new step vs N178) ──
  The reflections live in the monoid `Module.End Cut STVC`, not a group. Each squares to `1`
  (`parityLin_sq` etc.), so each is a UNIT: `Units.mk R R R_sq R_sq : (Module.End Cut STVC)ˣ`.
  This file lifts the three reflections to units `parityUnit`/`timeRevUnit`/`ptUnit`, forms
  the explicit 4-element subgroup `o19Comp : Subgroup (Module.End Cut STVC)ˣ`, and then reuses
  the EXACT N178 pattern on this NEW group:

    1. `o19Comp_natCard_eq_four` — `Nat.card ↥o19Comp = 4` (the four units are pairwise
       distinct, lifted from `fullO19_components_distinct`).
    2. `o19Comp_monoidExponent_eq_two` — `Monoid.exponent ↥o19Comp = 2` (each squares to `1`,
       and `parityUnit ≠ 1`).
    3. `o19Comp_isKleinFour` — the abstract group-object class `IsKleinFour ↥o19Comp`.
    4. `o19Comp_not_isCyclic` — the fingerprint distinguishing `ℤ/2 × ℤ/2` from `ℤ/4`.
    5. `o19Comp_mulEquiv_zmod2sq_nonempty` — the ABSTRACT ISO:
       `Nonempty (↥o19Comp ≃* Multiplicative (ZMod 2 × ZMod 2))`.

  THE ONE LAW / W1 REFRAME — no analysis, all levers banked. The unit lift is the structure
  constructor `Units.mk` fed the banked involution facts; the Klein table on units transports
  from the `Module.End`-level relations via `Units.ext`; the order is the `ncard` of the
  4-element carrier closed by the banked `fullO19_components_distinct`; the exponent is the
  banked involution via `Monoid.exponent_dvd_of_forall_pow_eq_one`; the iso is Mathlib's
  `IsKleinFour.nonempty_mulEquiv`. The Mathlib Klein-four / `ZMod 2` machinery operates on the
  DERIVED group object `↥o19Comp`; it is NOT content (no Mathlib ℝ/ℂ as content, no posited
  component group / topology / `π₀` / orthogonal group).

  ## PHYSICS-WORDS-REMOVABLE (docs/STANDARD.md §2)
  Delete every physics word (parity / time-reversal / Lorentz / O(1,9) / component / `π₀` /
  reflection / spacetime / orthogonal): the statements stand as pure group theory over the
  derived ℝ `Cut`. For the explicit 4-element subgroup `o19Comp` of the unit group
  `(Module.End Cut STVC)ˣ` of `Cut`-linear endomorphisms of `Cut × Cut × O Cut`, generated by
  the two involutive units `{parityUnit, timeRevUnit}`: its cardinality is `4`, its exponent
  is `2`, it satisfies `IsKleinFour`, it is not cyclic, and it is abstractly isomorphic (`≃*`)
  to `Multiplicative (ZMod 2 × ZMod 2)`. Every step is a theorem; the names carry no logical
  weight.
-/
import Phys.Algebra.LorentzContinuumFullO19
import Mathlib.GroupTheory.SpecificGroups.KleinFour

namespace Phys.Algebra

open Phys.Cascade Phys.Cascade.CD
open Phys.Foundation Phys.Foundation.ContinuumQ

attribute [local instance] CD.narCD CD.srCD
attribute [local instance] Phys.Algebra.dblModuleCut

noncomputable section

/-! ## A — the unit lift: each involutive reflection is a unit of `Module.End Cut STVC`. -/

/-- The spatial sign flip lifted to a unit (self-inverse: `parityLin * parityLin = 1`). -/
def parityUnit : (Module.End Cut STVC)ˣ :=
  ⟨parityLin, parityLin, parityLin_sq, parityLin_sq⟩

/-- The time sign flip lifted to a unit (self-inverse: `timeRevLin * timeRevLin = 1`). -/
def timeRevUnit : (Module.End Cut STVC)ˣ :=
  ⟨timeRevLin, timeRevLin, timeRevLin_sq, timeRevLin_sq⟩

/-- The total sign flip lifted to a unit (self-inverse: `ptLin * ptLin = 1`). -/
def ptUnit : (Module.End Cut STVC)ˣ :=
  ⟨ptLin, ptLin, ptLin_sq, ptLin_sq⟩

@[simp] theorem parityUnit_val : (parityUnit : Module.End Cut STVC) = parityLin := rfl
@[simp] theorem timeRevUnit_val : (timeRevUnit : Module.End Cut STVC) = timeRevLin := rfl
@[simp] theorem ptUnit_val : (ptUnit : Module.End Cut STVC) = ptLin := rfl

/-! ## B — the Klein-four multiplication table on the lifted units (via `Units.ext`). -/

/-- `parityUnit² = 1`. -/
theorem parityUnit_sq : parityUnit * parityUnit = 1 :=
  Units.ext (by show parityLin * parityLin = 1; exact parityLin_sq)

/-- `timeRevUnit² = 1`. -/
theorem timeRevUnit_sq : timeRevUnit * timeRevUnit = 1 :=
  Units.ext (by show timeRevLin * timeRevLin = 1; exact timeRevLin_sq)

/-- `ptUnit² = 1`. -/
theorem ptUnit_sq : ptUnit * ptUnit = 1 :=
  Units.ext (by show ptLin * ptLin = 1; exact ptLin_sq)

/-- `parityUnit · timeRevUnit = ptUnit`. -/
theorem parityUnit_mul_timeRevUnit : parityUnit * timeRevUnit = ptUnit :=
  Units.ext (by show parityLin * timeRevLin = ptLin; exact ptLin_eq.symm)

/-- `timeRevUnit · parityUnit = ptUnit` (they commute). -/
theorem timeRevUnit_mul_parityUnit : timeRevUnit * parityUnit = ptUnit :=
  Units.ext (by
    show timeRevLin * parityLin = ptLin
    rw [← parity_timeRev_comm, ← ptLin_eq])

/-- `parityUnit · ptUnit = timeRevUnit`. -/
theorem parityUnit_mul_ptUnit : parityUnit * ptUnit = timeRevUnit :=
  Units.ext (by
    show parityLin * ptLin = timeRevLin
    rw [ptLin_eq, ← mul_assoc, parityLin_sq, one_mul])

/-- `ptUnit · parityUnit = timeRevUnit`. -/
theorem ptUnit_mul_parityUnit : ptUnit * parityUnit = timeRevUnit :=
  Units.ext (by
    show ptLin * parityLin = timeRevLin
    rw [ptLin_eq, mul_assoc, ← parity_timeRev_comm, ← mul_assoc, parityLin_sq, one_mul])

/-- `timeRevUnit · ptUnit = parityUnit`. -/
theorem timeRevUnit_mul_ptUnit : timeRevUnit * ptUnit = parityUnit :=
  Units.ext (by
    show timeRevLin * ptLin = parityLin
    rw [ptLin_eq, parity_timeRev_comm, ← mul_assoc, timeRevLin_sq, one_mul])

/-- `ptUnit · timeRevUnit = parityUnit`. -/
theorem ptUnit_mul_timeRevUnit : ptUnit * timeRevUnit = parityUnit :=
  Units.ext (by
    show ptLin * timeRevLin = parityLin
    rw [ptLin_eq, mul_assoc, timeRevLin_sq, mul_one])

/-! ## C — pairwise distinctness of the four lifted units (from `fullO19_components_distinct`). -/

theorem o19_one_ne_parityUnit : (1 : (Module.End Cut STVC)ˣ) ≠ parityUnit :=
  fun h => fullO19_components_distinct.1 (congrArg Units.val h).symm

theorem o19_one_ne_timeRevUnit : (1 : (Module.End Cut STVC)ˣ) ≠ timeRevUnit :=
  fun h => fullO19_components_distinct.2.1 (congrArg Units.val h).symm

theorem o19_one_ne_ptUnit : (1 : (Module.End Cut STVC)ˣ) ≠ ptUnit :=
  fun h => fullO19_components_distinct.2.2.1 (congrArg Units.val h).symm

theorem o19_parityUnit_ne_timeRevUnit : parityUnit ≠ timeRevUnit :=
  fun h => fullO19_components_distinct.2.2.2.1 (congrArg Units.val h)

theorem o19_parityUnit_ne_ptUnit : parityUnit ≠ ptUnit :=
  fun h => fullO19_components_distinct.2.2.2.2.1 (congrArg Units.val h)

theorem o19_timeRevUnit_ne_ptUnit : timeRevUnit ≠ ptUnit :=
  fun h => fullO19_components_distinct.2.2.2.2.2 (congrArg Units.val h)

/-! ## D — the explicit 4-element subgroup of the unit group. -/

/-- ★★ THE EXPLICIT SUBGROUP: the 4-element carrier `{1, parityUnit, timeRevUnit, ptUnit}` is a
    `Subgroup` of the unit group `(Module.End Cut STVC)ˣ` — the discrete component group of the
    full indefinite orthogonal group `O(1,9)`. Closed under `*` (the Klein-four table) and
    inverse (each element is self-inverse). -/
def o19Comp : Subgroup (Module.End Cut STVC)ˣ where
  carrier := {1, parityUnit, timeRevUnit, ptUnit}
  one_mem' := by left; rfl
  mul_mem' := by
    intro a b ha hb
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at ha hb ⊢
    rcases ha with rfl | rfl | rfl | rfl <;> rcases hb with rfl | rfl | rfl | rfl <;>
      simp only [one_mul, mul_one, parityUnit_sq, timeRevUnit_sq, ptUnit_sq,
        parityUnit_mul_timeRevUnit, timeRevUnit_mul_parityUnit, parityUnit_mul_ptUnit,
        ptUnit_mul_parityUnit, timeRevUnit_mul_ptUnit, ptUnit_mul_timeRevUnit] <;>
      tauto
  inv_mem' := by
    intro a ha
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at ha ⊢
    rcases ha with rfl | rfl | rfl | rfl <;>
      simp only [inv_one, ← mul_eq_one_iff_inv_eq,
        parityUnit_sq, timeRevUnit_sq, ptUnit_sq] <;> tauto

/-- ★ `o19Comp` is GENERATED by the two involutive units `{parityUnit, timeRevUnit}` — the
    discrete component group is the subgroup closure of the parity and time-reversal lifts. -/
theorem o19Comp_eq_closure :
    o19Comp = Subgroup.closure {parityUnit, timeRevUnit} := by
  apply le_antisymm
  · intro x hx
    simp only [o19Comp, Subgroup.mem_mk] at hx
    rcases hx with rfl | rfl | rfl | rfl
    · exact one_mem _
    · exact Subgroup.subset_closure (by left; rfl)
    · exact Subgroup.subset_closure (by right; rfl)
    · rw [← parityUnit_mul_timeRevUnit]
      exact mul_mem (Subgroup.subset_closure (by left; rfl))
        (Subgroup.subset_closure (by right; rfl))
  · rw [Subgroup.closure_le]
    intro x hx
    rcases hx with rfl | rfl
    · show parityUnit ∈ o19Comp
      simp only [o19Comp, Subgroup.mem_mk]; tauto
    · show timeRevUnit ∈ o19Comp
      simp only [o19Comp, Subgroup.mem_mk]; tauto

/-- ★ EVERY element of `o19Comp` squares to `1` — the elementary abelian 2-group fingerprint. -/
theorem o19Comp_elem_involution (x : (Module.End Cut STVC)ˣ) (hx : x ∈ o19Comp) :
    x * x = 1 := by
  simp only [o19Comp, Subgroup.mem_mk] at hx
  rcases hx with rfl | rfl | rfl | rfl
  · rw [one_mul]
  · exact parityUnit_sq
  · exact timeRevUnit_sq
  · exact ptUnit_sq

/-! ## E — the cardinality of the abstract group object. -/

/-- ★ `Nat.card ↥o19Comp = 4` — the four lifted units `{1, parityUnit, timeRevUnit, ptUnit}` are
    pairwise distinct, so the order of the discrete component group is exactly `4`. -/
theorem o19Comp_natCard_eq_four : Nat.card ↥o19Comp = 4 := by
  show Nat.card (o19Comp : Set (Module.End Cut STVC)ˣ) = 4
  rw [Nat.card_coe_set_eq]
  show ({1, parityUnit, timeRevUnit, ptUnit} : Set (Module.End Cut STVC)ˣ).ncard = 4
  rw [Set.ncard_insert_of_notMem, Set.ncard_insert_of_notMem,
      Set.ncard_insert_of_notMem, Set.ncard_singleton]
  · simp only [Set.mem_singleton_iff]; exact o19_timeRevUnit_ne_ptUnit
  · simp only [Set.mem_insert_iff, Set.mem_singleton_iff, not_or]
    exact ⟨o19_parityUnit_ne_timeRevUnit, o19_parityUnit_ne_ptUnit⟩
  · simp only [Set.mem_insert_iff, Set.mem_singleton_iff, not_or]
    exact ⟨o19_one_ne_parityUnit, o19_one_ne_timeRevUnit, o19_one_ne_ptUnit⟩

/-! ## F — the exponent of the abstract group object. -/

/-- ★ `Monoid.exponent ↥o19Comp = 2` — the exponent divides `2` (every element squares to `1`,
    `o19Comp_elem_involution`) and is not `1` (the non-identity element `parityUnit ≠ 1`). -/
theorem o19Comp_monoidExponent_eq_two : Monoid.exponent ↥o19Comp = 2 := by
  have hpar : parityUnit ∈ o19Comp := by simp only [o19Comp, Subgroup.mem_mk]; tauto
  have hdvd : Monoid.exponent ↥o19Comp ∣ 2 := by
    apply Monoid.exponent_dvd_of_forall_pow_eq_one
    intro g
    apply Subtype.ext
    rw [pow_two]
    exact o19Comp_elem_involution g.1 g.2
  rcases (Nat.dvd_prime Nat.prime_two).mp hdvd with h1 | h2
  · exfalso
    have hg : (⟨parityUnit, hpar⟩ : ↥o19Comp) ^ Monoid.exponent ↥o19Comp = 1 :=
      Monoid.pow_exponent_eq_one _
    rw [h1, pow_one] at hg
    exact o19_one_ne_parityUnit (congrArg Subtype.val hg).symm
  · exact h2

/-! ## G — the abstract group object and the isomorphism to `ℤ/2 × ℤ/2`. -/

/-- ★★ THE ABSTRACT GROUP OBJECT: the discrete component group `o19Comp` of the full indefinite
    orthogonal group `O(1,9)` satisfies the abstract Klein-four mixin `IsKleinFour` (cardinality
    4 + exponent 2). The `π₀(O(1,9)) = 4` classification: the component group IS, as an abstract
    group, the Klein four-group. -/
instance o19Comp_isKleinFour : IsKleinFour ↥o19Comp where
  card_four := o19Comp_natCard_eq_four
  exponent_two := o19Comp_monoidExponent_eq_two

/-- ★ NOT CYCLIC — the fingerprint distinguishing `ℤ/2 × ℤ/2` from the only OTHER order-4 group
    `ℤ/4`. Together with order 4, this pins the abstract type. -/
theorem o19Comp_not_isCyclic : ¬ IsCyclic ↥o19Comp :=
  IsKleinFour.not_isCyclic

/-- ★★ THE ABSTRACT ISO: the discrete component group `o19Comp` of `O(1,9)` is, as an abstract
    group, exactly `ℤ/2 × ℤ/2` (`Multiplicative (ZMod 2 × ZMod 2)`). Any two Klein four-groups
    are isomorphic (`IsKleinFour.nonempty_mulEquiv`), and `ZMod 2 × ZMod 2` is the canonical one.
    This is the `π₀(O(1,9)) ≅ ℤ/2 × ℤ/2` statement. -/
theorem o19Comp_mulEquiv_zmod2sq_nonempty :
    Nonempty (↥o19Comp ≃* Multiplicative (ZMod 2 × ZMod 2)) :=
  IsKleinFour.nonempty_mulEquiv

end

end Phys.Algebra
