/-
  Phys.Algebra.LorentzContinuumGeneratedGroup — N54: THE GENERATED ISOMETRY SUBMONOID + the
  FORWARD half of the finite-product surjectivity (Cartan/polar KAK), over the DERIVED ℝ `Cut`.
  ===========================================================================
  THE NEXT FORCED NODE after the rotation-one-parameter-subgroup node (N53). N49–N53 banked BOTH
  one-parameter generator families over the derived ℝ `Cut`:
    • the BOOST one-parameter subgroup `boostOPS ≤ qvIsomMonoidC` (N52, the abelian HYPERBOLA group
      `(a,b)·(a',b') = (a a'+b b', a b'+b a')`, the exp-integration of the N51 infinitesimal boost
      generator — a finite hyperbola-parametrized polynomial, NO transcendental rapidity);
    • the ROTATION one-parameter subgroup `rotCircOPS a halt ≤ qvIsomMonoidC` (N53, the abelian
      CIRCLE group `(c,s)·(c',s') = (c c'−s s', c s'+s c')` around a fixed imaginary Born-unit `a`,
      the non-associativity DISSOLVED on the single-unit alternative subalgebra via the banked
      left-alternative operator-square law `a·(a·v)=−v`, NO transcendental angle).

  This node assembles the two families into the GENERATED isometry submonoid and proves the FORWARD
  half of the Cartan/polar KAK finite-product surjectivity onto the connected component:

    ── THE FORWARD SOUNDNESS (THIS NODE, fully proved) ──
    Let `genIsomMonoidC := ⟨boostOPS ∪ {all rotations around imaginary Born-units}⟩` be the
    submonoid of `Function.End STVC` GENERATED by both one-parameter generator families. Then

        genIsomMonoidC ≤ qvIsomMonoidC                                  [genIsomMonoidC_le_isom]

    — EVERY finite product of boosts and rotations is a continuum Born-form `QvC`-isometry. This is
    the "every word in the generators is an isometry" half of the KAK decomposition `g = k·exp(p)`:
    the boost part `exp(p)` (the positive-definite factor) and the compact rotation part `k` BOTH
    land in the isometry monoid, hence so does every finite product. It follows STRUCTURALLY from
    the banked exp-integration lemmas `boostOPS_le_isom` (N52) + `rotCircFun_mem` (N53) via
    `Submonoid.closure_le` — NO coordinate grind, NO analysis, NO topology.

    ── THE STRICT EXTENSION / NON-VACUITY (THIS NODE, W8) ──
    The generated group is GENUINELY larger than either one-parameter subgroup alone:

        boostOPS < genIsomMonoidC                                        [boostOPS_lt_gen]

    — the quarter-turn rotation around `e₂` lies in `genIsomMonoidC` but is NOT a boost (it moves
    the nine-dimensional space block `v`, which every boost fixes), and conversely the irrational
    continuum boost lies in `genIsomMonoidC` but is NOT a rotation around any imaginary unit (it
    moves the time–space `(t,x)` block, which every rotation fixes). So `genIsomMonoidC` is a
    genuine two-block group, not a trivial relabelling of one family.

  ── THE W1 HEAVY REMAINDER (childed N55, an honest dissolution ticket, NOT closed here) ──
  The REVERSE direction — that EVERY orientation/time-preserving continuum isometry of `QvC` IS
  such a finite product (`qvIsomMonoidC` restricted to the connected component `≤ genIsomMonoidC`)
  — is the genuine HEAVY core: the polar/KAK decomposition `g = k·exp(p)` requires the square root
  of a positive-definite operator over the derived `Cut` (to extract `exp(p)`), connectedness, and
  the full non-associative `SO(9)`/`Spin(9)` spacelike rotation completion (rotations in ARBITRARY
  planes, where two single-unit rotations around NON-associating units `u,u'` do not compose into a
  single-unit rotation — the Moufang/paired-product structure, the `2:1` cover `Spin(9)→SO(9)`).
  Mathlib has NO `SO⁺(1,9)`, no octonionic spinor cover, no Lie-group integration over `Cut`. It is
  to be attacked from the BORN POSITIVITY (the self-overlap form / `BvC` polarization, the trunk: a
  form-isometry's "boost part" is the positive-definite factor of its polar decomposition, and
  positivity is exactly what the Born self-overlap supplies) rather than a coordinate KAK grind —
  the surjectivity may DISSOLVE through the positivity structure. This is the W1 dissolution
  remainder, childed onto the chain tail.

  WHAT IS PROVED (each a theorem, foundations-only, forward from the banked objects):
    rotGenSetC            — the rotation generator SET: every circle rotation `rotCircFun a c s`
                            around an imaginary Born-unit `a` (`gFormC 1 a = 0`, `gFormC a a = 1`)
                            on the unit circle (`c²+s²=1`). The union of all single-unit rotation
                            one-parameter subgroups — the compact generator family in full.
    genIsomMonoidC        — ★ THE GENERATED ISOMETRY SUBMONOID: the closure of `boostOPS ∪ rotGenSetC`
                            in `Function.End STVC`. The group of all finite products of boosts and
                            rotations — the algebraic span of both one-parameter generator families.
    boostOPS_le_gen       — the boost one-parameter subgroup embeds in the generated group.
    rotGenSetC_subset_gen — every single-unit rotation embeds in the generated group.
    rotGenSetC_le_isom    — every rotation generator is a continuum `QvC`-isometry (N53).
    genIsomMonoidC_le_isom— ★★ THE FORWARD SOUNDNESS: `genIsomMonoidC ≤ qvIsomMonoidC`. Every finite
                            product of boosts and rotations preserves the continuum Born form `QvC`.
                            The "every word is an isometry" half of the KAK surjectivity.
    boostOPS_lt_gen       — ★ THE STRICT EXTENSION (W8): `boostOPS < genIsomMonoidC` — the generated
                            group strictly contains the boost subgroup (the rotation around `e₂` is a
                            non-boost member). With `irrBoost_not_rotGen`, both families are proper.
    quarterTurn_e2_* / irrBoost_* — the concrete non-vacuity witnesses over the derived ℝ.

  THE MOAT — posit-vs-derive (docs/STANDARD.md §0). That the connected Lorentz group is generated
  by boosts and rotations is standard. Here the generated group, and the forward soundness that
  every finite product of the two one-parameter generator families preserves the Born form, DESCEND
  from the banked exp-integration inclusions `boostOPS_le_isom` (N52) + `rotCircFun_mem` (N53) — the
  integrated tangents of the N51 infinitesimal generators — over the DERIVED ℝ `Cut` and the
  terminal algebra `O Cut`, NOT a posited Lorentz group / `SO⁺(1,9)`, NOT Mathlib ℝ/ℂ as content,
  NOT a bridge. The strict extension proves the assembly is non-vacuous: a genuine two-block group.

  PHYSICS-WORDS-REMOVABLE (docs/STANDARD.md §2). Delete "Lorentz / boost / rotation / Spin /
  SO⁺(1,9) / SO(9) / isometry / generator / one-parameter / KAK / Cartan / finite-product /
  surjectivity": what remains is the theorem that, over the derived complete ordered field `Cut`
  and the Cayley–Dickson double³ `O Cut`, the submonoid of `Function.End (Cut × Cut × O Cut)`
  generated by `{(t,x,v) ↦ (a t+b x, b t+a x, v) | a²−b²=1} ∪ {(t,x,v) ↦ (t,x, c•v+s•(a·v)) |
  a·(a·v)=−v, gFormC 1 a=0, gFormC a a=1, c²+s²=1}` is contained in the submonoid preserving
  `t²−x²−gFormC v v`, and strictly contains members of each generating family not in the other.
  No theorem STATEMENT needs a physics word.

  Foundations-only: no posited axiom, no sorry, no kernel-trust bypass, no bridge, NO Mathlib
  number-system content import (the continuum is the DERIVED `Cut`), NO posited Lorentz group.
-/
import Phys.Algebra.LorentzContinuumExpIntegration
import Phys.Algebra.LorentzContinuumRotationSubgroup

namespace Phys.Algebra

open Phys.Cascade Phys.Cascade.CD
open Phys.Foundation Phys.Foundation.ContinuumQ

attribute [local instance] CD.narCD CD.srCD

noncomputable section

/-! ## The rotation generator set (all single-unit rotations) and the generated submonoid. -/

/-- THE ROTATION GENERATOR SET: every circle rotation `rotCircFun a c s` around an imaginary
    Born-unit `a` (`gFormC 1 a = 0`, `gFormC a a = 1`) on the unit circle (`c²+s²=1`). The union of
    all single-unit rotation one-parameter subgroups (N53) — the compact generator family in full,
    over the derived ℝ. -/
def rotGenSetC : Set (Function.End STVC) :=
  {T | ∃ (a : O Cut) (c s : Cut),
        gFormC (1 : O Cut) a = 0 ∧ gFormC a a = 1 ∧ c^2 + s^2 = 1 ∧
          T = (rotCircFun a c s : Function.End STVC)}

/-- ★ THE GENERATED ISOMETRY SUBMONOID: the closure of `boostOPS ∪ rotGenSetC` in
    `Function.End STVC` — the group of all finite products of the boost one-parameter subgroup and
    the single-unit rotation generators. The algebraic span of both one-parameter generator
    families, the integrated whole whose tangent is the N51 infinitesimal isometry Lie algebra. -/
def genIsomMonoidC : Submonoid (Function.End STVC) :=
  Submonoid.closure ((boostOPS : Set (Function.End STVC)) ∪ rotGenSetC)

/-- The boost one-parameter subgroup embeds in the generated group. -/
theorem boostOPS_le_gen : boostOPS ≤ genIsomMonoidC := by
  intro x hx
  exact Submonoid.subset_closure (Set.mem_union_left _ hx)

/-- Every single-unit rotation embeds in the generated group. -/
theorem rotGenSetC_subset_gen : rotGenSetC ⊆ (genIsomMonoidC : Set (Function.End STVC)) := by
  intro x hx
  exact Submonoid.subset_closure (Set.mem_union_right _ hx)

/-- Every rotation generator is a continuum `QvC`-isometry (the N53 exp-integration `rotCircFun_mem`). -/
theorem rotGenSetC_le_isom : rotGenSetC ⊆ (qvIsomMonoidC : Set (Function.End STVC)) := by
  rintro T ⟨a, c, s, ha1, haa, hcs, rfl⟩
  exact rotCircFun_mem a hcs ha1 haa

/-! ## The forward soundness: every finite product of boosts + rotations is an isometry. -/

/-- ★★ THE FORWARD SOUNDNESS (the "every word is an isometry" half of the KAK finite-product
    surjectivity): `genIsomMonoidC ≤ qvIsomMonoidC`. EVERY finite product of boosts and rotations
    preserves the continuum Born form `QvC`. The KAK factorization `g = k·exp(p)` has BOTH factors
    in the isometry monoid — the boost part `exp(p)` (`boostOPS_le_isom`, N52) and the compact
    rotation part `k` (`rotGenSetC_le_isom`, N53) — so their generated submonoid lies in it. Proved
    STRUCTURALLY by `Submonoid.closure_le`, NO coordinate grind, NO analysis, NO topology. -/
theorem genIsomMonoidC_le_isom : genIsomMonoidC ≤ qvIsomMonoidC := by
  apply Submonoid.closure_le.mpr
  apply Set.union_subset
  · exact fun x hx => boostOPS_le_isom hx
  · exact rotGenSetC_le_isom

/-! ## Strict extension / non-vacuity (W8): the generated group exceeds either family. -/

/-- The quarter-turn `(c,s)=(0,1)` around the terminal imaginary unit `e₂` is a rotation generator. -/
theorem quarterTurn_e2_mem_rotGenSet :
    (rotCircFun (CD.e2 : O Cut) 0 1 : Function.End STVC) ∈ rotGenSetC :=
  ⟨CD.e2, 0, 1, e2_gFormC_one, e2_gFormC_self, by ring, rfl⟩

/-- The quarter-turn around `e₂` lies in the generated group. -/
theorem quarterTurn_e2_mem_gen :
    (rotCircFun (CD.e2 : O Cut) 0 1 : Function.End STVC) ∈ genIsomMonoidC :=
  rotGenSetC_subset_gen quarterTurn_e2_mem_rotGenSet

/-- A rotation around `e₂` is NOT a boost: at input `(0,0,1)` every boost fixes the nine-dimensional
    space block (`→ 1`), while the quarter-turn sends it to `e₂ ≠ 1`. The rotation moves space; the
    boost cannot. -/
theorem quarterTurn_e2_not_boost :
    (rotCircFun (CD.e2 : O Cut) 0 1 : Function.End STVC) ∉ boostOPS := by
  rintro ⟨a, b, hab, heq⟩
  have hev := congrArg (fun T => (T ((0:Cut),(0:Cut),(1:O Cut))).2.2) heq
  simp only [rotCircFun, boostFunC, zero_smul, one_smul, zero_add, mul_one] at hev
  have hne : (CD.e2 : O Cut) ≠ 1 := by
    intro hc2
    have h0 : gFormC (1 : O Cut) (CD.e2 : O Cut) = 0 := e2_gFormC_one
    rw [hc2, gFormC_one] at h0
    exact one_ne_zero h0
  exact hne hev

/-- The irrational continuum boost lies in the generated group. -/
theorem irrBoost_mem_gen :
    (boostFunC ((3 * sqrt2)/4) (sqrt2/4) : Function.End STVC) ∈ genIsomMonoidC :=
  boostOPS_le_gen irrBoost_mem_boostOPS

/-- The irrational boost is NOT a rotation around ANY imaginary unit: every rotation fixes the
    time–space `(t,x)` block, but the boost shifts `x` by `√2/4 ≠ 0` at input `(1,0,0)` (the derived
    √2 is strictly positive, `zero_lt_sqrt2`). The boost moves time–space; no rotation can. -/
theorem irrBoost_not_rotGen :
    (boostFunC ((3 * sqrt2)/4) (sqrt2/4) : Function.End STVC) ∉ rotGenSetC := by
  rintro ⟨a, c, s, -, -, -, heq⟩
  have hev := congrArg (fun T => (T ((1:Cut),(0:Cut),(0:O Cut))).2.1) heq
  simp only [rotCircFun, boostFunC, mul_zero, mul_one, add_zero] at hev
  -- hev : sqrt2/4 = 0
  have hpos : (0 : Cut) < sqrt2 := zero_lt_sqrt2
  have hz : sqrt2 = 0 := by
    have h4 : sqrt2 = (sqrt2 / 4) * 4 := by ring
    rw [h4, hev, zero_mul]
  rw [hz] at hpos; exact lt_irrefl 0 hpos

/-- ★ THE STRICT EXTENSION (W8 non-vacuity): `boostOPS < genIsomMonoidC` — the generated group
    STRICTLY contains the boost one-parameter subgroup, witnessed by the quarter-turn rotation
    around `e₂` (a generated member that is not a boost). Together with `irrBoost_not_rotGen`
    (the boost is not a rotation), both generating families are proper subobjects: the assembly is a
    genuine two-block group, not a trivial relabelling of one one-parameter subgroup. -/
theorem boostOPS_lt_gen : boostOPS < genIsomMonoidC := by
  refine lt_of_le_of_ne boostOPS_le_gen ?_
  intro heq
  have hmem : (rotCircFun (CD.e2 : O Cut) 0 1 : Function.End STVC) ∈ boostOPS := by
    rw [heq]; exact quarterTurn_e2_mem_gen
  exact quarterTurn_e2_not_boost hmem

end

end Phys.Algebra
