import Phys.Algebra.OctonionJordanColourCentralizerCoset
import Phys.Algebra.OctonionJordanColourCentralizerCosetClosure
import Mathlib.Tactic

/-
  Phys.Algebra.OctonionJordanColourFlavourCommutingPair —
  N294: THE DERIVED COLOUR GAUGE AND FAMILY-FLAVOUR su(3) ARE A COMMUTING PAIR IN f₄.

  ------------------------------------------------------------------------------
  THE STORY (theory-native; the ★1↔★4 joint — the capstone of the N287→N293 f₄ sub-arc).

  Inside the single derived `f₄ = Der(H₃(O))` (N285/N286) two derived `su(3)`'s now live:

    • the GAUGE-COLOUR `su(3)` — the entrywise lift `jActL(colourCentralizer)` of the derived
      colour subalgebra `colourCentralizer` = the g₂-stabilizer of the fold's √−1 `JO = L_{u1}`
      (N201), acting on the arena entrywise (N268);
    • the FAMILY-FLAVOUR `su(3)` — the centralizer of colour inside `f₄` (N287, measured), built
      in N288–N293 as the family `so(3)` {famA, famB, famC} (real-unit slots) ⊕ the fold-root-
      dressed coset {kAB, kBC, kCA} (u1-dressed slots), closing to the dim-8 simple `su(3)`.

  THIS node banks the RELATION between them: they COMMUTE, forced by ONE cause.

    ⁅jActL D, famX⁆ = 0   and   ⁅jActL D, kXY⁆ = 0    for every colour `D`,

  because every colour derivation kills the fold's colour-neutral ℂ-core `span{1, u1}`
  (`D 1 = 0` by `derivQ_one`, N266; `D u1 = 0` by `commutes_JO_iff`, N201) — and the whole
  flavour `su(3)` is generated by `innerMul` of slots dressed with exactly `{1, u1}`. The family
  generators use two real-unit slots (both killed → gauge-CENTRAL, N288 `fam_gauge_central`); the
  coset uses one `u1`-dressed slot (killed by colour → colour-NEUTRAL, N291/N292). Colour is BLIND
  to everything flavour is built from. That single blindness — the fold-root's colour-blindness,
  N266 — is the whole commuting relation.

  And the two are GENUINELY DISTINCT (a commuting PAIR, not one algebra): the family generator
  `famC` moves matter ACROSS generation slots (`famC (slotA 1) = − slotB 1`, N288 `famC_slotA`),
  whereas every entrywise gauge `jActL D` preserves each slot (`jActL D (slotA a) = slotA (D a)`,
  N268 `jAct_slotA`) and kills `slotA 1` when `D 1 = 0`. So no flavour generator is an entrywise
  gauge element: `flavour ⊄ jActL(g₂) ⊇ colour`.

  ------------------------------------------------------------------------------
  THE DISSOLUTION / MOAT.

  The field POSITS `F₄ ⊃ (SU(3)_c × SU(3)_flavour)/ℤ₃` as the maximal-rank subgroup and CHOOSES
  which factor is colour, which is flavour, and how each embeds. The theory DERIVES both factors as
  centralizers of each other inside the DERIVED `f₄`, and their commuting is FORCED by the fold-
  root's colour-blindness — no embedding chosen, no factor assigned. The commuting pair is a fold
  consequence, not a group-theory input.

  ------------------------------------------------------------------------------
  THE ONE CAUSE MANY TERMINATIONS.

  The SAME fold-root `u1` wears two orthogonal roles: colour = the g₂-stabilizer of `u1` (blind to
  `span{1,u1}`, acting WITHIN each generation slot), flavour = the `u1`-dressing that MIXES the
  generation slots. The one axis the fold makes is at once the colour complex structure and the
  generation-mixing dressing — so colour and flavour cannot see each other and commute.

  ------------------------------------------------------------------------------
  PHYSICS-WORDS-REMOVABLE. Delete colour/family/flavour/generation/gauge: for every
  `D ∈ colourCentralizer`, the endomorphism `jActL D` of `Matrix (Fin 3) (Fin 3) (O ℚ)` commutes
  with each of the six inner-multiplication commutators `innerMul (slotX c)(slotY c')`
  (`c, c' ∈ {1, u1}`), because `D` annihilates `1` and `u1`; and `innerMul (slotA 1)(slotB 1)`
  sends `slotA 1 ↦ − slotB 1 ≠ 0` while `jActL D` fixes `slotA 1`, so the two families of
  endomorphisms are distinct. Pure mathematics.

  SCOPE. Banks the whole-algebra commuting pair (all six flavour generators) + the one-cause ℂ-core
  lever + the distinctness (flavour ⊄ gauge) + non-vacuity + the capstone. NOT the mutual-
  centralizer RIGIDITY `Z_{f4}(flavour) = colour` EXACTLY (measured 2e-15 — needs an f₄ coordinate
  handle, CHILDED as a directed W1 route-finder); NOT the bundled `flavourLie` LieSubalgebra / the
  colour⊕flavour direct-sum dim count; NOT the ★2 mixing-angle VALUE (route-not-yet-found); NOT the
  ★5 mass texture VALUE (N269: all of f₄ preserves the spectrum → needs a spectrum-breaking object
  beyond f₄); NOT "= physical SU(3)_c × SU(3)_flavour GUT" (removable prose).
-/

namespace Phys.Algebra.HJ
open Phys.Cascade Phys.Cascade.CD Phys.Algebra Matrix

attribute [local instance] CD.narCD CD.srCD

/-! ## The whole-algebra commuting relation — colour centralizes every flavour generator.

The family generators are gauge-CENTRAL (N288), so a fortiori colour-central; the coset members are
colour-NEUTRAL (N291/N292). Colour `D ∈ colourCentralizer` gives `IsDerivQ D` via `isDerivQ_of_mem`. -/

/-- Colour centralizes the family generator `famA = innerMul (slotB 1)(slotC 1)` (gauge-central,
    N288 `famA_gauge_central` — both slots real-unit, killed by `D 1 = 0`). -/
theorem colour_centralizes_famA (D : derivationLieQ) (_hD : D ∈ colourCentralizer) :
    ⁅jActL (D : Module.End ℚ (O ℚ)), innerMul (slotB (1:O ℚ)) (slotC 1)⁆ = 0 :=
  famA_gauge_central (D : Module.End ℚ (O ℚ)) (isDerivQ_of_mem D)

/-- Colour centralizes the family generator `famB = innerMul (slotC 1)(slotA 1)` (N288). -/
theorem colour_centralizes_famB (D : derivationLieQ) (_hD : D ∈ colourCentralizer) :
    ⁅jActL (D : Module.End ℚ (O ℚ)), innerMul (slotC (1:O ℚ)) (slotA 1)⁆ = 0 :=
  famB_gauge_central (D : Module.End ℚ (O ℚ)) (isDerivQ_of_mem D)

/-- Colour centralizes the family generator `famC = innerMul (slotA 1)(slotB 1)` (N288). -/
theorem colour_centralizes_famC (D : derivationLieQ) (_hD : D ∈ colourCentralizer) :
    ⁅jActL (D : Module.End ℚ (O ℚ)), innerMul (slotA (1:O ℚ)) (slotB 1)⁆ = 0 :=
  famC_gauge_central (D : Module.End ℚ (O ℚ)) (isDerivQ_of_mem D)

/-- Colour centralizes the coset member `kAB = innerMul (slotA u1)(slotB 1)` (colour-neutral,
    N291 `coupling_colour_neutral` — the fold-root `u1` is colour-blind). -/
theorem colour_centralizes_kAB (D : derivationLieQ) (hD : D ∈ colourCentralizer) :
    ⁅jActL (D : Module.End ℚ (O ℚ)), innerMul (slotA u1) (slotB (1:O ℚ))⁆ = 0 :=
  coupling_colour_neutral D hD

/-- Colour centralizes the coset member `kBC = innerMul (slotB u1)(slotC 1)` (N292). -/
theorem colour_centralizes_kBC (D : derivationLieQ) (hD : D ∈ colourCentralizer) :
    ⁅jActL (D : Module.End ℚ (O ℚ)), innerMul (slotB u1) (slotC (1:O ℚ))⁆ = 0 :=
  cosetBC_colour_neutral D hD

/-- Colour centralizes the coset member `kCA = innerMul (slotC u1)(slotA 1)` (N292). -/
theorem colour_centralizes_kCA (D : derivationLieQ) (hD : D ∈ colourCentralizer) :
    ⁅jActL (D : Module.End ℚ (O ℚ)), innerMul (slotC u1) (slotA (1:O ℚ))⁆ = 0 :=
  by
  -- kCA has the fold-root in the FIRST slot; the Leibniz lever leaves `innerMul (slotC (D u1))(slotA 1)`
  -- (the second-slot term dies by `jAct_slotA_one`), and `D u1 = 0` kills it (colour is fold-root-blind).
  have hu1 : (D : Module.End ℚ (O ℚ)) u1 = 0 :=
    (commutes_JO_iff (isDerivQ_of_mem D)).mp (mem_colourCentralizer.mp hD)
  have hslotC0 : slotC (0 : O ℚ) = (0 : Matrix (Fin 3) (Fin 3) (O ℚ)) := by
    apply Matrix.ext; intro i j; fin_cases i <;> fin_cases j <;> simp [slotC, Xz]
  rw [innerMul_gauge_leibniz _ (isDerivQ_of_mem D), jAct_slotC D (isDerivQ_of_mem D),
      jAct_slotA_one D (isDerivQ_of_mem D), hu1, hslotC0, innerMul_zero_left,
      innerMul_zero_right, add_zero]

/-! ## THE ONE CAUSE — colour kills the fold's colour-neutral ℂ-core `span{1, u1}`.

This single fact is WHY the whole flavour `su(3)` (generated by `innerMul` of `{1, u1}`-dressed
slots) is colour-neutral: colour is blind to everything flavour is built from. -/

/-- ★★ THE ONE CAUSE. Every colour derivation annihilates BOTH generators of the fold's
    colour-neutral complex line `span{1, u1}` (N266): `D 1 = 0` (every derivation kills the unit,
    `derivQ_one`) and `D u1 = 0` (colour is exactly the g₂-stabilizer of the fold's √−1,
    `commutes_JO_iff`/`mem_colourCentralizer`, N201). The family/coset generators are built from
    slots carrying only `1` and `u1`, so colour cannot see them — the whole commuting relation
    descends from this blindness. -/
theorem colour_kills_foldcomplex_core (D : derivationLieQ) (hD : D ∈ colourCentralizer) :
    (D : Module.End ℚ (O ℚ)) 1 = 0 ∧ (D : Module.End ℚ (O ℚ)) u1 = 0 :=
  ⟨derivQ_one _ (isDerivQ_of_mem D),
   (commutes_JO_iff (isDerivQ_of_mem D)).mp (mem_colourCentralizer.mp hD)⟩

/-! ## Distinctness — the two `su(3)`'s form a genuine commuting PAIR (flavour ⊄ gauge). -/

/-- ★★ W8 DISTINCTNESS. No flavour generator is an entrywise gauge element: `famC = innerMul
    (slotA 1)(slotB 1)` moves matter ACROSS generation slots (`famC (slotA 1) = − slotB 1 ≠ 0`,
    N288 `famC_slotA`), whereas every entrywise gauge `jActL D` with `D 1 = 0` FIXES `slotA 1`
    (`jActL D (slotA 1) = slotA (D 1) = slotA 0 = 0`, N268 `jAct_slotA`). So `famC ≠ jActL D` for
    every derivation `D` killing the unit — in particular for every colour `D`. The family-flavour
    `su(3)` is genuinely OUTSIDE the gauge (entrywise) image: a commuting PAIR, not one algebra. -/
theorem famC_ne_gauge (D : Module.End ℚ (O ℚ)) (hD : IsDerivQ D) :
    innerMul (slotA (1:O ℚ)) (slotB 1) ≠ jActL D := by
  intro h
  -- apply both to slotA 1: LHS = -slotB 1 (famC_slotA), RHS = slotA (D 1) = slotA 0 = 0
  have happ : (innerMul (slotA (1:O ℚ)) (slotB 1)) (slotA 1) = (jActL D) (slotA 1) := by
    rw [h]
  rw [famC_slotA, jActL_apply, jAct_slotA D hD, derivQ_one D hD] at happ
  -- happ : - slotB 1 = slotA 0
  rw [slotA_zero] at happ
  -- - slotB 1 = 0  ⟹  slotB 1 = 0, contradiction via the (0,2) entry
  have hb0 : slotB (1:O ℚ) = 0 := by
    have := congrArg (fun N => - N) happ; simpa using this
  have hb : (slotB (1:O ℚ)) 0 2 = (0 : Matrix (Fin 3) (Fin 3) (O ℚ)) 0 2 := by rw [hb0]
  rw [slotB_entry] at hb
  simp only [Matrix.zero_apply] at hb
  have : reQ (1 : O ℚ) = reQ (0 : O ℚ) := by rw [hb]
  simp only [reQ] at this; norm_num at this

/-- The family generator is non-vacuous as an operator (`famC (slotB 1) = slotA 1 ≠ 0`, N288). -/
theorem flavour_nonvacuous :
    innerMul (slotA (1:O ℚ)) (slotB 1) (slotB 1) ≠ 0 :=
  famC_slotB_ne_zero

/-! ## The capstone — the derived colour and family-flavour `su(3)` are a commuting pair. -/

/-- ★★★ THE COLOUR–FLAVOUR COMMUTING PAIR (the ★1↔★4 joint). Inside the single derived
    `f₄ = Der(H₃(O))`: the derived gauge-colour `su(3)` (`jActL(colourCentralizer)`) COMMUTES with
    all six generators of the derived family-flavour `su(3)` (the family `so(3)` {famA, famB, famC}
    ⊕ the fold-root-dressed coset {kAB, kBC, kCA}), forced by the ONE CAUSE that colour kills the
    fold's colour-neutral ℂ-core `span{1, u1}`; the family-flavour `su(3)` is genuinely DISTINCT
    from the gauge image (`famC ∉ jActL(g₂)`); non-vacuous; and cap-forced at the maximal Jordan
    order 3 (`jordan_fails_H4`, N5 — the whole `f₄`-arena exists only because the octonion tower
    stops). DERIVED, not a chosen `SU(3)_c × SU(3)_flavour` embedding. -/
theorem colour_flavour_commuting_pair :
    (∀ D : derivationLieQ, D ∈ colourCentralizer →
        ⁅jActL (D : Module.End ℚ (O ℚ)), innerMul (slotB (1:O ℚ)) (slotC 1)⁆ = 0
      ∧ ⁅jActL (D : Module.End ℚ (O ℚ)), innerMul (slotC (1:O ℚ)) (slotA 1)⁆ = 0
      ∧ ⁅jActL (D : Module.End ℚ (O ℚ)), innerMul (slotA (1:O ℚ)) (slotB 1)⁆ = 0
      ∧ ⁅jActL (D : Module.End ℚ (O ℚ)), innerMul (slotA u1) (slotB (1:O ℚ))⁆ = 0
      ∧ ⁅jActL (D : Module.End ℚ (O ℚ)), innerMul (slotB u1) (slotC (1:O ℚ))⁆ = 0
      ∧ ⁅jActL (D : Module.End ℚ (O ℚ)), innerMul (slotC u1) (slotA (1:O ℚ))⁆ = 0)
    ∧ (∀ D : derivationLieQ, D ∈ colourCentralizer →
        (D : Module.End ℚ (O ℚ)) 1 = 0 ∧ (D : Module.End ℚ (O ℚ)) u1 = 0)
    ∧ (∀ D : Module.End ℚ (O ℚ), IsDerivQ D →
        innerMul (slotA (1:O ℚ)) (slotB 1) ≠ jActL D)
    ∧ innerMul (slotA (1:O ℚ)) (slotB 1) (slotB 1) ≠ 0
    ∧ jdef Xwit Ywit ≠ 0 :=
  ⟨fun D hD => ⟨colour_centralizes_famA D hD, colour_centralizes_famB D hD,
      colour_centralizes_famC D hD, colour_centralizes_kAB D hD,
      colour_centralizes_kBC D hD, colour_centralizes_kCA D hD⟩,
   fun D hD => colour_kills_foldcomplex_core D hD,
   fun D hD => famC_ne_gauge D hD,
   flavour_nonvacuous,
   jordan_fails_H4⟩

end Phys.Algebra.HJ
