/-
  Phys.Algebra.SpinorCoverGroup — N48: THE SPINOR-COVER GROUP STRUCTURE — the matrix (spinor)
  conjugations of N46/N47 ARE the abstract N45 isometry generators (the EQUIVARIANT INTERTWINING),
  and the SUBMONOID they GENERATE sits inside the Born-form isometry monoid, DERIVED.
  ===========================================================================
  THE NEXT FORCED NODE after the spinor-rotation-matrix node (N47). N45 banked the ABSTRACT
  isometry structure of the Born determinant form `Qv` on `STV = ℚ × ℚ × O ℚ`: the
  `Qv`-preserving ℚ-linear maps as a `Submonoid (Module.End ℚ STV)` (`qvIsomMonoid`), with the
  non-compact hyperbolic BOOST `boost a b` (`a² − b² = 1`) and the compact space-ROTATION `rot u`
  (`gForm u u = 1`) as generators. N46/N47 banked the MATRIX (spinor) picture: the conjugation
  `actBy A M = (A · M) · Aᴴ` on the banked `herm2` self-adjoint `2 × 2` carrier, with the diagonal
  rational `boostMat p` (N46) and the single-octonion-corner `rotMat u` (N47), each a
  determinant-preserving conjugation (`mdet_act`, `mdet_act_rot`).

  THIS module connects the two pictures and banks the COVER-GROUP object — the W1/W3-decomposed
  LIGHT part of the surjectivity node. It proves:
    (1) the matrix conjugations of N46/N47, read through the coordinatization `Hmap (t,x,v) =
        herm2 t x v`, ARE the abstract N45 isometry generators — the EQUIVARIANT INTERTWINING
        `actBy (rotMat u) ∘ Hmap = Hmap ∘ rot u` and `actBy (boostMat p) ∘ Hmap = Hmap ∘ boost a b`;
    (2) the SUBMONOID `spinorCoverMonoid` GENERATED by the boost+rotation generators sits inside
        `qvIsomMonoid` (`spinorCoverMonoid ≤ qvIsomMonoid`) — the "cover group" of the spinor
        cover, every element a Born-form isometry — and is NON-TRIVIAL (`≠ ⊥`).

  THE W1 REFRAME / W9-STRUCTURAL DISSOLUTION (THE ONE LAW). The "cover group" is the natural place
  the W9 octonionic-matrix non-associativity would bite: a GROUP of `2 × 2` matrices over the
  non-associative `O ℚ` does NOT exist as a monoid, because the matrix product of two octonionic
  matrices is itself NON-ASSOCIATIVE (`(A·B)·C ≠ A·(B·C)`), so `Matrix (Fin 2) (Fin 2) (O ℚ)` is
  NOT a monoid under multiplication and one cannot take `Submonoid.closure` of matrix generators.
  THE REFRAME: the cover group lives NOT on the matrix side but on the ABSTRACT side
  `Module.End ℚ STV`, where composition of ℚ-linear endomorphisms IS associative (it is ordinary
  function composition). The matrix conjugations enter ONLY through the equivariance intertwining
  `actBy A (Hmap q) = Hmap (T q)` — each a SINGLE application of the banked `act_herm2` /
  `act_herm2_rot` (where the coordinate work was already done once, no triple octonion product) —
  so the non-associativity of octonionic matrix multiplication is NEVER triggered. The generated
  group structure is carried entirely by the associative endomorphism monoid; the matrix picture
  is its faithful conjugation realization, intertwined coordinate-by-coordinate. This is exactly
  the trunk dissolving a difficulty the classical (matrix-group) framing creates.

  WHAT IS PROVED (each a theorem, foundations-only, forward from the banked objects):
    Hmap                    — the coordinatization `(t,x,v) ↦ herm2 t x v`.
    boostParam              — the abstract boost parameters `(a,b) = ((p²+p⁻²)/2, (p²−p⁻²)/2)`
                              realized by the matrix generator `boostMat p`.
    boostParam_hyperbola    — `a² − b² = 1` for `(a,b) = boostParam p` (`p ≠ 0`), pure ℚ — the
                              matrix boost lands on the unit hyperbola, the N45 isometry condition.
    actBy_rotMat_Hmap       — ★★ THE ROTATION EQUIVARIANCE: `actBy (rotMat u) (Hmap q) =
                              Hmap (rot u q)` (Born-unit `u`) — the matrix rotation conjugation IS
                              the abstract `rot u` read through the coordinatization.
    actBy_boostMat_Hmap     — ★★ THE BOOST EQUIVARIANCE: `actBy (boostMat p) (Hmap q) =
                              Hmap (boost a b q)` (`(a,b) = boostParam p`, `p ≠ 0`) — the matrix
                              boost conjugation IS the abstract `boost a b`.
    coverGens               — the generator set: the boosts on the unit hyperbola ∪ the Born-unit
                              rotations, as endomorphisms of `STV`.
    spinorCoverMonoid       — ★ THE COVER GROUP: the submonoid of `Module.End ℚ STV` GENERATED by
                              `coverGens` (associative — function composition, NOT octonionic
                              matrix multiplication).
    coverGens_subset_isom   — every generator is a `Qv`-isometry (N45 `boost_mem`/`rot_mem`).
    spinorCoverMonoid_le_qvIsom — ★★★ THE HEADLINE: `spinorCoverMonoid ≤ qvIsomMonoid` — every
                              element of the generated cover group preserves the Born form, by
                              `Submonoid.closure_le`. The cover acts by Born-form isometries.
    boost_mem_cover / rot_mem_cover — both generator families lie in the cover.
    comp_mem_cover          — a composite (boost ∘ rotation) lies in the cover (closure under `*`).
    cover_isom              — every cover element is a `Qv`-isometry (the usable corollary).
    spinorCoverMonoid_ne_bot — ★ NON-TRIVIALITY (W8 teeth): the cover is strictly larger than `{1}`
                              (it contains the concrete boost `(5/4, 3/4)`, `≠ id`).

  WHAT IS CHILDED (N49, the heavy continuum part). The SURJECTIVITY onto the connected isometry
  component `SO⁺(1,9)` — that EVERY orientation/time-preserving isometry is a finite product of
  these generators (the `2:1` covering degree `SL(2,𝕆) ↠ SO⁺(1,9)`) — is the genuinely heavy
  front: a generic isometry needs IRRATIONAL boost rapidity / rotation angle, so it must re-ground
  on the DERIVED ℝ `ContinuumQ.Cut` (N11–N13) + the banked Aut(𝕆)/exp stack (N33–N41g) and a
  constructed `SO⁺(1,9)` object (a continuum / Lie / exponential argument), NOT Mathlib ℝ/ℂ as
  content. This node banks the LIGHT, rational part — the cover-group object, its generators, the
  equivariant intertwining, and that the whole generated cover acts by isometries — childed onto
  the chain tail. The surjectivity onto the continuous component is its own node (or an honest W1
  dissolution ticket if it resists after measure + reframe through the derived-ℝ exp stack).

  THE MOAT — posit-vs-derive (docs/STANDARD.md §0). That the boost+rotation generators of the
  `SL(2,𝕆) ↠ SO⁺(1,9)` spinor cover generate the connected isometry component is standard
  (Sudbery, Manogue–Dray, Baez). Here the cover-group object, the equivariant intertwining, and
  the containment in the Born-form isometry monoid are DERIVED from the banked `herm2`/`herm2_det_eq`
  carrier (N43) + the banked abstract isometry monoid `qvIsomMonoid` + `boost`/`rot` generators
  (N45) + the banked matrix conjugations `act_herm2`/`act_herm2_rot` (N46/N47) + the cascade ground
  ring `ℚ` — NO posited Lorentz group, NO Mathlib ℝ/ℂ as content. The W1/W9 reframe — placing the
  cover group on the associative endomorphism side and connecting to the matrix picture only by
  equivariant intertwining — is exactly what dissolves the non-associative-matrix-group difficulty.

  PHYSICS-WORDS-REMOVABLE (docs/STANDARD.md §2). Delete "Lorentz / boost / spinor / rotation /
  SL(2,𝕆) / SO⁺(1,9) / isometry / cover / surjectivity": what remains is the theorem that
  conjugation by the matrices `boostMat p` / `rotMat u` intertwines, through the coordinatization
  `(t,x,v) ↦ herm2 t x v`, with the ℚ-linear self-maps `boost a b` (`(a,b) = ((p²+p⁻²)/2,
  (p²−p⁻²)/2)`, which satisfies `a² − b² = 1`) and `rot u` (`gForm u u = 1`); and that the submonoid
  of `Module.End ℚ STV` generated by `{boost a b | a² − b² = 1} ∪ {rot u | gForm u u = 1}` is
  contained in the submonoid preserving the quadratic form `t² − x² − gForm v v` and is strictly
  larger than `{1}`. No theorem STATEMENT needs a physics word.

  Foundations-only: no posited axiom, no sorry, no kernel-trust bypass, no bridge.
-/
import Phys.Algebra.SpinorRotation

namespace Phys.Algebra

open Phys.Cascade Phys.Cascade.CD
open Matrix

attribute [local instance] CD.narCD CD.srCD dblModuleQ cdModuleQ

noncomputable section

/-! ## The coordinatization and the boost parameters. -/

/-- THE COORDINATIZATION `(t, x, v) ↦ herm2 t x v` from the form's coordinate space `STV` to the
    self-adjoint `2 × 2` carrier. The matrix conjugations of N46/N47 are read through it. -/
def Hmap (q : STV) : Matrix (Fin 2) (Fin 2) (O ℚ) := herm2 q.1 q.2.1 q.2.2

/-- THE ABSTRACT BOOST PARAMETERS `(a, b) = ((p² + p⁻²)/2, (p² − p⁻²)/2)` realized by the matrix
    boost generator `boostMat p`. This is the rational reparametrization linking the matrix
    (lightcone-scaling) boost to the N45 abstract hyperbolic boost `boost a b`. -/
def boostParam (p : ℚ) : ℚ × ℚ := ((p^2 + p⁻¹^2)/2, (p^2 - p⁻¹^2)/2)

/-- The matrix boost parameters land on the unit hyperbola `a² − b² = 1` (`p ≠ 0`): the
    determinant-one / isometry condition of the abstract N45 boost, recovered as `a² − b² =
    ((p²+p⁻²)² − (p²−p⁻²)²)/4 = p²·p⁻² = 1`. Pure ℚ ring arithmetic. -/
theorem boostParam_hyperbola (p : ℚ) (hp : p ≠ 0) :
    (boostParam p).1 ^ 2 - (boostParam p).2 ^ 2 = 1 := by
  simp only [boostParam]
  have hpp : p^2 * p⁻¹^2 = 1 := by rw [← mul_pow, mul_inv_cancel₀ hp, one_pow]
  nlinarith [hpp]

/-! ## The equivariant intertwining — the matrix conjugations ARE the abstract generators. -/

/-- ★★ THE ROTATION EQUIVARIANCE. The matrix rotation conjugation `actBy (rotMat u)` (Born-unit
    `u`), read through the coordinatization `Hmap`, IS the abstract N45 space-rotation `rot u`:
    `actBy (rotMat u) (Hmap q) = Hmap (rot u q)`. The single banked `act_herm2_rot` carries the
    whole identity — no octonionic matrix-matrix product, no triple-product non-associativity. -/
theorem actBy_rotMat_Hmap (u : O ℚ) (hu : gForm u u = 1) (q : STV) :
    actBy (rotMat u) (Hmap q) = Hmap (rot u q) := by
  obtain ⟨t, x, v⟩ := q
  show actBy (rotMat u) (herm2 t x v) = herm2 _ _ _
  rw [act_herm2_rot u hu t x v]
  rfl

/-- ★★ THE BOOST EQUIVARIANCE. The matrix boost conjugation `actBy (boostMat p)` (`p ≠ 0`), read
    through the coordinatization `Hmap`, IS the abstract N45 hyperbolic boost `boost a b` with
    `(a, b) = boostParam p`: `actBy (boostMat p) (Hmap q) = Hmap (boost a b q)`. The single banked
    `act_herm2` carries the lightcone-coordinate identity; the rational reparametrization
    `boostParam` matches it to the abstract boost. -/
theorem actBy_boostMat_Hmap (p : ℚ) (hp : p ≠ 0) (q : STV) :
    actBy (boostMat p) (Hmap q) = Hmap (boost (boostParam p).1 (boostParam p).2 q) := by
  obtain ⟨t, x, v⟩ := q
  show actBy (boostMat p) (herm2 t x v)
      = herm2 ((boostParam p).1 * t + (boostParam p).2 * x)
              ((boostParam p).2 * t + (boostParam p).1 * x) v
  rw [act_herm2 p t x hp v]
  have e1 : (boostParam p).1 * t + (boostParam p).2 * x
      = (p^2*(t+x) + p⁻¹^2*(t-x))/2 := by simp only [boostParam]; ring
  have e2 : (boostParam p).2 * t + (boostParam p).1 * x
      = (p^2*(t+x) - p⁻¹^2*(t-x))/2 := by simp only [boostParam]; ring
  rw [e1, e2]

/-! ## The cover group — generated on the ASSOCIATIVE endomorphism side. -/

/-- THE GENERATOR SET of the cover: the hyperbolic boosts `boost a b` (`a² − b² = 1`) UNION the
    Born-unit space-rotations `rot u` (`gForm u u = 1`), as endomorphisms of `STV`. These are the
    two generator families of the `SL(2,𝕆) ↠ SO⁺(1,9)` cover, abstractly. -/
def coverGens : Set (Module.End ℚ STV) :=
  {T | ∃ a b : ℚ, a^2 - b^2 = 1 ∧ T = boost a b} ∪ {T | ∃ u : O ℚ, gForm u u = 1 ∧ T = rot u}

/-- ★ THE COVER GROUP: the submonoid of `Module.End ℚ STV` GENERATED by the boost+rotation
    generators. It lives on the ASSOCIATIVE endomorphism-composition side — NOT as a submonoid of
    octonionic `2 × 2` matrices (which is not a monoid: octonionic matrix multiplication is itself
    non-associative). The matrix picture realizes it by conjugation, via the equivariant
    intertwining `actBy A (Hmap q) = Hmap (T q)`. This is the cover-group object of the spinor
    cover, DERIVED. -/
def spinorCoverMonoid : Submonoid (Module.End ℚ STV) := Submonoid.closure coverGens

/-- Every generator of the cover is a `Qv`-isometry: the boosts by N45 `boost_mem`
    (`a² − b² = 1`), the rotations by N45 `rot_mem` (`gForm u u = 1`). -/
theorem coverGens_subset_isom : coverGens ⊆ qvIsomMonoid := by
  rintro T (⟨a, b, h, rfl⟩ | ⟨u, hu, rfl⟩)
  · exact boost_mem h
  · exact rot_mem hu

/-- ★★★ THE HEADLINE. The generated cover group is contained in the Born-form isometry monoid:
    `spinorCoverMonoid ≤ qvIsomMonoid`. EVERY element of the cover — every finite product of
    boosts and rotations — preserves the Born quadratic form `Qv = t² − x² − gForm v v`. The cover
    acts by isometries of the banked Lorentzian `(1,9)` form, DERIVED via `Submonoid.closure_le`
    from the generators being isometries — the associativity that makes this well-typed is exactly
    the endomorphism-composition associativity the W9/W1 reframe secured. -/
theorem spinorCoverMonoid_le_qvIsom : spinorCoverMonoid ≤ qvIsomMonoid :=
  Submonoid.closure_le.mpr coverGens_subset_isom

/-- The hyperbolic boost generator lies in the cover. -/
theorem boost_mem_cover {a b : ℚ} (h : a^2 - b^2 = 1) : boost a b ∈ spinorCoverMonoid :=
  Submonoid.subset_closure (Or.inl ⟨a, b, h, rfl⟩)

/-- The Born-unit rotation generator lies in the cover. -/
theorem rot_mem_cover {u : O ℚ} (hu : gForm u u = 1) : rot u ∈ spinorCoverMonoid :=
  Submonoid.subset_closure (Or.inr ⟨u, hu, rfl⟩)

/-- A composite boost ∘ rotation lies in the cover (closure under `*` = composition) — a genuine
    mixed Lorentz transformation in the cover-group picture. -/
theorem comp_mem_cover {a b : ℚ} (h : a^2 - b^2 = 1) {u : O ℚ} (hu : gForm u u = 1) :
    (boost a b) * (rot u) ∈ spinorCoverMonoid :=
  mul_mem (boost_mem_cover h) (rot_mem_cover hu)

/-- The usable corollary: every element of the cover group is a `Qv`-isometry. -/
theorem cover_isom {T : Module.End ℚ STV} (hT : T ∈ spinorCoverMonoid) : IsQvIsom T :=
  spinorCoverMonoid_le_qvIsom hT

/-! ## Non-triviality (W8 teeth) — the cover is strictly larger than the identity. -/

/-- ★ NON-TRIVIALITY: the cover group is NOT the trivial submonoid `⊥ = {1}`. It contains the
    concrete hyperbolic boost `(a, b) = (5/4, 3/4)` (`(5/4)² − (3/4)² = 25/16 − 9/16 = 1`), which is
    NOT the identity (its space component `b = 3/4 ≠ 0`). So the cover acts by genuinely nontrivial
    isometries — a real, non-compact element of the connected component, not a triviality. -/
theorem spinorCoverMonoid_ne_bot : spinorCoverMonoid ≠ ⊥ := by
  intro hc
  have hmem : boost (5/4) (3/4) ∈ spinorCoverMonoid := boost_mem_cover (by norm_num)
  rw [hc, Submonoid.mem_bot, Module.End.one_eq_id] at hmem
  exact boost_ne_id (b := 3/4) (by norm_num) hmem

end

end Phys.Algebra
