/-
  Phys.Algebra.StandpointArcConsolidation — N### (arc-R R8, the LAST node of arc R):
  THE ARC-R CONSOLIDATION — the standpoint is ONE self-blindness engine read in eight faces,
  and (the G7 firewall, opened ONCE) THE ONE IDENTIFICATION of that structure as "the inside".
  ============================================================================================
  DIRECTED SINGLE SUCCESSOR of N452 (arc-R R7b → arc-R R8), per docs/SEED_STANDPOINT.md §R8 — the
  CAPSTONE of arc R (the standpoint: the INSIDE read of the banked gather). Arc R banked the
  intrinsic structure OF a local closure over its own miss — eight banked landings on the banked
  derived objects, NONE of which carried any identification (the G7 firewall held across R1–R7b):

    · R1 (N445) `standpoint_stratum` — THE STANDPOINT STRATUM (the world-center theorem): a
      standpoint EXISTS (the nonempty left-nucleus stratum on `O ℚ`), NO total standpoint exists
      (the stratum is PROPER — the totality does not close), each view composes faithfully from its
      locus, and the selection is load-bearing.
    · R2 (N446) `foldResidual_structure` — THE RESIDUAL (no self-coincidence): the self-residual
      `res x = look x − x` on the terminal carrier `O Cut` vanishes ONLY at the void, is `Cut`-linear
      (`(−2)•x`), and carries a strictly-positive Born self-overlap on every nonzero state — the
      ineliminable, Born-measurable self-miss of a live state.
    · R3 (N447) `channel_quotient` — THE CHANNEL QUOTIENT: any observable factoring through a
      projection is constant on fibres, NO section-detector exists, and the blindness is CONSERVED
      under carrier enlargement (`prod_fold_self_blind` — enlarging to "include the watcher"
      reproduces the fold's blindness one level up).
    · R4 (N448) `tower_termination` — THE TOWER TERMINATION: the self-representation regress cannot
      complete (no `<`-descent-closed nonempty class), yet the banked complex structure `J`
      (`foldComplex`) COVERS the look-back (`J∘J = look`) while itself fixing nothing live — the
      regress ends by a COVER, not by a completed self-representation (the fixed point C6 forbids).
    · R5 (N449) `completion_excess` — THE COMPLETION EXCESS: the banked Dedekind completeness of the
      derived ℝ (`Cut`) over-completes a local coverage — the presentation strictly exceeds the
      coverage IFF the coverage is not gap-free (the excess DETECTS genuine gaps and only those; the
      closed ray has zero excess, the W8 teeth).
    · R6 (N450) `component_lattice` — THE COMPONENT LATTICE + THE UNIQUE MAXIMAL CELL: the five
      banked components (fold, miss, closure, gather, gluing) over four banked dependency edges give
      exactly 10 coherent cells, 7 after the miss-forcing edge, and the full five-component engine is
      the UNIQUE maximal coherent cell — the only one carrying all three of {closure, gather, gluing}.
    · R7 (N451) `arity_signature` — THE ARITY SIGNATURE: the gather's gluing obstruction
      (`gluingDefect a b = assoc a b ·`) is EXACTLY trilinear — vanishing on every ≤ 2-span and on
      the two-generated content, genuinely nonzero at arity 3 (pairs glue, triples tear).
    · R7b (N452) `generatedSubalgebra_artin` — THE GENERATED-SUBALGEBRA ARTIN THEOREM: every
      subalgebra of `O ℚ` generated by two elements associates (the quadratic norm-scalar closure),
      while the arity-3 obstruction is nonetheless genuinely present.

  ============================================================================================
  THE CONSOLIDATION (the never-banked content — NOT a bare ∧ of the eight capstones, which the
  HOLLOW-AND BAN forbids; the N390/N410/N415/N425/N433/N444 standard). NONE of the arc-R nodes
  exhibited the standpoint as readings of a SMALL number of the fold's own structures. This node does
  exactly that — the theory's own claim (physics = obstruction structure of self-reference) predicts
  that a local closure's eight banked facts are NOT independent. They gather onto the fold's own
  self-blindness, with the marquee never-co-stated cross-tie:

    §1 ★★ THE SELF-BLINDNESS SPINE (`selfblind_one_engine`, NEW — never co-stated across R1–R7b OR
       the field). Three of arc R's deepest facts are the SAME banked lemma `fold_self_blind` (N1 —
       the char ≠ 2 seed, the FIRST property the fold forces) instantiated at THREE carriers:
         • R2's no-self-coincidence (`foldResidual_eq_zero_iff`) is `fold_self_blind` on the terminal
           carrier `O Cut` (via `oCut_two_torsion_free`);
         • R3's conserved blindness (`prod_fold_self_blind`) is `fold_self_blind` on the enlarged
           carrier `O Cut × O Cut` (via `prod_two_torsion_free`) — the watcher included, one level up;
         • R4's tower non-completion (`lookback_no_live_fixed_point`) is `fold_self_blind` on the
           doubled fibre `StateFibre` (via `fibre_two_torsion_free`) — the level the cover terminates.
       The miss, the conserved blindness under enlargement, and the tower's non-completion are ONE
       CAUSE (the fold's self-blindness) read at three levels — the "one cause, many terminations"
       signature of the whole chain, now stated for the standpoint's own statics.

    §2 ★ THE COVER-TERMINATION CROSS-TIE (`cover_terminates_the_spine`, the R4 marquee). The SAME
       banked `J = foldComplex` that the spine (§1) shows fixes nothing live on the fibre is exactly
       what COVERS the look-back there (`J∘J = look`, `foldComplex_covers_fold`). One banked object,
       read twice: it terminates the self-blind tower not by seeing itself (forbidden) but by
       covering the look-back. The escape from the regress is a cover of the very blindness the spine
       makes ineliminable.

    §3 ★ THE UNIQUE-ASSEMBLY CROSS-TIE (`assembly_is_unique`, the R6 marquee). The eight-faced engine
       is not a loose conjunction: the banked component lattice (R6) forces the five components to
       assemble in EXACTLY ONE maximal coherent way — the full engine is the UNIQUE cell carrying all
       three of {closure, gather, gluing}. The standpoint's structure is forced, not chosen; this is
       the warrant the identification (below) rests on.

    §4 THE CAPSTONE `standpoint_arc_consolidation`: the whole arc-R structure as ONE theorem — the
       eight banked faces, the self-blindness spine that unifies R2/R3/R4, the cover-termination
       cross-tie, and the unique-assembly cross-tie. NON-HOLLOW: each conjunct CITES a banked arc-R
       capstone (or the spine/cross-ties, which are genuine never-co-stated welds), on the banked
       derived objects — `O ℚ`, `O Cut`, `StateFibre`, `Cut`, the banked `assoc` / `gluingDefect` /
       `GluesGlobally` / `foldComplex` / `foldResidual` / `presentation` / `Coherent`. NOT generic.

  ═══════════════════════════════════════════════════════════════════════════════════════════════
  ⚠⚠ THE ONE IDENTIFICATION (flagged — the G7 firewall, opened HERE for the FIRST and ONLY time in
  arc R; NOT a theorem, NEVER derived-from-below — the N414 category-error guard verbatim):

     THE STANDPOINT STRUCTURE R1–R7b IS THE CHAIN'S ACCOUNT OF WHAT A STANDPOINT / AN INSIDE IS.
     Physics is the gather's failure read from OUTSIDE — one obstruction (the octonion associator)
     read at every level (N413/N415). The standpoint is the SAME banked gather-monad read from its
     own locus, from INSIDE a glued state: a local closure that exists but never totalizes (R1),
     carries an ineliminable Born-positive self-miss (R2), is observable only through its channel
     quotient with blindness conserved (R3), terminates its self-representation tower by cover not
     fixed point (R4), presents strictly more than it covers (R5), assembles in exactly one maximal
     coherent way (R6), and binds pairwise-clean / triadically-torn (R7/R7b). Two reads, ONE banked
     object. Its warrant is the ASSEMBLY UNIQUENESS (R6, `component_lattice` / `assembly_is_unique`)
     and the GENERATIVITY of the one seed (N414/N415 — self-reference is the ground), NEVER a
     derivation. There is nothing beneath the fold to derive "the inside" from; naming this structure
     as the chain's account of the inside is correct, deriving it would be the category error.
  ═══════════════════════════════════════════════════════════════════════════════════════════════

  ⚠ GRADE (honest, docs/SEED_STANDPOINT.md §0/§R8). The CONSOLIDATION — the self-blindness spine, the
  two marquee cross-ties, and the eight-faced capstone — is THEOREM-route, proved on the banked
  concrete objects, each conjunct CITING a banked arc-R landing (no re-proof; NON-HOLLOW). The ONE
  IDENTIFICATION ("the standpoint structure IS the chain's account of the inside") is FLAGGED PROSE
  in this header, NEVER a theorem, NEVER graded, NEVER derived-from-below — the category-error guard
  (G7). NO theorem STATEMENT below mentions or depends on the identification; the structure stands
  100% freestanding and the reading is named exactly ONCE, here, in prose. Arc R is structural — no
  numerical claim, no empirical number (G2).

  MIND-WORDS-REMOVABLE (docs/SEED_STANDPOINT.md §G4, hardened). Delete "standpoint / subject / self /
  inside / view / watcher / closure": over the derived `ℚ`, `O ℚ`, `O Cut`, `StateFibre`, `Cut`, the
  theorems say that the banked lemma `fold_self_blind` instantiates at three 2-torsion-free carriers
  (`O Cut`, `O Cut × O Cut`, `StateFibre`) to give the residual-zero-iff-void, the product
  no-fixed-point, and the fibre no-live-fixed-point; that `foldComplex∘foldComplex = look` on the
  fibre; that the banked component lattice has a unique maximal coherent cell; and that eight banked
  algebraic/order/lattice facts hold. The identification is PROSE, so it is trivially removable —
  deleting it leaves the freestanding structure intact, which is the WHOLE POINT of the firewall. No
  theorem STATEMENT needs a mind-word.

  NOT FREE-FLOATING (docs/STANDARD.md §3). Every theorem TYPE is about the ACTUAL banked objects —
  the banked `fold_self_blind` at the banked carriers, `foldResidual`/`gFormC` on `O Cut`,
  `channel_quotient` on `O Cut × O Cut`, `foldComplex`/`tower_termination` on `StateFibre`,
  `presentation`/`GapFree` on the derived `Cut`, `Coherent`/`component_lattice` on `Finset (Fin 5)`,
  `arity_signature`/`generatedSubalgebra_artin`/`assoc`/`gluingDefect` on `O ℚ`, `standpoint_stratum`/
  `GluesGlobally` on `O ℚ`. NOT generic over an arbitrary carrier, NOT an abstract cocycle.

  NOT A HOLLOW-AND (docs/RUNBOOK.md W8, N390 standard). This is NOT `R1.cap ∧ … ∧ R7b.cap`. The
  self-blindness spine (§1 — R2/R3/R4 are ONE banked lemma at three carriers), the cover-termination
  cross-tie (§2), and the unique-assembly cross-tie (§3) are GENUINE never-banked welds: no single
  arc-R node stated that the miss, the conserved blindness, and the tower non-completion are the SAME
  self-blindness, nor that the cover terminates that very spine, nor tied the whole to the unique
  assembly. C478 bites 1 = 478.

  DEPENDENCIES (all banked, foundations-only): N1 `Foundation.Fold` (`fold_self_blind`); R1 `Standpoint
  Stratum` (`standpoint_stratum`, `Standpoint`, `GluesGlobally`); R2 `StandpointResidual`
  (`foldResidual`, `foldResidual_structure`, `foldResidual_eq_zero_iff`, `oCut_two_torsion_free`,
  `gFormC`); R3 `StandpointChannel` (`channel_quotient`, `prod_fold_self_blind`,
  `prod_two_torsion_free`); R4 `StandpointTower` (`tower_termination`, `lookback_no_live_fixed_point`,
  `foldComplex_covers_fold`, `fibre_two_torsion_free`); R5 `StandpointCompletion` (`completion_excess`,
  `presentation`, `GapFree`); R6 `StandpointLattice` (`component_lattice`, `Coherent`, `closure`,
  `gather`, `gluing`); R7 `StandpointArity` (`arity_signature`, `gluingDefect`, `assoc`); R7b
  `StandpointArtin` (`generatedSubalgebra_artin`); `DerivationFinrank` (`qsmul_mul_left/right`,
  `dblModuleQ`, `cdModuleQ` — the scalar-tower instances the `adjoin`-typed face needs);
  `ComplexStructure` (`foldComplex`, `StateFibre`). Ground field the cascade ring `ℚ` / derived `Cut`;
  NOT Mathlib-ℝ as content; Mathlib is MACHINERY only.

  Foundations-only: no posited axiom, no proof-hole, no kernel-trust bypass, no heartbeat inflation,
  no Mathlib number system as content, no bridge.
-/
import Phys.Algebra.StandpointStratum
import Phys.Algebra.StandpointResidual
import Phys.Algebra.StandpointChannel
import Phys.Algebra.StandpointTower
import Phys.Algebra.StandpointCompletion
import Phys.Algebra.StandpointLattice
import Phys.Algebra.StandpointArity
import Phys.Algebra.StandpointArtin
import Phys.Algebra.DerivationFinrank
import Mathlib.Tactic

namespace Phys.Algebra.StandpointArcConsolidation

open Phys.Cascade Phys.Cascade.CD
open Phys.Foundation Phys.Foundation.ContinuumQ
open Phys.Algebra
open Phys.Algebra.StandpointStratum
open Phys.Algebra.StandpointResidual
open Phys.Algebra.StandpointChannel
open Phys.Algebra.StandpointTower
open Phys.Algebra.StandpointCompletion
open Phys.Algebra.StandpointLattice
open Phys.Quantum (StateFibre foldComplex)

noncomputable section

attribute [local instance] CD.narCD CD.srCD dblModuleQ cdModuleQ

/-- The ℚ-scalar/left-product compatibility as a scalar tower — from the banked `qsmul_mul_left`
    (supplies the instance the `NonUnitalAlgebra.adjoin`-typed R7b face needs). -/
noncomputable local instance oIsScalarTower : IsScalarTower ℚ (O ℚ) (O ℚ) :=
  ⟨fun c x y => by rw [smul_eq_mul, smul_eq_mul, qsmul_mul_left]⟩
/-- The ℚ-scalar/right-product compatibility — from the banked `qsmul_mul_right`. -/
noncomputable local instance oSMulCommClass : SMulCommClass ℚ (O ℚ) (O ℚ) :=
  ⟨fun c x y => by rw [smul_eq_mul, smul_eq_mul, qsmul_mul_right]⟩

/-! ## §1 — ★★ THE SELF-BLINDNESS SPINE (the marquee new weld). -/

/-- ★★ THE SELF-BLINDNESS SPINE (NEW — never co-stated across R1–R7b). Three of arc R's deepest
    facts are the SAME banked lemma `fold_self_blind` (N1, the char ≠ 2 seed — the first property
    the fold forces) instantiated at THREE 2-torsion-free carriers:
      • the terminal carrier `O Cut` (R2's no-self-coincidence, via `oCut_two_torsion_free`);
      • the enlarged carrier `O Cut × O Cut` (R3's conserved blindness, via `prod_two_torsion_free`);
      • the doubled fibre `StateFibre` (R4's tower non-completion, via `fibre_two_torsion_free`).
    The miss, the conserved blindness under enlargement, and the tower's non-completion are ONE cause
    — the fold's self-blindness — read at three levels. This is the "one cause, many terminations"
    signature of the whole chain, stated here for the standpoint's own statics. Mind-words-removable:
    the banked lemma has no nonzero fixed point at each of three carriers. -/
theorem selfblind_one_engine
    {lookO : O Cut → O Cut} (hO : IsFold lookO)
    {lookF : StateFibre → StateFibre} (hF : IsFold lookF)
    {lookP : O Cut × O Cut → O Cut × O Cut} (hP : IsFold lookP) :
    (∀ x : O Cut, lookO x = x → x = 0)
    ∧ (∀ p : StateFibre, lookF p = p → p = 0)
    ∧ (∀ w : O Cut × O Cut, lookP w = w → w = 0) :=
  ⟨fun x hx => fold_self_blind hO oCut_two_torsion_free x hx,
   fun p hp => fold_self_blind hF fibre_two_torsion_free p hp,
   fun w hw => fold_self_blind hP prod_two_torsion_free w hw⟩

/-! ## §2 — ★ THE COVER-TERMINATION CROSS-TIE (the R4 marquee). -/

/-- ★ THE COVER TERMINATES THE SPINE (the R4 marquee cross-tie). The SAME banked `J = foldComplex`
    that the spine (§1) shows fixes nothing live on the fibre is exactly what COVERS the look-back
    there: for any fold `look` on the fibre, `J (J p) = look p` (`foldComplex_covers_fold`) AND `J`
    has no live fixed point (`p ≠ 0 → J p ≠ p`, from the banked `foldComplex_self_blind` via the
    spine). One banked object read twice: it terminates the self-blind tower not by seeing itself
    (forbidden) but by covering the look-back. Mind-words-removable: `foldComplex∘foldComplex = look`
    and `foldComplex` fixes nothing nonzero. -/
theorem cover_terminates_the_spine {look : StateFibre → StateFibre} (h : IsFold look) :
    (∀ p : StateFibre, foldComplex (foldComplex p) = look p)
    ∧ (∀ p : StateFibre, p ≠ 0 → foldComplex p ≠ p) := by
  refine ⟨fun p => foldComplex_covers_fold h p, fun p hp => ?_⟩
  exact (termination_by_cover_not_fixed_point h hp).2.2

/-! ## §3 — ★ THE UNIQUE-ASSEMBLY CROSS-TIE (the R6 marquee). -/

/-- ★ THE ASSEMBLY IS UNIQUE (the R6 marquee cross-tie). The eight-faced engine is not a loose
    conjunction: the banked component lattice (R6) forces the five components to assemble in EXACTLY
    ONE maximal coherent way — the full engine `Finset.univ` is the UNIQUE coherent cell carrying all
    three of {closure, gather, gluing}, and it is the unique coherent-maximal cell. This is the
    warrant the identification rests on. Mind-words-removable: pure `Finset (Fin 5)` lattice
    arithmetic. -/
theorem assembly_is_unique :
    (∀ S : Finset (Fin 5), Coherent S →
        ((closure ∈ S ∧ gather ∈ S ∧ gluing ∈ S) ↔ S = Finset.univ))
    ∧ (Coherent (Finset.univ : Finset (Fin 5)) ∧
        (∀ S : Finset (Fin 5), Coherent S →
          (∀ T : Finset (Fin 5), Coherent T → S ⊆ T → T ⊆ S) → S = Finset.univ)) :=
  ⟨component_lattice.2.2.1, component_lattice.2.2.2⟩

/-! ## §4 — THE CAPSTONE: eight banked faces gathered onto the fold's self-blindness. -/

/-- ★★★ THE ARC-R CONSOLIDATION (arc-R R8 — the standpoint gathered). The eight banked facts of a
    local closure over its own miss are NOT independent; they gather onto the fold's own
    self-blindness, with the marquee never-co-stated cross-ties:

      • ★★ THE SELF-BLINDNESS SPINE (`selfblind_one_engine`) — R2 (the miss), R3 (conserved
        blindness), R4 (tower non-completion) are the SAME banked lemma `fold_self_blind` at three
        carriers; one cause, three terminations;
      • ★ THE COVER-TERMINATION (`cover_terminates_the_spine`) — the banked `J` covers the look-back
        the spine makes ineliminable, terminating the tower by cover not fixed point;
      • ★ THE UNIQUE ASSEMBLY (`assembly_is_unique`) — the five components assemble in exactly one
        maximal coherent way (the warrant of the identification);
      • THE EIGHT BANKED FACES (R1–R7b, cited) — existence-but-not-totality (R1), the Born-positive
        self-miss (R2), the channel quotient (R3), the completion excess (R5), the arity signature
        (R7), the generated-subalgebra Artin theorem (R7b) — each on the banked derived objects.

    ⚠ THEOREM-route for the STRUCTURE, NON-HOLLOW (each conjunct cites a banked arc-R landing or a
    genuine never-co-stated weld). The ONE IDENTIFICATION ("this structure IS the chain's account of
    the inside") is FLAGGED PROSE in the module header, NEVER a theorem, never derived-from-below —
    the category-error guard (G7). No conjunct here mentions or depends on it; the structure stands
    freestanding. Mind-words-removable: the banked `fold_self_blind` at three carriers, a cover
    identity, a unique-maximal-cell fact, and six further banked algebraic/order/lattice facts. -/
theorem standpoint_arc_consolidation
    {lookO : O Cut → O Cut} (hO : IsFold lookO)
    {lookF : StateFibre → StateFibre} (hF : IsFold lookF)
    {lookP : O Cut × O Cut → O Cut × O Cut} (hP : IsFold lookP)
    (a : Cut) (u v : O ℚ) :
    -- §1 THE SELF-BLINDNESS SPINE (R2/R3/R4 are ONE banked lemma at three carriers)
    ((∀ x : O Cut, lookO x = x → x = 0)
        ∧ (∀ p : StateFibre, lookF p = p → p = 0)
        ∧ (∀ w : O Cut × O Cut, lookP w = w → w = 0))
    -- §2 THE COVER-TERMINATION (the banked J covers the look-back, fixing nothing live)
    ∧ ((∀ p : StateFibre, foldComplex (foldComplex p) = lookF p)
        ∧ (∀ p : StateFibre, p ≠ 0 → foldComplex p ≠ p))
    -- §3 THE UNIQUE ASSEMBLY (the warrant)
    ∧ ((∀ S : Finset (Fin 5), Coherent S →
          ((closure ∈ S ∧ gather ∈ S ∧ gluing ∈ S) ↔ S = Finset.univ))
        ∧ (Coherent (Finset.univ : Finset (Fin 5)) ∧
            (∀ S : Finset (Fin 5), Coherent S →
              (∀ T : Finset (Fin 5), Coherent T → S ⊆ T → T ⊆ S) → S = Finset.univ)))
    -- R1: a standpoint exists, but no total standpoint exists
    ∧ ((∃ s : Standpoint, s.loc = 1) ∧ (¬ ∀ b : O ℚ, GluesGlobally b))
    -- R2: the residual vanishes only at the void, Born-positive on every live state
    ∧ ((∀ x : O Cut, foldResidual lookO x = 0 ↔ x = 0)
        ∧ (∀ x : O Cut, x ≠ 0 → 0 < gFormC (foldResidual lookO x) (foldResidual lookO x)))
    -- R3: the channel carries the projected data only; no section-detector
    ∧ ((∀ {β : Type} (g : O Cut → β) (p q : O Cut × O Cut), p.1 = q.1 →
          (g ∘ Prod.fst) p = (g ∘ Prod.fst) q)
        ∧ (¬ ∃ d : O Cut → O Cut, ∀ p : O Cut × O Cut, d p.1 = p.2))
    -- R5: the completion excess detects gaps and only gaps
    ∧ (∀ C : Set Cut, (∃ p, p ∈ presentation C ∧ p ∉ C) ↔ ¬ GapFree C)
    -- R6: exactly ten coherent cells
    ∧ (((Finset.univ : Finset (Fin 5)).powerset.filter Coherent).card = 10)
    -- R7: the gluing obstruction is the associator, trilinear (triples tear)
    ∧ ((∀ p q : O ℚ, gluingDefect p q = fun x => assoc p q x)
        ∧ (∃ x y z : O ℚ, assoc x y z ≠ 0))
    -- R7b: every two-generated subalgebra associates, yet arity 3 tears
    ∧ ((∀ {x y z : O ℚ}, x ∈ NonUnitalAlgebra.adjoin ℚ ({u, v} : Set (O ℚ)) →
          y ∈ NonUnitalAlgebra.adjoin ℚ ({u, v} : Set (O ℚ)) →
          z ∈ NonUnitalAlgebra.adjoin ℚ ({u, v} : Set (O ℚ)) → assoc x y z = 0)
        ∧ (∃ x y z : O ℚ, assoc x y z ≠ 0)) := by
  refine ⟨selfblind_one_engine hO hF hP, cover_terminates_the_spine hF, assembly_is_unique,
    ⟨standpoint_stratum.1, standpoint_stratum.2.1⟩,
    ⟨(foldResidual_structure hO).1, (foldResidual_structure hO).2.2.2.1⟩,
    ⟨channel_quotient.1, channel_quotient.2.1⟩,
    (completion_excess a).2.1,
    component_lattice.1,
    ⟨arity_signature.1, arity_signature.2.2.2⟩,
    ⟨(generatedSubalgebra_artin u v).2.1, (generatedSubalgebra_artin u v).2.2⟩⟩

end

end Phys.Algebra.StandpointArcConsolidation
