/-
  Phys.Algebra.StandpointArtin — arc-R R7b: THE GENERATED-SUBALGEBRA ARTIN THEOREM.
  ============================================================================================
  THE LITERAL ARTIN STATEMENT — every subalgebra GENERATED by two elements associates. This is
  the piece N451 (`StandpointArity`) decomposed OUT under W3: N451 banked the arity SIGNATURE
  (pairs glue on any 2-dim span, triples tear at arity 3, generated CONTENT `span{1,a,b,a·b}`
  associates via `assoc_span4_vanishes`); this node closes the remaining machinery — that the
  actual GENERATED subalgebra `NonUnitalAlgebra.adjoin ℚ {a,b}` is CONTAINED in that content
  `span{1,a,b,a·b}`, hence (composing with the banked `assoc_span4_vanishes`) associates.

  THE ROUTE — the quadratic norm-scalar closure (the J-R7 machinery build).
  On the derived `O ℚ`, the self-overlap `z · star z` is a real scalar (`selfMul`, `Nrm`,
  ForcedStop): `Nrm z • 1`. Hence every element satisfies a QUADRATIC minimal relation
  `z·z = (2 Re z)•z − N(z)•1` (`o_quad_rel`, where `Re z = reQ z`, `N(z) = reQ (z · star z)`),
  which pins every product of the four generators `{1, a, b, a·b}` back into their linear span:

    • squares — `o_quad_rel` at `a`, `b`, and `a·b` (`o_ab_mul_ab`);
    • the mixed product `b·a` — `o_ba_formula` (`b·a = trace terms − a·b`, from the star
      anti-homomorphism + the trace identity, coordinate-derived);
    • the four alternating products `a·(a·b)`, `(a·b)·b`, `(a·b)·a`, `b·(a·b)` — `o_a_mul_ab`,
      `o_ab_mul_b`, `o_ab_mul_a`, `o_b_mul_ab`, each the linearized form of the banked
      alternative laws (`alt_left`/`alt_right`/`alt_flex`, N5b), coordinate-derived here.

  Every one of the sixteen generator products therefore lies in `span{1,a,b,a·b}`, so the span is
  closed under multiplication (`twoGenContent_mul_mem`), i.e. carries a non-unital subalgebra
  (`twoGenSubalg`). Since it contains the generators `a`, `b`, the universal property of `adjoin`
  gives the CONTAINMENT (`adjoin_pair_mem_content`), and composing with the banked
  `assoc_span4_vanishes` gives THE ARTIN COROLLARY (`twoGenerated_associates`): any three elements
  of the two-generated subalgebra associate.

  (Σ) ★ `generatedSubalgebra_artin` — the non-hollow capstone: the containment ∧ the two-generated
      associativity ∧ (anchoring against the genuine obstruction) the banked triples-tear
      `arity3_tear` (`∃ x y z, assoc x y z ≠ 0`). So the Artin theorem sits AGAINST the real
      arity-3 obstruction: pairwise/two-generated composition is clean, yet the associator does
      not vanish identically — the two faces are jointly non-vacuous.

  DERIVED-not-posited (G3): the quadratic relation is DERIVED from the banked `selfMul`/`Nrm`
  (self-overlap is real) and the banked alternative laws — never posited associativity, never a
  posited norm form. Words-removable (G4): delete "standpoint / subalgebra-reading" and every
  statement is a pure generated-subalgebra associativity fact about `assoc` on `O ℚ`. About the
  ACTUAL banked `O ℚ` and its banked associator/norm/alternative laws — `NonUnitalAlgebra.adjoin`
  and `Submodule.span` are standard Mathlib MACHINERY on the DERIVED octonions, not a generic
  alternative algebra. NO identification anywhere (G7 IDENTIFICATION FIREWALL — deferred to R8).
  Foundations-only ⊆ {propext, Classical.choice, Quot.sound}.

  Dependencies (all banked, cited):
    • `assoc`, `alt_left`/`alt_right`/`alt_flex`, `assoc_nonvanishing` — Alternative.lean (N5b).
    • `assoc_span4_vanishes`, `arity3_tear` — StandpointArity.lean (N451: the generated content
      associates; the triples tear).
    • `reQ` — DerivationSkew.lean; `Nrm`, `selfMul`, `star` (StarRing `srCD`) — ForcedStop.lean.
    • `qsmul_mul_left`/`qsmul_mul_right` — DerivationFinrank (the ℚ-scalar/product compatibility
      that supplies the `IsScalarTower`/`SMulCommClass` instances the `adjoin` construction needs).
-/
import Phys.Algebra.StandpointArity
import Phys.Algebra.DerivationSkew
import Phys.Cascade.ForcedStop
import Mathlib.Algebra.Algebra.NonUnitalSubalgebra
import Mathlib.Tactic

namespace Phys.Algebra
open Phys.Cascade Phys.Cascade.CD

attribute [local instance] CD.narCD CD.srCD dblModuleQ cdModuleQ

/-- The ℚ-scalar/left-product compatibility as a scalar tower — from the banked `qsmul_mul_left`.
    Needed so `NonUnitalAlgebra.adjoin ℚ {a,b}` forms cleanly over the global `Module ℚ (O ℚ)`. -/
noncomputable local instance oIsScalarTower : IsScalarTower ℚ (O ℚ) (O ℚ) :=
  ⟨fun c x y => by rw [smul_eq_mul, smul_eq_mul, qsmul_mul_left]⟩
/-- The ℚ-scalar/right-product compatibility — from the banked `qsmul_mul_right`. -/
noncomputable local instance oSMulCommClass : SMulCommClass ℚ (O ℚ) (O ℚ) :=
  ⟨fun c x y => by rw [smul_eq_mul, smul_eq_mul, qsmul_mul_right]⟩

set_option maxHeartbeats 4000000
set_option linter.unusedSimpArgs false

/-! ### The quadratic minimal relation and the sixteen generator products.

Every element of `O ℚ` satisfies a quadratic relation over `span{1, ·}`; combined with the banked
alternative laws this pins each product of `{1,a,b,a·b}` into `span{1,a,b,a·b}`. The identities are
coordinate-derived on the banked Cayley–Dickson multiplication (the `obashcore` bash, foundations-
only — the same 4M coordinate budget as `Alternative.lean`). -/

/-- Master coordinate expansion for octonion scalar identities: bottom out `re`/`im` through the
    three doublings to `Dbl ℚ` and close by `ring`. Foundations-only. -/
macro "obashcore" : tactic =>
  `(tactic| (ext <;>
    simp only [cd_qsmul_re, cd_qsmul_im,
      Dbl.smul_re, Dbl.smul_im, Dbl.mul_re, Dbl.mul_im,
      Dbl.add_re, Dbl.add_im, Dbl.neg_re, Dbl.neg_im,
      Dbl.one_re, Dbl.one_im, Dbl.zero_re, Dbl.zero_im,
      Dbl.star_re', Dbl.star_im',
      mul_re, mul_im, star_re, star_im, zero_re, zero_im,
      one_re, one_im, star_neg, neg_re, neg_im, star_add, star_mul', star_star,
      neg_mul, mul_neg, neg_neg, add_re, add_im, smul_eq_mul,
      mul_one, mul_zero] <;> ring))

/-- ★ THE QUADRATIC MINIMAL RELATION: `a·a = (2 Re a)•a − N(a)•1`, with `Re a = reQ a` and
    `N(a) = reQ (a·star a)` (the self-overlap, real by `selfMul`). A square lies in `span{1,a}`. -/
theorem o_quad_rel (a : O ℚ) :
    a * a = (2 * reQ a) • a - (reQ (a * star a)) • (1 : O ℚ) := by
  rw [sub_eq_add_neg]; unfold reQ; obashcore

/-- The mixed product `b·a` lies in `span{1,a,b,a·b}` (`b·a = trace terms − a·b`). -/
theorem o_ba_formula (a b : O ℚ) :
    b * a = (2 * reQ (a * b) - 4 * reQ a * reQ b) • (1 : O ℚ)
      + (2 * reQ b) • a + (2 * reQ a) • b - a * b := by
  rw [sub_eq_add_neg]; unfold reQ; obashcore

/-- `a·(a·b) = (2 Re a)•(a·b) − N(a)•b` (linearized left-alternative law). -/
theorem o_a_mul_ab (a b : O ℚ) :
    a * (a * b) = (2 * reQ a) • (a * b) - (reQ (a * star a)) • b := by
  rw [sub_eq_add_neg]; unfold reQ; obashcore

/-- `(a·b)·b = (2 Re b)•(a·b) − N(b)•a` (linearized right-alternative law). -/
theorem o_ab_mul_b (a b : O ℚ) :
    (a * b) * b = (2 * reQ b) • (a * b) - (reQ (b * star b)) • a := by
  rw [sub_eq_add_neg]; unfold reQ; obashcore

/-- `(a·b)·a` lies in `span{1,a,b}` (flexible law + trace). -/
theorem o_ab_mul_a (a b : O ℚ) :
    (a * b) * a = (2 * reQ (a * b)) • a - (2 * reQ b * reQ (a * star a)) • (1 : O ℚ)
      + (reQ (a * star a)) • b := by
  rw [sub_eq_add_neg]; unfold reQ; obashcore

/-- `b·(a·b)` lies in `span{1,a,b}` (flexible law + trace). -/
theorem o_b_mul_ab (a b : O ℚ) :
    b * (a * b) = (2 * reQ (a * b)) • b - (2 * reQ a * reQ (b * star b)) • (1 : O ℚ)
      + (reQ (b * star b)) • a := by
  rw [sub_eq_add_neg]; unfold reQ; obashcore

/-- `(a·b)·(a·b)` lies in `span{1, a·b}` — the quadratic relation at the product `a·b`. -/
theorem o_ab_mul_ab (a b : O ℚ) :
    (a * b) * (a * b)
      = (2 * reQ (a * b)) • (a * b) - (reQ ((a * b) * star (a * b))) • (1 : O ℚ) :=
  o_quad_rel (a * b)

/-! ### The two-generated CONTENT and its multiplicative closure. -/

/-- The linear span of the two generators together with their single product — the CONTENT of the
    two-generated subalgebra closed by one multiplication. -/
noncomputable def twoGenContent (a b : O ℚ) : Submodule ℚ (O ℚ) :=
  Submodule.span ℚ ({1, a, b, a * b} : Set (O ℚ))

theorem twoGenContent_one_mem (a b : O ℚ) : (1 : O ℚ) ∈ twoGenContent a b :=
  Submodule.subset_span (by simp)
theorem twoGenContent_a_mem (a b : O ℚ) : a ∈ twoGenContent a b :=
  Submodule.subset_span (by simp)
theorem twoGenContent_b_mem (a b : O ℚ) : b ∈ twoGenContent a b :=
  Submodule.subset_span (by simp)
theorem twoGenContent_ab_mem (a b : O ℚ) : a * b ∈ twoGenContent a b :=
  Submodule.subset_span (by simp)

/-- ★ THE MULTIPLICATIVE CLOSURE: `span{1,a,b,a·b}` is closed under multiplication. By bilinear
    reduction to the sixteen generator products, each pinned back into the span by the quadratic
    relation and the linearized alternative laws above. -/
theorem twoGenContent_mul_mem (a b : O ℚ) {x y : O ℚ}
    (hx : x ∈ twoGenContent a b) (hy : y ∈ twoGenContent a b) : x * y ∈ twoGenContent a b := by
  have h1 := twoGenContent_one_mem a b; have ha := twoGenContent_a_mem a b
  have hb := twoGenContent_b_mem a b; have hab := twoGenContent_ab_mem a b
  induction hx using Submodule.span_induction with
  | zero => rw [zero_mul]; exact Submodule.zero_mem _
  | add p q _ _ hp hq => rw [add_mul]; exact Submodule.add_mem _ hp hq
  | smul c p _ hp => rw [smul_mul_assoc]; exact Submodule.smul_mem _ _ hp
  | mem g hg =>
    induction hy using Submodule.span_induction with
    | zero => rw [mul_zero]; exact Submodule.zero_mem _
    | add p q _ _ hp hq => rw [mul_add]; exact Submodule.add_mem _ hp hq
    | smul c p _ hp => rw [mul_smul_comm]; exact Submodule.smul_mem _ _ hp
    | mem h hh =>
      simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hg hh
      rcases hg with rfl | rfl | rfl | rfl <;> rcases hh with rfl | rfl | rfl | rfl
      · rw [one_mul]; exact h1
      · rw [one_mul]; exact ha
      · rw [one_mul]; exact hb
      · rw [one_mul]; exact hab
      · rw [mul_one]; exact ha
      · rw [o_quad_rel]
        exact Submodule.sub_mem _ (Submodule.smul_mem _ _ ha) (Submodule.smul_mem _ _ h1)
      · exact hab
      · rw [o_a_mul_ab]
        exact Submodule.sub_mem _ (Submodule.smul_mem _ _ hab) (Submodule.smul_mem _ _ hb)
      · rw [mul_one]; exact hb
      · rw [o_ba_formula]
        exact Submodule.sub_mem _ (Submodule.add_mem _ (Submodule.add_mem _
          (Submodule.smul_mem _ _ h1) (Submodule.smul_mem _ _ ha)) (Submodule.smul_mem _ _ hb)) hab
      · rw [o_quad_rel]
        exact Submodule.sub_mem _ (Submodule.smul_mem _ _ hb) (Submodule.smul_mem _ _ h1)
      · rw [o_b_mul_ab]
        exact Submodule.add_mem _ (Submodule.sub_mem _ (Submodule.smul_mem _ _ hb)
          (Submodule.smul_mem _ _ h1)) (Submodule.smul_mem _ _ ha)
      · rw [mul_one]; exact hab
      · rw [o_ab_mul_a]
        exact Submodule.add_mem _ (Submodule.sub_mem _ (Submodule.smul_mem _ _ ha)
          (Submodule.smul_mem _ _ h1)) (Submodule.smul_mem _ _ hb)
      · rw [o_ab_mul_b]
        exact Submodule.sub_mem _ (Submodule.smul_mem _ _ hab) (Submodule.smul_mem _ _ ha)
      · rw [o_ab_mul_ab]
        exact Submodule.sub_mem _ (Submodule.smul_mem _ _ hab) (Submodule.smul_mem _ _ h1)

/-- The two-generated content as a non-unital subalgebra (closed under multiplication). -/
noncomputable def twoGenSubalg (a b : O ℚ) : NonUnitalSubalgebra ℚ (O ℚ) :=
  (twoGenContent a b).toNonUnitalSubalgebra (fun _ _ hx hy => twoGenContent_mul_mem a b hx hy)

/-! ### (1) ★ THE CONTAINMENT and (2) ★ THE ARTIN COROLLARY. -/

/-- ★ THE CONTAINMENT: the two-generated subalgebra `⟨a,b⟩ = adjoin ℚ {a,b}` is contained in the
    linear content `span{1,a,b,a·b}`. The universal property of `adjoin`: `twoGenSubalg` is a
    subalgebra containing the generators, so it contains the whole adjoin. -/
theorem adjoin_pair_mem_content (a b : O ℚ) {x : O ℚ}
    (hx : x ∈ NonUnitalAlgebra.adjoin ℚ ({a, b} : Set (O ℚ))) : x ∈ twoGenContent a b := by
  have hle : NonUnitalAlgebra.adjoin ℚ ({a, b} : Set (O ℚ)) ≤ twoGenSubalg a b := by
    apply NonUnitalAlgebra.adjoin_le
    intro y hy
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hy
    show y ∈ twoGenContent a b
    rcases hy with hy | hy <;> rw [hy]
    · exact twoGenContent_a_mem a b
    · exact twoGenContent_b_mem a b
  exact hle hx

/-- ★ THE ARTIN COROLLARY: every subalgebra generated by TWO elements associates. Any three
    elements of `adjoin ℚ {a,b}` have vanishing associator — composing the containment with the
    banked `assoc_span4_vanishes` (N451). Pairwise / two-generated composition has NO obstruction. -/
theorem twoGenerated_associates (a b : O ℚ) {x y z : O ℚ}
    (hx : x ∈ NonUnitalAlgebra.adjoin ℚ ({a, b} : Set (O ℚ)))
    (hy : y ∈ NonUnitalAlgebra.adjoin ℚ ({a, b} : Set (O ℚ)))
    (hz : z ∈ NonUnitalAlgebra.adjoin ℚ ({a, b} : Set (O ℚ))) :
    assoc x y z = 0 :=
  assoc_span4_vanishes a b (adjoin_pair_mem_content a b hx)
    (adjoin_pair_mem_content a b hy) (adjoin_pair_mem_content a b hz)

/-! ### (Σ) ★ THE CAPSTONE — non-hollow, sitting against the genuine obstruction. -/

/-- ★ THE GENERATED-SUBALGEBRA ARTIN THEOREM (non-hollow). Bundles: (1) the containment
    `⟨a,b⟩ ⊆ span{1,a,b,a·b}`; (2) the two-generated associativity `⟨a,b⟩ associates`; and (3)
    the banked triples-tear `arity3_tear` — so the Artin fact sits AGAINST the real arity-3
    obstruction (the associator is genuinely nonzero somewhere), and the two faces are jointly
    non-vacuous: two-generated composition is clean, yet the associator does not vanish
    identically. NO identification (G7 firewall — deferred to R8). -/
theorem generatedSubalgebra_artin (a b : O ℚ) :
    -- (1) THE CONTAINMENT
    (∀ {x : O ℚ}, x ∈ NonUnitalAlgebra.adjoin ℚ ({a, b} : Set (O ℚ)) → x ∈ twoGenContent a b) ∧
    -- (2) THE ARTIN COROLLARY: the two-generated subalgebra associates
    (∀ {x y z : O ℚ}, x ∈ NonUnitalAlgebra.adjoin ℚ ({a, b} : Set (O ℚ)) →
      y ∈ NonUnitalAlgebra.adjoin ℚ ({a, b} : Set (O ℚ)) →
      z ∈ NonUnitalAlgebra.adjoin ℚ ({a, b} : Set (O ℚ)) → assoc x y z = 0) ∧
    -- (3) yet the arity-3 obstruction is genuinely present (banked tear)
    (∃ x y z : O ℚ, assoc x y z ≠ 0) :=
  ⟨fun hx => adjoin_pair_mem_content a b hx,
   fun hx hy hz => twoGenerated_associates a b hx hy hz,
   arity3_tear⟩

end Phys.Algebra
