/-
  Phys.Algebra.TowerGatherArcConsolidation — N415 (arc-N N5, the LAST node of arc N):
  THE ARC-N CONSOLIDATION — the gather's obstruction is ONE proposition read at every level,
  forced by the fold at every level.
  ============================================================================================
  DIRECTED SUCCESSOR of N414 (arc-N N4 → arc-N N5), per docs/SEED_GATHER_TELOS.md §N5 — the
  LAST node of arc N, the physics TELOS: physics is the local→global (sheaf-like) obstruction
  of the gather trying, and failing, to totalize. Arc N built FOUR reading-LEVELS of the SAME
  object — the octonion associator `assoc` on `O ℚ` (= the banked N219 gluing obstruction = the
  N411 monad μ-comparison defect = the N385 confinement descent obstruction):

    · N411 `TowerGatherBarMonad` — the MONAD level: the gather is a monad-with-ONE-controlled-
      obstruction; the μ-comparison defect `barMultDefect a b` IS the associator on `O ℚ`; the
      octonion rung is GENUINELY non-strict (`o_bar_obstructed`).
    · N412 `TowerGatherPhysicalState` — the STATE level: a state is physical ⟺ it is a T-algebra
      / global section ⟺ it lies in the left nucleus; the `O ℚ` stratum is PROPER (some state is
      unphysical, `o_not_all_physical`) — a genuine selection rule.
    · N413 `TowerGatherObstructionUnification` — the FOUR-FACES level: confinement (arc I),
      the cascade stop (N2), curvature (arc E) are the SAME sector-global `∃` index of the ONE
      locus `AssocLocusNonempty := ∃ a b c, assoc a b c ≠ 0`, and CP (arc F2) is its reQ⊕Im
      channel refinement.
    · N414 `GatherFoldGroundGenerativity` — the FOLD-SEED level: the obstruction is FORCED by
      the fold's own seed (`obstruction_witness_iff_foldRoot_selfOpposed`, the witness ⟺ `J ≠
      star J`; `foldRoot_selfOpposed_forces_all_four`, the seed forces the N413 FACES).

  THE CONSOLIDATION (the never-banked content — NOT a bare ∧ of the four capstones, which the
  HOLLOW-AND BAN forbids). Each arc-N node tied ITS OWN level to the associator; NONE welded the
  LEVELS to EACH OTHER, nor to the common LOCUS, nor extended the fold-seed forcing PAST the
  N413 faces to the N411 monad and N412 state levels. This node does exactly that:

    §1 THE TWO NEW LEVEL⟺LOCUS WELDS (never banked):
      • `monad_nonstrict_iff_locus`: the gather is a genuinely NON-STRICT monad on `O ℚ`
        (`∃ a b, barMultDefect a b ≠ 0`, N411) IFF the associator locus is nonempty. (N411 tied
        the defect to the associator POINTWISE; it never tied the EXISTENCE of a nonzero defect
        to the LOCUS.)
      • `state_selection_iff_locus`: the state stratum is PROPER (`∃ a, ¬ GluesGlobally a`, N412
        — a genuine selection rule) IFF the associator locus is nonempty. (N412 tied confinement
        to an unphysical state; it never tied the unphysical state to the LOCUS.)

    §2 THE GRAND TFAE (★★ the consolidation): SIX a-priori-different readings of the octonion
      obstruction are pairwise EQUIVALENT — the locus, confinement (I), the cascade stop (N2),
      curvature-somewhere (E), the monad non-strictness (N411), and the state selection (N412)
      are ONE proposition (`gather_all_levels_tfae`). This is the arc-N statement made a single
      theorem: physics is where the gather fails, and "where the gather fails" is ONE place read
      six ways.

    §3 THE CROSS-LEVEL GENERATIVITY EXTENSION (★★ never banked): the fold-root's self-opposition
      `J ≠ star J` (N414's seed, itself the SAME char ≠ 2 that gives the fold's self-blindness)
      forces the obstruction at the MONAD and STATE levels too, not just the N413 faces
      (`foldRoot_forces_monad_and_state`): from the ONE seed, the gather monad is non-strict AND
      the state stratum is proper. Combined with N414 this means the fold seed forces ALL SIX
      TFAE levels at once (`foldRoot_forces_all_levels`).

    §4 ONE WITNESS AT EVERY LEVEL (★): the single banked non-associating triple's leading pair
      `(ι(ιJ), ι(e₂))` realizes the monad non-strictness (`witness_monad_level`) and the state
      un-physicality (`witness_state_level`) too — the same object N413 showed realizes all four
      faces now realizes the monad and state levels, so ONE witness fires at every arc-N level.

    §5 THE CAPSTONE `arcN_consolidation`: the whole arc-N structure as one theorem — the six-way
      equivalence, the fold-seed forcing all levels, and the one witness at every level.

  ⚠ GRADE (honest, docs/SEED_GATHER_TELOS.md §N5). The STRUCTURE — the two new level⟺locus welds,
  the six-way TFAE, the cross-level seed forcing, the one-witness-all-levels realization — is
  THEOREM-route, proved on the banked concrete objects `O ℚ` / `Dbl ℚ`. The reading "physics is
  the local→global obstruction of the gather, generated by self-reference, with every banked
  termination an instance" is the MECHANISM-grade telos statement: physics-words-removable prose
  over the cited banked theorems, NEVER a load-bearing theorem. The IDENTIFICATION "self-reference
  is the ground of all physics" is N414's flagged prose (the ground posit, never a theorem, never
  derived-from-below — the category-error guard). Arc N is structural — no numerical claim, no
  empirical number (G2).

  PHYSICS-WORDS-REMOVABLE (docs/STANDARD.md §2). Delete "gather / physics / monad / state /
  glue / confine / obstruction / fold / self-reference": over derived `ℚ` and `O ℚ = CD (H ℚ)`,
  the theorems say that for the single trilinear associator `assoc` on `O ℚ`, six a-priori-
  different non-vanishing/non-composition statements are pairwise equivalent (all equivalent to
  `∃ a b c, assoc a b c ≠ 0`); that the distinguished element `J = (0,1)` of `Dbl ℚ` being
  distinct from its conjugate (`J ≠ star J`) forces every one of them; and that one concrete
  triple witnesses them all. Pure statements about ONE trilinear form and ONE distinguished
  element. No theorem STATEMENT needs a physics word.

  NOT FREE-FLOATING (docs/STANDARD.md §3). Every theorem TYPE mentions the banked concrete
  objects — the banked `barMultDefect` / `GluesGlobally` / `AssocLocusNonempty` / `SectorConfines`
  / `SectorAssoc` / `WorldsGlue` / `assoc` on `O ℚ`, and the banked `Dbl.J` on `Dbl ℚ`. NOT a
  `List.TFAE` over abstract propositions, NOT an abstract `CategoryTheory` cocycle: every clause
  is octonion-SPECIFIC, on the banked tower.

  NOT A HOLLOW-AND (docs/RUNBOOK.md, N390 standard). This is NOT `N411.capstone ∧ N412.capstone ∧
  N413.capstone ∧ N414.capstone`. The two level⟺locus welds (§1), the six-way TFAE (§2), the
  cross-level seed forcing to the monad/state levels (§3), and the one-witness-at-monad/state (§4)
  are GENUINE NEVER-BANKED cross-ties: no single arc-N node stated that the monad, state, faces,
  and fold-seed levels are ONE proposition, nor that the fold seed forces the monad and state
  levels. C440 bites 1 = 440.

  DEPENDENCIES (all banked, foundations-only): N411 `TowerGatherBarMonad` (`barMultDefect`,
  `o_barMultDefect_eq_assoc`); N412 `TowerGatherPhysicalState` (`GluesGlobally`,
  `confines_iff_some_unphysical`); N413 `TowerGatherObstructionUnification` (`AssocLocusNonempty`,
  `confinement_is_obstruction`, `cascade_stop_is_obstruction`, `curvature_somewhere_is_obstruction`,
  `assoc`); N414 `GatherFoldGroundGenerativity` (`foldRoot_selfOpposed_forces_locus`,
  `foldRoot_selfOpposed_Q`); N5b `Alternative` (`assoc_nonvanishing`); arc-E `ConfinementMassGap`
  (`coloured_witness_not_flat`); N385 `ConfinementCriterion` (`SectorConfines`, `SectorAssoc`).
  Ground field the cascade ring `ℚ`; NOT Mathlib-ℝ as content; Mathlib is MACHINERY only (`TFAE`).

  Foundations-only: no posited axiom, no proof-hole, no kernel-trust bypass, no heartbeat
  inflation, no Mathlib number system as content, no bridge.
-/
import Phys.Algebra.TowerGatherPhysicalState
import Phys.Algebra.GatherFoldGroundGenerativity
import Mathlib.Tactic

namespace Phys.Algebra

open Phys.Cascade
open Phys.Cascade.CD

noncomputable section

attribute [local instance] CD.narCD CD.srCD

/-! ## §1 — THE TWO NEW LEVEL⟺LOCUS WELDS (never banked). -/

/-- ★ THE MONAD LEVEL ⟺ THE LOCUS (never banked). The gather is a genuinely NON-STRICT monad on
    `O ℚ` — some two standpoints' worlds fail to compose strictly, `∃ a b, barMultDefect a b ≠ 0`
    (N411) — IF AND ONLY IF the common associator locus `AssocLocusNonempty` is nonempty. N411
    tied the μ-comparison defect to the associator POINTWISE (`o_barMultDefect_eq_assoc`); this
    welds the EXISTENCE of a nonzero defect (the monad's non-strictness) to the SHARED locus.
    Physics-words-removable: `(∃ a b, (fun x => assoc a b x) ≠ 0) ↔ ∃ a b c, assoc a b c ≠ 0`. -/
theorem monad_nonstrict_iff_locus :
    (∃ a b : O ℚ, barMultDefect a b ≠ 0) ↔ AssocLocusNonempty := by
  constructor
  · rintro ⟨a, b, hab⟩
    rw [o_barMultDefect_eq_assoc] at hab
    obtain ⟨x, hx⟩ := Function.ne_iff.mp hab
    exact ⟨a, b, x, hx⟩
  · rintro ⟨a, b, c, h⟩
    refine ⟨a, b, ?_⟩
    rw [o_barMultDefect_eq_assoc]
    exact Function.ne_iff.mpr ⟨c, h⟩

/-- ★ THE STATE LEVEL ⟺ THE LOCUS (never banked). The physical state stratum on `O ℚ` is PROPER
    — some standpoint is NOT physical, `∃ a, ¬ GluesGlobally a` (N412, the genuine selection rule)
    — IF AND ONLY IF the common associator locus is nonempty. N412 tied confinement to an
    unphysical state (`confines_iff_some_unphysical`); this welds the unphysical-state existence
    (the selection rule) to the SHARED locus, via `confinement_is_obstruction`. Physics-words-
    removable: `(∃ a, ¬ (∀ b, L_a∘L_b = L_{a·b})) ↔ ∃ a b c, assoc a b c ≠ 0`. -/
theorem state_selection_iff_locus :
    (∃ a : O ℚ, ¬ GluesGlobally a) ↔ AssocLocusNonempty := by
  rw [← confines_iff_some_unphysical, confinement_is_obstruction]

/-! ## §2 — THE GRAND TFAE: six readings of the ONE obstruction are ONE proposition. -/

/-- ★★ THE ARC-N GRAND EQUIVALENCE. SIX a-priori-different readings of the octonion obstruction
    — spanning all of arc N's levels — are pairwise EQUIVALENT, hence ONE proposition:
      (1) `AssocLocusNonempty`        — the common obstruction locus (N413);
      (2) `SectorConfines (O ℚ)`      — confinement (arc I, N385);
      (3) `¬ SectorAssoc (O ℚ)`       — the cascade stop (N2);
      (4) `∃ a b, ¬ WorldsGlue a b`   — curvature-somewhere (arc E);
      (5) `∃ a b, barMultDefect a b ≠ 0` — the gather monad's non-strictness (N411);
      (6) `∃ a, ¬ GluesGlobally a`    — the state stratum's properness / selection rule (N412).
    N413 banked (1)⟺(2)⟺(3)⟺(4); §1 adds (1)⟺(5) and (1)⟺(6). This is the consolidation: physics
    is where the gather fails, and "where the gather fails" is ONE place read six ways. NOT a
    HOLLOW-AND — a genuine TFAE welding all arc-N levels through the ONE locus. -/
theorem gather_all_levels_tfae :
    List.TFAE
      [ AssocLocusNonempty,                                  -- (1) the locus (N413)
        SectorConfines (O ℚ),                                -- (2) confinement (arc I)
        ¬ SectorAssoc (O ℚ),                                 -- (3) cascade stop (N2)
        (∃ a b : O ℚ, ¬ WorldsGlue a b),                     -- (4) curvature (arc E)
        (∃ a b : O ℚ, barMultDefect a b ≠ 0),               -- (5) monad non-strict (N411)
        (∃ a : O ℚ, ¬ GluesGlobally a) ] := by               -- (6) state selection (N412)
  tfae_have 1 ↔ 2 := confinement_is_obstruction.symm
  tfae_have 1 ↔ 3 := cascade_stop_is_obstruction.symm
  tfae_have 1 ↔ 4 := curvature_somewhere_is_obstruction.symm
  tfae_have 1 ↔ 5 := monad_nonstrict_iff_locus.symm
  tfae_have 1 ↔ 6 := state_selection_iff_locus.symm
  tfae_finish

/-! ## §3 — THE CROSS-LEVEL GENERATIVITY EXTENSION: the fold seed forces every level. -/

/-- ★★ THE FOLD SEED FORCES THE MONAD AND STATE LEVELS (never banked — N414 only forced the N413
    faces). If the rung-1 fold-root generator is self-opposed (`J ≠ star J`, the SAME char ≠ 2
    that gives the fold's self-blindness, N414's seed) then the gather monad is genuinely
    NON-STRICT (N411 level) AND the state stratum is PROPER (N412 level). The single seed forces
    the obstruction at the monad and state levels, extending N414's `foldRoot_selfOpposed_
    forces_all_four` (which reached only the N413 faces). -/
theorem foldRoot_forces_monad_and_state
    (hJ : (Dbl.J : Dbl ℚ) ≠ star Dbl.J) :
    (∃ a b : O ℚ, barMultDefect a b ≠ 0) ∧ (∃ a : O ℚ, ¬ GluesGlobally a) := by
  have hloc := foldRoot_selfOpposed_forces_locus hJ
  exact ⟨monad_nonstrict_iff_locus.mpr hloc, state_selection_iff_locus.mpr hloc⟩

/-- ★★ THE FOLD SEED FORCES ALL SIX TFAE LEVELS AT ONCE. From the fold-root's self-opposition on
    the fold's own rational line (`foldRoot_selfOpposed_Q`, non-vacuous), the whole arc-N
    obstruction fires at every level: the locus is nonempty, the sector confines, `O ℚ` is
    non-associative, some pair fails to glue, the gather monad is non-strict, and the state
    stratum is proper. The ONE fold seed generates the entire six-way structure. -/
theorem foldRoot_forces_all_levels :
    AssocLocusNonempty
    ∧ SectorConfines (O ℚ)
    ∧ (¬ SectorAssoc (O ℚ))
    ∧ (∃ a b : O ℚ, ¬ WorldsGlue a b)
    ∧ (∃ a b : O ℚ, barMultDefect a b ≠ 0)
    ∧ (∃ a : O ℚ, ¬ GluesGlobally a) := by
  have hloc := foldRoot_selfOpposed_forces_locus foldRoot_selfOpposed_Q
  exact ⟨hloc,
    confinement_is_obstruction.mpr hloc,
    cascade_stop_is_obstruction.mpr hloc,
    curvature_somewhere_is_obstruction.mpr hloc,
    monad_nonstrict_iff_locus.mpr hloc,
    state_selection_iff_locus.mpr hloc⟩

/-! ## §4 — ONE WITNESS AT EVERY LEVEL. -/

/-- ★ THE ONE WITNESS AT THE MONAD LEVEL. The single banked non-associating triple's leading
    pair `(ι(ιJ), ι(e₂))` realizes the gather monad's non-strictness — its μ-comparison defect
    `barMultDefect` is nonzero (banked `assoc_nonvanishing`). -/
theorem witness_monad_level :
    barMultDefect (CD.iota (ιJ ℚ) : O ℚ) (CD.iota (CD.e2 : H ℚ)) ≠ 0 := by
  rw [o_barMultDefect_eq_assoc]
  exact Function.ne_iff.mpr ⟨(CD.e2 : O ℚ), assoc_nonvanishing⟩

/-- ★ THE ONE WITNESS AT THE STATE LEVEL. The same standpoint `ι(ιJ)` is NOT physical — its
    world fails to glue with `ι(e₂)` (banked `coloured_witness_not_flat`), so it is excluded by
    the selection rule. The single witness that realizes N413's four faces also realizes the
    monad and state levels — ONE object fires at every arc-N level. -/
theorem witness_state_level :
    ¬ GluesGlobally (CD.iota (ιJ ℚ) : O ℚ) := by
  intro h
  exact coloured_witness_not_flat (h (CD.iota (CD.e2 : H ℚ)))

/-! ## §5 — THE CAPSTONE. -/

/-- ★★★ THE ARC-N CONSOLIDATION (arc-N N5, the LAST node of arc N). The whole arc-N structure as
    ONE theorem — physics is the local→global obstruction of the gather, generated by
    self-reference, with every banked termination an instance:
      • THE SIX-WAY EQUIVALENCE (`gather_all_levels_tfae`): the locus, confinement (I), the
        cascade stop (N2), curvature (E), the monad non-strictness (N411), and the state selection
        (N412) are ONE proposition;
      • THE FOLD-SEED FORCING (`foldRoot_forces_all_levels`): the fold-root's self-opposition —
        the SAME char ≠ 2 that gives the fold's self-blindness — forces every one of the six
        levels at once;
      • ONE WITNESS AT EVERY LEVEL (`witness_monad_level`, `witness_state_level`): the single
        non-associating triple realizes the monad and state levels too.
    ⚠ THEOREM-route for the STRUCTURE; the reading "physics is where the gather fails, generated
    by the fold" is the MECHANISM-grade telos statement (physics-words-removable prose over the
    cited banked theorems), never a load-bearing theorem. The IDENTIFICATION "self-reference is
    the ground" is N414's flagged prose, never derived-from-below (the category-error guard).
    Physics-words-removable: pure statements about ONE trilinear associator and ONE distinguished
    element on the banked tower. -/
theorem arcN_consolidation :
    List.TFAE
      [ AssocLocusNonempty,
        SectorConfines (O ℚ),
        ¬ SectorAssoc (O ℚ),
        (∃ a b : O ℚ, ¬ WorldsGlue a b),
        (∃ a b : O ℚ, barMultDefect a b ≠ 0),
        (∃ a : O ℚ, ¬ GluesGlobally a) ]
    ∧ (AssocLocusNonempty
        ∧ SectorConfines (O ℚ)
        ∧ (¬ SectorAssoc (O ℚ))
        ∧ (∃ a b : O ℚ, ¬ WorldsGlue a b)
        ∧ (∃ a b : O ℚ, barMultDefect a b ≠ 0)
        ∧ (∃ a : O ℚ, ¬ GluesGlobally a))
    ∧ (barMultDefect (CD.iota (ιJ ℚ) : O ℚ) (CD.iota (CD.e2 : H ℚ)) ≠ 0
        ∧ ¬ GluesGlobally (CD.iota (ιJ ℚ) : O ℚ)) :=
  ⟨gather_all_levels_tfae,
   foldRoot_forces_all_levels,
   ⟨witness_monad_level, witness_state_level⟩⟩

end

end Phys.Algebra
