/-
# N235 — THE g₂-INVARIANT FORMS δ, φ, ψ ARE g₂-INVARIANT (the generator toolkit for the FFT ascent)

DISSOLUTION-TOOLKIT node for N234's genuine W1 wall (irreducibility of the 27, `tracelessSym`).
N234 MEASURED that the two banked levers closing the other three atoms of `7 ⊗ 7 = 1 ⊕ 7 ⊕ 14 ⊕ 27`
(the so(n) dimension-bound and the prime-collapse) BOTH provably die on `27 = 3³`, and REFRAMED the
irreducibility to the g₂ INVARIANT-THEORY endomorphism count `dim (ImO^{⊗4})^{g₂} = dim End_{g₂}(7⊗7)
= 4`, which with N233's four DISTINCT-dimension summands forces `Σ mᵢ² = 4` over ≥4 terms ⟹ four
multiplicity-one irreducibles ⟹ the 27 irreducible. That count is the g₂ First Fundamental Theorem
of invariant theory, whose GENERATORS are exactly two DERIVED trunk objects:
  • the metric  δ = `gForm`  (the Born self-overlap, N24), and
  • the associative 3-form  φ = `assoc3`  (the imaginary octonion product, N209) — the SAME
    non-associativity object that stops the cascade / IS the gather obstruction,
together with its Hodge dual ψ = `coassoc4` (the coassociative 4-form, N210).

THE MISSING STRUCTURAL FACT the FFT count needs, and the SMALLEST forward step of it, is that these
generators actually LIE in the g₂-invariant space — i.e. that δ, φ, ψ are g₂-INVARIANT forms:

      δ:  ⟨D x, y⟩ + ⟨x, D y⟩ = 0                                    (bornForm_g2_invariant)
      φ:  φ(D x, y, z) + φ(x, D y, z) + φ(x, y, D z) = 0             (assoc3_g2_invariant)
      ψ:  ψ(D x,y,z,w)+ψ(x,D y,z,w)+ψ(x,y,D z,w)+ψ(x,y,z,D w) = 0    (coassoc4_g2_invariant)

for every derivation `D ∈ derivationLieQ = g₂`. Without these invariances one cannot even STATE
"the degree-≤4 g₂-invariants generated by δ and φ," so they are a REQUIRED step of the named ascent
(a toolkit brick, W1 step 1 / W9.8), NOT a lateral wander. This node banks exactly that toolkit; the
deep FFT count `dim (ImO^{⊗4})^{g₂} = 4 ⟹ tracelessSym irreducible` is childed as the dedicated
dissolution node it serves.

## The dissolution (why this is trunk-native, forced, and cheap)
Each invariance is FORCED by two banked facts, no coordinate grind:
  • δ:  `gFormQ_skew` (N24) — every derivation is skew-adjoint for the Born form — is LITERALLY the
    δ-invariance. (A derivation kills the self-conjugate `x·star y + y·star x`.)
  • φ:  the last two slots combine by the CROSS-PRODUCT Leibniz law `derivationLieQ_octCross_leibniz`
    (N207, `D (y×z) = (D y)×z + y×(D z)`) into `⟨x, D(y×z)⟩`; the whole is then
    `⟨D x, y×z⟩ + ⟨x, D(y×z)⟩ = 0` by δ-invariance (`gFormQ_skew`). One symmetry algebra fixing both
    faces of the exceptional structure (the product AND the cross product) — N207's "two faces."
  • ψ:  the associator `[x,y,z] = (x·y)·z − x·(y·z)` obeys the Leibniz rule (`assoc_deriv_leibniz`,
    it is built from products only); the first three slots combine into `⟨D[x,y,z], w⟩`, and the whole
    is `⟨D[x,y,z], w⟩ + ⟨[x,y,z], D w⟩ = 0` again by δ-invariance. ψ = *φ inherits its invariance from φ.

ONE CAUSE, MANY TERMINATIONS: the SAME Born self-overlap/positivity skew-adjointness (δ-invariance,
N24) that made every derivation live in `so(7)` also pins the g₂-invariance of the associative 3-form
φ and the coassociative 4-form ψ — the generators whose contractions the FFT count contracts to force
the 27 irreducible. The gather obstruction (octonion non-associativity, carried by φ) IS the object
that fixes the invariant algebra.

## STANDARD compliance (the words-removable test, §2)
NO physics words in any theorem STATEMENT. Delete every comment and the mathematics stands: over `ℚ`
and `O ℚ = CD (H ℚ)`, for every `D ∈ derivationLieQ` the bilinear `gForm`, the trilinear `assoc3`, and
the quadrilinear `coassoc4` satisfy the derivation/Leibniz invariance identity above. `gForm`, `assoc3`,
`coassoc4`, `octCross`, `assoc`, `derivationLieQ` are all DERIVED trunk objects; ℚ is the coefficient
field the statements are WRITTEN IN (the N24/N207/N209/N210 precedent). The TYPE of every headline
theorem mentions the banked tower objects (`gForm`/`assoc3`/`coassoc4`/`derivationLieQ`/`octCross`/`assoc`
on `O ℚ`) — no free-floating carrier-agnostic statement.

DERIVED from the trunk (`gFormQ_skew` N24; `derivationLieQ_octCross_leibniz`/`octCross_deriv_leibniz`
N207; `gForm_add_right`/`gForm_add_left` N24; `assoc3` N209; `coassoc4` N210; `assoc` N5b;
`derivationLieQ`/`IsDerivQ` N16–N21; `octCross` N206; standard additive-group MACHINERY on the DERIVED
objects, STANDARD §3), NO posited G₂ / invariant theory / calibration / representation theory as
content, NO Mathlib ℝ/ℂ as content, NO bridge.
-/
import Phys.Algebra.OctonionCoassociative4Form
import Phys.Algebra.OctonionCrossProductDerivation
import Phys.Algebra.DerivationAutCompact
import Phys.Algebra.DerivationCompact

namespace Phys.Algebra

open Phys.Cascade Phys.Cascade.CD

attribute [local instance] CD.narCD CD.srCD dblModuleQ cdModuleQ

noncomputable section

/-! ## δ (the metric = Born self-overlap `gForm`) is g₂-invariant. -/

/-- ★ δ-INVARIANCE: the Born self-overlap form is g₂-invariant — for every derivation
    `D ∈ derivationLieQ` and all `x, y`, `⟨D x, y⟩ + ⟨x, D y⟩ = 0`. This is LITERALLY the banked
    skew-adjointness `gFormQ_skew` (N24): a derivation kills the self-conjugate `x·star y + y·star x`.
    δ is the degree-2 generator of the g₂-invariant algebra of the 7 (= `ImO`). -/
theorem bornForm_g2_invariant (D : derivationLieQ) (x y : O ℚ) :
    gForm ((D : Module.End ℚ (O ℚ)) x) y + gForm x ((D : Module.End ℚ (O ℚ)) y) = 0 :=
  gFormQ_skew (D : Module.End ℚ (O ℚ)) D.2 x y

/-! ## The associator `[x,y,z]` obeys the Leibniz rule under any derivation. -/

/-- ★ ASSOCIATOR LEIBNIZ: for any ℚ-linear derivation `D` (Leibniz law `IsDerivQ`), the associator
    `assoc x y z = (x·y)·z − x·(y·z)` — being built from products only — satisfies the third-order
    Leibniz identity `D [x,y,z] = [D x, y, z] + [x, D y, z] + [x, y, D z]`. Forced by distributing the
    product Leibniz law twice; no associativity, no coordinates. -/
theorem assoc_deriv_leibniz (D : Module.End ℚ (O ℚ)) (hD : IsDerivQ D) (x y z : O ℚ) :
    D (assoc x y z) = assoc (D x) y z + assoc x (D y) z + assoc x y (D z) := by
  unfold assoc
  rw [map_sub, hD (x * y) z, hD x (y * z), hD x y, hD y z]
  simp only [add_mul, mul_add]
  abel

/-- The associator Leibniz identity specialised to a member `D ∈ derivationLieQ = g₂`. -/
theorem assoc_deriv_leibniz_lieQ (D : derivationLieQ) (x y z : O ℚ) :
    (D : Module.End ℚ (O ℚ)) (assoc x y z)
      = assoc ((D : Module.End ℚ (O ℚ)) x) y z + assoc x ((D : Module.End ℚ (O ℚ)) y) z
        + assoc x y ((D : Module.End ℚ (O ℚ)) z) :=
  assoc_deriv_leibniz (D : Module.End ℚ (O ℚ)) D.2 x y z

/-! ## φ (the associative 3-form `assoc3 = ⟨x, y×z⟩`) is g₂-invariant. -/

/-- ★★ φ-INVARIANCE: the associative 3-form is g₂-invariant — for every derivation
    `D ∈ derivationLieQ` and all `x, y, z`,
    `φ(D x, y, z) + φ(x, D y, z) + φ(x, y, D z) = 0`.
    The last two slots combine via the cross-product Leibniz law (N207,
    `D (y×z) = (D y)×z + y×(D z)`) into `⟨x, D(y×z)⟩`; the whole is then
    `⟨D x, y×z⟩ + ⟨x, D(y×z)⟩ = 0` by δ-invariance (`gFormQ_skew`, N24). φ is the degree-3 generator
    of the g₂-invariant algebra of the 7 — the calibration whose stabiliser IS g₂. -/
theorem assoc3_g2_invariant (D : derivationLieQ) (x y z : O ℚ) :
    assoc3 ((D : Module.End ℚ (O ℚ)) x) y z
      + assoc3 x ((D : Module.End ℚ (O ℚ)) y) z
      + assoc3 x y ((D : Module.End ℚ (O ℚ)) z) = 0 := by
  unfold assoc3
  -- Leibniz for the cross product (N207): D(y×z) = (Dy)×z + y×(Dz)
  have hleib : octCross ((D : Module.End ℚ (O ℚ)) y) z + octCross y ((D : Module.End ℚ (O ℚ)) z)
      = (D : Module.End ℚ (O ℚ)) (octCross y z) :=
    (derivationLieQ_octCross_leibniz D y z).symm
  -- combine the last two terms via right-additivity of gForm
  have h2 : gForm x (octCross ((D : Module.End ℚ (O ℚ)) y) z)
              + gForm x (octCross y ((D : Module.End ℚ (O ℚ)) z))
            = gForm x ((D : Module.End ℚ (O ℚ)) (octCross y z)) := by
    rw [← gForm_add_right, hleib]
  rw [add_assoc, h2]
  -- now: ⟨D x, y×z⟩ + ⟨x, D (y×z)⟩ = 0 — skew-adjointness of D for gForm (N24)
  exact gFormQ_skew (D : Module.End ℚ (O ℚ)) D.2 x (octCross y z)

/-! ## ψ (the coassociative 4-form `coassoc4 = ⟨[x,y,z], w⟩`) is g₂-invariant. -/

/-- ★★ ψ-INVARIANCE: the coassociative 4-form ψ = *φ is g₂-invariant — for every derivation
    `D ∈ derivationLieQ` and all `x, y, z, w`,
    `ψ(D x,y,z,w) + ψ(x,D y,z,w) + ψ(x,y,D z,w) + ψ(x,y,z,D w) = 0`.
    The first three slots combine via the associator Leibniz law (`assoc_deriv_leibniz_lieQ`) into
    `⟨D[x,y,z], w⟩`; the whole is then `⟨D[x,y,z], w⟩ + ⟨[x,y,z], D w⟩ = 0` by δ-invariance
    (`gFormQ_skew`, N24). The Hodge dual ψ = *φ inherits its g₂-invariance from φ. -/
theorem coassoc4_g2_invariant (D : derivationLieQ) (x y z w : O ℚ) :
    coassoc4 ((D : Module.End ℚ (O ℚ)) x) y z w
      + coassoc4 x ((D : Module.End ℚ (O ℚ)) y) z w
      + coassoc4 x y ((D : Module.End ℚ (O ℚ)) z) w
      + coassoc4 x y z ((D : Module.End ℚ (O ℚ)) w) = 0 := by
  unfold coassoc4
  have hleib := assoc_deriv_leibniz_lieQ D x y z
  -- combine first three coassoc4 terms into ⟨D[x,y,z], w⟩
  have h3 : gForm (assoc ((D : Module.End ℚ (O ℚ)) x) y z) w
              + gForm (assoc x ((D : Module.End ℚ (O ℚ)) y) z) w
              + gForm (assoc x y ((D : Module.End ℚ (O ℚ)) z)) w
            = gForm ((D : Module.End ℚ (O ℚ)) (assoc x y z)) w := by
    rw [← gForm_add_left, ← gForm_add_left, ← hleib]
  -- δ-invariance (N24): ⟨D[x,y,z], w⟩ + ⟨[x,y,z], D w⟩ = 0
  have hskew := gFormQ_skew (D : Module.End ℚ (O ℚ)) D.2 (assoc x y z) w
  linarith [h3, hskew]

/-! ## Non-vacuity (W8): the invariant forms are GENUINELY nonzero — the invariance is not vacuous. -/

/-- W8 NON-VACUITY ANCHOR: the associative 3-form φ takes the value `1` on the derived orthonormal
    triple `(u1, u2, u1×u2)` (the banked witness `assoc3_witness_swapped`, N209). φ is therefore NOT
    the zero form, so its g₂-invariance (`assoc3_g2_invariant`) is genuine content, not a vacuous
    "invariance of 0." -/
theorem invariantForms_nonvacuity : assoc3 u1 u2 (octCross u1 u2) = 1 :=
  assoc3_witness_swapped

/-- ★★★ THE GENERATOR TOOLKIT, BUNDLED: the three derived invariant forms — the metric δ = `gForm`,
    the associative 3-form φ = `assoc3`, and the coassociative 4-form ψ = `coassoc4` — are ALL
    g₂-invariant (invariant under every derivation `D ∈ derivationLieQ`), and φ is genuinely nonzero.
    These are the generators of the g₂-invariant algebra of the fundamental 7 (= `ImO`) whose degree-4
    contractions the First Fundamental Theorem count contracts to force `dim (ImO^{⊗4})^{g₂} = 4` and
    hence the irreducibility of the 27 (`tracelessSym`) — the dedicated dissolution node this toolkit
    serves. -/
theorem invariant_forms_g2_invariant_toolkit :
    (∀ (D : derivationLieQ) (x y : O ℚ),
        gForm ((D : Module.End ℚ (O ℚ)) x) y + gForm x ((D : Module.End ℚ (O ℚ)) y) = 0)
    ∧ (∀ (D : derivationLieQ) (x y z : O ℚ),
        assoc3 ((D : Module.End ℚ (O ℚ)) x) y z + assoc3 x ((D : Module.End ℚ (O ℚ)) y) z
          + assoc3 x y ((D : Module.End ℚ (O ℚ)) z) = 0)
    ∧ (∀ (D : derivationLieQ) (x y z w : O ℚ),
        coassoc4 ((D : Module.End ℚ (O ℚ)) x) y z w + coassoc4 x ((D : Module.End ℚ (O ℚ)) y) z w
          + coassoc4 x y ((D : Module.End ℚ (O ℚ)) z) w + coassoc4 x y z ((D : Module.End ℚ (O ℚ)) w) = 0)
    ∧ assoc3 u1 u2 (octCross u1 u2) ≠ 0 :=
  ⟨bornForm_g2_invariant, assoc3_g2_invariant, coassoc4_g2_invariant,
    by rw [invariantForms_nonvacuity]; norm_num⟩

end

end Phys.Algebra
