/-
# N260 — THE GATHER TEAR REGENERATES THE AMBIENT

Over the DERIVED octonion rung `O ℚ = CD (H ℚ)`, fundamental 7 = `ImO`, inside the single derived
`so(7) = skewAdjointLieSubalgebra bornBil` (the gather tear `so(7) = 14 (Der O) ⊕ 7 (crossEmb)`,
N225): the gather-tear fundamental-7 (`range crossEmb`) LIE-GENERATES the WHOLE ambient. The 14-dim
derivation algebra g₂ (`range imRepL`, the adjoint the field POSITS as the structure group) is
GENERATED by brackets of the 7. Owner-authorized gather-side front, under the LOCK, gather-native
(`crossEmb` = the N225 gather-tear embedding 7 ↪ so(7); NOT the parked J₃(O) invariant-tower ascent).

THE DISSOLUTION (STANDARD §0): the field POSITS the structure/derivation group g₂ (or a GUT) as a
GIVEN container matter embeds in. The theory INVERTS + DISSOLVES it: the ambient `so(7)` is DERIVED
FIRST (gather tear, simple, N225), and the 14-dim derivation algebra is GENERATED by brackets of the
fold's own tear directions (the 7). No containing group posited — the ambient closes on itself from
the tear. DEEPER than the deferred "12→21 SM-factors-fill-so7" (the standard-physics FACTOR framing,
which needs the ugly `su(3)+su(2) → g₂(14)` coordinate rank — no clean structural proof). The tear
framing (7→21) is the fold-native object and closes CLEAN via g₂-irreducibility.

ONE CAUSE MANY TERMINATIONS: the SAME g₂-irreducibility of the fundamental 7 (here the adjoint-14
version `imRepL_range_no_proper_invariant`) that forces atom-irreducibility elsewhere here forces
the tear's brackets to REGENERATE the entire simple ambient — one simplicity fact, the whole 21.

THE OBJECTS (all derived, foundations-only):
  ⭐⭐  `bracket_cross_qI` — the witness bracket in the banked qI calculus.
  ⭐⭐  `witness_traceForm_eq` — `traceForm7 (witness) (imRep DI) = -12` (`decide` on integers).
  ⭐⭐  `traceForm7_crossOp_imRep_DI` — `traceForm7 (crossOp c) (imRep DI) = 0` for ALL c (7 ⟂ 14).
  ⭐⭐  `proj14_witness_ne_zero` — `proj14 ⁅crossOp (imBasis 1), crossOp (imBasis 2)⁆ ≠ 0` (W8 teeth).
  ⭐⭐  `adEnd_bracket_cross` — the g₂-equivariance of a tear-bracket (Jacobi + intertwine).
  ⭐⭐⭐ `range_imRepL_le_lieSpan` — the adjoint-14 g₂ REGENERATED: `range imRepL ≤ (lieSpan …)`.
  ⭐⭐⭐ `crossEmb_lieSpan_eq_so7` — THE HEADLINE: the tear-7 Lie-generates all of so(7).
  ⭐⭐  `finrank_lieSpan_crossEmb` — `= 21` (W8 non-vacuity: fills all 21 dims).
  ⭐⭐⭐ `gather_tear_generates_so7` — capstone.

⚠ COMPLEX FIELD METALANGUAGE (ROADMAP N242 warning light, still lit): `crossEmb`/`crossOp`/`imRepL`/
`imRep`/`proj14`/`traceForm7`/`skewAdjointLieSubalgebra bornBil` stay DERIVED REAL; `LieSubalgebra`/
`lieSpan`/`⁅·,·⁆`/`finrank`/`span` are Mathlib machinery; no `Algebra ℚ (Dbl ℚ)`, no `TensorProduct`,
no `ℚ[i]`-as-ground.

FREE-FLOATING check (SOUL rail): every headline TYPE mentions the banked tower objects — the CONCRETE
lieSpan of the banked fundamental-7 tear of `O ℚ`, NOT a carrier-agnostic "irreducible module
generates its ambient". PHYSICS-WORDS-REMOVABLE: delete gauge/colour/isospin/structure-group — the
pure statement "the Lie subalgebra generated by `range crossEmb` (dim 7) is the full 21-dim
`skewAdjointLieSubalgebra bornBil`, and `range imRepL` (dim 14) is contained in it" stands.
-/
import Phys.Algebra.TowerGatherSharedIsospinCartan
import Phys.Algebra.TowerGatherIsometry

open scoped Classical BigOperators
open LieSubalgebra

namespace Phys.Algebra

open Phys.Cascade Phys.Cascade.CD
open LinearMap (BilinForm)

-- Instance-search budget bump (instance search only, NOT the proof kernel) — the banked
-- N255/N257/N258/N259 precedent for the End-of-ImO / octonion-tower instance diamonds.
set_option synthInstance.maxHeartbeats 400000

/-! ## (A) The generated Lie subalgebra and the ambient. -/

/-- `traceForm7` is additive in its left argument. -/
theorem traceForm7_add_left (X Y Z : Module.End ℚ ImO) :
    traceForm7 (X + Y) Z = traceForm7 X Z + traceForm7 Y Z := by
  show LinearMap.trace ℚ ImO ((X + Y) * Z) = _
  rw [add_mul, map_add]

/-- `so7L` — the ambient `so(7)` as a Lie subalgebra; its carrier submodule is the banked
    `bornBil.skewAdjointSubmodule` (definitionally). -/
noncomputable abbrev so7L : LieSubalgebra ℚ (Module.End ℚ ImO) := skewAdjointLieSubalgebra bornBil

/-- `lieGenCross` — the Lie subalgebra GENERATED by the gather-tear fundamental-7
    (`range crossEmb`, N225). -/
noncomputable def lieGenCross : LieSubalgebra ℚ (Module.End ℚ ImO) :=
  LieSubalgebra.lieSpan ℚ (Module.End ℚ ImO) (↑(LinearMap.range crossEmb))

/-- The generators sit inside the generated subalgebra. -/
theorem range_crossEmb_le_lieGenCross :
    (LinearMap.range crossEmb : Submodule ℚ (Module.End ℚ ImO)) ≤ lieGenCross.toSubmodule := by
  intro x hx
  exact LieSubalgebra.subset_lieSpan (hx : x ∈ (↑(LinearMap.range crossEmb) : Set _))

/-- ★ (1) `lieGenCross ≤ so7`: the tear directions are skew-adjoint, and so(7) is a Lie subalgebra
    containing them. -/
theorem lieGenCross_le_so7 : lieGenCross ≤ so7L := by
  apply LieSubalgebra.lieSpan_le.mpr
  intro x hx
  exact crossEmb_range_le_so7' hx

/-! ## (B) The witness bracket in the banked integer-matrix calculus. -/

/-- ★★ The tear-bracket `⁅crossOp (imBasis 1), crossOp (imBasis 2)⁆` in the banked qI calculus:
    the End-bracket unfolds (defeq) to the commutator, then `qI_comp`/`qI_sub` collapse it to a
    single integer-matrix `qI`. -/
theorem bracket_cross_qI :
    (⁅crossOp (imBasis 1), crossOp (imBasis 2)⁆ : Module.End ℚ ImO)
      = qI (sub7 (mul7 (Km 1) (Km 2)) (mul7 (Km 2) (Km 1))) := by
  rw [crossOp_imBasis_eq_qI, crossOp_imBasis_eq_qI]
  show qI (Km 1) * qI (Km 2) - qI (Km 2) * qI (Km 1) = _
  rw [qI_comp, qI_comp, qI_sub]

/-- ★★ The 14-part witness value: `traceForm7 (witness) (imRep DI) = -12` (banked qI trace,
    `decide` on integers). NONZERO — so the witness has a genuine adjoint-14 component. -/
theorem witness_traceForm_eq :
    traceForm7 (⁅crossOp (imBasis 1), crossOp (imBasis 2)⁆ : Module.End ℚ ImO) (imRep DI) = -12 := by
  rw [bracket_cross_qI, imRep_DI_eq_qI, traceForm7_qI]; decide

/-! ## (C) 7 ⟂ 14: the fundamental-7 is trace-orthogonal to the isospin Cartan `imRep DI`. -/

/-- The linear functional `a ↦ traceForm7 (imRep DI) (crossEmb a)` vanishes: on the banked basis
    `bb` it reduces (via `crossOp_imBasis_eq_qI` + `imRep_DI_eq_qI` + `traceForm7_qI`) to
    `tr7 (mul7 (Km i) Imat) = 0` for each `i` (`decide`). -/
theorem traceForm7_imRepDI_crossEmb_eq_zero :
    ((traceBil (imRep DI)).comp crossEmb) = 0 := by
  apply Module.Basis.ext bb; intro i
  show traceForm7 (imRep DI) (crossEmb (bb i)) = 0
  rw [crossEmb_apply, bb_coe, crossOp_imBasis_eq_qI, traceForm7_symm, imRep_DI_eq_qI, traceForm7_qI]
  fin_cases i <;> decide

/-- ★★ THE ORTHOGONALITY: `traceForm7 (crossOp c) (imRep DI) = 0` for ALL `c : ImO` — the
    fundamental-7 tear is trace-orthogonal to the isospin Cartan. -/
theorem traceForm7_crossOp_imRep_DI (c : ImO) :
    traceForm7 (crossOp (c : O ℚ)) (imRep DI) = 0 := by
  have h := LinearMap.congr_fun traceForm7_imRepDI_crossEmb_eq_zero c
  rw [traceForm7_symm]
  simpa [traceBil_apply] using h

/-! ## (D) The witness has nonzero adjoint-14 part (W8 teeth). -/

/-- ★★ W8 TEETH: `proj14 ⁅crossOp (imBasis 1), crossOp (imBasis 2)⁆ ≠ 0`. The functional
    `X ↦ traceForm7 X (imRep DI)` is `-12` on the witness `B`, `0` on `proj7 B` (which lies in
    `range crossEmb`, orthogonal to `imRep DI`); since `B = proj7 B + proj14 B` on `B ∈ so7`, the
    functional on `proj14 B` is `-12 ≠ 0`, so `proj14 B ≠ 0`. -/
theorem proj14_witness_ne_zero :
    proj14 (⁅crossOp (imBasis 1), crossOp (imBasis 2)⁆ : Module.End ℚ ImO) ≠ 0 := by
  set B : Module.End ℚ ImO := ⁅crossOp (imBasis 1), crossOp (imBasis 2)⁆ with hBdef
  -- B ∈ so7 (bracket of two so7 elements)
  have hB_so7 : B ∈ (bornBil).skewAdjointSubmodule := by
    have h1 : crossOp (imBasis 1 : O ℚ) ∈ so7L := crossOp_mem_so7 _ (imBasis_mem_ImO 1)
    have h2 : crossOp (imBasis 2 : O ℚ) ∈ so7L := crossOp_mem_so7 _ (imBasis_mem_ImO 2)
    exact (so7L.lie_mem h1 h2 : B ∈ so7L)
  -- functional φ X := traceForm7 X (imRep DI)
  -- φ (proj7 B) = 0 : proj7 B ∈ range crossEmb
  have hproj7_mem : proj7 B ∈ LinearMap.range crossEmb := proj7_apply_mem B
  obtain ⟨c, hc⟩ := hproj7_mem
  have hφ7 : traceForm7 (proj7 B) (imRep DI) = 0 := by
    rw [← hc, crossEmb_apply]; exact traceForm7_crossOp_imRep_DI c
  -- B = proj7 B + proj14 B  (since projSo7 B = B on so7)
  have hsplit : proj7 B + proj14 B = B := by
    rw [proj7_add_proj14]; exact projSo7_apply_skew hB_so7
  -- φ B = φ (proj7 B) + φ (proj14 B)
  have hlin : traceForm7 B (imRep DI)
      = traceForm7 (proj7 B) (imRep DI) + traceForm7 (proj14 B) (imRep DI) := by
    conv_lhs => rw [← hsplit]
    exact traceForm7_add_left _ _ _
  have hφ14 : traceForm7 (proj14 B) (imRep DI) = -12 := by
    have := witness_traceForm_eq
    rw [← hBdef] at this
    rw [hlin, hφ7, zero_add] at this
    exact this
  intro hzero
  rw [hzero] at hφ14
  simp only [show traceForm7 (0 : Module.End ℚ ImO) (imRep DI) = 0 by
    show LinearMap.trace ℚ ImO ((0 : Module.End ℚ ImO) * _) = 0
    rw [zero_mul, map_zero]] at hφ14
  norm_num at hφ14

/-! ## (E) The ⊇ engine: the adjoint-14 g₂ is regenerated from brackets of the 7. -/

/-- ★★ The g₂-EQUIVARIANCE of a tear-bracket (over `ImO`): `adEnd D` of a bracket of two tear
    operators `crossEmb a, crossEmb b` is a sum of two tear-brackets `crossEmb (imRep D a)`,
    `crossEmb (imRep D b)`, via the Jacobi identity + the banked intertwiner
    `crossOp_imRep_intertwine` (`⁅imRep D, crossOp a⁆ = crossOp (D a)`). -/
theorem adEnd_bracket_crossEmb (D : derivationLieQ) (a b : ImO) :
    adEnd D (⁅crossEmb a, crossEmb b⁆ : Module.End ℚ ImO)
      = ⁅crossEmb (imRep D a), crossEmb b⁆ + ⁅crossEmb a, crossEmb (imRep D b)⁆ := by
  simp only [crossEmb_apply]
  rw [adEnd_apply]
  rw [show ⁅imRep D, (⁅crossOp (a : O ℚ), crossOp (b : O ℚ)⁆ : Module.End ℚ ImO)⁆
        = ⁅⁅imRep D, crossOp (a : O ℚ)⁆, crossOp (b : O ℚ)⁆
          + ⁅crossOp (a : O ℚ), ⁅imRep D, crossOp (b : O ℚ)⁆⁆
        from LieRing.leibniz_lie _ _ _]
  rw [crossOp_imRep_intertwine, crossOp_imRep_intertwine]
  -- crossOp (D.val ↑a) = crossOp ↑(imRep D a)  (imRep_coe)
  rw [← imRep_coe D a, ← imRep_coe D b]

/-- The submodule generated by the adjoint-14 parts of all tear-brackets (over `ImO`). -/
noncomputable def W14 : Submodule ℚ (Module.End ℚ ImO) :=
  Submodule.span ℚ
    { Y | ∃ a b : ImO, Y = proj14 (⁅crossEmb a, crossEmb b⁆ : Module.End ℚ ImO) }

/-- Each generator of `W14` lies in the adjoint 14 `range imRepL`. -/
theorem W14_le_range_imRepL : W14 ≤ LinearMap.range imRepL := by
  apply Submodule.span_le.mpr
  rintro _ ⟨a, b, rfl⟩
  exact proj14_apply_mem _

/-- `crossEmb a ∈ lieGenCross` for every `a : ImO` (a generator of the lieSpan). -/
theorem crossEmb_mem_lieGenCross (a : ImO) : crossEmb a ∈ lieGenCross :=
  LieSubalgebra.subset_lieSpan (⟨a, rfl⟩ : crossEmb a ∈ (↑(LinearMap.range crossEmb) : Set _))

/-- A tear-bracket lies in `lieGenCross` (bracket-closed, generators inside). -/
theorem bracket_crossEmb_mem_lieGenCross (a b : ImO) :
    (⁅crossEmb a, crossEmb b⁆ : Module.End ℚ ImO) ∈ lieGenCross :=
  lieGenCross.lie_mem (crossEmb_mem_lieGenCross a) (crossEmb_mem_lieGenCross b)

/-- Each generator of `W14` lies in the generated subalgebra `lieGenCross`. The bracket `B` is in
    `lieGenCross`; `proj7 B ∈ range crossEmb ⊆ lieGenCross`; and on `B ∈ so7`,
    `proj14 B = B - proj7 B ∈ lieGenCross`. -/
theorem W14_le_lieGenCross : W14 ≤ lieGenCross.toSubmodule := by
  apply Submodule.span_le.mpr
  rintro _ ⟨a, b, rfl⟩
  set B : Module.End ℚ ImO := ⁅crossEmb a, crossEmb b⁆ with hBdef
  have hB_mem : B ∈ lieGenCross := bracket_crossEmb_mem_lieGenCross a b
  have hB_so7 : B ∈ (bornBil).skewAdjointSubmodule := lieGenCross_le_so7 hB_mem
  -- proj7 B ∈ range crossEmb ⊆ lieGenCross
  obtain ⟨c, hc⟩ := proj7_apply_mem B
  have hproj7_mem : proj7 B ∈ lieGenCross.toSubmodule := by
    rw [← hc]; exact crossEmb_mem_lieGenCross c
  -- proj14 B = B - proj7 B
  have hsplit : proj14 B = B - proj7 B := by
    have h := proj7_add_proj14 B
    rw [projSo7_apply_skew hB_so7] at h
    rw [eq_sub_iff_add_eq, add_comm]; exact h
  show proj14 B ∈ lieGenCross.toSubmodule
  rw [hsplit]
  exact Submodule.sub_mem _ hB_mem hproj7_mem

/-- `W14` is `adEnd`-invariant: `adEnd D (proj14 B) = proj14 (adEnd D B)` (`proj14_equivariant`)
    and `adEnd D B` is a sum of two tear-brackets (`adEnd_bracket_crossEmb`), whose `proj14`-parts
    are generators of `W14`. -/
theorem W14_adEnd_invariant (D : derivationLieQ) (X : Module.End ℚ ImO) (hX : X ∈ W14) :
    adEnd D X ∈ W14 := by
  induction hX using Submodule.span_induction with
  | mem Y hY =>
      obtain ⟨a, b, rfl⟩ := hY
      rw [← proj14_equivariant, adEnd_bracket_crossEmb, map_add]
      refine Submodule.add_mem _ ?_ ?_
      · exact Submodule.subset_span ⟨imRep D a, b, rfl⟩
      · exact Submodule.subset_span ⟨a, imRep D b, rfl⟩
  | zero => rw [map_zero]; exact Submodule.zero_mem _
  | add Y Z _ _ hY hZ => rw [map_add]; exact Submodule.add_mem _ hY hZ
  | smul r Y _ hY => rw [map_smul]; exact Submodule.smul_mem _ r hY

/-- `W14 ≠ ⊥`: the witness `proj14 ⁅crossOp (imBasis 1), crossOp (imBasis 2)⁆ ≠ 0` is a generator. -/
theorem W14_ne_bot : W14 ≠ ⊥ := by
  intro h
  apply proj14_witness_ne_zero
  have hmem : proj14 (⁅crossEmb (bvec 1), crossEmb (bvec 2)⁆ : Module.End ℚ ImO) ∈ W14 :=
    Submodule.subset_span ⟨bvec 1, bvec 2, rfl⟩
  rw [h, Submodule.mem_bot] at hmem
  -- crossEmb (bvec i) = crossOp (imBasis i)  (bvec i coerces to imBasis i by rfl)
  have he : (⁅crossEmb (bvec 1), crossEmb (bvec 2)⁆ : Module.End ℚ ImO)
      = ⁅crossOp (imBasis 1), crossOp (imBasis 2)⁆ := by
    simp only [crossEmb_apply]; rfl
  rw [he] at hmem
  exact hmem

/-- ★★★ THE ⊇ ENGINE — the adjoint-14 g₂ is REGENERATED from brackets of the 7:
    `range imRepL ≤ lieGenCross`. `W14 ≤ range imRepL` (dim 14), nonzero and `adEnd`-invariant, so
    by irreducibility of the adjoint 14 (`imRepL_range_no_proper_invariant`) it has dim ≥ 14, hence
    `W14 = range imRepL`; and `W14 ≤ lieGenCross`. -/
theorem range_imRepL_le_lieGenCross :
    (LinearMap.range imRepL : Submodule ℚ (Module.End ℚ ImO)) ≤ lieGenCross.toSubmodule := by
  have hW_eq : W14 = LinearMap.range imRepL := by
    refine Submodule.eq_of_le_of_finrank_le W14_le_range_imRepL ?_
    -- finrank (range imRepL) ≤ finrank W14
    have hd14 : Module.finrank ℚ (LinearMap.range imRepL) = 14 := finrank_imRep_range
    rw [hd14]
    -- goal: 14 ≤ finrank W14. Suppose not: then finrank W14 < 14; with 0 < finrank W14
    -- (W14 ≠ ⊥) this contradicts irreducibility of the adjoint 14.
    by_contra hlt
    rw [not_le] at hlt
    have hpos : 0 < Module.finrank ℚ W14 := by
      have := (Submodule.one_le_finrank_iff (S := W14)).mpr W14_ne_bot
      omega
    exact imRepL_range_no_proper_invariant W14 W14_le_range_imRepL
      (fun D X hX => W14_adEnd_invariant D X hX) hpos hlt
  rw [← hW_eq]; exact W14_le_lieGenCross

/-! ## (F) THE HEADLINE. -/

/-- ★★★ THE GATHER TEAR REGENERATES THE AMBIENT: the Lie subalgebra generated by the gather-tear
    fundamental-7 (`range crossEmb`) is the WHOLE `so(7) = skewAdjointLieSubalgebra bornBil`. -/
theorem crossEmb_lieSpan_eq_so7 : lieGenCross = so7L := by
  refine le_antisymm lieGenCross_le_so7 ?_
  -- so7 ≤ lieGenCross: range imRepL ⊔ range crossEmb = so7, both ≤ lieGenCross
  intro x hx
  have hx' : x ∈ (bornBil).skewAdjointSubmodule := hx
  rw [← sup_eq_so7] at hx'
  have hle : (LinearMap.range imRepL ⊔ LinearMap.range crossEmb :
      Submodule ℚ (Module.End ℚ ImO)) ≤ lieGenCross.toSubmodule :=
    sup_le range_imRepL_le_lieGenCross range_crossEmb_le_lieGenCross
  exact hle hx'

/-- ★★ W8 NON-VACUITY: the generated subalgebra fills all `21` dims of so(7). -/
theorem finrank_lieSpan_crossEmb : Module.finrank ℚ lieGenCross.toSubmodule = 21 := by
  rw [crossEmb_lieSpan_eq_so7]; exact finrank_so7_eq_21

/-- ★★★ CAPSTONE: the gather-tear fundamental-7 Lie-generates all of so(7); the adjoint-14 g₂ is
    regenerated from its brackets; and the generated algebra has finrank 21. -/
theorem gather_tear_generates_so7 :
    lieGenCross = so7L ∧
    (LinearMap.range imRepL : Submodule ℚ (Module.End ℚ ImO)) ≤ lieGenCross.toSubmodule ∧
    Module.finrank ℚ lieGenCross.toSubmodule = 21 ∧
    proj14 (⁅crossOp (imBasis 1), crossOp (imBasis 2)⁆ : Module.End ℚ ImO) ≠ 0 :=
  ⟨crossEmb_lieSpan_eq_so7, range_imRepL_le_lieGenCross, finrank_lieSpan_crossEmb,
    proj14_witness_ne_zero⟩

end Phys.Algebra
